const ROOT="https://note.com";
const o=(v:any)=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};const a=(v:any)=>Array.isArray(v)?v:[];const s=(v:any,d="")=>typeof v==="string"?v:d;const n=(v:any,d=0)=>typeof v==="number"&&Number.isFinite(v)?v:d;
async function get(path:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(ROOT+path,{headers:{Accept:"application/json","User-Agent":"Mumei-S-note-INSIGHT/3.1"},signal:c.signal});if(!r.ok)throw new Error(`NOTE_PUBLIC_${r.status}`);return o(await r.json())}finally{clearTimeout(t)}}
export async function creator(id:string){const d=o((await get(`/api/v2/creators/${encodeURIComponent(id)}`)).data);return{noteId:s(d.urlname,id),name:s(d.nickname,id),image:s(d.profileImageUrl??d.profile_image_url)||null,followers:n(d.followerCount??d.follower_count),following:n(d.followingCount??d.following_count),notes:n(d.noteCount??d.note_count)}}
export type Article={key:string;title:string;url:string;published:string|null;likes:number;comments:number};
export async function articles(id:string,page:number){const p=await get(`/api/v2/creators/${encodeURIComponent(id)}/contents?kind=note&page=${page}`),d=o(p.data),rows=a(d.contents??d.notes).map((x:any)=>{const v=o(o(x).note??x),key=s(v.key);return key?{key,title:s(v.name??v.title,"無題の記事"),url:s(v.noteUrl??v.url,`${ROOT}/${id}/n/${key}`),published:s(v.publishAt??v.publish_at)||null,likes:n(v.likeCount??v.like_count),comments:n(v.commentCount??v.comment_count)}:null}).filter(Boolean) as Article[];return{rows,last:Boolean(d.isLastPage??d.is_last_page)||rows.length===0}}
export async function likes(key:string){const d=o((await get(`/api/v3/notes/${encodeURIComponent(key)}/likes`)).data);return a(d.likes).map((x:any)=>{const r=o(x),u=o(r.user),urlname=s(u.urlname)||null;return{key:s(u.key)||(u.id!=null?String(u.id):urlname||"unknown"),name:s(u.nickname,"noteユーザー"),url:urlname?`${ROOT}/${urlname}`:null,image:s(u.profileImageUrl??u.profile_image_url)||null,at:s(r.created_at??r.createdAt)||null}})}
function commentPage(p:any){const payload=p?.data;if(Array.isArray(payload))return{rows:payload,last:payload.length<100};const d=o(payload),rows=a(d.comments??d.note_comments??d.contents);return{rows,last:Boolean(d.isLastPage??d.is_last_page)||rows.length<100}}
export async function comments(key:string){const all:any[]=[];for(let page=1;page<=20;page++){const p=await get(`/api/v3/notes/${encodeURIComponent(key)}/note_comments?order=oldest&per_page=100&page=${page}`),cp=commentPage(p);for(const x of cp.rows){const r=o(x),u=o(r.user??r.author),urlname=s(u.urlname)||null,key2=s(r.key??r.comment_key);if(key2)all.push({key:key2,parent:s(r.parent_key??r.parentKey)||null,name:s(u.nickname,"noteユーザー"),url:urlname?`${ROOT}/${urlname}`:null,urlname,image:s(u.profileImageUrl??u.profile_image_url)||null,body:s(r.body??r.comment??r.text).replace(/\s+/g," ").trim().slice(0,500),at:s(r.created_at??r.createdAt)||null})}if(cp.last)break}return all}
export async function followers(id:string,page:number){const p=await get(`/api/v2/creators/${encodeURIComponent(id)}/followers?page=${page}&per=20`),d=o(p.data);const rows=a(d.follows??d.followers??d.users??d.contents??p.data).map((x:any)=>{const u=o(o(x).user??x),urlname=s(u.urlname)||null;return{key:s(u.key)||(u.id!=null?String(u.id):urlname||"unknown"),name:s(u.nickname??u.name,"noteユーザー"),url:urlname?`${ROOT}/${urlname}`:null}});return{rows,last:Boolean(d.isLastPage??d.is_last_page)||rows.length===0}}
