import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const NOTE="https://note.com";
const ORIGIN="https://mumei-s.github.io";
const db=createClient(U,K,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token,x-cron-secret","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const now=new Date().toISOString();const{data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const{data:a}=await db.from("insight_access_applications").select("id,note_id,display_name,status,verified_at").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase(),scope=noteId==="ss_yr"?"owner":String(a.id);await db.from("insight_member_sessions").update({last_seen_at:now}).eq("id",s.id);await db.from("insight_notification_profiles").upsert({member_id:scope,note_urlname:noteId,note_nickname:a.display_name||noteId,role:scope==="owner"?"owner":"member",verified_at:a.verified_at||now,updated_at:now},{onConflict:"member_id"});return{id:String(a.id),scope,noteId,displayName:String(a.display_name||noteId)}}
async function cronAuthorized(req:Request){const supplied=req.headers.get("X-Cron-Secret")||"";if(!supplied)return false;const{data,error}=await db.from("insight_notification_cron_secret").select("secret").eq("singleton",true).maybeSingle();if(error)throw error;return Boolean(data?.secret&&supplied===data.secret)}
function obj(v:any){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}
function arr(v:any){return Array.isArray(v)?v:[]}
function txt(v:any,d=""){return typeof v==="string"?v:d}
function num(v:any,d=0){return Number.isFinite(Number(v))?Number(v):d}
async function noteJson(path:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(`${NOTE}${path}`,{headers:{Accept:"application/json","User-Agent":"Mumei-S-note-INSIGHT/4.2 (+public-read-only)"},cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(`NOTE_${r.status}`);return obj(await r.json())}finally{clearTimeout(timer)}}
type Direction="followers"|"followings";
type Person={key:string;name:string;url:string|null;image:string|null;rank:number};
type Identity={scope:string;noteId:string;displayName:string};
async function creator(noteId:string){const p=await noteJson(`/api/v2/creators/${encodeURIComponent(noteId)}`),d=obj(p.data),key=txt(d.key);if(!key)throw new Error("CREATOR_KEY_NOT_FOUND");return{key,noteId:txt(d.urlname,noteId),name:txt(d.nickname,noteId),followers:num(d.followerCount??d.follower_count),followings:num(d.followingCount??d.following_count)}}
function relationUser(x:any){const row=obj(x);return obj(row.user??row.follower??row.following??row.followee??row.creator??row)}
function person(x:any,rank:number):Person|null{const row=obj(x),u=relationUser(row),un=txt(u.urlname??row.urlname),key=txt(u.key??row.key)||(u.id!=null?String(u.id):row.id!=null?String(row.id):un);if(!key)return null;const image=txt(u.user_profile_image_url??u.profile_image_url??u.profileImageUrl??row.user_profile_image_url??row.profile_image_url??row.profileImageUrl)||null;return{key,name:txt(u.nickname??u.name??row.nickname??row.name,"noteユーザー"),url:un?`${NOTE}/${un}`:null,image,rank}}
async function relationPage(creatorKey:string,direction:Direction,page:number){const p=await noteJson(`/api/v3/users/${encodeURIComponent(creatorKey)}/${direction}?page=${page}&per=20`),d=obj(p.data),raw=arr(d.follows??d.followers??d.followings??d.users??d.contents),people=raw.map((x:any,i:number)=>person(x,(page-1)*20+i+1)).filter(Boolean) as Person[];return{people,total:num(d.total_count??d.totalCount),last:Boolean(d.is_last_page??d.isLastPage??raw.length===0)}}
async function visibleRelations(creatorKey:string,direction:Direction,official:number){const first=await relationPage(creatorKey,direction,1),endpoint=first.total||official,accessible=Math.min(endpoint||official,1000),pages=Math.max(1,Math.ceil(accessible/20)),all=[first];for(let start=2;start<=pages;start+=5){const ns=[] as number[];for(let p=start;p<start+5&&p<=pages;p++)ns.push(p);all.push(...await Promise.all(ns.map(p=>relationPage(creatorKey,direction,p))));if(start+5<=pages)await sleep(80)}const map=new Map<string,Person>();for(const p of all.flatMap(x=>x.people))map.set(p.key,p);const people=[...map.values()].sort((a,b)=>a.rank-b.rank),capped=official>1000||endpoint>1000,complete=!capped&&people.length===official&&Boolean(all.at(-1)?.last);return{people,official,endpoint,pages,complete,capped}}
async function active(scope:string,direction:Direction){const rows:any[]=[];for(let from=0;;from+=1000){const{data,error}=await db.from("insight_relations").select("person_key,actor_name,actor_url,actor_image_url,active,first_seen_at").eq("member_id",scope).eq("direction",direction).eq("active",true).range(from,from+999);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<1000)break}return rows}
async function previousRun(scope:string,direction:Direction){const{data,error}=await db.from("insight_relation_sync_runs").select("id,expected_count,received_count,complete,created_at").eq("member_id",scope).eq("direction",direction).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data||null}
async function upsertPeople(scope:string,direction:Direction,people:Person[],now:string,changed:Set<string>){for(let i=0;i<people.length;i+=400){const rows=people.slice(i,i+400).map(p=>({member_id:scope,direction,person_key:p.key,actor_name:p.name,actor_url:p.url,actor_image_url:p.image,active:true,last_seen_at:now,source_rank:p.rank,...(changed.has(p.key)?{last_changed_at:now}:{})}));const{error}=await db.from("insight_relations").upsert(rows,{onConflict:"member_id,direction,person_key"});if(error)throw error}}
async function markRemoved(scope:string,direction:Direction,keys:string[],now:string){for(let i=0;i<keys.length;i+=200){const{error}=await db.from("insight_relations").update({active:false,last_changed_at:now}).eq("member_id",scope).eq("direction",direction).in("person_key",keys.slice(i,i+200));if(error)throw error}}
async function eventRows(scope:string,runId:number,direction:Direction,type:"added"|"removed",people:Person[],now:string){for(let i=0;i<people.length;i+=400){const rows=people.slice(i,i+400).map(p=>({member_id:scope,run_id:runId,direction,event_type:type,person_key:p.key,actor_name:p.name,actor_url:p.url,actor_image_url:p.image,detected_at:now}));const{error}=await db.from("insight_relation_events").insert(rows);if(error)throw error}}
async function syncDirection(scope:string,c:any,direction:Direction){const now=new Date().toISOString(),official=direction==="followers"?c.followers:c.followings,previous=await previousRun(scope,direction),old=await active(scope,direction),oldMap=new Map(old.map((x:any)=>[String(x.person_key),x]));let f;try{f=await visibleRelations(c.key,direction,official)}catch(e){await db.from("insight_relation_sync_runs").insert({member_id:scope,direction,expected_count:official,received_count:0,page_count:0,complete:false,baseline:false,added_count:0,removed_count:0,error:e instanceof Error?e.message:String(e)});throw e}const current=new Map(f.people.map(p=>[p.key,p])),baseline=!previous,added=f.complete&&!baseline?f.people.filter(p=>!oldMap.has(p.key)):[],removed=f.complete&&!baseline?[...oldMap.keys()].filter(k=>!current.has(k)).map(k=>({key:k,name:String(oldMap.get(k)?.actor_name||"noteユーザー"),url:oldMap.get(k)?.actor_url||null,image:oldMap.get(k)?.actor_image_url||null,rank:999999})):[],changed=new Set(added.map(p=>p.key));if(f.complete&&removed.length)await markRemoved(scope,direction,removed.map(p=>p.key),now);await upsertPeople(scope,direction,f.people,now,changed);const{data:run,error}=await db.from("insight_relation_sync_runs").insert({member_id:scope,direction,expected_count:official,received_count:f.people.length,page_count:f.pages,complete:f.complete,baseline,added_count:added.length,removed_count:removed.length,error:f.capped?`NOTE_IDENTITY_LIST_CAPPED_AT_1000:${official}`:f.complete?null:`COUNT_MISMATCH:${f.people.length}/${official}`}).select("id").single();if(error)throw error;if(f.complete&&!baseline){await eventRows(scope,run.id,direction,"added",added,now);await eventRows(scope,run.id,direction,"removed",removed,now)}return{direction,officialCount:official,namedCount:f.people.length,complete:f.complete,capped:f.capped,baseline,added:added.length,removed:removed.length,netDelta:previous?official-Number(previous.expected_count||0):0,scannedAt:now}}
async function syncIdentity(identity:Identity){const c=await creator(identity.noteId),followings=await syncDirection(identity.scope,c,"followings"),followers=await syncDirection(identity.scope,c,"followers");return{ok:true,member:{noteId:identity.noteId,displayName:identity.displayName},creator:c,followers,followings}}
async function sync(req:Request){const m=await auth(req);return await syncIdentity({scope:m.scope,noteId:m.noteId,displayName:m.displayName})}
async function cron(req:Request){if(!(await cronAuthorized(req)))throw new Error("CRON_SECRET_INVALID");const identities=new Map<string,Identity>();const{data:ownerProfile}=await db.from("insight_notification_profiles").select("note_urlname,note_nickname,verified_at").eq("member_id","owner").maybeSingle();if(ownerProfile?.verified_at)identities.set("owner",{scope:"owner",noteId:String(ownerProfile.note_urlname||"ss_yr").toLowerCase(),displayName:String(ownerProfile.note_nickname||"無名S note")});const{data:apps,error}=await db.from("insight_access_applications").select("id,note_id,display_name,status,verified_at").eq("status","active").not("verified_at","is",null).limit(100);if(error)throw error;for(const a of apps||[]){const noteId=String(a.note_id||"").toLowerCase(),scope=noteId==="ss_yr"?"owner":String(a.id);identities.set(scope,{scope,noteId,displayName:String(a.display_name||noteId)})}const results:any[]=[];for(const x of identities.values()){try{results.push(await syncIdentity(x))}catch(e){results.push({ok:false,member:{noteId:x.noteId},error:e instanceof Error?e.message:String(e)})}await sleep(150)}return{ok:true,scanned:results.length,results}}
async function dashboard(req:Request){const m=await auth(req);const{data:runs,error}=await db.from("insight_relation_sync_runs").select("id,direction,expected_count,received_count,complete,baseline,added_count,removed_count,error,created_at").eq("member_id",m.scope).order("created_at",{ascending:false}).limit(60);if(error)throw error;return{ok:true,runs:runs||[]}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const b=await req.json().catch(()=>({})),action=txt(b.action,"dashboard");if(action==="cron")return out(await cron(req));if(action==="sync")return out(await sync(req));return out(await dashboard(req))}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE|CRON_SECRET/.test(msg)?401:500)}});
