import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,NOTE="https://note.com",ORIGIN="https://mumei-s.github.io";
const db=createClient(U,K,{auth:{persistSession:false}}),H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token,x-cron-secret","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"},out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const now=new Date().toISOString(),{data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const{data:a}=await db.from("insight_access_applications").select("id,note_id,display_name,status,verified_at").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase(),scope=noteId==="ss_yr"?"owner":String(a.id);await db.from("insight_member_sessions").update({last_seen_at:now}).eq("id",s.id);return{id:String(a.id),scope,noteId,displayName:String(a.display_name||noteId)}}
async function cronAuthorized(req:Request){const supplied=req.headers.get("X-Cron-Secret")||"";if(!supplied)return false;const{data}=await db.from("insight_notification_cron_secret").select("secret").eq("singleton",true).maybeSingle();return Boolean(data?.secret&&supplied===data.secret)}
const obj=(v:any)=>v&&typeof v==="object"&&!Array.isArray(v)?v:{},arr=(v:any)=>Array.isArray(v)?v:[],txt=(v:any,d="")=>typeof v==="string"?v:d,num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
async function noteJson(path:string){let last:unknown=null;for(let a=1;a<=3;a++){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(NOTE+path,{headers:{Accept:"application/json","User-Agent":"Mumei-S-note-INSIGHT/5.5 (+official-count-capped-snapshot)"},cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(`NOTE_${r.status}`);return obj(await r.json())}catch(e){last=e;if(a<3)await sleep(180*a)}finally{clearTimeout(timer)}}throw last instanceof Error?last:new Error("NOTE_READ_FAILED")}
type Direction="followers"|"followings";type Person={key:string;name:string;url:string|null;image:string|null;rank:number};type Identity={scope:string;noteId:string;displayName:string};
async function creator(noteId:string){const p=await noteJson(`/api/v2/creators/${encodeURIComponent(noteId)}`),d=obj(p.data),key=txt(d.key);if(!key)throw new Error("CREATOR_KEY_NOT_FOUND");return{key,noteId:txt(d.urlname,noteId),name:txt(d.nickname,noteId),followers:num(d.followerCount??d.follower_count),followings:num(d.followingCount??d.following_count)}}
function relationUser(x:any){const r=obj(x);return obj(r.user??r.follower??r.following??r.followee??r.creator??r)}
function person(x:any,rank:number):Person|null{const r=obj(x),u=relationUser(r),un=txt(u.urlname??r.urlname),key=txt(u.key??r.key)||(u.id!=null?String(u.id):r.id!=null?String(r.id):un);if(!key)return null;return{key,name:txt(u.nickname??u.name??r.nickname??r.name,"noteユーザー"),url:un?`${NOTE}/${un}`:null,image:txt(u.user_profile_image_url??u.profile_image_url??u.profileImageUrl??r.user_profile_image_url??r.profile_image_url??r.profileImageUrl)||null,rank}}
async function v3Page(key:string,d:Direction,page:number){const p=await noteJson(`/api/v3/users/${encodeURIComponent(key)}/${d}?page=${page}&per=20`),x=obj(p.data),raw=arr(x.follows??x.followers??x.followings??x.users??x.contents),people=raw.map((r:any,i:number)=>person(r,(page-1)*20+i+1)).filter(Boolean) as Person[],next=x.next_page??x.nextPage??p.next_page??p.nextPage,lastFlag=x.is_last_page??x.isLastPage??p.is_last_page??p.isLastPage;return{people,last:lastFlag===true||raw.length===0||next===null||next===false||next===""}}
async function v2Page(noteId:string,d:Direction,page:number){const p=await noteJson(`/api/v2/creators/${encodeURIComponent(noteId)}/${d}?page=${page}&per=20`),x=obj(p.data),raw=arr(x.follows??x.followers??x.followings??x.users??x.contents??p.data),people=raw.map((r:any,i:number)=>person(r,(page-1)*20+i+1)).filter(Boolean) as Person[],last=Boolean(x.isLastPage??x.is_last_page)||raw.length===0;return{people,last}}
async function collect(source:"v3"|"v2",creatorKey:string,noteId:string,d:Direction,official:number){const map=new Map<string,Person>();let pages=0,last=false,error="";const maxPages=Math.min(120,Math.max(20,Math.ceil(Math.max(official,1)/20)+8));for(let page=1;page<=maxPages;page++){try{const p=source==="v3"?await v3Page(creatorKey,d,page):await v2Page(noteId,d,page);pages=page;for(const x of p.people)if(!map.has(x.key))map.set(x.key,x);if(p.last){last=true;break}}catch(e){error=e instanceof Error?e.message:String(e);break}await sleep(30)}return{people:[...map.values()],pages,last,error}}
async function combinedRelations(c:any,d:Direction){const official=d==="followers"?c.followers:c.followings,[a,b]=await Promise.all([collect("v3",c.key,c.noteId,d,official),collect("v2",c.key,c.noteId,d,official)]),map=new Map<string,Person>();for(const x of [...a.people,...b.people]){const old=map.get(x.key);map.set(x.key,old?{...old,...x,image:x.image||old.image,rank:Math.min(old.rank,x.rank)}:x)}const people=[...map.values()].sort((x,y)=>x.rank-y.rank),complete=people.length===official,cap=!complete&&official>1000&&Math.max(a.people.length,b.people.length)>=1000,error=complete?null:cap?`NOTE_IDENTITY_LIST_CAPPED_AT_1000:${official}`:`RELATION_COUNT_MISMATCH:${d}:${people.length}/${official}:v3=${a.people.length}:v2=${b.people.length}`;return{people,official,complete,cap,error,pages:a.pages+b.pages,sources:{v3:a.people.length,v2:b.people.length}}}
async function active(scope:string,d:Direction){const rows:any[]=[];for(let from=0;;from+=1000){const{data,error}=await db.from("insight_relations").select("person_key,actor_name,actor_url,actor_image_url,active,first_seen_at,last_seen_at,source_rank").eq("member_id",scope).eq("direction",d).eq("active",true).range(from,from+999);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<1000)break}return rows}
async function activeKeys(scope:string,d:Direction){const rows=await active(scope,d);return new Set(rows.map((x:any)=>String(x.person_key)))}
async function latestRun(scope:string,d:Direction){const{data}=await db.from("insight_relation_sync_runs").select("id,expected_count,received_count,complete,error,created_at").eq("member_id",scope).eq("direction",d).order("created_at",{ascending:false}).limit(1).maybeSingle();return data||null}
async function latestCompleteRun(scope:string,d:Direction){const{data}=await db.from("insight_relation_sync_runs").select("id,expected_count,received_count,complete,created_at").eq("member_id",scope).eq("direction",d).eq("complete",true).order("created_at",{ascending:false}).limit(1).maybeSingle();return data||null}
async function upsertPeople(scope:string,d:Direction,people:Person[],now:string,changed:Set<string>){for(let i=0;i<people.length;i+=400){const rows=people.slice(i,i+400).map(p=>({member_id:scope,direction:d,person_key:p.key,actor_name:p.name,actor_url:p.url,actor_image_url:p.image,active:true,last_seen_at:now,source_rank:p.rank,...(changed.has(p.key)?{last_changed_at:now}:{})}));const{error}=await db.from("insight_relations").upsert(rows,{onConflict:"member_id,direction,person_key"});if(error)throw error}}
async function markRemoved(scope:string,d:Direction,keys:string[],now:string){for(let i=0;i<keys.length;i+=200){const{error}=await db.from("insight_relations").update({active:false,last_changed_at:now}).eq("member_id",scope).eq("direction",d).in("person_key",keys.slice(i,i+200));if(error)throw error}}
async function eventRows(scope:string,runId:number,d:Direction,type:"added"|"removed",people:Person[],now:string){if(!people.length)return;for(let i=0;i<people.length;i+=400){const rows=people.slice(i,i+400).map(p=>({member_id:scope,run_id:runId,direction:d,event_type:type,person_key:p.key,actor_name:p.name,actor_url:p.url,actor_image_url:p.image,detected_at:now,change_count:1}));const{error}=await db.from("insight_relation_events").insert(rows);if(error)throw error}}
async function unknownEvent(scope:string,runId:number,d:Direction,type:"added"|"removed",count:number,now:string){if(count<=0)return;const{error}=await db.from("insight_relation_events").insert({member_id:scope,run_id:runId,direction:d,event_type:type,person_key:`unknown:${runId}:${d}:${type}`,actor_name:"不明",actor_url:null,actor_image_url:null,detected_at:now,change_count:count});if(error)throw error}
function toPerson(x:any):Person{return{key:String(x.person_key),name:String(x.actor_name||"noteユーザー"),url:x.actor_url||null,image:x.actor_image_url||null,rank:Number(x.source_rank||999999)}}
async function syncCappedFollowers(scope:string,d:Direction,f:any,previous:any,now:string){const old=await active(scope,d),oldMap=new Map(old.map((x:any)=>[String(x.person_key),x])),current=new Map(f.people.map((p:Person)=>[p.key,p])),visibleRemoved=old.filter((x:any)=>!current.has(String(x.person_key))),visibleAdded=f.people.filter((p:Person)=>!oldMap.has(p.key)),expectedPrevious=Number(previous?.expected_count||0),receivedPrevious=Number(previous?.received_count||0),legacy=!previous||previous.complete===true||!String(previous.error||"").startsWith("NOTE_IDENTITY_LIST_CAPPED_AT_1000:")||old.length>Math.max(f.people.length,receivedPrevious)+5,delta=previous?f.official-expectedPrevious:0;let namedAdded:Person[]=[],namedRemoved:Person[]=[],unknownAdded=0,unknownRemoved=0,addedCount=0,removedCount=0;
if(!legacy&&d==="followers"){
  if(delta<0){const drop=Math.abs(delta),followed=await activeKeys(scope,"followings"),candidates=visibleRemoved.map(toPerson).sort((a,b)=>Number(followed.has(b.key))-Number(followed.has(a.key))||a.rank-b.rank);namedRemoved=candidates.slice(0,Math.min(drop,candidates.length));unknownRemoved=Math.max(0,drop-namedRemoved.length);removedCount=drop}
  else if(delta>0){const rise=delta,candidates=[...visibleAdded].sort((a,b)=>a.rank-b.rank);namedAdded=candidates.slice(0,Math.min(rise,candidates.length));unknownAdded=Math.max(0,rise-namedAdded.length);addedCount=rise}
}
const snapshotRemoved=visibleRemoved.map((x:any)=>String(x.person_key));if(snapshotRemoved.length)await markRemoved(scope,d,snapshotRemoved,now);await upsertPeople(scope,d,f.people,now,new Set(namedAdded.map(p=>p.key)));const{data:run,error}=await db.from("insight_relation_sync_runs").insert({member_id:scope,direction:d,expected_count:f.official,received_count:f.people.length,page_count:f.pages,complete:false,baseline:legacy,added_count:addedCount,removed_count:removedCount,error:f.error}).select("id").single();if(error)throw error;if(!legacy&&d==="followers"){await eventRows(scope,run.id,d,"added",namedAdded,now);await eventRows(scope,run.id,d,"removed",namedRemoved,now);await unknownEvent(scope,run.id,d,"added",unknownAdded,now);await unknownEvent(scope,run.id,d,"removed",unknownRemoved,now)}return{direction:d,officialCount:f.official,namedCount:f.people.length,complete:false,baseline:legacy,added:addedCount,removed:removedCount,identityExact:false,error:f.error,sources:f.sources,scannedAt:now,trackingMode:d==="followers"?"official_total_plus_latest_1000":"capped_snapshot",unknownAdded,unknownRemoved}}
async function syncDirection(scope:string,c:any,d:Direction){const now=new Date().toISOString(),previous=await latestRun(scope,d),lastExact=await latestCompleteRun(scope,d),f=await combinedRelations(c,d);if(!f.complete){if(f.cap)return await syncCappedFollowers(scope,d,f,previous,now);await upsertPeople(scope,d,f.people,now,new Set());await db.from("insight_relation_sync_runs").insert({member_id:scope,direction:d,expected_count:f.official,received_count:f.people.length,page_count:f.pages,complete:false,baseline:!lastExact,added_count:0,removed_count:0,error:f.error});return{direction:d,officialCount:f.official,namedCount:f.people.length,complete:false,baseline:!lastExact,added:0,removed:0,identityExact:false,error:f.error,sources:f.sources,scannedAt:now,previousCompleteAt:lastExact?.created_at||null}}
const old=await active(scope,d),oldMap=new Map(old.map((x:any)=>[String(x.person_key),x])),current=new Map(f.people.map((p:Person)=>[p.key,p])),baseline=!lastExact,added=baseline?[]:f.people.filter((p:Person)=>!oldMap.has(p.key)),removedKeys=[...oldMap.keys()].filter(k=>!current.has(k)),removed=baseline?[]:removedKeys.map(k=>({key:k,name:String(oldMap.get(k)?.actor_name||"noteユーザー"),url:oldMap.get(k)?.actor_url||null,image:oldMap.get(k)?.actor_image_url||null,rank:999999})),changed=new Set(added.map((p:Person)=>p.key));if(removedKeys.length)await markRemoved(scope,d,removedKeys,now);await upsertPeople(scope,d,f.people,now,changed);await db.from("insight_relation_events").delete().eq("member_id",scope).like("person_key","aggregate:%");const{data:run,error}=await db.from("insight_relation_sync_runs").insert({member_id:scope,direction:d,expected_count:f.official,received_count:f.people.length,page_count:f.pages,complete:true,baseline,added_count:added.length,removed_count:removed.length,error:null}).select("id").single();if(error)throw error;if(!baseline){await eventRows(scope,run.id,d,"added",added,now);await eventRows(scope,run.id,d,"removed",removed,now)}return{direction:d,officialCount:f.official,namedCount:f.people.length,complete:true,baseline,added:added.length,removed:removed.length,identityExact:true,sources:f.sources,scannedAt:now,previousCompleteAt:lastExact?.created_at||null,previousRunComplete:previous?.complete===true}}
async function syncIdentity(x:Identity){const c=await creator(x.noteId),followings=await syncDirection(x.scope,c,"followings"),followers=await syncDirection(x.scope,c,"followers");return{ok:true,member:{noteId:x.noteId,displayName:x.displayName},creator:c,followers,followings}}
async function sync(req:Request){const m=await auth(req);return await syncIdentity({scope:m.scope,noteId:m.noteId,displayName:m.displayName})}
async function cron(req:Request){if(!(await cronAuthorized(req)))throw new Error("CRON_SECRET_INVALID");const identities=new Map<string,Identity>(),{data:apps}=await db.from("insight_access_applications").select("id,note_id,display_name,status,verified_at").eq("status","active").not("verified_at","is",null).limit(100);identities.set("owner",{scope:"owner",noteId:"ss_yr",displayName:"無名S note"});for(const a of apps||[]){const noteId=String(a.note_id||"").toLowerCase(),scope=noteId==="ss_yr"?"owner":String(a.id);identities.set(scope,{scope,noteId,displayName:String(a.display_name||noteId)})}const results:any[]=[];for(const x of identities.values()){try{results.push(await syncIdentity(x))}catch(e){results.push({ok:false,member:{noteId:x.noteId},error:e instanceof Error?e.message:String(e)})}await sleep(120)}return{ok:true,scanned:results.length,results}}
async function dashboard(req:Request){const m=await auth(req),{data:runs,error}=await db.from("insight_relation_sync_runs").select("id,direction,expected_count,received_count,complete,baseline,added_count,removed_count,error,created_at").eq("member_id",m.scope).order("created_at",{ascending:false}).limit(60);if(error)throw error;return{ok:true,runs:runs||[]}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const b=await req.json().catch(()=>({})),action=txt(b.action,"dashboard");if(action==="cron")return out(await cron(req));if(action==="sync")return out(await sync(req));return out(await dashboard(req))}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE|CRON_SECRET/.test(msg)?401:500)}});
