import { createClient } from "npm:@supabase/supabase-js@2";
import { checkedFetch, backgroundGate, rpcValue, batchUpsert, quotaError } from "../_shared/egress-20260930.ts";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!, SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false},global:{fetch:checkedFetch}});
const INSIGHT_ORIGIN="https://note-like-tracker.sabosan0404.chatgpt.site", NOTE_ORIGIN="https://note.com";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-insight-member,x-insight-device,x-ingest-token,x-owner-token,x-cron-secret","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Content-Type":"application/json; charset=utf-8"};
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:CORS})}
function cleanText(v:unknown,max=2000){return typeof v==="string"?v.replace(/\u0000/g,"").trim().slice(0,max):null}
function obj(v:unknown):Record<string,any>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,any>:{} }
function arr(v:unknown):any[]{return Array.isArray(v)?v:[]}
function num(v:unknown,f=0){return typeof v==="number"&&Number.isFinite(v)?v:f}
function txt(v:unknown,f=""){return typeof v==="string"?v:f}
function bool(v:unknown,f=false){return typeof v==="boolean"?v:f}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}
async function sha256(input:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function randomCode(){const b=crypto.getRandomValues(new Uint8Array(5));return "INSIGHT-"+[...b].map(x=>x.toString(16).padStart(2,"0")).join("").toUpperCase()}
function classify(text:string){const t=text.replace(/\s+/g," ");if(/あなたの記事が話題|話題です/.test(t))return"buzz";if(/チップ|サポートされ|サポートを受け/.test(t))return"tip";if(/購入され|購入しました|売れました|購入があり/.test(t))return"purchase";if(/マガジン.{0,30}追加|マガジンに追加/.test(t))return"magazine";if(/引用され|引用しました|ほかの記事で引用|記事で紹介/.test(t))return"quote";if(/返信|あなたのコメント.{0,30}(返事|返信)|コメントに返/.test(t))return"reply";if(/コメント/.test(t))return"comment";if(/高評価/.test(t))return"rating";if(/スキ/.test(t))return"like";if(/フォロー/.test(t))return"follow";if(/ポイント/.test(t))return"points";return"other"}
async function noteJson(path:string){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(`${NOTE_ORIGIN}${path}`,{headers:{Accept:"application/json","User-Agent":"Mumei-S-note-INSIGHT/2.0 (+public-read-only)"},signal:ctrl.signal});if(!r.ok)throw new Error(`NOTE_PUBLIC_${r.status}`);return obj(await r.json())}finally{clearTimeout(timer)}}
async function fetchCreator(urlname:string){const p=await noteJson(`/api/v2/creators/${encodeURIComponent(urlname)}`),d=obj(p.data);return{urlname:txt(d.urlname,urlname).toLowerCase(),nickname:txt(d.nickname,urlname),profile:txt(d.profile),image:cleanText(d.profileImageUrl??d.profile_image_url,1200),followerCount:num(d.followerCount??d.follower_count),noteCount:num(d.noteCount??d.note_count)}}
type Article={key:string;title:string;url:string;publishAt:string|null;likeCount:number;commentCount:number};
async function fetchArticles(urlname:string,page:number){const p=await noteJson(`/api/v2/creators/${encodeURIComponent(urlname)}/contents?kind=note&page=${Math.max(1,page)}`),d=obj(p.data);const contents=arr(d.contents??d.notes).map((item):Article|null=>{const row=obj(item),n=obj(row.note??row),key=txt(n.key);if(!key)return null;return{key,title:txt(n.name??n.title,"無題の記事"),url:txt(n.noteUrl??n.url,`${NOTE_ORIGIN}/${urlname}/n/${key}`),publishAt:cleanText(n.publishAt??n.publish_at,80),likeCount:num(n.likeCount??n.like_count),commentCount:num(n.commentCount??n.comment_count)}}).filter(Boolean) as Article[];return{contents,isLast:bool(d.isLastPage??d.is_last_page)||bool(p.isLastPage??p.is_last_page)||contents.length===0}}
type PublicLike={key:string;name:string;url:string|null;likedAt:string|null};
async function fetchLikes(articleKey:string){const p=await noteJson(`/api/v3/notes/${encodeURIComponent(articleKey)}/likes`),d=obj(p.data);return arr(d.likes).map((item):PublicLike=>{const row=obj(item),u=obj(row.user),un=txt(u.urlname)||null;return{key:txt(u.key)||(typeof u.id==="number"?String(u.id):un??"unknown"),name:txt(u.nickname,"noteユーザー"),url:un?`${NOTE_ORIGIN}/${un}`:null,likedAt:cleanText(row.created_at??row.createdAt,80)}})}
type PublicComment={key:string;name:string;url:string|null;urlname:string|null;body:string;occurredAt:string|null};
function commentRows(p:Record<string,any>){const d=obj(p.data);return arr(d.comments??d.note_comments??d.contents)}
function commentUser(r:Record<string,any>){return obj(r.user??r.author)}
async function fetchComments(articleKey:string){const first=await noteJson(`/api/v3/notes/${encodeURIComponent(articleKey)}/note_comments?order=oldest&per_page=100&page=1`),base=commentRows(first).map(obj),all=new Map<string,Record<string,any>>();for(const row of base){const key=txt(row.key??row.comment_key);if(key)all.set(key,row)}for(const root of base.filter(r=>!txt(r.parent_key??r.parentKey))){const rootKey=txt(root.key??root.comment_key);if(!rootKey||num(root.reply_count??root.replyCount)<=0)continue;const known=base.filter(r=>txt(r.parent_key??r.parentKey)===rootKey).length;if(known>=num(root.reply_count??root.replyCount))continue;try{await sleep(120);const replies=await noteJson(`/api/v3/notes/${encodeURIComponent(articleKey)}/note_comments?order=oldest&per_page=100&parent_key=${encodeURIComponent(rootKey)}`);for(const item of commentRows(replies)){const row=obj(item),key=txt(row.key??row.comment_key);if(key)all.set(key,row)}}catch{}}return[...all.values()].map((row):PublicComment=>{const u=commentUser(row),un=txt(u.urlname)||null;return{key:txt(row.key??row.comment_key),name:txt(u.nickname,"noteユーザー"),url:un?`${NOTE_ORIGIN}/${un}`:null,urlname:un,body:txt(row.body??row.comment??row.text).replace(/\s+/g," ").trim().slice(0,500),occurredAt:cleanText(row.created_at??row.createdAt,80)}}).filter(x=>x.key)}
type PublicPerson={key:string;name:string;url:string|null};
async function fetchFollowerPage(urlname:string,page:number){const p=await noteJson(`/api/v2/creators/${encodeURIComponent(urlname)}/followers?page=${Math.max(1,page)}&per=20`),d=obj(p.data),rows=arr(d.follows??d.followers??d.users??d.contents??p.data);const people=rows.map((item):PublicPerson=>{const u=obj(obj(item).user??item),un=txt(u.urlname)||null;return{key:txt(u.key)||(typeof u.id==="number"?String(u.id):un??"unknown"),name:txt(u.nickname??u.name,"noteユーザー"),url:un?`${NOTE_ORIGIN}/${un}`:null}});return{people,isLast:bool(d.isLastPage??d.is_last_page)||bool(p.isLastPage??p.is_last_page)||people.length===0}}
async function verifyInsight(req:Request){const mt=req.headers.get("X-Insight-Member")||"",device=req.headers.get("X-Insight-Device")||"";if(!mt||!device)throw new Error("INSIGHT_LOGIN_REQUIRED");const r=await fetch(`${INSIGHT_ORIGIN}/api/member/me`,{cache:"no-store",headers:{"X-Insight-Member":mt,"X-Insight-Device":device,Accept:"application/json"}});if(!r.ok)throw new Error("INSIGHT_SESSION_INVALID");const payload=await r.json(),m=payload?.member;if(!m?.id||(m.status!=="active"&&m.role!=="owner"))throw new Error("INSIGHT_MEMBER_INACTIVE");await supabase.from("insight_notification_profiles").upsert({member_id:String(m.id),note_urlname:m.noteUrlname??null,note_nickname:m.noteNickname??null,role:m.role??"member",updated_at:new Date().toISOString()},{onConflict:"member_id"});return{id:String(m.id),noteUrlname:m.noteUrlname??null,noteNickname:m.noteNickname??null,role:m.role??"member"}}
async function isOwnerToken(token:string){if(!token)return false;const{data,error}=await supabase.rpc("is_owner_token",{p_token:token});return!error&&data===true}
async function authIdentity(req:Request){const ot=req.headers.get("X-Owner-Token")||"";if(ot&&await isOwnerToken(ot)){const{data:p}=await supabase.from("insight_notification_profiles").select("member_id,note_urlname,note_nickname,role").eq("member_id","owner").maybeSingle();return{id:"owner",noteUrlname:p?.note_urlname??"ss_yr",noteNickname:p?.note_nickname??"無名S note",role:"owner"}}return await verifyInsight(req)}
async function ownerLogin(body:any){const token=cleanText(body?.ownerToken,500)||"";if(!(await isOwnerToken(token)))throw new Error("OWNER_TOKEN_INVALID");await supabase.from("insight_notification_profiles").upsert({member_id:"owner",note_urlname:"ss_yr",note_nickname:"無名S note",role:"owner",updated_at:new Date().toISOString()},{onConflict:"member_id"});return json({ok:true,owner:true})}
async function tokenMember(req:Request){const token=req.headers.get("X-Ingest-Token")||"";if(!token)throw new Error("INGEST_TOKEN_REQUIRED");const{data,error}=await supabase.from("insight_notification_ingest_tokens").select("member_id").eq("token_hash",await sha256(token)).is("revoked_at",null).maybeSingle();if(error||!data?.member_id)throw new Error("INGEST_TOKEN_INVALID");return String(data.member_id)}
async function ingest(req:Request,body:any){const memberId=await tokenMember(req),incoming=Array.isArray(body?.notifications)?body.notifications.slice(0,1000):[];let inserted=0;for(const item of incoming){const raw=cleanText(item?.raw_text??item?.text,3000);if(!raw||raw.length<2)continue;const sourceUrl=cleanText(item?.source_url,1200),oa=cleanText(item?.occurred_at,80),fp=cleanText(item?.fingerprint,128)||await sha256(`${raw}|${sourceUrl??""}|${oa??""}`);const{error}=await supabase.from("insight_notifications").insert({member_id:memberId,fingerprint:fp,notification_type:cleanText(item?.notification_type,40)||classify(raw),raw_text:raw,actor_name:cleanText(item?.actor_name,200),actor_url:cleanText(item?.actor_url,1200),target_title:cleanText(item?.target_title,500),target_url:cleanText(item?.target_url,1200),source_url:sourceUrl,occurred_at:oa&&!Number.isNaN(Date.parse(oa))?new Date(oa).toISOString():null,meta:typeof item?.meta==="object"&&item.meta?item.meta:{}});if(!error)inserted++;else if(error.code!=="23505")console.error(error)}await supabase.from("insight_notification_sync_runs").insert({member_id:memberId,inserted_count:inserted,received_count:incoming.length,source:cleanText(body?.source,50)||"browser"});return json({ok:true,received:incoming.length,inserted})}
async function addDerivedNotification(memberId:string,input:{fingerprint:string;type:string;text:string;actorName?:string|null;actorUrl?:string|null;title?:string|null;url?:string|null;occurredAt?:string|null;meta?:Record<string,unknown>}){const occurred=input.occurredAt&&!Number.isNaN(Date.parse(input.occurredAt))?new Date(input.occurredAt).toISOString():null;const{error}=await supabase.from("insight_notifications").insert({member_id:memberId,fingerprint:input.fingerprint,notification_type:input.type,raw_text:input.text,actor_name:input.actorName??null,actor_url:input.actorUrl??null,target_title:input.title??null,target_url:input.url??null,source_url:input.url??null,occurred_at:occurred,meta:{source:"public_watcher",derived:true,...(input.meta??{})}});if(error&&error.code!=="23505")throw error;return!error}
async function syncLikes(memberId:string,a:Article,baseline:boolean,oldCount:number){const likes=await fetchLikes(a.key),{data:rows}=await supabase.from("insight_public_likes").select("liker_key").eq("member_id",memberId).eq("article_key",a.key),existing=new Set((rows??[]).map((r:any)=>String(r.liker_key)));let detailed=0;for(const l of likes){if(existing.has(l.key))continue;await supabase.from("insight_public_likes").upsert({member_id:memberId,article_key:a.key,liker_key:l.key,actor_name:l.name,actor_url:l.url,liked_at:l.likedAt&&!Number.isNaN(Date.parse(l.likedAt))?new Date(l.likedAt).toISOString():null},{onConflict:"member_id,article_key,liker_key"});if(!baseline&&await addDerivedNotification(memberId,{fingerprint:`public-like|${a.key}|${l.key}`,type:"like",text:`${l.name}さんが「${a.title}」にスキしました`,actorName:l.name,actorUrl:l.url,title:a.title,url:a.url,occurredAt:l.likedAt,meta:{article_key:a.key}}))detailed++}const delta=Math.max(0,a.likeCount-oldCount);if(!baseline&&delta>detailed)await addDerivedNotification(memberId,{fingerprint:`public-like-summary|${a.key}|${a.likeCount}`,type:"like",text:`「${a.title}」に新しいスキが${delta-detailed}件増えました`,title:a.title,url:a.url,meta:{article_key:a.key,summary:true}})}
async function syncComments(memberId:string,a:Article,creator:string,baseline:boolean,oldCount:number){const comments=await fetchComments(a.key),{data:rows}=await supabase.from("insight_public_comments").select("comment_key").eq("member_id",memberId).eq("article_key",a.key),existing=new Set((rows??[]).map((r:any)=>String(r.comment_key)));let detailed=0;for(const c of comments){if(existing.has(c.key))continue;await supabase.from("insight_public_comments").upsert({member_id:memberId,article_key:a.key,comment_key:c.key,actor_name:c.name,actor_url:c.url,body:c.body,occurred_at:c.occurredAt&&!Number.isNaN(Date.parse(c.occurredAt))?new Date(c.occurredAt).toISOString():null},{onConflict:"member_id,article_key,comment_key"});if(!baseline&&(c.urlname??"").toLowerCase()!==creator.toLowerCase()){const body=c.body?`：「${c.body.slice(0,100)}」`:"";if(await addDerivedNotification(memberId,{fingerprint:`public-comment|${a.key}|${c.key}`,type:"comment",text:`${c.name}さんが「${a.title}」にコメントしました${body}`,actorName:c.name,actorUrl:c.url,title:a.title,url:a.url,occurredAt:c.occurredAt,meta:{article_key:a.key,comment_key:c.key}}))detailed++}}const delta=Math.max(0,a.commentCount-oldCount);if(!baseline&&delta>detailed)await addDerivedNotification(memberId,{fingerprint:`public-comment-summary|${a.key}|${a.commentCount}`,type:"comment",text:`「${a.title}」に新しいコメントが${delta-detailed}件増えました`,title:a.title,url:a.url,meta:{article_key:a.key,summary:true}})}
async function syncFollowers(memberId:string,urlname:string,baseline:boolean){
 const people=new Map<string,PublicPerson>();
 for(let page=1;page<=3;page++){const r=await fetchFollowerPage(urlname,page);for(const p of r.people)people.set(p.key,p);if(r.isLast)break;await sleep(120)}
 const now=new Date().toISOString(),rows=[...people.values()].map(p=>({member_id:memberId,person_key:p.key,actor_name:p.name,actor_url:p.url,last_seen_at:now}));
 for(let i=0;i<rows.length;i+=400)await rpcValue(supabase,"insight_followers_refresh_batch",{p_member:memberId,p_rows:rows.slice(i,i+400),p_baseline:baseline});
}
async function scanMember(memberId:string,forceBaseline=false){
 const{data:p,error}=await supabase.from("insight_notification_profiles").select("member_id,note_urlname,verified_at,public_watch_initialized_at,watch_cursor").eq("member_id",memberId).maybeSingle();if(error)throw error;if(!p?.note_urlname)throw new Error("NOTE_ID_REQUIRED");if(!p.verified_at)throw new Error("PROFILE_VERIFICATION_REQUIRED");
 const baseline=forceBaseline||!p.public_watch_initialized_at,creator=await fetchCreator(p.note_urlname);await supabase.from("insight_notification_profiles").update({note_nickname:creator.nickname,watch_error:null,updated_at:new Date().toISOString()}).eq("member_id",memberId);
 const pages=[1,2,3+Math.max(0,Number(p.watch_cursor||0))],articleMap=new Map<string,Article>();let rotatedLast=false;
 for(const page of [...new Set(pages)]){const r=await fetchArticles(p.note_urlname,page);for(const a of r.contents)articleMap.set(a.key,a);if(page===pages[2]&&r.isLast)rotatedLast=true;await sleep(120)}
 const keys=[...articleMap.keys()];const oldRows=keys.length?await supabase.from("insight_public_articles").select("article_key,like_count,comment_count").eq("member_id",memberId).in("article_key",keys):{data:[],error:null};if(oldRows.error)throw oldRows.error;
 const oldMap=new Map<string,any>((oldRows.data||[]).map((r:any)=>[String(r.article_key),r]));
 const{count:before}=await supabase.from("insight_notifications").select("id",{count:"exact",head:true}).eq("member_id",memberId),cutoff=Date.now()-7*86400000;let scanned=0;const updates:any[]=[];
 for(const a of articleMap.values()){
  const old=oldMap.get(a.key),oldLike=old?.like_count??a.likeCount,oldComment=old?.comment_count??a.commentCount,isRecent=a.publishAt&&!Number.isNaN(Date.parse(a.publishAt))&&Date.parse(a.publishAt)>=cutoff;
  try{if(baseline||!old||a.likeCount!==oldLike||Boolean(isRecent&&a.likeCount>0)){await syncLikes(memberId,a,baseline,oldLike);await sleep(100)}if(baseline||!old||a.commentCount!==oldComment||Boolean(isRecent)){try{await syncComments(memberId,a,creator.urlname,baseline,oldComment)}catch(e){if(!(e instanceof Error&&e.message==="NOTE_PUBLIC_403"))throw e}await sleep(100)}}catch(e){if(quotaError(e))throw e;console.error("article scan",a.key,e instanceof Error?e.message:e)}
  updates.push({member_id:memberId,article_key:a.key,title:a.title,url:a.url,publish_at:a.publishAt&&!Number.isNaN(Date.parse(a.publishAt))?new Date(a.publishAt).toISOString():null,like_count:a.likeCount,comment_count:a.commentCount,last_seen_at:new Date().toISOString()});scanned++;
 }
 await batchUpsert(supabase,"insight_public_articles",updates);await syncFollowers(memberId,creator.urlname,baseline);
 const now=new Date().toISOString(),nextCursor=rotatedLast?0:Math.max(0,Number(p.watch_cursor||0))+1;
 await supabase.from("insight_notification_profiles").update({public_watch_enabled:true,public_watch_initialized_at:p.public_watch_initialized_at??now,last_watch_at:now,watch_error:null,watch_cursor:nextCursor,updated_at:now}).eq("member_id",memberId);
 await supabase.from("insight_notification_sync_runs").insert({member_id:memberId,inserted_count:0,received_count:scanned,source:"public-watcher"});const{count:after}=await supabase.from("insight_notifications").select("id",{count:"exact",head:true}).eq("member_id",memberId);return{ok:true,baseline,articles:scanned,newNotifications:Math.max(0,(after??0)-(before??0)),lastWatchAt:now};
}
async function startVerification(req:Request){const m=await authIdentity(req);if(!m.noteUrlname)throw new Error("NOTE_ID_REQUIRED");const code=randomCode();await supabase.from("insight_notification_profiles").update({verification_code:code,verified_at:null,public_watch_enabled:false,watch_error:null,updated_at:new Date().toISOString()}).eq("member_id",m.id);return json({ok:true,verificationCode:code,noteUrlname:m.noteUrlname,profileUrl:`${NOTE_ORIGIN}/${m.noteUrlname}`})}
async function checkVerification(req:Request){const m=await authIdentity(req),{data:p}=await supabase.from("insight_notification_profiles").select("*").eq("member_id",m.id).maybeSingle();if(!p?.note_urlname||!p?.verification_code)throw new Error("VERIFICATION_NOT_STARTED");const creator=await fetchCreator(p.note_urlname);if(!creator.profile.includes(p.verification_code))throw new Error("VERIFICATION_CODE_NOT_FOUND");const now=new Date().toISOString();await supabase.from("insight_notification_profiles").update({verified_at:now,verification_code:null,public_watch_enabled:true,note_nickname:creator.nickname,updated_at:now}).eq("member_id",m.id);return json({ok:true,verified:true,scan:await scanMember(m.id,true)})}
async function watchNow(req:Request){const m=await authIdentity(req);return json(await scanMember(m.id,false))}
async function cronWatch(req:Request){if(await backgroundGate(supabase,req))return json({ok:true,paused:true,reason:"maintenance"});const{data:profiles,error}=await supabase.from("insight_notification_profiles").select("member_id").eq("public_watch_enabled",true).not("verified_at","is",null).limit(100);if(error)throw error;const results:any[]=[];for(const p of profiles??[]){try{results.push({memberId:p.member_id,...await scanMember(String(p.member_id),false)})}catch(e){if(quotaError(e))throw e;const msg=e instanceof Error?e.message:String(e);await supabase.from("insight_notification_profiles").update({watch_error:msg,last_watch_at:new Date().toISOString()}).eq("member_id",String(p.member_id));results.push({memberId:p.member_id,ok:false,error:msg})}await sleep(250)}return json({ok:true,scanned:results.length,results})}
async function dashboard(req:Request){const m=await authIdentity(req),id=m.id,[{data:rows,error},{data:p}]=await Promise.all([supabase.from("insight_notifications").select("id,notification_type,raw_text,actor_name,actor_url,target_title,target_url,source_url,occurred_at,captured_at,is_read,meta").eq("member_id",id).order("captured_at",{ascending:false}).limit(1500),supabase.from("insight_notification_profiles").select("note_urlname,note_nickname,role,verification_code,verified_at,public_watch_enabled,public_watch_initialized_at,last_watch_at,watch_error").eq("member_id",id).maybeSingle()]);if(error)throw error;const list=rows??[],counts:Record<string,number>={all:list.length,unread:0},people=new Map<string,number>(),articles=new Map<string,{title:string;url:string;count:number}>(),daily=new Map<string,number>();for(const n of list){counts[n.notification_type]=(counts[n.notification_type]??0)+1;if(!n.is_read)counts.unread++;if(n.actor_name)people.set(n.actor_name,(people.get(n.actor_name)??0)+1);if(n.target_url){const a=articles.get(n.target_url)??{title:n.target_title||n.target_url,url:n.target_url,count:0};a.count++;articles.set(n.target_url,a)}const dt=n.occurred_at||n.captured_at,key=String(dt).slice(0,10);daily.set(key,(daily.get(key)??0)+1)}return json({ok:true,member:{id,noteUrlname:p?.note_urlname??m.noteUrlname,noteNickname:p?.note_nickname??m.noteNickname,role:p?.role??m.role},watch:{verified:Boolean(p?.verified_at),verificationCode:p?.verification_code??null,enabled:Boolean(p?.public_watch_enabled),initializedAt:p?.public_watch_initialized_at??null,lastWatchAt:p?.last_watch_at??null,error:p?.watch_error??null},counts,notifications:list,topPeople:[...people.entries()].sort((a,b)=>b[1]-a[1]).slice(0,20).map(([name,count])=>({name,count})),topArticles:[...articles.values()].sort((a,b)=>b.count-a.count).slice(0,20),daily:[...daily.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-30).map(([date,count])=>({date,count}))})}
async function issueToken(req:Request){const m=await authIdentity(req),{data:p}=await supabase.from("insight_notification_profiles").select("verified_at").eq("member_id",m.id).maybeSingle();if(!p?.verified_at)throw new Error("PROFILE_VERIFICATION_REQUIRED");await supabase.from("insight_notification_ingest_tokens").update({revoked_at:new Date().toISOString()}).eq("member_id",m.id).is("revoked_at",null);const raw=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");await supabase.from("insight_notification_ingest_tokens").insert({member_id:m.id,token_hash:await sha256(raw)});return json({ok:true,ingestToken:raw})}
async function markRead(req:Request,body:any){const m=await authIdentity(req),ids=Array.isArray(body?.ids)?body.ids.filter((x:unknown)=>Number.isInteger(x)).slice(0,1000):[];let q=supabase.from("insight_notifications").update({is_read:body?.read!==false}).eq("member_id",m.id);if(ids.length)q=q.in("id",ids);const{error}=await q;if(error)throw error;return json({ok:true})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});try{const body=req.method==="POST"?await req.json().catch(()=>({})):{},action=body?.action||new URL(req.url).searchParams.get("action")||"dashboard";if(action==="owner-login")return await ownerLogin(body);if(action==="ingest")return await ingest(req,body);if(action==="start-verification")return await startVerification(req);if(action==="check-verification")return await checkVerification(req);if(action==="watch-now")return await watchNow(req);if(action==="cron-public-watch")return await cronWatch(req);if(action==="issue-token")return await issueToken(req);if(action==="mark-read")return await markRead(req,body);return await dashboard(req)}catch(e){const message=e instanceof Error?e.message:"UNKNOWN_ERROR",status=quotaError(e)?402:/REQUIRED|INVALID|INACTIVE|NOT_FOUND|NOT_STARTED/.test(message)?401:500;console.error(message);return json({ok:false,error:message},status)}});
