import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const ORIGIN="https://mumei-s.github.io";
const H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const{data:s}=await db.from("insight_member_sessions").select("application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const{data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),scope:noteId==="ss_yr"?"owner":String(a.id),noteId}}
function valid(v:any){if(!v)return null;const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),page=Math.max(1,Number(b.page||1)),pageSize=Math.min(100,Math.max(20,Number(b.pageSize||50))),offset=(page-1)*pageSize,direction=String(b.direction||"all"),change=String(b.change||"all"),dateFrom=valid(b.dateFrom),dateTo=valid(b.dateTo);let q=db.from("insight_relation_events").select("id,direction,event_type,person_key,actor_name,actor_url,actor_image_url,detected_at,change_count",{count:"exact"}).eq("member_id",m.scope).not("person_key","like","aggregate:%");if(direction==="followers"||direction==="followings")q=q.eq("direction",direction);if(change==="added"||change==="removed")q=q.eq("event_type",change);if(dateFrom)q=q.gte("detected_at",dateFrom);if(dateTo)q=q.lt("detected_at",dateTo);const[{data,error,count},{data:runs,error:re}]=await Promise.all([q.order("detected_at",{ascending:false}).range(offset,offset+pageSize-1),db.from("insight_relation_sync_runs").select("direction,expected_count,received_count,complete,created_at").eq("member_id",m.scope).eq("complete",true).order("created_at",{ascending:false}).limit(12)]);if(error)throw error;if(re)throw re;const latest:any={followers:null,followings:null};for(const r of runs||[]){const d=String(r.direction||"");if((d==="followers"||d==="followings")&&!latest[d])latest[d]=r}return out({ok:true,page,pageSize,total:count||0,rows:data||[],latest})}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
