import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import ts from 'typescript';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const plain=x=>JSON.parse(JSON.stringify(x));
function parser(t){const dom=new JSDOM('<main></main>',{url:'https://note.com/sitesettings/stats',runScripts:'outside-only'}),w=dom.window;t.after(()=>dom.window.close());w.fetch=async()=>Response.json({});const source=readFileSync('public/note-insight-dashboard-sync-core-v1.1.0.js','utf8'),end=source.indexOf("  window.addEventListener('DOMContentLoaded'");w.eval(source.slice(0,end)+'window.parser={dailyMetrics,mergeMetrics};})();');return w.parser}
test('公式の日別PVの0件を保持し、欠けたPVを0にしない',t=>{const p=parser(t),rows=plain(p.dailyMetrics({data:[{date:'2026-09-20',page_views:0},{date:'2026-09-21',likes:5},{date:'2026-09-22',page_views:15}]}));assert.equal(rows.length,3);assert.equal(rows[0].pageViews,0);assert.equal(rows[1].pageViews,null);assert.equal(rows[2].pageViews,15)});
test('グラフのラベル系列・日付キーの系列を日別値として読む',t=>{const p=parser(t),rows=plain(p.dailyMetrics({chart:{labels:['2026-09-20','2026-09-21'],datasets:[{label:'ページビュー',data:[12,0]}]},likes:{'2026-09-20':3,'2026-09-21':1}}));assert.deepEqual(rows.map(r=>[r.date,r.pageViews,r.likes]),[['2026-09-20',12,3],['2026-09-21',0,1]])});
test('記事単位・流入元のPVと月別集計を全体の日別PVに混ぜない',t=>{const p=parser(t);assert.deepEqual(plain(p.dailyMetrics({notes:[{date:'2026-09-20',title:'記事',key:'n1',page_views:900}],traffic:[{date:'2026-09-20',source:'search',pv:50}],monthly:{granularity:'monthly',data:[{date:'2026-09-01',page_views:9000}]}})),[])});
test('最新保存に日別値がなくても前の実績を残し、後日の公式訂正値を優先する',()=>{const s=readFileSync('supabase/functions/insight-dashboard-data/index.ts','utf8'),part=s.slice(s.indexOf('function dailyMetricSeries('),s.indexOf('async function analysis(')),ctx=vm.createContext({arr:v=>Array.isArray(v)?v:[],txt:v=>typeof v==='string'?v:''});vm.runInContext(ts.transpileModule(part+'this.daily=dailyMetricSeries;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx);const rows=plain(ctx.daily([{captured_at:'2026-09-20',metric_series:[{date:'2026-09-19',pageViews:50,likes:3}]},{captured_at:'2026-09-21',metric_series:[{date:'2026-09-19',pageViews:40},{date:'2026-09-20',pageViews:0}]},{captured_at:'2026-09-22',metric_series:[]}]));assert.deepEqual(rows.map(r=>[r.pageViews,r.likes]),[[40,3],[0,null]])});
test('曜日の平均は取得済み日だけで計算し、未取得曜日は欠損にする',()=>{const s=readFileSync('src/member-insight-analytics-pro-v3.tsx','utf8'),start=s.indexOf('function weekdayMetrics('),end=s.indexOf('\nfunction ',start+10),ctx=vm.createContext({avg:xs=>xs.reduce((a,b)=>a+b,0)/xs.length,n:v=>String(v)});vm.runInContext(ts.transpileModule(s.slice(start,end)+'\nthis.weekday=weekdayMetrics;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx);const rows=plain(ctx.weekday([{date:'2026-09-07',pageViews:10},{date:'2026-09-14',pageViews:0},{date:'2026-09-15',pageViews:null}]));assert.equal(rows.find(r=>r.label==='月曜').value,5);assert.equal(rows.find(r=>r.label==='火曜').value,null);assert.ok(rows.every(r=>r.label==='月曜'||r.value===null))});

test('指標名つきの座標・日付値ペア・JST timestampを日別として読む',t=>{const p=parser(t),rows=plain(p.dailyMetrics({series:[{name:'pv',data:[{x:'2026-09-20',y:0},['2026-09-21',24],{timestamp:Date.parse('2026-09-21T15:00:00Z'),value:50}]}]}));assert.deepEqual(rows.map(r=>[r.date,r.pageViews]),[['2026-09-20',0],['2026-09-21',24],['2026-09-22',50]]);assert.deepEqual(plain(p.dailyMetrics({pv:[{date:'2026-99-01',value:20}]})),[])});
