import test from 'node:test';
import assert from 'node:assert/strict';
import * as React from 'react';
import {sceneFixture,pause} from './react-scene-fixture.mjs';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
const record={id:'1',notification_type:'tip',display_category:'tip',actor_name:'テスト',actor_url:'https://note.com/creator',raw_text:'チップを受け取りました',captured_at:'2026-10-06T00:00:00Z',article_key:'n1',liker_key:'123',article_title:'記事',confirmed:false};
async function scene(t,type){const waits=[],calls=[];let saved=false;const h=await sceneFixture(t,{dependencies:{'./member-insight-magazines':{MemberInsightMagazines:()=>null},'./member-insight-dm':{MemberInsightDm:()=>null},'./creator-avatar':{CreatorAvatar:()=>null,creatorImage:()=>null,creatorNoteId:()=>''},'./insight-account-store':{INSIGHT_TOKEN_KEY:'fixture-token',currentStoredInsightAccount:()=>({noteId:'tester',memberToken:'fixture'}),setAccessIntent:()=>{}}},fetch:async(url,init)=>{const b=JSON.parse(init.body);calls.push(b);if(['like_completion','completion'].includes(b.action)){const wait=deferred();waits.push(wait);await wait.promise;saved=b.completed;return Response.json({ok:true,completed:saved})}if(b.action==='summary')return Response.json({member:{noteId:'tester',displayName:'テスト'},summary:{},analysis:{},counts:{},articles:[]});if(b.action==='likes')return Response.json({total:1,rows:[{...record,confirmed:saved}]});if(b.action==='recent')return Response.json({ok:true,noteId:'tester',rows:[]});if(String(url).includes('reclassify'))return Response.json({ok:true,checked:0,nextCursor:null});return Response.json({ok:true,noteId:'tester',rows:[{...record,confirmed:saved}],total:1,categoryCounts:{all:1,tip:1},statusCounts:{all:1,pending:saved?0:1,completed:saved?1:0}})}});h.w.localStorage.setItem('fixture-token','fixture');h.w.localStorage.setItem('mumei-notification-reclassify-version:tester','action-v28-context:evidence-v2-articles');h.w.scrollTo=()=>{};await h.render(h.load(type==='like'?'src/member-insight-unified-v4.tsx':'src/member-insight-notifications-final.tsx')[type==='like'?'MemberInsightUnifiedV4':'MemberInsightNotificationsFinal'],{noteId:'tester'});const selector=type==='like'?'.miu-handled':'.minf-completion button';return{...h,waits,calls,button:()=>h.w.document.querySelector(selector)}}
for(const type of ['like','notification']){
 test(`${type}: 押した同じ瞬間に点灯し、遅い保存中も取り消せる`,async t=>{const h=await scene(t,type);React.act(()=>{h.button().click();assert.equal(h.button().getAttribute('aria-pressed'),'true','same event, before any network response');assert.equal(h.button().disabled,false);h.button().click();assert.equal(h.button().getAttribute('aria-pressed'),'false')});assert.equal(h.waits.length,1,'one write in flight per row');await React.act(async()=>{h.waits[0].resolve();await pause()});assert.equal(h.waits.length,2);assert.equal(h.button().getAttribute('aria-pressed'),'false','old successful response cannot relight it');await React.act(async()=>{h.waits[1].resolve();await pause()});assert.deepEqual(h.calls.filter(b=>['completion','like_completion'].includes(b.action)).map(b=>b.completed),[true,false]);assert.equal(h.button().getAttribute('aria-pressed'),'false');assert.equal(h.button().getAttribute('aria-busy'),'false');const actions=type==='like'?'.miu-like-actions':'.minf-row-actions';assert.ok(h.button().closest(actions));assert.equal(h.w.document.querySelectorAll(actions).length,1)});
 test(`${type}: 取り消しの保存失敗では最後の保存状態へ戻す`,async t=>{const h=await scene(t,type);await h.click(h.button());await h.click(h.button());await React.act(async()=>{h.waits[0].resolve();await pause()});await React.act(async()=>{h.waits[1].reject(new Error('offline'));await pause()});assert.equal(h.button().getAttribute('aria-pressed'),'true');assert.match(h.w.document.querySelector(type==='like'?'.miu-error':'.minf-error').textContent,/元に戻/);if(type==='notification')assert.equal(JSON.parse(h.w.localStorage.getItem('mumei-notification-board:tester'))[0].confirmed,true,'retain the last acknowledged intermediate save')});
}
