import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=(p)=>readFile(new URL(`../${p}`,import.meta.url),"utf8");

test("production uses final unified wrapper",async()=>{const app=await read("src/App.tsx"),live=await read("src/member-insight-live-v2.tsx"),full=await read("src/member-insight-unified-v4.tsx");assert.match(app,/MemberInsightLiveV2/);for(const x of ["MemberInsightUnifiedV4","MemberInsightCompleteness","MemberInsightCommentsFinal","MemberInsightSocialV2","MemberInsightNotificationsFinal","MemberInsightAnalyticsFinal"])assert.match(live,new RegExp(x));for(const x of ["スキ履歴","スキ順位","コメント","コメント順位","マガジン","お気に入り","フォロー","通知","記事","アカウント切替"])assert.match(full,new RegExp(x));});

test("likes magazines favorites and archive regressions stay intact",async()=>{const full=await read("src/member-insight-unified-v4.tsx");for(const x of ["creator-icons","favorite_toggle","日ごと","月ごと","年ごと","参加人数","フォロワー","記事数","magazine_articles","favorite_articles","favorite_read_set","自分の記事・過去アーカイブ","insight-article-thumbnails","さらに40件表示"])assert.match(full,new RegExp(x));});

test("comments preserve workflow and exact counterpart final-reply heart",async()=>{const c=await read("src/member-insight-comments-final.tsx"),e=await read("supabase/functions/insight-member-extras/index.ts");for(const x of ["要対応","未返信","相手返信","あなたの♡で終了","自分返信","comment_articles","comments_filtered","comment_thread","insight-comment-hearts","counterpartHearted","最終返信に","さんの♡あり","さんの♡なし","<select value={page}"])assert.match(c,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace("<select value=\\{page\\}","<select value=\\{page\\}")));assert.match(e,/X-Insight-Token/);});

test("full article catalog and missing detail repair remain enabled",async()=>{const api=await read("supabase/functions/insight-member-api/index.ts"),note=await read("supabase/functions/insight-member-api/note.ts"),likes=await read("supabase/functions/insight-like-backfill/index.ts"),comments=await read("supabase/functions/insight-comment-refresh/index.ts");assert.match(api,/syncArticleCatalog/);assert.match(api,/page<=200/);assert.match(likes,/discoverCatalog/);assert.match(likes,/missingArticles/);assert.match(note,/disabled_pinned=true/);assert.match(note,/per_page=100/);assert.match(note,/api\/v1\/note\/\$\{id\}\/likes/);assert.match(comments,/insight_missing_comment_articles/);assert.match(comments,/upsert\(row/);});

test("social uses official totals plus latest-1000 capped follower tracking",async()=>{const s=await read("src/member-insight-social-v2.tsx"),css=await read("src/member-insight-live-v2.css"),rel=await read("supabase/functions/insight-relations/index.ts"),events=await read("supabase/functions/insight-social-events/index.ts");for(const x of ["フォロー・フォロワー","【増】","【減】","相手 → 本人","本人 → 相手","人物一覧","INSIGHT最終確認","note公式の実数値","最新1,000人","不明 −N"])assert.match(s,new RegExp(x));assert.match(s,/<select value=\{page\}/);assert.match(s,/action:"people"/);assert.match(s,/m\.get\(noteId\(x\.actor_url\)\)\|\|x\.actor_image_url/);assert.doesNotMatch(s,/最新を再同期/);assert.match(s,/startsWith\("aggregate:"\)/);assert.match(s,/startsWith\("unknown:"\)/);assert.match(css,/mode-social/);assert.match(css,/min-height:0!important/);for(const x of ["NOTE_IDENTITY_LIST_CAPPED_AT_1000","syncCappedFollowers","official_total_plus_latest_1000","unknownEvent","activeKeys\(scope,\"followings\"\)","removedCount=drop"])assert.match(rel,new RegExp(x));assert.match(events,/action==="people"/);assert.doesNotMatch(events,/last_seen_at.*10\*60\*1000/);});

test("notification feed uses canonical comments and complete categories",async()=>{const ui=await read("src/member-insight-notifications-final.tsx"),feed=await read("supabase/functions/insight-notification-feed-final/index.ts"),ingest=await read("supabase/functions/insight-notification-ingest-v2/index.ts");for(const x of ["人物フォロー","マガジンフォロー","自分の記事追加","マガジン記事追加","マガジン参加","メンシプ掲示板","メンシプ開始","プラン追加","メンシプ参加","購入","サポート","話題","高評価","ポイント","その他"])assert.match(ui,new RegExp(x));assert.match(ui,/v2\.9\.[23]/);assert.match(ui,/表示通知を読み込む/);assert.match(ui,/自分の記事がマガジンに追加/);assert.match(ui,/コメントに♡/);assert.match(feed,/insight_public_comments/);assert.match(feed,/canonical-public-comments/);assert.match(feed,/semanticKey/);assert.match(feed,/type==="other"/);assert.match(ingest,/classifier:"action-v8-v292-manual"/);assert.match(ingest,/note-notification-explicit-sync-v292/);assert.match(ingest,/actor_image_url/);});

test("v2.9.3 notification viewing is manual, lightweight, grouped and resilient",async()=>{const u=await read("public/note-insight-notification-sync.user.js"),setup=await read("public/notification-import.html"),entry=await read("public/notification-setup.html");assert.match(u,/@version\s+2\.9\.3/);assert.match(setup,/共通同期ツール v2\.9\.3/);assert.match(entry,/v2\.9\.3共通ツール/);assert.match(entry,/v=293/);assert.match(setup,/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);assert.match(setup,/iPhone Safari/);assert.match(setup,/Userscripts/);for(const x of ["閲覧のみ","表示通知を読み込む","過去通知を読み込む","mumei_insight_magazine_mute_ids_v5","mumei_insight_magazine_filter_enabled_v3","mumei_insight_notification_groups_v1","mumei_groups_sync","グループ分け","mumei-v293-fallback","retryPanel"])assert.match(u+setup,new RegExp(x));assert.match(u,/const enabled=Boolean\(await get\(key\(FILTER,accountId\),false\)\)/);assert.match(u,/box\.scrollTop=original/);assert.doesNotMatch(u,/\.click\(\)/);assert.doesNotMatch(u,/documentObserver/);assert.doesNotMatch(u,/observe\(document\.documentElement/);assert.doesNotMatch(u,/mumei_insight_magazine_mute_ids_v2:/);});

test("dashboard is manual and never leaves official settings stats path",async()=>{const u=await read("public/note-insight-notification-sync.user.js"),setup=await read("public/notification-import.html"),dash=await read("supabase/functions/insight-dashboard-data/index.ts");assert.match(setup,/https:\/\/note\.com\/sitesettings\/stats/);assert.doesNotMatch(setup,/https:\/\/note\.com\/stats["']/);assert.match(u,/startsWith\('\/sitesettings\/stats'\)/);assert.doesNotMatch(u,/startsWith\('\/stats'\)/);assert.match(u,/Dashboardを読み取る → INSIGHT反映/);assert.match(u,/note-dashboard-manual-v292/);assert.match(dash,/insight_dashboard_snapshots/);});

test("analysis shows real data only and refreshes saved dashboard data",async()=>{const a=await read("src/member-insight-analytics-final.tsx"),live=await read("src/member-insight-live-v2.tsx");assert.match(live,/✓ 分析表示中/);assert.match(a,/取得した実データだけをグラフ化/);assert.match(a,/グラフはまだ表示しません/);assert.match(a,/snapshots\.length<2/);assert.match(a,/setInterval/);for(const x of ["総VIEW推移","総スキ推移","総コメント推移","縦軸","横軸","最新"])assert.match(a,new RegExp(x));});

test("completeness separates public catalog totals from identity coverage",async()=>{const c=await read("src/member-insight-completeness.tsx"),api=await read("supabase/functions/insight-data-completeness/index.ts"),live=await read("src/member-insight-live-v2.tsx");assert.match(live,/MemberInsightCompleteness/);for(const x of ["DATA COMPLETENESS","公開データ確認済み","identityComplete","note公式総数と公開一覧","ダッシュボード","通知"])assert.match(c,new RegExp(x));for(const x of ["公開記事一覧","スキ総数","コメント総数","フォロワー総数","フォロー中総数","identityStored","identityExpected","publicExact=catalogComplete","runIdentityCount","RELATION_COUNT_MISMATCH","CAPPED_AT_"])assert.match(api,new RegExp(x));assert.doesNotMatch(api,/function relationCount\(/);assert.doesNotMatch(c,/記事一覧の再取得が必要|公開データ全件一致/);});

test("access session gate prevents login and dashboard flashing",async()=>{const app=await read("src/App.tsx"),access=await read("src/access-portal-v6.tsx"),main=await read("src/main.tsx"),sw=await read("public/sw.js"),recovery=await read("public/recovery.html");assert.match(app,/validatedMemberToken/);assert.match(app,/checkingMember/);assert.match(app,/ログイン状態を1回だけ確認しています/);assert.match(app,/action:"session"/);assert.match(app,/goTo\(hasMember \? "dashboard" : "access\/insight"\)/);assert.match(access,/アカウント切替/);assert.doesNotMatch(access,/type="password"/);assert.match(main,/if \(pwaTopLaunch\)/);assert.match(sw,/mumei-note-insight-v31/);assert.doesNotMatch(sw,/client\.navigate/);assert.match(recovery,/getRegistrations/);assert.match(recovery,/caches\.delete/);assert.doesNotMatch(recovery,/localStorage\.clear/);});
