import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=(p)=>readFile(new URL(`../${p}`,import.meta.url),"utf8");

test("production uses final unified wrapper",async()=>{const app=await read("src/App.tsx"),live=await read("src/member-insight-live-v2.tsx"),full=await read("src/member-insight-unified-v4.tsx");assert.match(app,/MemberInsightLiveV2/);for(const x of ["MemberInsightUnifiedV4","MemberInsightCompleteness","MemberInsightCommentsFinal","MemberInsightFavoritesFinal","MemberInsightSocialV2","MemberInsightNotificationsFinal","MemberInsightAnalyticsFinal"])assert.match(live,new RegExp(x));for(const x of ["スキ履歴","スキ順位","コメント","コメント順位","マガジン","お気に入り","フォロー","通知","記事","アカウント切替"])assert.match(full,new RegExp(x));});

test("likes magazines favorites and archive regressions stay intact",async()=>{const full=await read("src/member-insight-unified-v4.tsx");for(const x of ["creator-icons","favorite_toggle","日ごと","月ごと","年ごと","参加人数","フォロワー","記事数","magazine_articles","favorite_articles","favorite_read_set","自分の記事・過去アーカイブ","insight-article-thumbnails","さらに40件表示"])assert.match(full,new RegExp(x));});

test("comments preserve workflow and exact counterpart final-reply heart",async()=>{const c=await read("src/member-insight-comments-final.tsx"),e=await read("supabase/functions/insight-member-extras/index.ts");for(const x of ["要対応","未返信","相手返信","あなたの♡で終了","自分返信","comment_articles","comments_filtered","comment_thread","insight-comment-hearts","counterpartHearted","最終返信に","さんの♡あり","さんの♡なし","<select value={page}"])assert.match(c,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace("<select value=\\{page\\}","<select value=\\{page\\}")));assert.match(e,/X-Insight-Token/);});

test("full article catalog and missing detail repair remain enabled",async()=>{const api=await read("supabase/functions/insight-member-api/index.ts"),note=await read("supabase/functions/insight-member-api/note.ts"),likes=await read("supabase/functions/insight-like-backfill/index.ts"),comments=await read("supabase/functions/insight-comment-refresh/index.ts");assert.match(api,/syncArticleCatalog/);assert.match(api,/page<=200/);assert.match(likes,/discoverCatalog/);assert.match(likes,/missingArticles/);assert.match(note,/disabled_pinned=true/);assert.match(note,/per_page=100/);assert.match(note,/api\/v1\/note\/\$\{id\}\/likes/);assert.match(comments,/insight_missing_comment_articles/);assert.match(comments,/upsert\(row/);});

test("social uses official totals, latest-1000 tracking, and people list first",async()=>{const s=await read("src/member-insight-social-v2.tsx"),css=await read("src/member-insight-live-v2.css"),rel=await read("supabase/functions/insight-relations/index.ts"),events=await read("supabase/functions/insight-social-events/index.ts");for(const x of ["フォロー・フォロワー","【増】","【減】","相手 → 本人","本人 → 相手","人物一覧","INSIGHT最終確認","note公式の実数値","最新1,000人","不明 −N"])assert.match(s,new RegExp(x));assert.match(s,/useState<View>\("people"\)/);assert.ok(s.indexOf('>人物一覧</button>')<s.indexOf('>【増】【減】履歴</button>'));assert.match(s,/<select value=\{page\}/);assert.match(s,/action:"people"/);assert.match(s,/m\.get\(noteId\(x\.actor_url\)\)\|\|x\.actor_image_url/);assert.doesNotMatch(s,/最新を再同期/);assert.match(s,/startsWith\("aggregate:"\)/);assert.match(s,/startsWith\("unknown:"\)/);assert.match(css,/mode-social/);for(const x of ["NOTE_IDENTITY_LIST_CAPPED_AT_1000","syncCappedFollowers","official_total_plus_latest_1000","unknownEvent","removedCount=drop"])assert.match(rel,new RegExp(x));assert.match(rel,/activeKeys\(scope,"followings"\)/);assert.match(events,/action==="people"/);assert.doesNotMatch(events,/last_seen_at.*10\*60\*1000/);});

test("favorite groups are connected to production with explicit delete",async()=>{const live=await read("src/member-insight-live-v2.tsx"),ui=await read("src/member-insight-favorites-final.tsx"),group=await read("supabase/functions/insight-favorite-groups/index.ts"),css=await read("src/member-insight-live-v2.css");assert.match(live,/label==="お気に入り"/);assert.match(live,/mode==="favorites"/);assert.match(live,/MemberInsightFavoritesFinal/);assert.match(css,/mode-favorites/);for(const x of ["お気に入り・グループ管理","グループ作成","未分類","グループ管理","グループ削除","favorite_articles","favorite_read_set"])assert.match(ui,new RegExp(x));for(const x of ["insight_favorite_groups","insight_favorite_creators","insight_member_sessions"])assert.match(group,new RegExp(x));for(const x of ["list","create","assign","rename","delete"])assert.match(group,new RegExp(`a===?"${x}"`));});

test("notification feed includes board replies and v2.9.11 shortcuts",async()=>{const ui=await read("src/member-insight-notifications-final.tsx"),feed=await read("supabase/functions/insight-notification-feed-final/index.ts"),ingest=await read("supabase/functions/insight-notification-ingest-v2/index.ts");for(const x of ["人物フォロー","マガジンフォロー","自分の記事追加","マガジン記事追加","マガジン参加","メンシプ掲示板","掲示板返信","メンシプ開始","プラン追加","メンシプ参加","購入","サポート","話題","高評価","ポイント","その他"])assert.match(ui,new RegExp(x));assert.match(ui,/v2\.9\.11/);assert.match(ui,/v=2911/);assert.match(ui,/note公式Dashboardへ/);assert.match(ui,/https:\/\/note\.com\/sitesettings\/stats/);assert.match(ui,/表示分読込/);assert.match(ui,/過去まで読込/);assert.match(ui,/自動更新/);assert.match(ui,/クリーン遷移/);assert.match(ui,/setInterval\(refresh,2000\)/);assert.match(ui,/pageshow/);assert.doesNotMatch(ui,/今すぐ反映/);assert.match(ui,/自分の記事がマガジンに追加/);assert.match(ui,/コメントに♡/);assert.match(ui,/membership_board_reply/);assert.match(feed,/insight_public_comments/);assert.match(feed,/canonical-public-comments/);assert.match(feed,/semanticKey/);assert.match(feed,/membership_board_reply/);assert.match(feed,/type==="other"/);assert.match(ingest,/membership_board_reply/);assert.match(ingest,/actor_image_url/);});

test("v2.9.11 notification runtime preserves manual sync while install is browser-aware and verified",async()=>{const boot=await read("public/note-insight-notification-sync.user.js"),runtime=await read("public/note-insight-notification-runtime-v298.js"),setup=await read("public/notification-import.html"),entry=await read("public/notification-setup.html"),helper=await read("public/notification-install.html");assert.match(boot,/@version\s+2\.9\.11/);assert.match(boot,/@require\s+https:\/\/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-runtime-v298\.js\?v=2911/);assert.match(entry,/v2\.9\.11共通ツール/);assert.match(entry,/v=2911/);assert.match(entry,/端末とブラウザを自動判定/);for(const x of ["note-notification-manual-sync-v298","manualCurrent","manualSweep","mumei_insight_magazine_mute_ids_v5","mumei_insight_magazine_filter_enabled_v3","mumei_insight_notification_groups_v1","mumei_groups_sync","m297-filter-switch","setMasterFilter","setGroupEnabled","liveItems","panelUsable","resetPanel","retryPanel","GM_xmlhttpRequest","mumei_return","location.replace(back)"])assert.match(runtime+setup,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(setup,/display-mode: standalone/);assert.match(setup,/package=\$\{pkg\}/);assert.match(setup,/androidIntent\('com\.microsoft\.emmx'\)/);assert.match(setup,/androidIntent\('org\.mozilla\.firefox'\)/);assert.match(setup,/Safari＋Tampermonkey/);assert.match(setup,/Android Chrome/);assert.match(setup,/この端末の動線/);assert.match(setup,/このブラウザで v2\.9\.11/);assert.match(setup,/notification-install\.html/);assert.match(helper,/この先の流れ/);assert.match(helper,/このブラウザで v2\.9\.11/);assert.match(helper,/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);assert.match(helper,/mumei_insight_version_check=1/);assert.match(boot,/notificationInstalled/);assert.match(setup,/v2\.9\.11 実動確認済み/);assert.match(boot,/INSIGHT_NOTIFICATIONS/);assert.match(boot,/mumei-insight-return/);assert.match(boot,/repairToolbarHost/);assert.match(runtime,/読込→INSIGHT自動保存完了/);assert.match(runtime,/過去読込→INSIGHT自動保存完了/);assert.match(runtime,/box\.scrollTop=box\.scrollHeight/);assert.match(runtime,/box\.scrollTop=start/);assert.doesNotMatch(runtime,/autoSweep\(root\)/);assert.doesNotMatch(runtime,/scheduleSweep/);assert.doesNotMatch(runtime,/documentObserver/);assert.doesNotMatch(runtime,/observe\(document\.documentElement/);});

test("dashboard auto-sync stays intact while dashboard bell hard-resets to clean note",async()=>{const boot=await read("public/note-insight-notification-sync.user.js"),runtime=await read("public/note-insight-notification-runtime-v298.js"),setup=await read("public/notification-import.html"),dash=await read("supabase/functions/insight-dashboard-data/index.ts");assert.match(setup,/https:\/\/note\.com\/sitesettings\/stats/);assert.doesNotMatch(setup,/https:\/\/note\.com\/stats["']/);assert.match(runtime,/startsWith\('\/sitesettings\/stats'\)/);assert.match(runtime,/note-dashboard-auto-v298/);assert.match(runtime,/#mumei-v297-dashboard\{position:fixed!important/);assert.match(runtime,/saveDashboardAuto/);assert.doesNotMatch(runtime,/host\.prepend/);assert.doesNotMatch(runtime,/Dashboardを読み取る → INSIGHT反映/);assert.match(boot,/mumei_open_notice_v2911/);assert.match(boot,/stopImmediatePropagation/);assert.match(boot,/https:\/\/note\.com\/\?\$\{CLEAN_NOTICE\}=1/);assert.match(boot,/openBellAfterCleanNavigation/);assert.match(dash,/insight_dashboard_snapshots/);assert.match(dash,/limit\(500\)/);});

test("analysis is manual, includes 60 days, exact values, numbered points and pie verification",async()=>{const a=await read("src/member-insight-analytics-final.tsx"),css=await read("src/member-insight-analytics-final.css"),live=await read("src/member-insight-live-v2.tsx");for(const x of ["フォロワー推移","フォロワー日次増減","直近のフォロワー実数記録","60日","記事別VIEW構成比","記事VIEW合計","Dashboard総VIEW","記事別 VIEW × スキ","記事別 VIEW × 総反応率","丸の数字は下の一覧番号","記事ごとの反応分析","スキ率＝スキ÷VIEW","累計VIEW推移","累計スキ推移","累計コメント推移","グラフをタップ＝その日の正確な値"])assert.match(a,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(a,/useEffect\(\(\)=>\{void refresh\(\)\},\[\]\)/);assert.doesNotMatch(a,/setInterval/);assert.doesNotMatch(a,/visibilitychange/);assert.match(a,/ArticleViewPie/);assert.match(a,/ArticleReactionTable/);assert.match(a,/reactionRate/);for(const x of ["miaf-chart-readout","miaf-pie-table","miaf-pie-check","miaf-point-key","miaf-selected-value","miaf-scatter-readout"])assert.match(css,new RegExp(x));assert.match(css,/miaf-table-scroll/);assert.match(css,/-webkit-line-clamp:2/);assert.match(live,/openMode\("analysis"\)/);});

test("global data plus latest refresh covers every INSIGHT panel",async()=>{const live=await read("src/member-insight-live-v2.tsx");for(const x of ["INSIGHT全体の公開履歴を更新中","INSIGHT全体・データ＋アプリ最新版を更新しました","fullRefreshSeq","mumei-insight-refresh-all","記事・スキ・コメント・お気に入り・フォロー・通知保存データ・分析表示","key={`analysis-${fullRefreshSeq}`}"])assert.match(live,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("INSIGHT subviews preserve scroll position and direct notification deep links",async()=>{const live=await read("src/member-insight-live-v2.tsx"),app=await read("src/App.tsx");assert.match(live,/history\.pushState/);assert.match(live,/insightMode/);assert.match(live,/requestedMode/);assert.match(live,/searchParams\.delete\("insightMode"\)/);assert.match(live,/insightScrollY/);assert.match(live,/const y=window\.scrollY/);assert.match(live,/scrollTo\(\{top:y,behavior:"auto"\}\)/);assert.doesNotMatch(live,/scrollTo\(\{top:0,behavior:"auto"\}\)/);assert.match(live,/window\.history\.back\(\)/);assert.match(app,/大元TOP｜ここで端末の「戻る」を押すと終了/);});

test("TOP twice exits while note button is plain navigation and never logs out",async()=>{const index=await read("index.html"),home=await read("src/hub-home.tsx"),app=await read("src/App.tsx");assert.match(app,/note-exit/);assert.match(app,/aria-label="noteへ"/);assert.match(app,/https:\/\/note\.com\//);assert.match(app,/もう1回で終了/);assert.match(app,/function exitApp/);assert.match(app,/android\.intent\.action\.MAIN/);assert.match(app,/android\.intent\.category\.HOME/);assert.doesNotMatch(app,/note-exit[^\n]*アプリ終了/);assert.doesNotMatch(index,/app-exit-to-note/);assert.doesNotMatch(home,/hub-note-exit-wrap|hub-note-exit/);assert.doesNotMatch(app,/forgetMemberSession|forgetInsightAccount/);assert.match(home,/ログアウト/);assert.match(home,/退会/);});

test("join login and account switch always open the access portal even while logged in",async()=>{const app=await read("src/App.tsx"),home=await read("src/hub-home.tsx"),access=await read("src/access-portal-v6.tsx");assert.match(app,/route === "access\/insight"\) page = <AccessPortalV6 \/>/);assert.doesNotMatch(app,/route === "access\/insight"\) page = memberValid/);assert.match(app,/function memberRoute\(route: string\) \{ return route === "owner-insight"/);for(const x of ["openAccess(accounts.length ? \"switch\" : \"login\")","openAccess(\"apply\")","setAccessIntent(intent)"])assert.match(home,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(access,/consumeAccessIntent/);assert.match(access,/intent === "apply"/);assert.match(access,/intent === "switch" \|\| intent === "login"/);assert.match(access,/switchAccount/);});

test("owner management is double-locked and can force a participant out",async()=>{const manage=await read("src/management-page.tsx"),api=await read("supabase/functions/insight-access/index.ts");for(const x of ["X-Admin-Pass","管理パスワード","強制退会","owner-remove","OWNER本人認証＋管理パスワードの二重ロック"])assert.match(manage+api,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(api,/ADMIN_PASS_SHA/);assert.match(api,/requireAdminPassword/);assert.match(api,/originAllowed/);assert.match(api,/ORIGIN_NOT_ALLOWED/);assert.match(api,/insight_notification_ingest_tokens/);assert.match(api,/Cache-Control/);assert.match(api,/X-Content-Type-Options/);assert.doesNotMatch(manage+api,/mumei4444/);});

test("completeness separates public catalog totals from identity coverage",async()=>{const c=await read("src/member-insight-completeness.tsx"),api=await read("supabase/functions/insight-data-completeness/index.ts"),live=await read("src/member-insight-live-v2.tsx");assert.match(live,/MemberInsightCompleteness/);for(const x of ["DATA COMPLETENESS","公開データ確認済み","identityComplete","note公式総数と公開一覧","ダッシュボード","通知"])assert.match(c,new RegExp(x));for(const x of ["公開記事一覧","スキ総数","コメント総数","フォロワー総数","フォロー中総数","identityStored","identityExpected","publicExact=catalogComplete","runIdentityCount","RELATION_COUNT_MISMATCH","CAPPED_AT_"])assert.match(api,new RegExp(x));assert.doesNotMatch(api,/function relationCount\(/);});

test("access session gate prevents login and dashboard flashing",async()=>{const app=await read("src/App.tsx"),access=await read("src/access-portal-v6.tsx"),main=await read("src/main.tsx"),sw=await read("public/sw.js"),recovery=await read("public/recovery.html");assert.match(app,/validatedMemberToken/);assert.match(app,/checkingMember/);assert.match(app,/ログイン状態を1回だけ確認しています/);assert.match(app,/action:"session"/);assert.match(app,/goTo\(hasMember \? "dashboard" : "access\/insight"\)/);assert.match(access,/アカウント切替/);assert.doesNotMatch(access,/type="password"/);assert.match(main,/if \(pwaTopLaunch\)/);assert.match(sw,/mumei-note-insight-v31/);assert.doesNotMatch(sw,/client\.navigate/);assert.match(recovery,/getRegistrations/);assert.match(recovery,/caches\.delete/);assert.doesNotMatch(recovery,/localStorage\.clear/);});
