import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {sceneFixture} from './react-scene-fixture.mjs';
const read=p=>readFileSync(p,'utf8');
test('スキ対応済みは本人のスキだけに保存し、別人の項目は変更しない',async()=>{let saved;const db={from(table){let scope;const q={select:()=>q,eq:(k,v)=>{if(k==='member_id')scope=v;return q},maybeSingle:async()=>({data:scope==='member-a'?{}:null}),upsert:async v=>(saved=v,{error:null}),delete:()=>q,match:async()=>({error:null})};return q}};const source=read('supabase/functions/insight-member-history/index.ts'),part=source.slice(source.indexOf('async function likeCompletion('),source.indexOf('async function likes(')),c=vm.createContext({db,txt:v=>String(v)});vm.runInContext(ts.transpileModule(part+'\nthis.complete=likeCompletion',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,c);await c.complete({scope:'member-a'},{articleKey:'n1',likerKey:'a',completed:true});assert.equal(saved.member_id,'member-a');assert.equal(saved.item_key,'n1:a');await assert.rejects(c.complete({scope:'member-b'},{articleKey:'n1',likerKey:'a',completed:true}),/LIKE_NOT_FOUND/);assert.equal(saved.member_id,'member-a')});
test('スキ履歴に対応済みボタンを表示し、状態を保存・復元する',async t=>{let confirmed=false;const calls=[];const h=await sceneFixture(t,{dependencies:{'./member-insight-magazines':{MemberInsightMagazines:()=>null},'./member-insight-dm':{MemberInsightDm:()=>null},'./creator-avatar':{CreatorAvatar:()=>null,creatorImage:()=>null},'./insight-account-store':{INSIGHT_TOKEN_KEY:'fixture-token',currentStoredInsightAccount:()=>({noteId:'tester',memberToken:'fixture'}),setAccessIntent:()=>{}}},fetch:async(input,init)=>{const b=JSON.parse(init.body);calls.push(b);if(b.action==='summary')return Response.json({member:{noteId:'tester',displayName:'テスト'},summary:{},analysis:{},counts:{},articles:[]});if(b.action==='likes')return Response.json({total:1,rows:[{article_key:'n1',liker_key:'creator',actor_name:'クリエイター',article_title:'記事',liked_at:'2026-10-06T00:00:00Z',confirmed}]});if(b.action==='like_completion'){confirmed=b.completed;return Response.json({ok:true,completed:confirmed})}return Response.json({})}});h.w.localStorage.setItem('fixture-token','fixture');h.w.scrollTo=()=>{};await h.render(h.load('src/member-insight-unified-v4.tsx').MemberInsightUnifiedV4,{});let button=[...h.w.document.querySelectorAll('button')].find(b=>b.textContent==='対応済みにする');assert.ok(button);await h.click(button);assert.ok(calls.some(b=>b.action==='like_completion'&&b.articleKey==='n1'&&b.likerKey==='creator'));button=[...h.w.document.querySelectorAll('button')].find(b=>b.textContent.includes('未対応に戻す'));assert.equal(button.getAttribute('aria-pressed'),'true');await h.click(button);assert.equal(confirmed,false)});
