import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
function helpers(p,names){let source=read(p).replace(/^import .*;\n/gm,'');const ctx={createClient:()=>({}),Deno:{env:{get:()=>''},serve:()=>{}},console,URL,Date,Intl,Map,Set,Number,JSON};vm.createContext(ctx);source+='\nglobalThis.result={'+names.join(',')+'};';vm.runInContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,ctx);return ctx.result}
test('important actions beat words in article title',()=>{const {classify,allowedExplicitSource}=helpers('supabase/functions/insight-notification-ingest-v2/index.ts',['classify','allowedExplicitSource']);assert.equal(classify('あなたの記事がメンバーシップ応援に追加されました スキしましたという題名3分前','https://note.com/a/m/m1'),'my_article_magazine_added');assert.equal(classify('Aさんがあなたのコメントに返信しました メンバーシップのスキ3分前','https://note.com/a/n/n1?c=c1'),'reply');assert.equal(classify('Aさんがあなたのメンバーシップに参加しました スキした人','https://note.com/ss_yr/membership'),'membership_join');assert.equal(allowedExplicitSource('note-notification-manual-sync-v2968'),true);assert.equal(allowedExplicitSource('note-notification-passive-sync'),false)});
test('different article additions survive dedupe',()=>{const {dedupe,decorate}=helpers('supabase/functions/insight-notification-feed-final/index.ts',['dedupe','decorate']);const base={notification_type:'my_article_magazine_added',actor_url:'https://note.com/a',target_url:'https://note.com/a/m/m1',occurred_at:'2026-09-13T00:00:00Z',meta:{source:'note-notification-manual-sync-v2968'}};assert.equal(dedupe([{...base,raw_text:'あなたの記事がMに追加されました 記事A'},{...base,raw_text:'あなたの記事がMに追加されました 記事B'}]).length,2);assert.equal(decorate({notification_type:'membership_reaction',target_url:'https://note.com/membership'},'ss_yr').display_category,'membership_reaction_unknown')});
test('private analysis excludes public duplicate rows',()=>{const {useful,summarize}=helpers('supabase/functions/insight-notification-analysis-summary/index.ts',['useful','summarize']);for(const notification_type of ['reply','membership_join','my_article_magazine_added','other'])assert.equal(useful({notification_type,raw_text:'通知です',meta:{source:'note-notification-manual-sync-v2968'}}),true);for(const notification_type of ['like','follow','comment','creator_article_posted'])assert.equal(useful({notification_type,raw_text:'通知です',meta:{source:'note-notification-manual-sync-v2968'}}),false);assert.equal(summarize([],'ss_yr',false,0).sample,0)});
test('active package uses V3.2.8 rescue dock and independent component startup',()=>{const manifest=JSON.parse(read('public/insight-release.json')),v3=read('public/note-insight-notification-v3.user.js'),setup=read('public/tool-setup.html'),dock=read('public/note-insight-notification-dock-watch-v312.js'),reader=read('public/note-insight-notification-reader-v322.js'),loader=read('public/note-insight-notification-loader-v318.js'),picker=read('src/insight-notification-ui-v18.ts'),feed=read('supabase/functions/insight-notification-feed-final/index.ts');assert.equal(manifest.appVersion,'2026.09.16.3');assert.equal(manifest.notificationVersion,'3.2.8');assert.equal(manifest.dashboardVersion,'1.4.4');assert.match(v3,/@version\s+3\.2\.8/);assert.match(v3,/raw\.githubusercontent\.com/);assert.match(v3,/runtime-checked-v328/);assert.match(v3,/mumei-v3-rescue-dock-v328/);assert.match(v3,/function startRescue\(\)/);assert.match(v3,/async function loadPart\(name\)/);assert.ok(v3.indexOf("loadPart('note-insight-notification-dock-watch-v312.js')")<v3.indexOf("loadPart('note-insight-notification-reader-v322.js')"));assert.doesNotMatch(v3.split("// ==/UserScript==")[0],/@require/);assert.match(setup,/INSIGHTをインストール \/ 更新/);assert.match(setup,/https:\/\/note\.com\/notifications/);assert.match(dock,/repeat\(4,minmax\(0,1fr\)\)/);assert.match(dock,/touch-action:manipulation/);assert.doesNotMatch(dock,/pointerdown|pointerup|touch-action:none/);assert.match(reader,/confirmedClientSignatures/);assert.match(reader,/rediscoverPanel/);assert.match(loader,/mumei-dashboard-flow-v143/);assert.match(picker,/通知項目：/);assert.match(feed,/\["like","follow","comment","creator_article_posted"\]/)});
test('seven-day selection still compares against preceding seven days',()=>{const {summarize}=helpers('supabase/functions/insight-notification-analysis-summary/index.ts',['summarize']);const row=days=>({notification_type:'my_article_magazine_added',occurred_at:new Date(Date.now()-days*86400000).toISOString(),actor_name:'A'});const recent=row(1),previous=row(9);const r=summarize([recent],'ss_yr',false,1,7,[recent,previous]);assert.equal(r.recent7,1);assert.equal(r.prev7,1);assert.equal(r.ownArticleAdds,1)});
