import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import * as React from 'react';
import {JSDOM} from 'jsdom';
import {sceneFixture,pause} from './react-scene-fixture.mjs';
const read=p=>readFileSync(p,'utf8'),feed=read('supabase/functions/insight-notification-feed-final/index.ts');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
const row=(id,confirmed=false)=>({id,notification_type:'tip',display_category:'tip',actor_name:'クリエイター',actor_url:'https://note.com/creator',actor_image_url:'https://example.test/avatar.png',raw_text:'チップを受け取りました',captured_at:'2026-10-06T00:00:00Z',confirmed,favorite:false});
function response(rows,status='all',kind='all'){const category=kind==='all'?rows:rows.filter(r=>r.display_category===kind),selected=category.filter(r=>status==='all'||(status==='completed')===Boolean(r.confirmed));return Response.json({ok:true,noteId:'tester',rows:selected,total:selected.length,categoryCounts:{all:selected.length,tip:selected.length},statusCounts:{all:category.length,pending:category.filter(r=>!r.confirmed).length,completed:category.filter(r=>r.confirmed).length}})}
async function notificationScene(t,{rows=[row('1')],completion=async b=>({completed:b.completed}),favorite=async b=>({favorite:b.favorite,creatorKey:'creator'})}={}){const calls=[];const h=await sceneFixture(t,{globals:{location:new URL('https://mumei-s.github.io/note-insight/'),URLSearchParams},fetch:async(url,init)=>{const b=JSON.parse(init.body);calls.push(b);if(b.action==='completion'){const x=await completion(b);rows.find(r=>r.id===b.id).confirmed=x.completed;return Response.json({ok:true,...x})}if(b.action==='favorite_toggle'){const x=await favorite(b);for(const r of rows)r.favorite=x.favorite;return Response.json({ok:true,...x})}if(b.action==='recent')return Response.json({ok:true,noteId:'tester',rows:[]});if(String(url).includes('reclassify'))return Response.json({ok:true,checked:0,nextCursor:null});if(String(url).includes('feed-final'))return response(rows,b.handlingStatus,b.kind);return Response.json({})}});h.w.localStorage.setItem('mumei-insight-access-token','fixture');h.w.localStorage.setItem('mumei-notification-reclassify-version:tester','action-v28-context:evidence-v2-articles');await h.render(h.load('src/member-insight-notifications-final.tsx').MemberInsightNotificationsFinal,{noteId:'tester'});return{...h,calls,rows}}
test('本人通知の対応済みは保存待ちでも即時点灯し、未保存状態は履歴へ確定しない',async t=>{const wait=deferred(),h=await notificationScene(t,{completion:()=>wait.promise});const count=h.calls.length;await h.click(h.w.document.querySelector('.minf-completion button'));const button=h.w.document.querySelector('.minf-completion button');assert.equal(button.getAttribute('aria-pressed'),'true');assert.equal(button.getAttribute('aria-busy'),'true');assert.match(button.className,/is-flashing/);assert.equal(h.calls.length,count+1);assert.equal(JSON.parse(h.w.localStorage.getItem('mumei-notification-board:tester'))[0].confirmed,false);await React.act(async()=>{wait.resolve({completed:true});await pause()});assert.equal(JSON.parse(h.w.localStorage.getItem('mumei-notification-board:tester'))[0].confirmed,true);assert.equal(h.calls.length,count+1,'click must not trigger a complete feed reload')});
test('未対応から即時に隠した後、保存失敗なら元の行を復元する',async t=>{const wait=deferred(),h=await notificationScene(t,{completion:()=>wait.promise});await h.click(h.w.document.querySelector('.minf-handling-tabs button:nth-child(2)'));await h.click(h.w.document.querySelector('.minf-completion button'));assert.equal(h.w.document.querySelector('.minf-list'),null);await React.act(async()=>{wait.reject(new Error('offline'));await pause()});assert.equal(h.w.document.querySelector('.minf-completion button').getAttribute('aria-pressed'),'false');assert.match(h.w.document.querySelector('.minf-error').textContent,/元に戻/);assert.equal(JSON.parse(h.w.localStorage.getItem('mumei-notification-board:tester'))[0].confirmed,false)});
test('本人通知の対応済み一覧に保存した行が入り、取り消すと未対応へ戻る',async t=>{const h=await notificationScene(t,{rows:[row('1'),row('2')]});await h.click(h.w.document.querySelector('.minf-completion button'));await h.click(h.w.document.querySelector('.minf-handling-tabs button:nth-child(3)'));assert.equal(h.w.document.querySelectorAll('.minf-list article').length,1);assert.equal(h.calls.at(-1).handlingStatus,'completed');await h.click(h.w.document.querySelector('.minf-completion button'));assert.equal(h.w.document.querySelector('.minf-list'),null);await h.click(h.w.document.querySelector('.minf-handling-tabs button:nth-child(2)'));assert.equal(h.w.document.querySelectorAll('.minf-list article').length,2)});
test('本人通知の★は同じ人物の全行へ即反映し、既存お気に入りへの行き先を表示',async t=>{const wait=deferred(),h=await notificationScene(t,{rows:[row('1'),row('2')],favorite:()=>wait.promise});await h.click(h.w.document.querySelector('.minf-star'));assert.deepEqual([...h.w.document.querySelectorAll('.minf-star')].map(b=>b.textContent),['★','★']);assert.ok([...h.w.document.querySelectorAll('.minf-star')].every(b=>b.disabled));assert.equal(h.w.document.querySelector('.minf-handling-tabs a').getAttribute('href'),'?insightMode=favorites#dashboard');await React.act(async()=>{wait.resolve({favorite:true,creatorKey:'numeric-existing'});await pause()});assert.ok(JSON.parse(h.w.localStorage.getItem('mumei-notification-board:tester')).every(r=>r.favorite));assert.equal(h.w.document.querySelector('.minf-star').disabled,false)});
test('本人通知の★保存失敗は全行を戻し、失敗を知らせる',async t=>{const h=await notificationScene(t,{favorite:async()=>{throw new Error('offline')}});await h.click(h.w.document.querySelector('.minf-star'));assert.equal(h.w.document.querySelector('.minf-star').textContent,'☆');assert.match(h.w.document.querySelector('.minf-error').textContent,/お気に入り.*元に戻/)});
test('対応済み保存中に別アカウントへ切り替えた応答は新アカウントへ保存しない',async t=>{const wait=deferred(),h=await notificationScene(t,{completion:()=>wait.promise});await h.click(h.w.document.querySelector('.minf-completion button'));h.w.localStorage.setItem('mumei-insight-access-token','other-fixture');await React.act(async()=>{wait.resolve({completed:true});await pause()});assert.equal(JSON.parse(h.w.localStorage.getItem('mumei-notification-board:tester'))[0].confirmed,false);assert.equal(h.w.localStorage.getItem('mumei-notification-board:other'),null)});
function compile(source,globals){const c=vm.createContext({URL,Date,Intl,...globals});vm.runInContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,c);return c}
test('サーバーの対応状況別表示は分類・日付を保って全履歴から抽出する',()=>{const source=feed.slice(feed.indexOf('function handlingMatch('),feed.indexOf('function commentIdentity(')),c=compile(source+'\nthis.select=selectHandling',{jstDay:v=>String(v).slice(0,10)}),rows=[row('1'),row('2',true),{...row('3',true),display_category:'reply_other'},{...row('4',true),captured_at:'2026-10-05T00:00:00Z'}];const result=c.select(rows,'tip','2026-10-06','completed');assert.deepEqual(result.selected.map(r=>r.id),['2']);assert.equal(result.statusCounts.pending,1);assert.equal(result.statusCounts.completed,1);assert.equal(result.statusCounts.all,2)});
function mockDatabase(records,initialFavorites){const tables={insight_notifications:records,insight_favorite_creators:initialFavorites.map(x=>({...x}))},writes=[];return{tables,writes,from(table){const filters=[];let payload,remove=false;const q={select(){return q},eq(k,v){filters.push(r=>String(r[k])===String(v));return q},in(k,values){filters.push(r=>values.includes(r[k]));return q},upsert(v){payload=v;return q},delete(){remove=true;return q},async maybeSingle(){return{data:tables[table].find(r=>filters.every(f=>f(r)))||null,error:null}},then(y,n){const found=tables[table].filter(r=>filters.every(f=>f(r)));if(payload){writes.push({table,payload});const existing=tables[table].find(r=>r.member_id===payload.member_id&&r.creator_key===payload.creator_key);if(existing)Object.assign(existing,payload);else tables[table].push(payload)}if(remove){writes.push({table,remove:true});tables[table]=tables[table].filter(r=>!filters.every(f=>f(r)))}return Promise.resolve({data:found,error:null}).then(y,n)}};return q}}}
test('通知★は認証済み本人の既存お気に入りキーを再利用し、別人の通知を拒否する',async()=>{const db=mockDatabase([{...row('1'),member_id:'a'},{...row('2'),member_id:'b'}],[{member_id:'a',creator_key:'12345',actor_url:'https://note.com/creator'},{member_id:'b',creator_key:'678',actor_url:'https://note.com/creator'}]),source=feed.slice(feed.indexOf('const completionKey='),feed.indexOf('function commentIdentity(')),c=compile(source+'\nthis.favorite=notificationFavorite;this.decorateRows=decorateHandling;',{db,decorate:r=>r}),m={scope:'a',id:'a',noteId:'tester'};await c.favorite(m,{id:'1',favorite:true});assert.equal(db.writes[0].payload.creator_key,'12345');assert.equal(db.tables.insight_favorite_creators.length,2);await assert.rejects(c.favorite(m,{id:'2',favorite:true}),/NOTIFICATION_NOT_FOUND/);await c.favorite(m,{id:'1',favorite:false});assert.equal(db.tables.insight_favorite_creators.length,1);assert.equal(db.tables.insight_favorite_creators[0].member_id,'b')});
test('通常履歴の★も通知から登録したURLを同じお気に入りと判定・解除する',async()=>{const db=mockDatabase([],[{member_id:'a',creator_key:'creator',actor_url:'https://note.com/creator'},{member_id:'b',creator_key:'creator',actor_url:'https://note.com/creator'}]),source=read('supabase/functions/insight-member-history/index.ts'),helpers=source.slice(source.indexOf('const favoriteUrl='),source.indexOf('async function summary('))+source.slice(source.indexOf('async function favoriteToggle('),source.indexOf('async function articlesPage(')),c=compile(helpers+'\nthis.withFavorites=withFavorites;this.toggle=favoriteToggle;',{db,txt:v=>String(v)});assert.equal((await c.withFavorites({scope:'a'},[{liker_key:'12345',actor_url:'https://note.com/creator'}],'liker_key'))[0].favorite,true);await c.toggle({scope:'a'},{creatorKey:'12345',actorUrl:'https://note.com/creator',favorite:false});assert.equal(db.tables.insight_favorite_creators.length,1);assert.equal(db.tables.insight_favorite_creators[0].member_id,'b')});
test('公式🔔パネルは進捗とON/OFF案内を同じ段に保ち、読込・停止操作を維持',async t=>{const d=new JSDOM('<main id="panel">通知</main>',{url:'https://note.com/',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;t.after(()=>w.close());w.HTMLElement.prototype.getBoundingClientRect=()=>({width:390,height:100});w.GM={getValue:async(k,v)=>v,setValue:async()=>{}};w.fetch=async()=>Response.json({data:{urlname:'tester'}});w.__mumeiNotificationReaderV4={findPanel:()=>w.document.getElementById('panel')};w.eval(read('public/note-insight-notification-controls-v1.js'));w.__mumeiNotificationControlsV1.mount();await new Promise(r=>setTimeout(r,30));const bar=w.document.getElementById('mumei-inline-notification-controls-v1');assert.equal(bar.querySelector('.read-status').parentElement,bar.querySelector('.panel-settings').parentElement);assert.equal(bar.querySelector('.panel-settings').textContent,'ON/OFFはメイン🔔から');w.dispatchEvent(new w.CustomEvent('mumei-notification-reader-status',{detail:{state:'saving',busy:true,phase:'saving',readCount:20,savedCount:5,total:20}}));assert.match(bar.querySelector('.read-status').textContent,/保存/);assert.equal(bar.querySelectorAll('button').length,5)});
test('小型対応済みの高さと色・発光が端末別の大きいボタン指定に上書きされない',()=>{for(const file of ['src/member-insight-unified-v4.css','src/member-insight-notifications-final.css']){const s=read(file);assert.match(s,/html\[data-insight-layout\].*min-height:30px!important/);assert.match(s,/background:#102432/);assert.match(s,/@keyframes .*handled-flash/);assert.match(s,/prefers-reduced-motion:reduce/)}assert.match(read('public/note-insight-notification-v3.user.js'),/controls-v1\.js\?v=153/)});
async function likesScene(t,save){const calls=[];let confirmed=false;const h=await sceneFixture(t,{dependencies:{'./member-insight-magazines':{MemberInsightMagazines:()=>null},'./member-insight-dm':{MemberInsightDm:()=>null},'./creator-avatar':{CreatorAvatar:()=>null,creatorImage:()=>null},'./insight-account-store':{INSIGHT_TOKEN_KEY:'fixture-token',currentStoredInsightAccount:()=>({noteId:'tester',memberToken:'fixture'}),setAccessIntent:()=>{}}},fetch:async(input,init)=>{const b=JSON.parse(init.body);calls.push(b);if(b.action==='summary')return Response.json({member:{noteId:'tester',displayName:'テスト'},summary:{},analysis:{},counts:{},articles:[]});if(b.action==='likes')return Response.json({total:1,rows:[{article_key:'n1',liker_key:'123',actor_name:'クリエイター',article_title:'記事',confirmed}]});if(b.action==='like_completion'){await save(b);confirmed=b.completed;return Response.json({ok:true,completed:confirmed})}return Response.json({})}});h.w.localStorage.setItem('fixture-token','fixture');h.w.scrollTo=()=>{};await h.render(h.load('src/member-insight-unified-v4.tsx').MemberInsightUnifiedV4,{});return{...h,calls}}
test('通常スキの対応済みも保存待ち前に即反応し、保存後に一覧を再取得しない',async t=>{const wait=deferred(),h=await likesScene(t,()=>wait.promise);const feeds=h.calls.filter(b=>b.action==='likes').length,button=h.w.document.querySelector('.miu-handled');await h.click(button);assert.equal(button.getAttribute('aria-pressed'),'true');assert.equal(button.getAttribute('aria-busy'),'true');assert.match(button.className,/is-flashing/);assert.equal(button.textContent,'✓ 対応済み');await React.act(async()=>{wait.resolve();await pause()});assert.equal(h.calls.filter(b=>b.action==='likes').length,feeds);const pages=[...Array(h.w.localStorage.length)].map((_,i)=>h.w.localStorage.key(i)).filter(k=>k.startsWith('mumei-insight-data-cache-v1:tester:')).map(k=>JSON.parse(h.w.localStorage.getItem(k))).filter(x=>x.payload.rows?.some(r=>r.article_key==='n1'&&r.liker_key==='123'));assert.equal(pages[0].payload.rows[0].confirmed,true)});
test('通常スキの対応済み保存失敗は即時切替を戻し、保存履歴を消さない',async t=>{const wait=deferred(),h=await likesScene(t,()=>wait.promise);await h.click(h.w.document.querySelector('.miu-handled'));await React.act(async()=>{wait.reject(new Error('offline'));await pause()});assert.equal(h.w.document.querySelector('.miu-handled').getAttribute('aria-pressed'),'false');assert.match(h.w.document.querySelector('.miu-error').textContent,/元に戻/);const cache=[...Array(h.w.localStorage.length)].map((_,i)=>h.w.localStorage.key(i)).filter(k=>k.startsWith('mumei-insight-data-cache-v1:tester:')).map(k=>JSON.parse(h.w.localStorage.getItem(k))).find(x=>x.payload.rows?.some(r=>r.article_key==='n1'));assert.equal(cache.payload.rows[0].confirmed,false)});
test('対応済み保存を待つ間に対応済み一覧へ移動しても表示と件数が一致する',async t=>{const wait=deferred(),h=await notificationScene(t,{completion:()=>wait.promise});await h.click(h.w.document.querySelector('.minf-completion button'));await h.click(h.w.document.querySelector('.minf-handling-tabs button:nth-child(3)'));assert.equal(h.w.document.querySelectorAll('.minf-list article').length,1);await React.act(async()=>{wait.resolve({completed:true});await pause()});assert.equal(h.w.document.querySelector('.minf-handling-tabs button:nth-child(3) small').textContent,'1');assert.equal(h.w.document.querySelector('.minf-completion button').getAttribute('aria-pressed'),'true')});
