import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const read=p=>fs.readFileSync(new URL('../public/'+p,import.meta.url),'utf8');
const dock=read('note-insight-notification-dock-watch-v312.js');
const reader=read('note-insight-notification-reader-v323.js');
const v3=read('note-insight-notification-v3.user.js');
function env(){const dom=new JSDOM('<button id="bell" aria-label="通知">🔔</button><main><a class="background">背景の記事です</a></main><section id="popup" role="dialog" hidden><button>通知</button><button>お知らせ</button><div id="list"></div></section>',{url:'https://note.com/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.HTMLElement.prototype.getBoundingClientRect=function(){return {width:320,height:200,left:0,top:40,right:320,bottom:240}};w.fetch=async()=>({ok:true,json:async()=>({data:{urlname:'fixture'}})});const values=new Map();w.GM={getValue:async(k,d)=>values.get(k)??d,setValue:async(k,v)=>values.set(k,v)};return{dom,w,values}}
function expose(w,src,names){w.eval(src.replace(/\}\)\(\);?\s*$/,'window.testAPI={'+names.join(',')+'};})();'));return w.testAPI}
function exposeDock(w){const src=dock.replace("if(document.body)boot();else document.addEventListener('DOMContentLoaded',boot,{once:true});\n})();","window.testAPI={findShell,showDock,ensureRoot};\n})();");w.eval(src);return w.testAPI}

test('dock recognizes the opened notification shell and keeps a notifications-route fallback',()=>{const{dom,w}=env();try{w.history.replaceState(null,'','/notifications');const api=exposeDock(w),popup=w.document.getElementById('popup');popup.hidden=false;w.document.getElementById('list').innerHTML='<a class="m-navbarNoticeItem">Aさんがコメントしました3分前</a>';assert.equal(api.findShell().id,'popup');api.showDock(true);const root=w.document.querySelector('[data-mumei-notification-dock="1"]');assert.ok(root);assert.equal(root.querySelectorAll('button').length,4);assert.equal(root.querySelector('[data-act="settings"]').textContent,'設定');popup.hidden=true;assert.equal(api.findShell().tagName,'MAIN')}finally{dom.window.close()}});

test('reader can rediscover a notification panel when the dock marker is missing',()=>{const{dom,w}=env();try{w.history.replaceState(null,'','/notifications');const popup=w.document.getElementById('popup');popup.hidden=false;w.document.getElementById('list').innerHTML='<a class="m-navbarNoticeItem" href="https://note.com/a/n/n1">Aさんがコメントしました3分前</a>';const api=expose(w,reader,['panel','rediscoverPanel']);assert.equal(api.panel().id,'popup');assert.equal(popup.getAttribute('data-mumei-notice-shell-v3'),'1')}finally{dom.window.close()}});

test('direct reader extracts rows and sends oldest-to-newest without iframe forwarding',async()=>{const{dom,w,values}=env();try{const popup=w.document.getElementById('popup');popup.hidden=false;popup.setAttribute('data-mumei-notice-shell-v3','1');w.document.getElementById('list').innerHTML='<a class="m-navbarNoticeItem" data-notification-id="new" href="https://note.com/a/n/n1?c=c1">Aさんがあなたのコメントに返信しました3分前</a><a class="m-navbarNoticeItem" data-notification-id="old" href="https://note.com/a/m/m1">未知の通知3分前</a>';const api=expose(w,reader,['rows','rowData','panel','sendBatch','sig','scan']);assert.equal(api.panel().id,'popup');const rs=api.rows(popup);assert.equal(rs.length,2);assert.match(api.rowData(rs[0]).target_url,/n1\?c=c1/);values.set('mumei_insight_notification_sync_token_v2:fixture','fixture-only');const sent=[];w.GM.xmlHttpRequest=o=>{const batch=JSON.parse(o.data).notifications;sent.push(...batch.map(x=>x.meta.event_identity));o.onload({status:200,responseText:JSON.stringify({ok:true,confirmedClientSignatures:batch.map(api.sig)})})};await api.scan();assert.deepEqual(sent,['notice:old','notice:new']);assert.equal(values.get('mumei_insight_notification_saved_v2919:fixture').length,2)}finally{dom.window.close()}});

test('partial acknowledgement leaves only missing rows in outbox',async()=>{const{dom,w,values}=env();try{const api=expose(w,reader,['sendBatch','sig','readOutbox']),a={id:'fixture'},saved=new Set();values.set('mumei_insight_notification_sync_token_v2:fixture','fixture-only');const input=['old','new'].map(id=>({raw_text:id+'さんが返信しました',target_url:'https://note.com/a/n/n1',meta:{event_identity:'notice:'+id}}));w.GM.xmlHttpRequest=o=>o.onload({status:200,responseText:JSON.stringify({ok:true,confirmedClientSignatures:[api.sig(input[0])]})});await assert.rejects(api.sendBatch(input,a,saved),/未保存/);assert.equal(api.readOutbox('fixture').length,1);assert.equal(api.readOutbox('fixture')[0].meta.event_identity,'notice:new')}finally{dom.window.close()}});

test('account change blocks transmitting a previous-account outbox',async()=>{const{dom,w,values}=env();try{const api=expose(w,reader,['sendBatch','readOutbox']);values.set('mumei_insight_notification_sync_token_v2:fixture','fixture-only');w.fetch=async()=>({ok:true,json:async()=>({data:{urlname:'different'}})});let sent=false;w.GM.xmlHttpRequest=()=>{sent=true};await assert.rejects(api.sendBatch([{raw_text:'Aさんが返信しました',meta:{event_identity:'notice:1'}}],{id:'fixture'},new Set()),/NOTE_ACCOUNT_CHANGED/);assert.equal(sent,false);assert.equal(api.readOutbox('fixture').length,1)}finally{dom.window.close()}});

test('active notification scripts parse',()=>{for(const name of ['note-insight-notification-dock-watch-v312.js','note-insight-notification-reader-v323.js','note-insight-notification-loader-v318.js','note-insight-dashboard-integrated-v318.js','note-insight-notification-v3.user.js'])assert.doesNotThrow(()=>new Function(read(name)))});

test('parent-owned visible dock captures all four taps before page handlers',async()=>{const{w}=env();try{w.history.replaceState(null,'','/notifications');const source=v3.replace('void boot();','window.parentControls={startRescue,placeRescue};').replace("location.href='https://mumei-s.github.io/note-insight/notification-filter.html?from=note&v=3213&ts='+Date.now();return","window.testDestination='settings';return").replace('location.href=u.href}}',"window.testDestination='insight'}}");w.eval(source);let reads=0,filters=0;w.__mumeiV3Reader323={scan:async()=>{reads++},readyToScan:()=>true};w.__mumeiV3Dock322={toggleFilter:async()=>{filters++;return true}};w.parentControls.startRescue();const root=w.document.getElementById('mumei-v3-rescue-dock-v329');assert.ok(root);assert.equal(root.querySelectorAll('button').length,4);root.querySelector('[data-r="read"]').click();await new Promise(r=>setTimeout(r,10));assert.equal(reads,1);root.querySelector('[data-r="filter"]').click();await new Promise(r=>setTimeout(r,20));assert.equal(filters,1);assert.match(root.querySelector('[data-r="filter"]').textContent,/ON/);root.querySelector('[data-r="settings"]').click();assert.equal(w.testDestination,'settings');root.querySelector('[data-r="ins"]').click();await new Promise(r=>setTimeout(r,20));assert.equal(w.testDestination,'insight')}finally{w.close()}});

test('parent dock stays close to the visible page bottom without double-counting mobile chrome',()=>{const{w}=env();try{Object.defineProperty(w,'innerWidth',{value:360,configurable:true});Object.defineProperty(w,'innerHeight',{value:800,configurable:true});const viewport={offsetTop:0,height:740,addEventListener(){}};Object.defineProperty(w,'visualViewport',{value:viewport,configurable:true});w.history.replaceState(null,'','/notifications');w.eval(v3.replace('void boot();','window.parentControls={startRescue,placeRescue};'));w.parentControls.startRescue();const root=w.document.getElementById('mumei-v3-rescue-dock-v329');assert.ok(root);assert.equal(root.style.display,'grid');assert.equal(Number(root.dataset.bottomInset),10);viewport.height=580;w.parentControls.placeRescue(root);assert.equal(Number(root.dataset.bottomInset),10);assert.match(root.style.bottom,/10px/);assert.equal(root.style.top,'auto');assert.equal(root.style.transform,'none')}finally{w.close()}});

test('parent dock never appears on an unrelated creator page until a verified notification surface exists',()=>{const{w}=env();try{const popup=w.document.getElementById('popup');popup.hidden=false;w.document.getElementById('list').innerHTML='<div class="notificationItem">Aさんが返信しました 1分前</div>';w.eval(v3.replace('void boot();','window.parentControls={startRescue,refreshRescue};'));w.parentControls.startRescue();const root=w.document.getElementById('mumei-v3-rescue-dock-v329');assert.equal(root.style.display,'none');popup.setAttribute('data-mumei-notice-shell-v3','1');w.parentControls.refreshRescue();assert.equal(root.style.display,'grid');popup.hidden=true;w.parentControls.refreshRescue();assert.equal(root.style.display,'none');assert.equal(w.location.pathname,'/')}finally{w.close()}});

test('automatic notification loading waits for a verified notification surface before scanning',async()=>{const{w}=env();try{let ready=false,scans=0;w.__mumeiV3Reader323={scan:async()=>{scans++},isScanning:()=>false,readyToScan:()=>ready};w.eval(v3.replace('void boot();','window.parentControls={startRescue,scheduleAutoRead};'));w.parentControls.startRescue();w.document.getElementById('bell').click();w.parentControls.scheduleAutoRead(0);await new Promise(r=>setTimeout(r,80));assert.equal(scans,0);const popup=w.document.getElementById('popup');popup.hidden=false;popup.setAttribute('data-mumei-notice-shell-v3','1');w.document.getElementById('list').innerHTML='<div class="notificationItem">Aさんが返信しました 1分前</div>';ready=true;w.parentControls.scheduleAutoRead(0);await new Promise(r=>setTimeout(r,80));assert.equal(scans,1)}finally{w.close()}});

test('notification target return reopens the bell and restores the opened row',async()=>{const{w}=env();try{const popup=w.document.getElementById('popup'),list=w.document.getElementById('list'),bell=w.document.getElementById('bell');popup.hidden=false;list.innerHTML='<div class="notificationItem"><a href="https://note.com/a/n/n1">Aさんがあなたの記事にコメントしました 3分前</a></div>';const source=v3.replace('void boot();','window.parentControls={startRescue,restoreNotificationReturn};');w.eval(source);w.parentControls.startRescue();const first=list.querySelector('a');first.addEventListener('click',e=>e.preventDefault());first.click();const saved=JSON.parse(w.sessionStorage.getItem('mumei-v3-notification-return-v3213'));assert.equal(saved.source,'https://note.com/');assert.match(saved.href,/\/a\/n\/n1/);popup.hidden=true;list.textContent='';bell.addEventListener('click',()=>{popup.hidden=false;list.innerHTML='<div class="notificationItem"><a href="https://note.com/a/n/n1">Aさんがあなたの記事にコメントしました 3分前</a></div>'});await w.parentControls.restoreNotificationReturn();const restored=list.querySelector('.notificationItem');assert.ok(restored);assert.match(restored.style.outline,/55d8f1/);assert.equal(w.sessionStorage.getItem('mumei-v3-notification-return-v3213'),null)}finally{w.close()}});

test('notification route starts the real reader automatically and manual loading never stays preparing',async()=>{const{w}=env();try{w.history.replaceState(null,'','/notifications');let scans=0;w.__mumeiV3Reader323={scan:async()=>{scans++},isScanning:()=>false,readyToScan:()=>true};w.eval(v3.replace('void boot();','window.parentControls={startRescue,scheduleAutoRead};'));w.parentControls.startRescue();w.parentControls.scheduleAutoRead(0);await new Promise(r=>setTimeout(r,25));assert.equal(scans,1);const readButton=w.document.querySelector('[data-r="read"]');readButton.click();await new Promise(r=>setTimeout(r,20));assert.equal(scans,2);assert.doesNotMatch(readButton.textContent,/準備中/);assert.match(v3,/async function ensureReaderReady\(\)/);assert.doesNotMatch(v3,/textContent='準備中…'/)}finally{w.close()}});

test('filter settings ignore every supplied creator return and always use note notifications',async()=>{const html=read('notification-filter.html'),dom=new JSDOM(html,{url:'https://mumei-s.github.io/note-insight/notification-filter.html?mumei_return=https%3A%2F%2Fnote.com%2Funknown_creator',runScripts:'outside-only'}),w=dom.window;try{w.fetch=async()=>({ok:true,json:async()=>({noteId:'fixture',paired:true})});const script=w.document.querySelector('script').textContent.replace("const returnUrl='https://note.com/notifications';","window.testReturn='https://note.com/notifications';const returnUrl=window.testReturn;");w.eval(script);assert.equal(w.testReturn,'https://note.com/notifications');assert.doesNotMatch(html,/safeNoteReturn|q\.get\('mumei_return'\)/)}finally{w.close()}});

test('all four dock controls respond with the direct reader path',async()=>{const{w}=env();try{w.history.replaceState(null,'','/notifications');const source=dock.replace("if(document.body)boot();else document.addEventListener('DOMContentLoaded',boot,{once:true});",'window.controls={ensureRoot,showDock};').replaceAll('location.href=u.href','window.testDestination=u.href');w.eval(source);w.__mumeiV3Reader322Ready=true;const root=w.controls.ensureRoot();let directReads=0;w.__mumeiV3Reader322={scan:()=>{directReads++}};root.querySelector('[data-act="read"]').click();await new Promise(r=>setTimeout(r,5));assert.equal(directReads,1);root.querySelector('[data-act="filter"]').click();await new Promise(r=>setTimeout(r,20));assert.match(root.querySelector('[data-act="filter"]').textContent,/ON/);root.querySelector('[data-act="settings"]').click();await new Promise(r=>setTimeout(r,20));assert.match(w.testDestination,/notification-filter.html/);root.querySelector('[data-act="ins"]').click();await new Promise(r=>setTimeout(r,20));assert.match(w.testDestination,/notification-entry.html/);assert.match(w.testDestination,/account=fixture/);assert.match(dock,/async function ensureReader\(\)/);assert.match(dock,/READER_API_MISSING/)}finally{w.close()}});

test('installer opens the real userscript directly and never sends users to Tampermonkey intermediary page',async()=>{const html=read('tool-setup.html'),dom=new JSDOM(html,{url:'https://mumei-s.github.io/note-insight/tool-setup.html?browser=android-edge',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;try{w.fetch=async()=>({ok:true,json:async()=>({notificationVersion:'3.2.13',dashboardVersion:'1.4.4'})});w.eval(w.document.querySelector('script').textContent);await new Promise(r=>setTimeout(r,30));const install=w.document.getElementById('install'),handoff=new URL(install.href);assert.equal(handoff.origin,'https://mumei-s.github.io');assert.equal(handoff.pathname,'/note-insight/note-insight-notification-v3.user.js');assert.equal(handoff.searchParams.get('v'),'3213');assert.doesNotMatch(install.href,/script_installation\.php/);assert.equal(install.target,'_blank');assert.equal(w.location.pathname,'/note-insight/tool-setup.html');assert.match(w.document.getElementById('currentSteps').textContent,/ユーザースクリプトの更新を確認/);assert.match(w.document.getElementById('recoverySteps').textContent,/Userscript URL detection.*Legacy/);assert.match(w.document.body.textContent,/文字列だけが表示された場合/);const verify=w.document.getElementById('verify');assert.equal(verify.tagName,'BUTTON');assert.equal(verify.hasAttribute('target'),false);assert.equal(verify.hasAttribute('href'),false);assert.doesNotMatch(html,/https:\/\/note\.com\/notifications|mumei_insight_version_check/);assert.equal(w.document.getElementById('notice'),null);assert.equal(w.document.getElementById('dash'),null);assert.doesNotMatch(w.document.body.textContent,/通知フィルター設定|初回の連携・読み込み/)}finally{w.close()}});

test('same-page V3.2.13 runtime confirmation is shown clearly as updated',async()=>{const url='https://mumei-s.github.io/note-insight/tool-setup.html?browser=android-edge&runtimeCheck=1',dom=new JSDOM(read('tool-setup.html'),{url,runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;try{w.fetch=async()=>({ok:true,json:async()=>({notificationVersion:'3.2.13',dashboardVersion:'1.4.4'})});w.eval(w.document.querySelector('script').textContent);await new Promise(r=>setTimeout(r,20));w.localStorage.setItem('mumei-notification-v3-loader','3.2.13');await new Promise(r=>setTimeout(r,150));const box=w.document.getElementById('verifyResult');assert.match(box.textContent,/更新済み/);assert.match(box.textContent,/V3\.2\.13/);assert.match(box.textContent,/この画面で起動しました/);assert.ok(box.classList.contains('ok'));assert.equal(w.location.pathname,'/note-insight/tool-setup.html');assert.match(w.document.getElementById('versionLine').textContent,/現在：V3\.2\.13.*最新：V3\.2\.13/)}finally{w.close()}});

test('version confirmation reloads only the setup page',async()=>{const dom=new JSDOM(read('tool-setup.html'),{url:'https://mumei-s.github.io/note-insight/tool-setup.html?account=fixture&browser=android-edge',runScripts:'outside-only'}),w=dom.window;try{w.fetch=async()=>({ok:true,json:async()=>({notificationVersion:'3.2.13'})});w.eval(w.document.querySelector('script').textContent);await new Promise(r=>setTimeout(r,20));const u=new URL(w.eval('runtimeCheckUrl()'));assert.equal(u.origin,'https://mumei-s.github.io');assert.equal(u.pathname,'/note-insight/tool-setup.html');assert.equal(u.searchParams.get('runtimeCheck'),'1');assert.equal(u.searchParams.get('browser'),'android-edge');assert.notEqual(u.searchParams.get('checkAt'),null)}finally{w.close()}});

test('V3.2.13 wrapper handles version return before loading remote components',()=>{const source=read('note-insight-notification-v3.user.js');assert.match(source,/@version\s+3\.2\.13/);assert.match(source,/function directVersionCheck\(\)/);assert.match(source,/runtime-checked-v329/);assert.match(source,/location\.replace\(dest\.href\)/);assert.ok(source.indexOf('async function boot(){if(directVersionCheck())return')<source.indexOf("await loadPart('note-insight-notification-dock-watch-v312.js')"));for(const key of ['@updateURL','@downloadURL'])assert.match(source,new RegExp(key+'\\s+https://raw\\.githubusercontent\\.com/mumei-s/note-insight/main/public/note-insight-notification-v3\\.user\\.js'))});

test('browser-specific setup keeps slim route controls and verified manager routes',async()=>{const html=read('tool-setup.html');assert.match(html,/\.browser-grid\{display:grid;grid-template-columns:1fr;gap:3px\}/);assert.doesNotMatch(html,/grid-template-columns:repeat\(2/);const dom=new JSDOM(html,{url:'https://mumei-s.github.io/note-insight/tool-setup.html?account=fixture&browser=android-edge',runScripts:'outside-only'}),w=dom.window;try{w.fetch=async()=>({ok:true,json:async()=>({notificationVersion:'3.2.13'})});w.eval(w.document.querySelector('script').textContent);await new Promise(r=>setTimeout(r,30));const d=w.document,supported=['android-firefox','ios-safari','pc-edge','pc-chrome','pc-firefox','mac-safari','android-edge'];assert.equal(d.querySelectorAll('.browser-choice').length,9);for(const key of ['android-other',...supported.slice(0,1),'ios-other',...supported.slice(1)]){d.querySelector(`[data-browser="${key}"]`).click();const blocked=key.endsWith('other');assert.equal(d.getElementById('updateFlow').hidden,blocked);assert.equal(d.getElementById('confirmFlow').hidden,blocked);assert.equal(d.getElementById('verify').hasAttribute('aria-disabled'),blocked);assert.equal(d.querySelectorAll('[aria-pressed="true"]').length,1);assert.equal(new URL(w.location.href).searchParams.get('browser'),key);const check=new URL(w.eval('runtimeCheckUrl()'));assert.equal(check.pathname,'/note-insight/tool-setup.html');assert.equal(check.searchParams.get('browser'),key);assert.equal(check.searchParams.get('runtimeCheck'),'1');assert.equal(d.getElementById('install').hasAttribute('download'),false);if(!blocked){const installUrl=new URL(d.getElementById('install').href);assert.equal(installUrl.origin,'https://mumei-s.github.io');assert.equal(installUrl.pathname,'/note-insight/note-insight-notification-v3.user.js');assert.equal(installUrl.searchParams.get('v'),'3213');const manager=new URL(d.getElementById('extensionGuide').href);if(key.includes('safari'))assert.equal(manager.pathname,'/app/tampermonkey/id6738342400');else if(key.includes('firefox'))assert.match(manager.hostname,/mozilla\.org$/);else assert.equal(manager.hostname,'www.tampermonkey.net')}}assert.match(d.body.textContent,/URLを貼り付ける操作はありません/);assert.doesNotMatch(d.body.textContent,/Userscripts/);assert.equal(new URL(d.getElementById('pageUrl').value).searchParams.get('account'),'fixture');assert.equal(new URL(d.getElementById('pageUrl').value).searchParams.has('browser'),false)}finally{w.close()}});

test('dashboard launcher releases its boot lock so automatic reading can retry',()=>{const source=read('note-insight-dashboard-integrated-v318.js');assert.match(source,/finally\{booting=false\}/);assert.match(source,/window\.addEventListener\('pageshow',run\)/);assert.match(source,/visibilityState==='visible'/)});
