import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read=(name)=>readFile(new URL(`../public/${name}`,import.meta.url),"utf8");
const readRoot=(name)=>readFile(new URL(`../${name}`,import.meta.url),"utf8");

async function sources(){return{boot:await read("note-insight-notification-sync.user.js"),runtime:await read("note-insight-notification-runtime-v298.js"),patch:await read("note-insight-notification-runtime-v2914-patch.js"),setup:await read("notification-import.html"),helper:await read("notification-install.html")}}

test("v2.9.14 keeps runtime fallback and launch diff sync",async()=>{const{boot,runtime,patch}=await sources();assert.match(boot,/@version\s+2\.9\.14/);assert.match(boot,/runtime-v298\.js\?v=2914/);assert.match(boot,/runtime-v2914-patch\.js\?v=2914/);for(const x of ["manualCurrent(root,current)","manualSweep(root,past)","🔔 表示分読込","↧ 過去まで読込","読込→INSIGHT自動保存完了","過去読込→INSIGHT自動保存完了","saveRows(rows)","saveRows([...seen.values()])","panelObserver.observe(root,{childList:true,subtree:true})"])assert.match(runtime,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const x of ["mumei_auto_notice_v2914","mumei_auto_notice_v2913","runAutoSync","waitButtonDone","setupToolbar","mumei2914Ready"])assert.match(patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(patch,/setInterval\(/);});

test("toolbar is flicker-safe and prioritizes filter plus INSIGHT",async()=>{const{patch}=await sources();for(const x of ["grid-template-columns:minmax(138px,1fr) minmax(96px,118px) 38px","m297-filter-switch","mumei-insight-return","mumei-more-tools","mumei-more-panel","data-mumei-role","past","dataset.mumei2914Ready==='1'"])assert.match(patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(patch,/button\[data-mumei-role=\"current\"\]/);assert.match(patch,/observer\.observe\(document\.body/);assert.doesNotMatch(patch,/compactToolbar/);assert.doesNotMatch(patch,/refreshAccountLabel/)});

test("notification screen can add creators directly to filter groups",async()=>{const{patch}=await sources();for(const x of ["＋フィルター","openPicker","readGroupsFor","saveGroupsFor","＋ 新しいグループ","mumei-filter-picker","actorIdFromItem","mumei-add-filter"])assert.match(patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(patch,/GROUPS='mumei_insight_notification_groups_v1:'/);assert.match(patch,/MUTES='mumei_insight_magazine_mute_ids_v5:'/)});

test("self-added magazine notifications remain supplemented",async()=>{const{patch}=await sources();for(const x of ["SELF_ADDED","selfCandidates","selfRows","self-magazine-added-v2914","表示分読込","過去まで読込","ITEM_SELECTOR"])assert.match(patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(patch,/\/あなたの記事が\.\{0,420\}\?に追加されました\/u/)});

test("account identity stays server-locked",async()=>{const{runtime,patch}=await sources(),ingest=await readRoot("supabase/functions/insight-notification-ingest-v2/index.ts"),feed=await readRoot("supabase/functions/insight-notification-feed-final/index.ts");assert.match(runtime,/source:'note-notification-manual-sync-v298'/);assert.match(patch,/SOURCE='note-notification-manual-sync-v2914'/);assert.match(patch,/TOKEN\+account\.id/);assert.match(patch,/noteId:account\.id/);assert.match(ingest,/function allowedExplicitSource/);assert.match(ingest,/manual-sync-v\\d\+/);assert.match(ingest,/NOTIFICATION_SOURCE_BLOCKED/);assert.match(ingest,/NOTIFICATION_ACCOUNT_MISMATCH/);assert.match(ingest,/suppliedNoteId!==who\.noteId/);assert.match(feed,/membership_board_reply/)});

test("pairing still returns only to INSIGHT after verification",async()=>{const{runtime}=await sources();assert.match(runtime,/function insightReturn/);assert.match(runtime,/u\.origin==='https:\/\/mumei-s\.github\.io'/);assert.match(runtime,/u\.pathname\.startsWith\('\/note-insight\/'\)/);assert.match(runtime,/mumei_return/);assert.match(runtime,/location\.replace\(back\)/)});

test("dashboard bell hard-resets through normal note",async()=>{const{boot,runtime}=await sources();assert.match(boot,/startsWith\('\/sitesettings\/stats'\)/);assert.match(boot,/event\.stopImmediatePropagation\(\)/);assert.match(boot,/mumei_open_notice_v2914/);assert.match(boot,/openBellAfterCleanNavigation/);assert.match(boot,/bell\.dispatchEvent\(new MouseEvent\('click'/);for(const x of ["liveItems","panelUsable","resetPanel","retryPanel","observedRoot&&observedRoot!==root"])assert.match(runtime,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});

test("filter and group runtime remains intact",async()=>{const{runtime,patch}=await sources();for(const x of ["mumei_insight_magazine_mute_ids_v5:","mumei_insight_magazine_filter_enabled_v3:","mumei_insight_notification_groups_v1:","m297-filter-switch","setMasterFilter","setGroupEnabled","readGroups","mumei_filter_reset","mumei_groups_sync"])assert.match(runtime+patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});

test("v2.9.14 uses raw update URLs and modern plus legacy GM APIs",async()=>{const{boot,runtime,patch}=await sources();assert.match(boot,/@updateURL\s+https:\/\/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);for(const x of ["GM.xmlHttpRequest","GM.getValue","GM.setValue","GM_xmlhttpRequest","GM_getValue","GM_setValue"])assert.match(boot+runtime+patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});

test("dashboard automatic ingest is preserved",async()=>{const{runtime}=await sources();assert.match(runtime,/startsWith\('\/sitesettings\/stats'\)/);assert.match(runtime,/note-dashboard-auto-v298/);assert.match(runtime,/saveDashboardAuto/);assert.doesNotMatch(runtime,/host\.prepend/);assert.doesNotMatch(runtime,/observe\(document\.documentElement/)});

test("installer verifies v2.9.14 on note",async()=>{const{boot,helper}=await sources();assert.match(helper,/TAMPERMONKEY INSTALL/);assert.match(helper,/v2\.9\.14/);assert.match(helper,/このブラウザで v2\.9\.14/);assert.match(helper,/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);assert.match(helper,/mumei_insight_version_check=1/);assert.match(boot,/mumei_insight_version_check/);assert.match(boot,/notificationInstalled/)});
