import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import * as React from 'react';
import {flushSync} from 'react-dom';
import * as jsx from 'react/jsx-runtime';
import {PGlite} from '@electric-sql/pglite';
import {sceneFixture,pause} from './react-scene-fixture.mjs';
const read=p=>readFileSync(p,'utf8');
const feed=read('supabase/functions/insight-notification-feed-final/index.ts');
function compile(source, globals={}){const context=vm.createContext({URL,AbortController,setTimeout,clearTimeout,console,...globals});vm.runInContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,context);return context}
function helpers(db,fetch){return compile(feed.slice(feed.indexOf('const completionKey='),feed.indexOf('async function recentRows('))+'\nthis.api={notificationCompletion,notificationComment,commentIdentity,actualCommentBody};',{db,fetch}).api}
function database(records){const writes=[],completions=new Map();return{writes,completions,from(table){const filters=[];let payload,remove=false;const q={select(){return q},eq(k,v){filters.push(r=>String(r[k])===String(v));return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},match(v){for(const[k,x]of Object.entries(v))q.eq(k,x);return q},upsert(v){payload=v;return q},update(v){payload=v;return q},delete(){remove=true;return q},async maybeSingle(){return result()},then(y,n){return Promise.resolve(result()).then(y,n)}};function result(){const rows=table==='insight_notifications'?records:[];const row=rows.find(r=>filters.every(f=>f(r)));if(table==='insight_notifications'&&payload&&row){Object.assign(row,payload);writes.push({table,row})}if(table==='insight_manual_completions'){if(payload){completions.set(payload.item_key,payload);writes.push({table,payload})}if(remove){for(const[k,v]of completions)if(filters.every(f=>f(v)))completions.delete(k)}}return{data:row||null,error:null}}return q}}}
const member={id:'member-a',scope:'member-a',noteId:'creator_a'};
const record=(id='1',member_id='member-a')=>({id,member_id,notification_type:'reply',target_url:'https://note.com/other/n/nabc?scrollpos=comment&c=nc222',raw_text:'相手さんがあなたのコメントに返信しました',meta:{body:'相手さんがあなたのコメントに返信しました',event_identity:'notice:111'}});
test('返信案内文は実本文として扱わず、コメントID付きリンクを保持する',()=>{const a=helpers(database([]));assert.equal(a.actualCommentBody(record()),'');assert.equal(a.commentIdentity(record()).commentKey,'nc222');assert.match(a.commentIdentity(record()).url,/c=nc222$/);assert.equal(a.commentIdentity({...record(),target_url:'https://evil.test/other/n/nabc?c=nc222'}),null)});
test('返信の対象IDだけを照合し、保存済み本文は再取得しない',async()=>{const row=record(),db=database([row]);let reads=0;const a=helpers(db,async()=>{reads++;return Response.json({data:[{key:'nc111',comment:'別コメント',latest_creator_reply:{key:'nc222',comment:{content:[{type:'text',value:'返信の実本文です'}]},user:{nickname:'返信者'}}}],next_page:null})});const x=await a.notificationComment(member,{id:'1'});assert.equal(x.body,'返信の実本文です');assert.equal(row.meta.comment_key,'nc222');assert.equal(row.raw_text,'相手さんがあなたのコメントに返信しました');assert.equal((await a.notificationComment(member,{id:'1'})).status,'saved');assert.equal(reads,1)});
test('旧通知の共通識別ラベルで別の通知まで対応済みにしない',async()=>{const first={...record('1'),meta:{event_identity:'classification-independent-v2'}},second={...record('2'),meta:{event_identity:'classification-independent-v2'}},db=database([first,second]),a=helpers(db);await a.notificationCompletion(member,{id:'1',completed:true});assert.ok(db.completions.has('row:1'));assert.equal(db.completions.has('row:2'),false);assert.equal(db.completions.has('classification-independent-v2'),false)});
test('コメントのスキは同じ記事の別コメントではなく対象IDを表示する',async()=>{const row={...record(),notification_type:'comment_like'},db=database([row]),a=helpers(db,async()=>Response.json({data:[{key:'nc111',comment:'同じ記事の別コメント'},{key:'nc222',comment:'スキされた本人コメント'}],next_page:null}));assert.equal((await a.notificationComment(member,{id:'1'})).body,'スキされた本人コメント')});
test('本人通知の対応済みは通知IDと本人を検証し、取り消しも保存する',async()=>{const row=record(),foreign=record('2','member-b'),db=database([row,foreign]),a=helpers(db);await a.notificationCompletion(member,{id:'1',completed:true});assert.equal(db.completions.get('notice:111').member_id,'member-a');await assert.rejects(a.notificationCompletion(member,{id:'2',completed:true}),/NOTIFICATION_NOT_FOUND/);await assert.rejects(a.notificationComment(member,{id:'2'}),/NOTIFICATION_NOT_FOUND/);await a.notificationCompletion(member,{id:'1',completed:false});assert.equal(db.completions.size,0);assert.deepEqual(foreign,record('2','member-b'))});
for(const name of ['ingest-v2','reclassify'])test(name+'：記事タイトルを挟んだ更新と既知のバッジ・購入メッセージを分類する',()=>{const source=read(`supabase/functions/insight-notification-${name}/index.ts`),end=name==='ingest-v2'?source.indexOf('\nasync function identity'):source.indexOf('\nfunction noise'),c=compile(source.slice(source.indexOf('const KIND_TYPES'),end)+'\nthis.classify=classify',{actionText:v=>String(v),canonicalText:v=>String(v)});assert.equal(c.classify('みゆこさんが みゆこ「やってみた制作室」の記事を更新しました','https://note.com/miyuki11920/n/nabc',{}),'creator_article_posted');assert.equal(c.classify('継続記念バッジを獲得しました',null,{kind:'user_badge'}),'badge');assert.equal(c.classify('購入した記事にメッセージがとどきました',null,{kind:'thank_you_message'}),'purchase_message');assert.equal(c.classify('「継続記念」を購入しました',null,{kind:'purchase'}),'purchase')});
test('手動再分類は既に確認済みの未分類を再試行し、自動は未処理だけに限定する',()=>{const source=read('supabase/functions/insight-notification-reclassify/index.ts');assert.match(source,/if\(b.onlyPending!==false\)q=q.or/);const ui=read('src/member-insight-notifications-final.tsx');assert.match(ui,/reclassify\(false\)/);assert.match(ui,/onlyPending:auto/)});
test('DB最終分類トリガーは新カテゴリを未分類で上書きしない',async t=>{const db=new PGlite();t.after(()=>db.close());await db.exec('create table insight_notifications(id bigint,notification_type text,meta jsonb,raw_text text);');const file=readdirSync('supabase/migrations').find(f=>f.endsWith('_notification_context_classification_v28.sql'));await db.exec(read('supabase/migrations/'+file));await db.exec('create trigger classify before insert on insight_notifications for each row execute function apply_insight_notification_classification_v25();');const result=await db.query("insert into insight_notifications values(1,'other','{\"classifier\":\"action-v28-context\",\"classified_type\":\"badge\"}','バッジ獲得') returning notification_type");assert.equal(result.rows[0].notification_type,'badge')});
function component(h,name,post){const source=read('src/member-insight-notifications-final.tsx'),part=source.slice(source.indexOf('function NotificationCompletion('),source.indexOf('export function MemberInsightNotificationsFinal('));return compile('import {useState} from "react";\n'+part+'\nthis.Component='+name,{exports:{},require:k=>k==='react'?React:jsx,localStorage:h.w.localStorage,INSIGHT_TOKEN_KEY:'fixture-token',post,flushSync,...h.load('src/insight-completion-queue.ts')}).Component}
test('本人通知の本文表示・対応済み保存を実画面操作で確認する',async t=>{const h=await sceneFixture(t);h.w.localStorage.setItem('fixture-token','fixture');const calls=[],saved=[],row={...record(),comment_identity:{commentKey:'nc222',url:record().target_url}};const C=component(h,'NotificationComment',async b=>{calls.push(b);return{body:'相手からの実際の返信',commentKey:'nc222',articleKey:'nabc',url:row.target_url}});await h.render(C,{row,onSaved:r=>saved.push(r)});const details=h.w.document.querySelector('details');await React.act(async()=>{details.open=true;details.dispatchEvent(new h.w.Event('toggle'));await pause()});assert.equal(calls[0].action,'comment_detail');assert.equal(saved[0].meta.comment_body,'相手からの実際の返信');assert.match(details.textContent,/相手からの実際の返信/);assert.doesNotMatch(details.textContent,/さんがあなたのコメントに返信しました/);const D=component(h,'NotificationCompletion',async b=>{calls.push(b);return{completed:b.completed}});await h.render(D,{row,onSaved:r=>saved.push(r)});await h.click(h.w.document.querySelector('button'));assert.equal(saved.at(-1).confirmed,true)});
test('対応済み保存で古い取得を止めても次の差分・全件確認を続けられる',async t=>{let feeds=0,confirmed=false;const timers=[];const row={...record(),notification_type:'tip',display_category:'tip'};const h=await sceneFixture(t,{globals:{location:new URL('https://mumei-s.github.io/note-insight/'),URLSearchParams},fetch:async(url,init)=>{const b=JSON.parse(init.body);if(b.action==='completion'){confirmed=b.completed;return Response.json({ok:true,completed:confirmed})}if(b.action==='recent')return Response.json({ok:true,noteId:'tester',rows:[]});if(String(url).includes('reclassify'))return Response.json({ok:true,checked:0,rows:[],nextCursor:null});if(String(url).includes('feed-final')){feeds++;if(feeds===2)return new Promise((resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new DOMException('Cancelled','AbortError')),{once:true}));return Response.json({ok:true,noteId:'tester',rows:[{...row,confirmed}],total:1,categoryCounts:{all:1,tip:1}})}return Response.json({})}});h.w.localStorage.setItem('mumei-insight-access-token','fixture');h.w.setInterval=(fn,ms)=>{timers.push({fn,ms});return timers.length};h.w.clearInterval=()=>{};await h.render(h.load('src/member-insight-notifications-final.tsx').MemberInsightNotificationsFinal,{noteId:'tester'});const refresh=timers.find(t=>t.ms===120000).fn;await React.act(async()=>{refresh();await pause()});assert.equal(feeds,2);await h.click(h.w.document.querySelector('.minf-completion button'));assert.equal(confirmed,true);await React.act(async()=>{refresh();await pause()});assert.equal(feeds,3);assert.equal(h.w.document.querySelector('.minf-completion button').getAttribute('aria-pressed'),'true')});
