import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read=(name)=>readFile(new URL(`../public/${name}`,import.meta.url),"utf8");
const readRoot=(name)=>readFile(new URL(`../${name}`,import.meta.url),"utf8");
async function sources(){return{boot:await read("note-insight-notification-sync.user.js"),runtime:await read("note-insight-notification-runtime-v298.js"),patch:await read("note-insight-notification-runtime-v2915-patch.js"),setup:await read("notification-import.html"),entry:await read("notification-setup.html"),helper:await read("notification-install.html")}}

test("v2.9.15 bootstrap loads only the continuous patch and no flicker timer",async()=>{const{boot}=await sources();assert.match(boot,/@version\s+2\.9\.15/);assert.match(boot,/runtime-v298\.js\?v=2915/);assert.match(boot,/runtime-v2915-patch\.js\?v=2915/);assert.doesNotMatch(boot,/runtime-v2914-patch/);assert.doesNotMatch(boot,/toolbarTimer|setToolbarTop|ensureInsightReturnButton/);assert.match(boot,/mumei_open_notice_v2915/);assert.match(boot,/mumei_insight_version_check/);});

test("continuous sync watches counts, backfills once, then stops at cursor",async()=>{const{patch}=await sources();for(const x of ["/api/v3/notice_counts","mumei_insight_notification_cursor_v2915:","mumei_insight_notification_backfill_v2915:","note-notification-continuous-sync-v2915","count-change","first-backfill","heartbeat","known.has(q)","if(deep)await set(k(BACK,a.id),true)"])assert.match(patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(patch,/setInterval\(\(\)=>void poll\(\),45000\)/);assert.match(patch,/setInterval\(\(\)=>void sweep\(false,'heartbeat'\),5\*60\*1000\)/);});

test("launch sync returns to the same INSIGHT route",async()=>{const{patch}=await sources();for(const x of ["mumei_auto_notice_v2915","mumei_return","safeBack","launchReturn","notificationAutoSynced","notificationAutoAt","notificationNoteId","notificationAutoError","location.replace(r.href)"])assert.match(patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(patch,/u\.origin==='https:\/\/mumei-s\.github\.io'/);assert.match(patch,/u\.pathname\.startsWith\('\/note-insight\/'\)/);});

test("notification UI is tiny and keeps filter INSIGHT and on-row add",async()=>{const{patch}=await sources();for(const x of ["#mumei-v297-actions{display:none!important}","mumei-v2915-dock","F ON","F OFF","INS","+F","過去まで補完","フィルター設定","mumei-filter-picker","＋ 新しいグループ"])assert.match(patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(patch,/height:23px/);});

test("self magazine additions and chips are capture candidates",async()=>{const{patch}=await sources(),ingest=await readRoot("supabase/functions/insight-notification-ingest-v2/index.ts");assert.match(patch,/追加\(\?:しました\|されました\)/);for(const x of ["チップ","サポート","支援","応援金"])assert.match(patch,new RegExp(x));assert.match(ingest,/あなたの記事が\.\{0,260\}に追加されました/);assert.match(ingest,/チップ\|サポート/);assert.match(ingest,/支援\|応援金/);assert.match(ingest,/continuous-sync-v\\d\+/);assert.match(ingest,/action-v11-continuous/);});

test("account identity remains locked to the actual note login",async()=>{const{patch}=await sources(),ingest=await readRoot("supabase/functions/insight-notification-ingest-v2/index.ts");assert.match(patch,/\/api\/v2\/current_user/);assert.match(patch,/TOK\+a\.id/);assert.match(patch,/noteId:a\.id/);assert.match(ingest,/NOTIFICATION_ACCOUNT_MISMATCH/);assert.match(ingest,/suppliedNoteId!==who\.noteId/);});

test("manual fallback and dashboard automatic ingest are preserved",async()=>{const{runtime}=await sources();for(const x of ["manualCurrent","manualSweep","読込→INSIGHT自動保存完了","過去読込→INSIGHT自動保存完了","note-dashboard-auto-v298","saveDashboardAuto","mumei_insight_notification_groups_v1:","mumei_insight_magazine_filter_enabled_v3:"])assert.match(runtime,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(runtime,/startsWith\('\/sitesettings\/stats'\)/);});

test("pairing still returns only to INSIGHT after verification",async()=>{const{runtime}=await sources();assert.match(runtime,/function insightReturn/);assert.match(runtime,/u\.origin==='https:\/\/mumei-s\.github\.io'/);assert.match(runtime,/u\.pathname\.startsWith\('\/note-insight\/'\)/);assert.match(runtime,/mumei_return/);assert.match(runtime,/location\.replace\(back\)/);});

test("installer and setup pages expose v2.9.15 everywhere",async()=>{const{boot,setup,entry,helper}=await sources();for(const src of [setup,entry,helper])assert.match(src,/2\.9\.15/);assert.match(setup,/VERSION='2\.9\.15'/);assert.match(entry,/v=2915/);assert.match(helper,/TAMPERMONKEY INSTALL/);assert.match(helper,/このブラウザで v2\.9\.15/);assert.match(helper,/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);assert.match(helper,/mumei_insight_version_check=1/);assert.match(boot,/notificationInstalled/);});

test("raw update URLs and modern plus legacy GM APIs remain available",async()=>{const{boot,runtime,patch}=await sources();assert.match(boot,/@updateURL\s+https:\/\/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);for(const x of ["GM.xmlHttpRequest","GM.getValue","GM.setValue","GM_xmlhttpRequest","GM_getValue","GM_setValue"])assert.match(boot+runtime+patch,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});
