import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read=(name)=>readFile(new URL(`../public/${name}`,import.meta.url),"utf8");
const readRoot=(name)=>readFile(new URL(`../${name}`,import.meta.url),"utf8");

async function sources(){return{boot:await read("note-insight-notification-sync.user.js"),runtime:await read("note-insight-notification-runtime-v298.js"),setup:await read("notification-import.html"),helper:await read("notification-install.html")}}

test("v2.9.10 keeps manual notification read and auto-save runtime",async()=>{const{boot,runtime}=await sources();assert.match(boot,/@version\s+2\.9\.10/);assert.match(boot,/@require\s+https:\/\/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-runtime-v298\.js\?v=298/);for(const x of ["manualCurrent(root,current)","manualSweep(root,past)","🔔 表示分読込","↧ 過去まで読込","読込→INSIGHT自動保存完了","過去読込→INSIGHT自動保存完了","saveRows(rows)","saveRows([...seen.values()])","box.scrollTop=box.scrollHeight","box.scrollTop=start","panelObserver.observe(root,{childList:true,subtree:true})"])assert.match(runtime,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(runtime,/autoSweep\(root\)/);assert.doesNotMatch(runtime,/scheduleSweep/)});

test("current manual source is accepted by ingest and membership board replies stay distinct",async()=>{const{runtime}=await sources(),ingest=await readRoot("supabase/functions/insight-notification-ingest-v2/index.ts"),feed=await readRoot("supabase/functions/insight-notification-feed-final/index.ts");assert.match(runtime,/source:'note-notification-manual-sync-v298'/);assert.match(ingest,/function allowedExplicitSource/);assert.match(ingest,/manual-sync-v\\d\+/);assert.match(ingest,/explicit-sync/);assert.match(ingest,/note-notification-auto-sync/);assert.match(ingest,/NOTIFICATION_SOURCE_BLOCKED/);assert.match(ingest,/blocked===incoming\.length/);assert.match(ingest,/browser-manual-v2910/);assert.match(ingest,/membership_board_reply/);assert.match(ingest,/\/membership\\\/boards/);assert.match(feed,/membership_board_reply/);assert.match(ingest,/memberId,noteId:"ss_yr"/);assert.match(ingest,/insight_access_applications/)});

test("pairing still returns only to INSIGHT after actual note verification",async()=>{const{runtime}=await sources();assert.match(runtime,/function insightReturn/);assert.match(runtime,/u\.origin==='https:\/\/mumei-s\.github\.io'/);assert.match(runtime,/u\.pathname\.startsWith\('\/note-insight\/'\)/);assert.match(runtime,/mumei_return/);assert.match(runtime,/location\.replace\(back\)/)});

test("dashboard bell is hard-reset through normal note before notification toolbar binds",async()=>{const{boot,runtime}=await sources();assert.match(boot,/startsWith\('\/sitesettings\/stats'\)/);assert.match(boot,/event\.stopImmediatePropagation\(\)/);assert.match(boot,/mumei_open_notice_v2910/);assert.match(boot,/location\.replace\(`https:\/\/note\.com\/\?\$\{CLEAN_NOTICE\}=1`\)/);assert.match(boot,/openBellAfterCleanNavigation/);assert.match(boot,/bell\.dispatchEvent\(new MouseEvent\('click'/);for(const x of ["liveItems","panelUsable","resetPanel","retryPanel","observedRoot&&observedRoot!==root"])assert.match(runtime,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});

test("note notification toolbar has a direct return to INSIGHT notifications",async()=>{const{boot}=await sources();assert.match(boot,/INSIGHT_NOTIFICATIONS/);assert.match(boot,/insightMode=notifications#dashboard/);assert.match(boot,/mumei-insight-return/);assert.match(boot,/INSIGHTへ/)});

test("notification filters and groups remain available",async()=>{const{runtime}=await sources();for(const x of ["mumei_insight_magazine_mute_ids_v5:","mumei_insight_magazine_filter_enabled_v3:","mumei_insight_notification_groups_v1:","m297-filter-switch","setMasterFilter","setGroupEnabled","readGroups","mumei_filter_reset","mumei_groups_sync"])assert.match(runtime,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});

test("v2.9.10 uses raw update URLs and supports modern plus legacy GM APIs",async()=>{const{boot,runtime}=await sources();assert.match(boot,/@updateURL\s+https:\/\/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);for(const x of ["GM.xmlHttpRequest","GM.getValue","GM.setValue","GM_xmlhttpRequest","GM_getValue","GM_setValue"])assert.match(boot+runtime,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});

test("dashboard automatic ingest is preserved",async()=>{const{runtime}=await sources();assert.match(runtime,/startsWith\('\/sitesettings\/stats'\)/);assert.match(runtime,/note-dashboard-auto-v298/);assert.match(runtime,/saveDashboardAuto/);assert.doesNotMatch(runtime,/host\.prepend/);assert.doesNotMatch(runtime,/Dashboardを読み取る → INSIGHT反映/);assert.doesNotMatch(runtime,/observe\(document\.documentElement/)});

test("PWA install flow is browser-aware, explains routing, and verifies installed v2.9.10 on note",async()=>{const{boot,setup,helper}=await sources();assert.match(setup,/display-mode: standalone/);assert.match(setup,/package=\$\{pkg\}/);assert.match(setup,/androidIntent\('com\.microsoft\.emmx'\)/);assert.match(setup,/androidIntent\('org\.mozilla\.firefox'\)/);assert.match(setup,/Safari＋Tampermonkey/);assert.match(setup,/Android Chrome/);assert.match(setup,/この端末の動線/);assert.match(setup,/このブラウザで v2\.9\.10/);assert.match(setup,/notification-install\.html/);assert.match(helper,/TAMPERMONKEY INSTALL/);assert.match(helper,/この先の流れ/);assert.match(helper,/このブラウザで v2\.9\.10/);assert.match(helper,/Safari＋Tampermonkey/);assert.match(helper,/Android Chrome/);assert.match(helper,/raw\.githubusercontent\.com\/mumei-s\/note-insight\/main\/public\/note-insight-notification-sync\.user\.js/);assert.match(helper,/mumei_insight_version_check=1/);assert.match(boot,/mumei_insight_version_check/);assert.match(boot,/notificationInstalled/);assert.match(setup,/v2\.9\.10 実動確認済み/)});
