import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
function helpers(p,names){let source=read(p).replace(/^import .*;\n/gm,'');const ctx={createClient:()=>({}),Deno:{env:{get:()=>''},serve:()=>{}},console,URL,Date,Intl,Map,Set,Number,JSON};vm.createContext(ctx);source+='\nglobalThis.result={'+names.join(',')+'};';vm.runInContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,ctx);return ctx.result}
test('important actions beat words in the article title',()=>{const {classify,allowedExplicitSource}=helpers('supabase/functions/insight-notification-ingest-v2/index.ts',['classify','allowedExplicitSource']);assert.equal(classify('あなたの記事がメンバーシップ応援に追加されました スキしましたという題名3分前','https://note.com/a/m/m1'),'my_article_magazine_added');assert.equal(classify('Aさんがあなたのコメントに返信しました メンバーシップのスキ3分前','https://note.com/a/n/n1?c=c1'),'reply');assert.equal(classify('Aさんがあなたのメンバーシップに参加しました スキした人','https://note.com/ss_yr/membership'),'membership_join');assert.equal(classify('新形式の通知','https://note.com/a/membership?kind=circle_plan_join'),'membership_join');assert.equal(classify('新形式の通知',null),'other');assert.equal(allowedExplicitSource('note-notification-reader-v2963'),true);assert.equal(allowedExplicitSource('note-notification-manual-sync-v2968'),true);assert.equal(allowedExplicitSource('note-notification-passive-sync'),false)});
test('different article additions survive dedupe and unknown ownership is not invented',()=>{const {dedupe,decorate}=helpers('supabase/functions/insight-notification-feed-final/index.ts',['dedupe','decorate']);const base={notification_type:'my_article_magazine_added',actor_url:'https://note.com/a',target_url:'https://note.com/a/m/m1',occurred_at:'2026-09-13T00:00:00Z',meta:{source:'note-notification-manual-sync-v2968'}};assert.equal(dedupe([{...base,raw_text:'あなたの記事がMに追加されました 記事A'},{...base,raw_text:'あなたの記事がMに追加されました 記事B'}]).length,2);assert.equal(decorate({notification_type:'membership_reaction',target_url:'https://note.com/membership'},'ss_yr').display_category,'membership_reaction_unknown');assert.equal(decorate({notification_type:'reply',target_url:null},'ss_yr').display_category,'reply_unknown');assert.equal(dedupe([{notification_type:'other',raw_text:'未知通知',meta:{source:'note-notification-manual-sync-v2968'}}]).length,1)});
test('private analysis keeps replies and unclassified notifications and excludes public rows',()=>{const {useful,summarize}=helpers('supabase/functions/insight-notification-analysis-summary/index.ts',['useful','summarize']);for(const notification_type of ['reply','membership_join','my_article_magazine_added','other'])assert.equal(useful({notification_type,raw_text:'通知です',meta:{source:'note-notification-manual-sync-v2968'}}),true);for(const notification_type of ['like','follow','comment','creator_article_posted'])assert.equal(useful({notification_type,raw_text:'通知です',meta:{source:'note-notification-manual-sync-v2968'}}),false);assert.equal(summarize([],'ss_yr',false,0).sample,0);assert.equal(summarize([],'ss_yr',false,0).classifiedRate,0)});
test('active package and restored setup flow agree',()=>{const manifest=JSON.parse(read('public/insight-release.json')),v3=read('public/note-insight-notification-v3.user.js'),setup=read('public/tool-setup.html'),bridge=read('public/note-insight-bridge.user.js'),legacy=read('public/notification-update-v29665.html'),watch=read('public/note-insight-notification-dock-watch-v312.js');assert.equal(manifest.notificationVersion,'3.1.3');assert.equal(manifest.dashboardVersion,'1.4.4');assert.equal(manifest.bridgeVersion,undefined);assert.match(v3,new RegExp('@version\\s+'+manifest.notificationVersion.replaceAll('.','\\.')));assert.match(bridge,/@version\s+1\.0\.1/);assert.match(setup,/script_installation\.php#url=/);assert.match(setup,/Dashboard同期をインストール／更新/);assert.match(setup,/本人通知をインストール／更新/);assert.match(setup,/mumei_insight_version_check/);assert.match(setup,/location\.replace\(back\)/);assert.doesNotMatch(setup,/mumei-insight-bridge-version|ONE BRIDGE SETUP/);assert.match(legacy,/tool-setup\.html/);assert.match(watch,/tryAutoStart/);assert.match(watch,/read\.click\(\)/)});
test('seven-day selection still compares against the preceding seven days',()=>{const {summarize}=helpers('supabase/functions/insight-notification-analysis-summary/index.ts',['summarize']);const row=days=>({notification_type:'my_article_magazine_added',occurred_at:new Date(Date.now()-days*86400000).toISOString(),actor_name:'A'});const recent=row(1),previous=row(9);const r=summarize([recent],'ss_yr',false,1,7,[recent,previous]);assert.equal(r.recent7,1);assert.equal(r.prev7,1);assert.equal(r.ownArticleAdds,1)});
