import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const read=p=>fs.readFileSync(new URL('../public/'+p,import.meta.url),'utf8');
const dock=read('note-insight-notification-dock-watch-v312.js');
const reader=read('note-insight-notification-reader-v322.js');
function env(){const dom=new JSDOM('<button id="bell" aria-label="通知">🔔</button><main><a class="background">背景の記事です</a></main><section id="popup" role="dialog" hidden><button>通知</button><button>お知らせ</button><div id="list"></div></section>',{url:'https://note.com/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.HTMLElement.prototype.getBoundingClientRect=function(){return {width:320,height:200,left:0,top:40,right:320,bottom:240}};w.fetch=async()=>({ok:true,json:async()=>({data:{urlname:'fixture'}})});const values=new Map();w.GM={getValue:async(k,d)=>values.get(k)??d,setValue:async(k,v)=>values.set(k,v)};return{dom,w,values}}
function expose(w,src,names){w.eval(src.replace(/\}\)\(\);?\s*$/,'window.testAPI={'+names.join(',')+'};})();'));return w.testAPI}
function exposeDock(w){const src=dock.replace("if(document.body)boot();else document.addEventListener('DOMContentLoaded',boot,{once:true});\n})();","window.testAPI={findShell,showDock,ensureRoot};\n})();");w.eval(src);return w.testAPI}

test('dock recognizes only an opened notification shell on notifications route',()=>{const{dom,w}=env();try{w.history.replaceState(null,'','/notifications');const api=exposeDock(w),popup=w.document.getElementById('popup');popup.hidden=false;w.document.getElementById('list').innerHTML='<a class="m-navbarNoticeItem">Aさんがコメントしました3分前</a>';assert.equal(api.findShell().id,'popup');api.showDock(true);const root=w.document.querySelector('[data-mumei-notification-dock="1"]');assert.ok(root);assert.equal(root.querySelectorAll('button').length,4);popup.hidden=true;assert.equal(api.findShell(),null)}finally{dom.window.close()}});

test('direct reader extracts rows and sends oldest-to-newest without iframe forwarding',async()=>{const{dom,w,values}=env();try{const popup=w.document.getElementById('popup');popup.hidden=false;popup.setAttribute('data-mumei-notice-shell-v3','1');w.document.getElementById('list').innerHTML='<a class="m-navbarNoticeItem" data-notification-id="new" href="https://note.com/a/n/n1?c=c1">Aさんがあなたのコメントに返信しました3分前</a><a class="m-navbarNoticeItem" data-notification-id="old" href="https://note.com/a/m/m1">未知の通知3分前</a>';const api=expose(w,reader,['rows','rowData','panel','sendBatch','sig','scan']);assert.equal(api.panel().id,'popup');const rs=api.rows(popup);assert.equal(rs.length,2);assert.match(api.rowData(rs[0]).target_url,/n1\?c=c1/);values.set('mumei_insight_notification_sync_token_v2:fixture','fixture-only');const sent=[];w.GM.xmlHttpRequest=o=>{const batch=JSON.parse(o.data).notifications;sent.push(...batch.map(x=>x.meta.event_identity));o.onload({status:200,responseText:JSON.stringify({ok:true,confirmedClientSignatures:batch.map(api.sig)})})};await api.scan();assert.deepEqual(sent,['notice:old','notice:new']);assert.equal(values.get('mumei_insight_notification_saved_v2919:fixture').length,2)}finally{dom.window.close()}});

test('partial acknowledgement leaves only missing rows in outbox',async()=>{const{dom,w,values}=env();try{const api=expose(w,reader,['sendBatch','sig','readOutbox']),a={id:'fixture'},saved=new Set();values.set('mumei_insight_notification_sync_token_v2:fixture','fixture-only');const input=['old','new'].map(id=>({raw_text:id+'さんが返信しました',target_url:'https://note.com/a/n/n1',meta:{event_identity:'notice:'+id}}));w.GM.xmlHttpRequest=o=>o.onload({status:200,responseText:JSON.stringify({ok:true,confirmedClientSignatures:[api.sig(input[0])]})});await assert.rejects(api.sendBatch(input,a,saved),/未保存/);assert.equal(api.readOutbox('fixture').length,1);assert.equal(api.readOutbox('fixture')[0].meta.event_identity,'notice:new')}finally{dom.window.close()}});

test('account change blocks transmitting a previous-account outbox',async()=>{const{dom,w,values}=env();try{const api=expose(w,reader,['sendBatch','readOutbox']);values.set('mumei_insight_notification_sync_token_v2:fixture','fixture-only');w.fetch=async()=>({ok:true,json:async()=>({data:{urlname:'different'}})});let sent=false;w.GM.xmlHttpRequest=()=>{sent=true};await assert.rejects(api.sendBatch([{raw_text:'Aさんが返信しました',meta:{event_identity:'notice:1'}}],{id:'fixture'},new Set()),/NOTE_ACCOUNT_CHANGED/);assert.equal(sent,false);assert.equal(api.readOutbox('fixture').length,1)}finally{dom.window.close()}});

test('active notification scripts parse',()=>{for(const name of ['note-insight-notification-dock-watch-v312.js','note-insight-notification-reader-v322.js','note-insight-notification-loader-v318.js','note-insight-dashboard-integrated-v318.js'])assert.doesNotThrow(()=>new Function(read(name)))});
