import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=(p)=>readFile(new URL(`../${p}`,import.meta.url),"utf8");

test("TOP requires two TOP presses while note remains plain navigation",async()=>{const app=await read("src/App.tsx"),home=await read("src/hub-home.tsx"),index=await read("index.html");for(const x of ["topArmed","もう1回で終了","exitApp","android.intent.action.MAIN","android.intent.category.HOME","note-exit","aria-label=\"noteへ\"","https://note.com/"])assert.match(app,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(app,/note-exit[^\n]*アプリ終了/);assert.doesNotMatch(home,/hub-note-exit-wrap|hub-note-exit/);assert.doesNotMatch(index,/app-exit-to-note/);assert.doesNotMatch(app,/forgetMemberSession|forgetInsightAccount/);});

test("notification list is denser while category badges stay prominent",async()=>{const css=await read("src/insight-polish-v1.css"),base=await read("src/member-insight-notifications-final.css"),ui=await read("src/member-insight-notifications-final.tsx");for(const x of [".minf-list{gap:5px", ".minf-list article{padding:7px 8px", ".minf-avatar{width:32px", ".minf-main{gap:2px", "-webkit-line-clamp:2", ".minf-meta span{padding:4px 9px!important;font-size:11.5px!important", ".minf-tabs button{min-height:31px!important;padding:0 9px!important;font-size:10.5px!important"])assert.match(css,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(base,/type-membership_board_reply/);assert.match(base,/type-membership_reaction/);for(const x of ["minf-meta","minf-who","minf-main","minf-target","掲示板返信","メンシプ反応","minf-compact-status","更新状態・精度"])assert.match(ui,new RegExp(x));assert.doesNotMatch(ui,/note公式Dashboardへ/);});

test("supporter metric is explicitly inbound",async()=>{const css=await read("src/insight-polish-v1.css");assert.match(css,/スキしてくれた人数/);assert.match(css,/inbound unique supporters/);});

test("dashboard analysis compares only like-for-like periods and never mixes participant data",async()=>{const api=await read("supabase/functions/insight-dashboard-data/index.ts"),ui=await read("src/member-insight-analytics-final.tsx"),sync=await read("public/note-insight-dashboard-sync.user.js");assert.match(api,/samePeriod=latest\?all\.filter\(\(r:any\)=>String\(r\.period_type\)===String\(latest\.period_type\)\):\[\]/);assert.match(api,/\.eq\("member_id",m\.scope\)/);assert.match(api,/DASHBOARD_ACCOUNT_MISMATCH/);assert.match(sync,/current!==paired/);for(const x of ["本人の公式データだけ","別参加者やオーナーの数値は混ぜません","スクリーンショットや他参加者の値は分析データに使用しません"])assert.match(ui,new RegExp(x));});

test("comment likes are analyzed as events, people, and ranked actors only on analysis load",async()=>{const ui=await read("src/member-insight-analytics-final.tsx"),css=await read("src/member-insight-analytics-final.css");for(const x of ["loadCommentLikes","comment_like","コメントスキ","COMMENT SUPPORTERS","コメントへスキした人"])assert.match(ui,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(css,/mia2-people/);assert.match(ui,/useEffect\(\(\)=>\{void refresh\(\)\},\[revision\]\)/);assert.doesNotMatch(ui,/setInterval|visibilitychange/);});

test("social analytics preserve official follower value and exact previous-snapshot delta",async()=>{const ui=await read("src/member-insight-analytics-final.tsx"),css=await read("src/member-insight-analytics-final.css");for(const x of ["latest=f.at(-1)","prev=f.at(-2)","delta=latest&&prev","フォロワー公式値","前回比","直近7日スキ","直近7日コメント"])assert.match(ui,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(css,/mia2-kpis/);assert.match(css,/mia2-people/);});

test("INSIGHT native Dashboard visuals remain distinct from official bar and pie charts",async()=>{const ui=await read("src/member-insight-analytics-final.tsx"),css=await read("src/member-insight-analytics-final.css");for(const x of ["PULSE WAVE","SOURCE ORBIT","ARTICLE CONSTELLATION","REVENUE THERMAL","INSIGHT NEXT ACTION"])assert.match(ui,new RegExp(x));for(const x of ["mia2-wave .pv","mia2-wave .sales","mia2-orbit","mia2-constellation","mia2-thermal","mia2-recs"])assert.match(css,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});
