import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const room='11111111-1111-1111-1111-111111111111';
for(const withNotifications of [false,true])test(`DMのURLのまま🔔を開くと、通信待ちのDMパネルも消え、遅い進捗で復活しない（通知ツール${withNotifications?'あり':'なし'}）`,async()=>{
 const dom=new JSDOM('<header><button aria-label="通知">🔔</button></header><main><p>DMの会話 1分前</p><textarea></textarea></main>',{url:'https://note.com/messages/rooms/'+room,runScripts:'outside-only'}),w=dom.window;
 const observers=[],Observer=w.MutationObserver;w.MutationObserver=class extends Observer{constructor(callback){super(callback);observers.push(this)}};
 w.HTMLElement.prototype.getBoundingClientRect=()=>({width:390,height:300,left:0,top:0});w.setTimeout=()=>0;w.setInterval=()=>0;w.fetch=()=>new Promise(()=>{});
 const src=readFileSync('public/note-insight-dm-reader-v1.js','utf8'),end=src.lastIndexOf('{let timer=0,running=false;');w.eval(src.slice(0,end)+'window.__dmTest={showStatus,dmRoute};'+src.slice(end));
 if(withNotifications){for(const name of ['reader-v4','controls-v1'])w.eval(readFileSync('public/note-insight-notification-'+name+'.js','utf8'));assert.equal(w.__mumeiNotificationReaderV4.findPanel(),null)}
 w.__dmTest.showStatus({threadCount:20});assert.ok(w.document.getElementById('mumei-dm-reader-status'));assert.equal(w.__mumeiInsightDmReaderV1Api.run(),true);
 const bell=w.document.createElement('section');bell.id='bell';bell.innerHTML='<button role="tab">通知</button><button role="tab">お知らせ</button><ul><li class="m-navbarNoticeItem">人物さんがスキしました <time>1分前</time></li></ul>';w.document.body.append(bell);
 await new Promise(r=>setImmediate(r));assert.equal(w.__dmTest.dmRoute(),false);assert.equal(w.document.getElementById('mumei-dm-reader-status'),null);
 w.__dmTest.showStatus({lastReadCount:12,lastSavedCount:12});assert.equal(w.document.getElementById('mumei-dm-reader-status'),null,'late save acknowledgements must not restore DM controls');
 if(withNotifications){assert.equal(w.__mumeiNotificationReaderV4.findPanel(),bell);w.__mumeiNotificationControlsV1.mount();assert.ok(w.document.getElementById('mumei-inline-notification-controls-v1'))}
 bell.hidden=true;await new Promise(r=>setImmediate(r));assert.equal(w.__dmTest.dmRoute(),true);w.__dmTest.showStatus({lastSavedCount:12});assert.ok(w.document.getElementById('mumei-dm-reader-status'));
 if(withNotifications){w.__mumeiNotificationControlsV1.mount();assert.equal(w.document.getElementById('mumei-inline-notification-controls-v1'),null)}
 bell.hidden=false;await new Promise(r=>setImmediate(r));assert.equal(w.document.getElementById('mumei-dm-reader-status'),null,'attribute-only reopening must also hide DM controls');observers.forEach(o=>o.disconnect());dom.window.close();
});
function dm(){const dom=new JSDOM('<main></main>',{url:'https://note.com/messages/rooms/'+room,runScripts:'outside-only'}),w=dom.window;w.setTimeout=()=>0;w.fetch=async()=>({ok:true,json:async()=>({data:{urlname:'tester'}})});w.eval(readFileSync('public/note-insight-dm-network-v2.js','utf8'));return{dom,w,api:w.__mumeiDmNetworkV2}}
test('DMのルームAPIのdata配列から本文を取り出し、改行を保持する',()=>{const h=dm(),rows=h.api.extract({data:[{id:'m1',body:'一行目\n二行目',created_at:'2026-09-22T00:00:00Z'}]},'https://note.com/api/v1/messages/rooms/'+room,'tester');assert.equal(rows.length,1);assert.equal(rows[0].body,'一行目\n二行目');h.dom.window.close()});
test('DMの分割されたReact配信データを実行せずに解析し、本文への参照を解決する',()=>{const h=dm(),flight='1:'+JSON.stringify({room:{id:room,messages:['$a']}})+'\na:'+JSON.stringify({id:'m2',body:'会話の本文\n続き',created_at:'2026-09-22T00:00:00Z'})+'\n',parts=[flight.slice(0,35),flight.slice(35)];for(const part of parts){const s=h.w.document.createElement('script');s.textContent='self.__next_f.push('+JSON.stringify([1,part])+')';h.w.document.body.append(s)}const bad=h.w.document.createElement('script');bad.textContent='window.unsafeExecuted=true;';h.w.document.body.append(bad);const rows=h.api.fromDocument(h.w.document,h.w.location.href,'tester');assert.equal(rows.length,1);assert.equal(rows[0].body,'会話の本文\n続き');assert.equal(h.w.unsafeExecuted,undefined);h.dom.window.close()});
test('ネットワークで確認した保存位置を、ID属性のない通知DOMに表示する',async()=>{const dom=new JSDOM('<main id="notices"><div class="m-navbarNoticeItem"><a href="https://note.com/m/m123">人物さんが 新しい記事を2本追加しました</a><p>記事の見出し</p><small>1分前</small></div></main>',{url:'https://note.com/',runScripts:'outside-only'}),w=dom.window,cp={boundaryEventIdentity:'notice:10',boundaryDisplayText:'人物さんが 新しい記事を2本追加しました',boundaryTargetUrl:'https://note.com/m/m123',boundaryAt:100,lastSaveAt:100};w.fetch=async()=>({ok:true,json:async()=>({data:{urlname:'tester'}})});w.GM={getValue:async()=>cp,setValue:async()=>{}};w.__mumeiNotificationReaderV4={findPanel:()=>w.document.querySelector('main')};w.eval(readFileSync('public/note-insight-notification-checkpoint-v325.js','utf8'));await w.__mumeiV3Checkpoint325.ready;w.__mumeiV3Checkpoint325.mark();assert.match(w.document.querySelector('#mumei-v3-saved-boundary-v3223').textContent,/ここまで保存/);w.document.querySelector('a').textContent='人物さんが 新しい記事を3本追加しました';w.__mumeiV3Checkpoint325.mark();assert.equal(w.document.querySelector('#mumei-v3-saved-boundary-v3223'),null);dom.window.close()});
test('本人通知なし分析は立体SVG・棒の意味と単位・公開日軸を表示し、保存済み表示を通信待ちにしない',async()=>{const html=readFileSync('public/install-free-analysis-v3.html','utf8'),dom=new JSDOM(html,{url:'https://mumei-s.github.io/note-insight/install-free-analysis-v3.html',runScripts:'outside-only'}),w=dom.window;w.localStorage.setItem('mumei-insight-access-token','fixture');w.localStorage.setItem('mumei-insight-active-account-v3','tester');w.localStorage.setItem('mumei-public-analysis-cache-v1:tester',JSON.stringify({at:Date.now(),data:{articles:[{title:'テスト記事',published_at:new Date().toISOString(),like_count:30,comment_count:10}],counts:{}}}));w.fetch=()=>new Promise(()=>{});w.eval([...w.document.scripts].map(s=>s.textContent).join('\n'));const svg=w.document.querySelector('#reactionDonut svg');assert.ok(svg);assert.match(svg.getAttribute('aria-label'),/30件 コメント 10件/);assert.match(w.document.querySelector('#distribution').textContent,/記事本数.*本/s);assert.match(w.document.querySelector('#days').textContent,/平均反応.*件\/記事/s);assert.match(w.document.querySelector('#topBars').textContent,/テスト記事/);assert.match(w.document.querySelector('#trend').getAttribute('aria-label'),/公開日/);assert.match(w.document.querySelector('#kpis').textContent,/フォロワー未取得/);w.document.querySelector('[data-label="コメント"]').click();assert.equal(w.document.querySelector('#reactionTotal').textContent,'10');assert.equal(w.document.querySelector('#content').classList.contains('hidden'),false);dom.window.close()});
async function backend({failArticles=false}={}){
 const ts=(await import('typescript')).default,vm=await import('node:vm'),writes=[],reads=[];
 const db={from(table){let action='select',payload;const q={};for(const method of ['select','eq','gt','is','in','gte','order','range','limit'])q[method]=()=>q;for(const method of ['insert','update','upsert'])q[method]=p=>{action=method;payload=p;return q};const run=()=>{if(action!=='select'){writes.push({table,action,payload});return{data:action==='insert'&&table==='insight_dashboard_snapshots'?{id:42}:[],error:failArticles&&table==='insight_dashboard_article_snapshots'?new Error('fixture-save-failure'):null}}reads.push(table);if(table==='insight_member_sessions')return{data:{application_id:'member',expires_at:'2099-01-01',revoked_at:null}};if(table==='insight_access_applications')return{data:{id:'member',status:'active',verified_at:'2026-01-01',note_id:'tester'}};if(table==='insight_notification_ingest_tokens')return{data:{member_id:'member'}};if(table==='insight_dashboard_snapshots')return{data:[{id:2,captured_at:'2026-09-22',dashboard_schema_version:2,total_page_views:2222},{id:1,captured_at:'2026-09-01',dashboard_schema_version:2,total_page_views:1111}]};return{data:[]}};q.maybeSingle=q.single=async()=>run();q.then=(yes,no)=>Promise.resolve(run()).then(yes,no);return q}};
 let handler;const ctx=vm.createContext({Deno:{env:{get:()=> 'fixture'},serve:fn=>handler=fn},crypto:globalThis.crypto,TextEncoder,Request,Response,console});const src=ts.transpileModule(readFileSync('supabase/functions/insight-dashboard-data/index.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText,mod=new vm.SourceTextModule(src,{context:ctx});await mod.link(()=>new vm.SyntheticModule(['createClient'],function(){this.setExport('createClient',()=>db)},{context:ctx}));await mod.evaluate();return{writes,reads,call:async body=>(await handler(new Request('https://example.test',{method:'POST',headers:{'X-Insight-Token':'fixture','X-Ingest-Token':'fixture'},body:JSON.stringify(body)}))).json()}
}
test('ダッシュボード先行APIは公開スキ全履歴を待たず、最新スナップショットを選ぶ',async()=>{const h=await backend(),r=await h.call({action:'analysis',dashboardOnly:true});assert.equal(r.latestDashboard.pageViews,2222);assert.ok(!h.reads.includes('insight_public_likes'));assert.ok(!h.reads.includes('insight_public_comments'))});
test('ダッシュボードの記事保存が失敗したら未完了スナップショットを公開しない',async()=>{for(const failArticles of [true,false]){const h=await backend({failArticles}),r=await h.call({action:'ingest',noteId:'tester',articles:[{key:'n1',title:'記事',pageViews:10}]});assert.equal(h.writes.find(x=>x.table==='insight_dashboard_snapshots'&&x.action==='insert').payload.confirmed,false);const confirmed=h.writes.filter(x=>x.table==='insight_dashboard_snapshots'&&x.action==='update');assert.equal(confirmed.length,failArticles?0:1);assert.equal(r.ok,!failArticles)}});
