import { createClient } from "npm:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false}});
const NOTE_ORIGIN="https://note.com";
const SESSION_MS=1000*60*60*24*365*5;
const ALLOWED_ORIGIN="https://mumei-s.github.io";

function cors(req:Request){const origin=req.headers.get("origin")||"";return {"Access-Control-Allow-Origin":origin===ALLOWED_ORIGIN?origin:ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"content-type,x-owner-token,x-insight-applicant,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function json(req:Request,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:cors(req)})}
function clean(v:unknown,max=300){return typeof v==="string"?v.trim().slice(0,max):""}
function noteId(v:unknown){const raw=clean(v,300);let id=raw;if(/^https?:\/\//i.test(raw)){try{const u=new URL(raw);if(u.hostname!=="note.com"&&u.hostname!=="www.note.com")return "";id=u.pathname.split("/").filter(Boolean)[0]||""}catch{return ""}}id=id.replace(/^@/,"").trim();return /^[A-Za-z0-9_-]{1,80}$/.test(id)?id.toLowerCase():""}
async function sha256(s:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function randomHex(bytes=24){const b=crypto.getRandomValues(new Uint8Array(bytes));return [...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
function randomCode(){const b=crypto.getRandomValues(new Uint8Array(4));return "INSIGHT-"+[...b].map(x=>x.toString(16).padStart(2,"0")).join("").toUpperCase()}
async function fetchCreator(id:string){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(`${NOTE_ORIGIN}/api/v2/creators/${encodeURIComponent(id)}`,{headers:{Accept:"application/json","User-Agent":"Mumei-S-note-INSIGHT/3.0 (+public-profile-verification)"},signal:ctrl.signal});if(!r.ok)throw new Error(r.status===404?"NOTE_ACCOUNT_NOT_FOUND":"NOTE_PROFILE_UNAVAILABLE");const p=await r.json().catch(()=>({})),d=p?.data||{};return {noteId:String(d.urlname||id).toLowerCase(),displayName:String(d.nickname||id).slice(0,300),imageUrl:typeof (d.profileImageUrl??d.profile_image_url)==="string"?(d.profileImageUrl??d.profile_image_url):null,profile:String(d.profile||d.description||"")}}finally{clearTimeout(timer)}}
async function isOwner(token:string){if(!token)return false;const {data,error}=await supabase.rpc("is_owner_token",{p_token:token});return !error&&data===true}
async function appByApplicant(req:Request){const raw=req.headers.get("X-Insight-Applicant")||"";if(!raw)throw new Error("APPLICANT_TOKEN_REQUIRED");const {data,error}=await supabase.from("insight_access_applications").select("*").eq("applicant_token_hash",await sha256(raw)).maybeSingle();if(error||!data)throw new Error("APPLICANT_TOKEN_INVALID");return data}
async function appBySession(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const h=await sha256(raw),now=new Date().toISOString();const {data:s,error}=await supabase.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",h).maybeSingle();if(error||!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const {data:a,error:ae}=await supabase.from("insight_access_applications").select("*").eq("id",s.application_id).maybeSingle();if(ae||!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");await supabase.from("insight_member_sessions").update({last_seen_at:now}).eq("id",s.id);return {app:a,sessionId:s.id}}
async function issueSession(applicationId:string){const raw=randomHex(36),now=Date.now();await supabase.from("insight_member_sessions").insert({application_id:applicationId,token_hash:await sha256(raw),expires_at:new Date(now+SESSION_MS).toISOString()});return raw}
async function publicParticipantUpsert(a:any,active=true){const now=new Date().toISOString();const {data:existing,error:findError}=await supabase.from("insight_participants_public").select("member_id,role,display_name,image_url").eq("note_id",a.note_id).maybeSingle();if(findError)throw findError;const payload={note_id:a.note_id,display_name:a.display_name||existing?.display_name||`@${a.note_id}`,image_url:a.image_url||existing?.image_url||null,active,synced_at:now};if(existing?.member_id){const {error}=await supabase.from("insight_participants_public").update(payload).eq("member_id",existing.member_id);if(error)throw error;return}const {error}=await supabase.from("insight_participants_public").insert({member_id:String(a.id),role:"member",...payload});if(error)throw error}
async function notificationProfileUpsert(a:any,verified:boolean){const now=new Date().toISOString();await supabase.from("insight_notification_profiles").upsert({member_id:String(a.id),note_urlname:a.note_id,note_nickname:a.display_name||a.note_id,role:"member",verified_at:verified?now:null,verification_code:null,public_watch_enabled:verified,watch_error:null,updated_at:now},{onConflict:"member_id"})}
function safeApp(a:any,includeCode=false){return {id:a.id,noteId:a.note_id,displayName:a.display_name,imageUrl:a.image_url,status:a.status,verificationCode:includeCode?a.verification_code_plain||null:null,approvedAt:a.approved_at,verifiedAt:a.verified_at,createdAt:a.created_at,updatedAt:a.updated_at}}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});try{if(req.method!=="POST")return json(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);const body=await req.json().catch(()=>({})),action=clean(body?.action,80)||"session";

if(action==="public-participants"){const {data,error}=await supabase.from("insight_participants_public").select("member_id,note_id,display_name,image_url,role,active,synced_at").eq("active",true).order("synced_at",{ascending:true});if(error)throw error;return json(req,{ok:true,participants:data||[]})}

if(action==="apply"){const id=noteId(body?.noteInput);if(!id)throw new Error("NOTE_ID_INVALID");const creator=await fetchCreator(id);const {data:existing}=await supabase.from("insight_access_applications").select("*").ilike("note_id",creator.noteId).maybeSingle();if(existing&&["pending","approved","active"].includes(existing.status))return json(req,{ok:false,error:existing.status==="active"?"ALREADY_ACTIVE":"APPLICATION_EXISTS",status:existing.status},409);const applicant=randomHex(32),hash=await sha256(applicant),now=new Date().toISOString();let row:any;if(existing){const {data,error}=await supabase.from("insight_access_applications").update({display_name:creator.displayName,image_url:creator.imageUrl,status:"pending",applicant_token_hash:hash,verification_code_hash:null,verification_code_plain:null,approved_at:null,verified_at:null,revoked_at:null,application_attempts:Number(existing.application_attempts||0)+1,updated_at:now}).eq("id",existing.id).select().single();if(error)throw error;row=data}else{const {data,error}=await supabase.from("insight_access_applications").insert({note_id:creator.noteId,display_name:creator.displayName,image_url:creator.imageUrl,status:"pending",applicant_token_hash:hash}).select().single();if(error)throw error;row=data}return json(req,{ok:true,applicantToken:applicant,application:safeApp(row)})}

if(action==="application-status"){const a=await appByApplicant(req);return json(req,{ok:true,application:safeApp(a,a.status==="approved")})}

if(action==="verify-profile"){const a=await appByApplicant(req);if(a.status!=="approved"||!a.verification_code_plain)throw new Error("APPLICATION_NOT_APPROVED");const creator=await fetchCreator(a.note_id),attempts=Number(a.verification_attempts||0)+1;if(attempts>30)throw new Error("VERIFICATION_ATTEMPTS_EXCEEDED");await supabase.from("insight_access_applications").update({verification_attempts:attempts,updated_at:new Date().toISOString()}).eq("id",a.id);if(!creator.profile.includes(a.verification_code_plain))throw new Error("PROFILE_CODE_NOT_FOUND");const now=new Date().toISOString();const {data:active,error}=await supabase.from("insight_access_applications").update({display_name:creator.displayName,image_url:creator.imageUrl,status:"active",verified_at:now,verification_code_plain:null,updated_at:now}).eq("id",a.id).select().single();if(error)throw error;await publicParticipantUpsert(active,true);await notificationProfileUpsert(active,true);const memberToken=await issueSession(active.id);return json(req,{ok:true,verified:true,memberToken,application:safeApp(active),message:"PROFILE_VERIFIED_RESTORE_BIO"})}

if(action==="login"){const id=noteId(body?.noteInput),pass=clean(body?.passcode,120);if(!id||!pass)throw new Error("LOGIN_FIELDS_REQUIRED");const {data:a}=await supabase.from("insight_access_applications").select("*").ilike("note_id",id).maybeSingle();if(!a||a.status!=="active"||!a.verification_code_hash||await sha256(pass)!==a.verification_code_hash)throw new Error("LOGIN_INVALID");const memberToken=await issueSession(a.id);return json(req,{ok:true,memberToken,application:safeApp(a)})}

if(action==="session"){const {app}=await appBySession(req);return json(req,{ok:true,application:safeApp(app)})}

if(action==="logout"){const raw=req.headers.get("X-Insight-Token")||"";if(raw)await supabase.from("insight_member_sessions").update({revoked_at:new Date().toISOString()}).eq("token_hash",await sha256(raw)).is("revoked_at",null);return json(req,{ok:true})}

if(action.startsWith("owner-")){const token=req.headers.get("X-Owner-Token")||"";if(!(await isOwner(token)))throw new Error("OWNER_LOGIN_REQUIRED");if(action==="owner-list"){const {data,error}=await supabase.from("insight_access_applications").select("*").order("created_at",{ascending:false});if(error)throw error;return json(req,{ok:true,applications:(data||[]).map((a:any)=>safeApp(a,false))})}const id=clean(body?.id,80);if(!id)throw new Error("APPLICATION_ID_REQUIRED");const {data:a,error:findError}=await supabase.from("insight_access_applications").select("*").eq("id",id).maybeSingle();if(findError||!a)throw new Error("APPLICATION_NOT_FOUND");const now=new Date().toISOString();if(action==="owner-approve"||action==="owner-reissue"){const code=randomCode();await supabase.from("insight_member_sessions").update({revoked_at:now}).eq("application_id",a.id).is("revoked_at",null);const {data:next,error}=await supabase.from("insight_access_applications").update({status:"approved",verification_code_hash:await sha256(code),verification_code_plain:code,approved_at:now,verified_at:null,revoked_at:null,verification_attempts:0,updated_at:now}).eq("id",a.id).select().single();if(error)throw error;await publicParticipantUpsert(next,false);await notificationProfileUpsert(next,false);return json(req,{ok:true,application:safeApp(next,false)})}if(action==="owner-reject"||action==="owner-revoke"){const status=action==="owner-reject"?"rejected":"revoked";await supabase.from("insight_member_sessions").update({revoked_at:now}).eq("application_id",a.id).is("revoked_at",null);const {data:next,error}=await supabase.from("insight_access_applications").update({status,verification_code_plain:null,verification_code_hash:null,revoked_at:status==="revoked"?now:null,updated_at:now}).eq("id",a.id).select().single();if(error)throw error;await publicParticipantUpsert(next,false);await notificationProfileUpsert(next,false);return json(req,{ok:true,application:safeApp(next)})}throw new Error("ACTION_NOT_SUPPORTED")}

throw new Error("ACTION_NOT_SUPPORTED");
}catch(e){const message=e instanceof Error?e.message:String(e);console.error(message);const status=/NOT_FOUND/.test(message)?404:/EXISTS|ALREADY_ACTIVE/.test(message)?409:/REQUIRED|INVALID|INACTIVE|NOT_APPROVED|PROFILE_CODE|ATTEMPTS/.test(message)?401:500;return json(req,{ok:false,error:message},status)}});
