import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,PURPOSE="note_dashboard_sync";
const db=createClient(U,K,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-owner-token,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function owner(req:Request){const raw=req.headers.get("X-Owner-Token")||"";if(!raw)return false;const{data}=await db.from("unified_owner_sessions").select("id").eq("token_hash",await sha(raw)).is("revoked_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();return!!data?.id}
const ownerIdentity=()=>({id:"owner",noteId:"ss_yr",name:"無名S note",role:"owner",authorized:true,verifiedAt:new Date().toISOString()});
async function participant(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)return null;const now=new Date().toISOString(),{data:s}=await db.from("insight_member_sessions").select("application_id").eq("token_hash",await sha(raw)).is("revoked_at",null).gt("expires_at",now).maybeSingle();if(!s?.application_id)return null;const{data:a}=await db.from("insight_access_applications").select("id,note_id,display_name,status,verified_at").eq("id",s.application_id).maybeSingle();if(!a?.id||a.status!=="active")return null;return{id:String(a.id),noteId:String(a.note_id).toLowerCase(),name:a.display_name||a.note_id,role:"member",authorized:true,verifiedAt:a.verified_at||null}}
async function identity(req:Request,preferred="member"){const p=await participant(req);if(p?.noteId==="ss_yr"&&p.verifiedAt)return ownerIdentity();if(preferred==="owner"&&await owner(req))return ownerIdentity();if(p)return p;if(await owner(req))return ownerIdentity();throw new Error("DASHBOARD_LOGIN_REQUIRED")}
async function identityByMemberId(memberId:string){if(memberId==="owner")return ownerIdentity();const{data:a}=await db.from("insight_access_applications").select("id,note_id,display_name,status,verified_at").eq("id",memberId).maybeSingle();if(!a?.id||a.status!=="active"||!a.verified_at)throw new Error("DASHBOARD_ACCOUNT_UNKNOWN");const noteId=String(a.note_id).toLowerCase();if(noteId==="ss_yr")return ownerIdentity();return{id:String(a.id),noteId,name:a.display_name||a.note_id,role:"member",authorized:true,verifiedAt:a.verified_at}}
function token(){return crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","")}
function pairCode(){return String(crypto.getRandomValues(new Uint32Array(1))[0]%100000000).padStart(8,"0")}
async function issue(memberId:string,noteId:string){const raw=token(),now=new Date(),exp=new Date(now.getTime()+3650*86400000).toISOString();await db.from("insight_notification_ingest_tokens").update({revoked_at:now.toISOString()}).eq("member_id",memberId).eq("purpose",PURPOSE).is("revoked_at",null);const{error}=await db.from("insight_notification_ingest_tokens").insert({member_id:memberId,token_hash:await sha(raw),purpose:PURPOSE,expires_at:exp});if(error)throw error;return{ingestToken:raw,expiresAt:exp,memberId,noteId}}
async function paired(memberId:string){const now=new Date().toISOString(),{data,error}=await db.from("insight_notification_ingest_tokens").select("expires_at,created_at").eq("member_id",memberId).eq("purpose",PURPOSE).is("revoked_at",null).gt("expires_at",now).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return{paired:Boolean(data?.expires_at),pairedExpiresAt:data?.expires_at||null}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);try{const b=await req.json().catch(()=>({})),action=String(b?.action||"stats"),preferred=String(b?.role||"member");if(action==="pair-exchange"){const code=String(b?.code||"").replace(/\D/g,"").slice(0,8);if(code.length!==8)return out({ok:false,error:"PAIR_CODE_INVALID"},400);const now=new Date().toISOString(),{data,error}=await db.from("insight_notification_pair_codes").select("id,member_id,expires_at,used_at,purpose").eq("code_hash",await sha(code)).eq("purpose","dashboard").is("used_at",null).gt("expires_at",now).maybeSingle();if(error)throw error;if(!data?.id)return out({ok:false,error:"PAIR_CODE_EXPIRED"},401);const who=await identityByMemberId(String(data.member_id)),issued=await issue(who.id,who.noteId);await db.from("insight_notification_pair_codes").update({used_at:now}).eq("id",data.id);return out({ok:true,...issued,paired:true,toolVersion:"1.0.0"})}const who=await identity(req,preferred);if(action==="pair-start"){const code=pairCode(),now=new Date(),exp=new Date(now.getTime()+10*60*1000).toISOString();await db.from("insight_notification_pair_codes").delete().eq("member_id",who.id).eq("purpose","dashboard").is("used_at",null);const{error}=await db.from("insight_notification_pair_codes").insert({member_id:who.id,code_hash:await sha(code),expires_at:exp,purpose:"dashboard"});if(error)throw error;return out({ok:true,memberId:who.id,noteId:who.noteId,pairingCode:code,expiresAt:exp,...await paired(who.id)})}if(action==="stats"){const[{data:s,error},p]=await Promise.all([db.from("insight_dashboard_snapshots").select("id,captured_at,official_collected_at,dashboard_schema_version,total_impressions,total_page_views,total_sales_yen").eq("member_id",who.id).order("captured_at",{ascending:false}).limit(1).maybeSingle(),paired(who.id)]);if(error)throw error;return out({ok:true,memberId:who.id,noteId:who.noteId,name:who.name,role:who.role,lastSnapshot:s||null,...p})}if(action==="issue")return out({ok:true,...await issue(who.id,who.noteId),paired:true});return out({ok:false,error:"UNKNOWN_ACTION"},400)}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/REQUIRED|INVALID|UNKNOWN|EXPIRED/.test(msg)?401:500)}});
