import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}}),ORIGIN="https://mumei-s.github.io";
const H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const{data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const{data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),scope:noteId==="ss_yr"?"owner":String(a.id),noteId}}
const txt=(v:any,d="")=>typeof v==="string"?v:d;
const ts=(r:any)=>Date.parse(r.occurred_at||r.captured_at||0)||0;
const canon=(v:any)=>String(v||"").replace(/\s+/g," ").replace(/\s(?:たった今|昨日|\d+\s*(?:秒|分|時間|日|週|か月|ヶ月|月|年)前)$/u,"").trim();
const urlKey=(v:any)=>String(v||"").split(/[?#]/)[0].replace(/\/$/,"").toLowerCase();
function jstDay(v:any){const ms=Date.parse(String(v||""));if(!Number.isFinite(ms))return"";return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(ms))}
function actorKey(r:any){return urlKey(r.actor_url)||String(r.actor_name||"").toLowerCase()}
function explicitManual(source:string){return /^note-notification-(?:manual-sync-v\d+|explicit-sync(?:-v\d+)?|continuous-sync-v\d+)$/.test(source)}
function useful(r:any){const source=String(r?.meta?.source||""),type=String(r.notification_type||"other"),raw=canon(r.raw_text);if(source==="canonical-public-comments")return true;if(raw.length<5||raw.length>700)return false;if(explicitManual(source))return true;if(type==="other")return false;if(["my_article_magazine_added","tip","membership_reaction","membership_join","membership_started","membership_plan","membership_board","membership_board_reply","creator_article_posted"].includes(type))return true;if(type==="follow"&&/フォロー|フォロワー/u.test(raw))return true;const action=/(?:さん(?:他\d+名)?(?:が|に)|あなた(?:の|を|に)|新しい(?:スキ|コメント|フォロワー)).{0,320}(?:スキしました|コメントしました|返信しました|フォローしました|フォローされました|追加しました|追加されました|仲間入りしました|参加しました|購入されました|購入しました|投稿しました|話題|高評価|ポイント)|(?:メンバーシップ|メンシプ|Member\s*Ship|掲示板).{0,200}(?:投稿しました|開始しました|始めました|はじめました|追加しました|追加されました|公開しました|参加しました|加入しました|入会しました|メンバーになりました)|(?:購入がありました|返信がありました|コメントがありました)|(?:チップ|サポート|支援|応援金).{0,180}(?:届きました|届いた|受け取りました|受け取った|もらいました|いただきました|贈られました|送られました)/iu.test(raw);return action}
function semanticKey(r:any){const type=String(r.notification_type||"other"),actor=actorKey(r),target=urlKey(r.target_url)||urlKey(r.source_url),raw=canon(r.raw_text),time=ts(r),five=time?Math.floor(time/(5*60_000)):Math.floor((Date.parse(r.captured_at||0)||0)/(5*60_000));if(type==="follow"){const half=time?Math.floor(time/(30*60_000)):Math.floor((Date.parse(r.captured_at||0)||0)/(30*60_000));return`follow|${actor}|${half}`}if(type==="reply"||type==="comment")return`${type}|${actor}|${raw}|${five}`;const base=`${type}|${actor}|${target}|${five}`;if(type==="my_article_magazine_added"&&!target)return`${base}|${r.target_title||raw}`;if(type==="tip"&&!actor&&!target)return`${base}|${raw}`;if(["magazine_follow","magazine_article_added","my_article_magazine_added","magazine_join","membership_board","membership_board_reply","membership_reaction","membership_started","membership_plan","membership_join","purchase","tip","buzz","rating","points","quote","comment_like","like","creator_article_posted"].includes(type))return base;return`${base}|${raw}`}
function score(x:any){return(x?.meta?.body?32:0)+(x.actor_image_url?16:0)+(x.actor_url?8:0)+(x.actor_name?4:0)+(x.target_url?4:0)+(x.target_title?2:0)+(x.occurred_at?1:0)}
function mergeMeta(a:any,b:any){const am=a&&typeof a==="object"?a:{},bm=b&&typeof b==="object"?b:{},body=bm.body||bm.comment_body||am.body||am.comment_body||null;return{...am,...bm,...(body?{body}:{})}}
function dedupe(rows:any[]){const map=new Map<string,any>();for(const r of(rows||[]).filter(useful)){const source=String(r?.meta?.source||""),k=source==="canonical-public-comments"?String(r.id):semanticKey(r),prev=map.get(k);if(!prev){map.set(k,r);continue}const rich=score(r)>score(prev)?r:prev,other=rich===r?prev:r;map.set(k,{...other,...rich,meta:mergeMeta(other.meta,rich.meta),actor_image_url:rich.actor_image_url||other.actor_image_url||null,actor_name:rich.actor_name||other.actor_name||null,actor_url:rich.actor_url||other.actor_url||null,target_title:rich.target_title||other.target_title||null,target_url:rich.target_url||other.target_url||null,source_url:rich.source_url||other.source_url||null,occurred_at:rich.occurred_at||other.occurred_at||null,captured_at:rich.captured_at||other.captured_at||null})}return[...map.values()].sort((a,b)=>ts(b)-ts(a))}
function ownerFromUrl(url:any){try{return(new URL(String(url||""))).pathname.split("/").filter(Boolean)[0]?.toLowerCase()||""}catch{return""}}
function articleOwner(url:any){try{const u=new URL(String(url||"")),m=u.pathname.match(/^\/([^/]+)\/n\//);return m?.[1]?.toLowerCase()||""}catch{return""}}
function decorate(r:any,noteId:string){const article=articleOwner(r.target_url),targetOwner=ownerFromUrl(r.target_url),source=String(r?.meta?.source||""),selfArticle=source==="canonical-public-comments"||(article&&article===noteId),type=String(r.notification_type||"");let contextLabel="",displayCategory=type,articleContext=selfArticle?"self":article?"other":"unknown";if(type==="comment"){contextLabel=selfArticle?"自分の記事へのコメント":article?`@${article} の記事へのコメント`:"コメント"}else if(type==="reply"){displayCategory=selfArticle?"reply_self":"reply_other";contextLabel=selfArticle?"自分の記事のコメントへの返信":article?`@${article} の記事で自分のコメントへの返信`:"相手の記事で自分のコメントへの返信"}else if(type==="comment_like"){contextLabel=selfArticle?"自分の記事のコメントへの♡":article?`@${article} の記事コメントへの♡`:"コメントへの♡"}else if(type==="like"){contextLabel=selfArticle?"自分の記事へのスキ":article?`@${article} の記事へのスキ`:"記事へのスキ"}else if(type==="membership_reaction"){displayCategory=targetOwner&&targetOwner===noteId?"membership_reaction_self":"membership_reaction_joined";contextLabel=displayCategory==="membership_reaction_self"?"自分のメンシプ反応":"参加中のメンシプ反応"}return{...r,comment_body:r?.meta?.body||r?.meta?.comment_body||null,article_context:articleContext,article_owner:article||null,membership_owner:targetOwner||null,display_category:displayCategory,context_label:contextLabel}}
async function commentRows(scope:string,kind:string|null,limit:number,offset=0){let q=db.from("insight_public_comments").select("comment_key,article_key,actor_name,actor_url,actor_image_url,body,occurred_at,is_root",{count:"exact"}).eq("member_id",scope).eq("is_creator",false);if(kind==="comment"||kind==="reply")q=q.eq("is_root",kind==="comment");const{data,error,count}=await q.order("occurred_at",{ascending:false}).range(offset,offset+limit-1);if(error)throw error;const keys=[...new Set((data||[]).map((r:any)=>r.article_key).filter(Boolean))];const{data:arts}=keys.length?await db.from("insight_public_articles").select("article_key,title,url").eq("member_id",scope).in("article_key",keys):{data:[] as any[]};const am=new Map((arts||[]).map((a:any)=>[a.article_key,a]));const rows=(data||[]).map((r:any)=>{const a:any=am.get(r.article_key)||{},type=r.is_root?"comment":"reply";return{id:`public-comment:${r.comment_key}`,member_id:scope,notification_type:type,raw_text:`${r.actor_name||"noteユーザー"}さんが「${a.title||"記事"}」に${type==="reply"?"返信":"コメント"}しました`,actor_name:r.actor_name,actor_url:r.actor_url,actor_image_url:r.actor_image_url,target_title:a.title||null,target_url:a.url||null,occurred_at:r.occurred_at,captured_at:r.occurred_at,is_read:false,meta:{source:"canonical-public-comments",comment_key:r.comment_key,body:r.body}}});return{rows,total:Number(count||0)}}
async function status(scope:string,ids:string[]){const[n,c,s]=await Promise.all([db.from("insight_notifications").select("captured_at").in("member_id",ids).order("captured_at",{ascending:false}).limit(1).maybeSingle(),db.from("insight_public_comments").select("occurred_at").eq("member_id",scope).order("occurred_at",{ascending:false}).limit(1).maybeSingle(),db.from("insight_notification_sync_runs").select("created_at,inserted_count,received_count,source").in("member_id",ids).order("created_at",{ascending:false}).limit(1).maybeSingle()]);const a=Date.parse(String(n.data?.captured_at||""))||0,b=Date.parse(String(c.data?.occurred_at||""))||0,last=Math.max(a,b);return{lastUpdatedAt:last?new Date(last).toISOString():null,lastSyncAt:s.data?.created_at||null,lastSyncSource:s.data?.source||null,lastSyncInserted:Number(s.data?.inserted_count||0),lastSyncReceived:Number(s.data?.received_count||0)}}
async function notificationRows(ids:string[],type:string|null){let q=db.from("insight_notifications").select("id,member_id,notification_type,raw_text,actor_name,actor_url,actor_image_url,target_title,target_url,source_url,occurred_at,captured_at,is_read,meta").in("member_id",ids);if(type)q=q.eq("notification_type",type);const{data,error}=await q.order("captured_at",{ascending:false}).limit(6000);if(error)throw error;return(data||[]).filter((r:any)=>{const t=String(r.notification_type||"");if(t!=="comment"&&t!=="reply")return true;const source=String(r?.meta?.source||"");return explicitManual(source)||source==="canonical-public-comments"})}
function baseKind(kind:string){if(kind==="reply_self"||kind==="reply_other")return"reply";if(kind==="membership_reaction_self"||kind==="membership_reaction_joined")return"membership_reaction";return kind==="all"?null:kind}
function filterDisplay(rows:any[],kind:string,noteId:string){const decorated=rows.map(r=>decorate(r,noteId));if(kind==="all")return decorated;if(kind==="reply_self"||kind==="reply_other"||kind==="membership_reaction_self"||kind==="membership_reaction_joined")return decorated.filter(r=>String(r.display_category||"")===kind);return decorated}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),kind=txt(b.kind,"all"),page=Math.max(1,Number(b.page||1)),size=Math.min(100,Math.max(20,Number(b.pageSize||100))),offset=(page-1)*size,ids=m.scope===m.id?[m.id]:[m.scope,m.id],meta=await status(m.scope,ids),base=baseKind(kind),day=/^\d{4}-\d{2}-\d{2}$/.test(txt(b.day,""))?txt(b.day,""):"";let rows:any[]=[];
if(kind==="comment"||kind==="reply"||kind==="reply_self"||kind==="reply_other"){const[n,c]=await Promise.all([notificationRows(ids,base),commentRows(m.scope,base==="comment"?"comment":"reply",6000,0)]);rows=dedupe([...n,...c.rows])}else if(kind==="all"){const[n,c]=await Promise.all([notificationRows(ids,null),commentRows(m.scope,null,6000,0)]);rows=dedupe([...n,...c.rows])}else rows=dedupe(await notificationRows(ids,base));const filtered=filterDisplay(rows,kind,m.noteId),dated=day?filtered.filter(r=>jstDay(r.occurred_at||r.captured_at)===day):filtered;return out({ok:true,page,pageSize:size,total:dated.length,rows:dated.slice(offset,offset+size),noteId:m.noteId,selectedDay:day||null,...meta})}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
