import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}}),ORIGIN="https://mumei-s.github.io";
function H(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H()})}
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const {data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const {data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),scope:noteId==="ss_yr"?"owner":String(a.id),noteId}}
const txt=(v:any,d="")=>typeof v==="string"?v:d;
const ts=(r:any)=>Date.parse(r.occurred_at||r.captured_at||0)||0;
const canon=(v:any)=>String(v||"").replace(/\s+/g," ").replace(/\s(?:たった今|昨日|\d+\s*(?:秒|分|時間|日|週|か月|ヶ月|月|年)前)$/u,"").trim();
function actorKey(r:any){return String(r.actor_url||r.actor_name||"").toLowerCase()}
function dedupe(rows:any[]){const map=new Map<string,any>();for(const r of rows||[]){const source=String(r?.meta?.source||"");const key=source==="canonical-public-comments"?String(r.id):`${r.notification_type||"other"}|${actorKey(r)}|${r.occurred_at||""}|${canon(r.raw_text)}`;const prev=map.get(key);if(!prev){map.set(key,r);continue}const score=(x:any)=>(x.actor_image_url?8:0)+(x.actor_name?4:0)+(x.target_title?2:0)+(x.target_url?1:0);const rich=score(r)>score(prev)?r:prev,other=rich===r?prev:r;map.set(key,{...other,...rich,actor_image_url:rich.actor_image_url||other.actor_image_url||null,actor_name:rich.actor_name||other.actor_name||null,target_title:rich.target_title||other.target_title||null,target_url:rich.target_url||other.target_url||null})}return[...map.values()].sort((a,b)=>ts(b)-ts(a))}
function articleOwner(url:any){try{const u=new URL(String(url||""));const m=u.pathname.match(/^\/([^/]+)\/n\//);return m?.[1]?.toLowerCase()||""}catch{return""}}
function decorate(r:any,noteId:string){const owner=articleOwner(r.target_url),source=String(r?.meta?.source||""),self=source==="canonical-public-comments"||(owner&&owner===noteId),contextOwner=self?"self":owner?"other":"unknown";let contextLabel="";const type=String(r.notification_type||"");if(type==="comment")contextLabel=self?"自分の記事へのコメント":owner?`@${owner} の記事へのコメント`:"コメント";else if(type==="reply")contextLabel=self?"自分の記事のコメントへの返信":owner?`@${owner} の記事コメントへの返信`:"コメントへの返信";else if(type==="comment_like")contextLabel=self?"自分の記事のコメントへの♡":owner?`@${owner} の記事コメントへの♡`:"コメントへの♡";else if(type==="like")contextLabel=self?"自分の記事へのスキ":owner?`@${owner} の記事へのスキ`:"記事へのスキ";return{...r,article_context:contextOwner,article_owner:owner||null,context_label:contextLabel}}
async function commentRows(scope:string,kind:string|null,limit:number,offset=0){let q=db.from("insight_public_comments").select("comment_key,article_key,actor_name,actor_url,actor_image_url,body,occurred_at,is_root",{count:"exact"}).eq("member_id",scope).eq("is_creator",false);if(kind==="comment"||kind==="reply")q=q.eq("is_root",kind==="comment");const {data,error,count}=await q.order("occurred_at",{ascending:false}).range(offset,offset+limit-1);if(error)throw error;const keys=[...new Set((data||[]).map((r:any)=>r.article_key).filter(Boolean))];const {data:arts}=keys.length?await db.from("insight_public_articles").select("article_key,title,url").eq("member_id",scope).in("article_key",keys):{data:[] as any[]};const am=new Map((arts||[]).map((a:any)=>[a.article_key,a]));const rows=(data||[]).map((r:any)=>{const a:any=am.get(r.article_key)||{},type=r.is_root?"comment":"reply";return{id:`public-comment:${r.comment_key}`,member_id:scope,notification_type:type,raw_text:`${r.actor_name||"noteユーザー"}さんが「${a.title||"記事"}」に${type==="reply"?"返信":"コメント"}しました`,actor_name:r.actor_name,actor_url:r.actor_url,actor_image_url:r.actor_image_url,target_title:a.title||null,target_url:a.url||null,occurred_at:r.occurred_at,captured_at:r.occurred_at,is_read:false,meta:{source:"canonical-public-comments",comment_key:r.comment_key,body:r.body}}});return{rows,total:Number(count||0)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H()});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),kind=txt(b.kind,"all"),page=Math.max(1,Number(b.page||1)),size=Math.min(100,Math.max(20,Number(b.pageSize||100))),offset=(page-1)*size,need=offset+size,ids=m.scope===m.id?[m.id]:[m.scope,m.id];
  if(kind==="comment"||kind==="reply"){const c=await commentRows(m.scope,kind,size,offset);return out({ok:true,page,pageSize:size,total:c.total,rows:c.rows.map(r=>decorate(r,m.noteId)),noteId:m.noteId})}
  let nq=db.from("insight_notifications").select("id,member_id,notification_type,raw_text,actor_name,actor_url,actor_image_url,target_title,target_url,source_url,occurred_at,captured_at,is_read,meta",{count:"exact"}).in("member_id",ids);if(kind==="all")nq=nq.not("notification_type","in",'(comment,reply)');else nq=nq.eq("notification_type",kind);const fetchN=Math.min(Math.max(need*2,200),4000),{data:notices,error:ne,count:nc}=await nq.order("captured_at",{ascending:false}).limit(fetchN);if(ne)throw ne;
  if(kind!=="all"){const rows=dedupe(notices||[]).map(r=>decorate(r,m.noteId));return out({ok:true,page,pageSize:size,total:Math.min(Number(nc||0),rows.length||Number(nc||0)),rows:rows.slice(offset,offset+size),noteId:m.noteId})}
  const c=await commentRows(m.scope,null,fetchN,0),merged=dedupe([...(notices||[]),...c.rows]).map(r=>decorate(r,m.noteId));return out({ok:true,page,pageSize:size,total:Math.max(merged.length,Number(nc||0)+c.total),rows:merged.slice(offset,offset+size),noteId:m.noteId});
}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
