import { createClient } from "npm:@supabase/supabase-js@2.112.3";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}}),ORIGIN="https://mumei-s.github.io";
function H(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H()})}
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const {data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const {data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),scope:noteId==="ss_yr"?"owner":String(a.id)}}
const txt=(v:any,d="")=>typeof v==="string"?v:d;
const ts=(r:any)=>Date.parse(r.occurred_at||r.captured_at||0)||0;
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H()});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),kind=txt(b.kind,"all"),page=Math.max(1,Number(b.page||1)),size=Math.min(100,Math.max(20,Number(b.pageSize||100))),offset=(page-1)*size,need=offset+size,ids=m.scope===m.id?[m.id]:[m.scope,m.id];
  if(kind==="comment"||kind==="reply"){
    let q=db.from("insight_public_comments").select("comment_key,article_key,actor_name,actor_url,actor_image_url,body,occurred_at,is_root",{count:"exact"}).eq("member_id",m.scope).eq("is_creator",false).eq("is_root",kind==="comment").order("occurred_at",{ascending:false}).range(offset,offset+size-1);
    const {data,error,count}=await q;if(error)throw error;const keys=[...new Set((data||[]).map((r:any)=>r.article_key).filter(Boolean))];const {data:arts}=keys.length?await db.from("insight_public_articles").select("article_key,title,url").eq("member_id",m.scope).in("article_key",keys):{data:[] as any[]};const am=new Map((arts||[]).map((a:any)=>[a.article_key,a]));const rows=(data||[]).map((r:any)=>{const a:any=am.get(r.article_key)||{},type=r.is_root?"comment":"reply";return{id:`public-comment:${r.comment_key}`,member_id:m.scope,notification_type:type,raw_text:`${r.actor_name||"noteユーザー"}さんが「${a.title||"記事"}」に${type==="reply"?"返信":"コメント"}しました`,actor_name:r.actor_name,actor_url:r.actor_url,actor_image_url:r.actor_image_url,target_title:a.title||null,target_url:a.url||null,occurred_at:r.occurred_at,captured_at:r.occurred_at,is_read:false,meta:{source:"canonical-public-comments",comment_key:r.comment_key,body:r.body}}});return out({ok:true,page,pageSize:size,total:count||0,rows});
  }
  let nq=db.from("insight_notifications").select("id,member_id,notification_type,raw_text,actor_name,actor_url,target_title,target_url,source_url,occurred_at,captured_at,is_read,meta",{count:"exact"}).in("member_id",ids);if(kind==="all")nq=nq.not("notification_type","in",'(comment,reply)');else nq=nq.eq("notification_type",kind);const {data:notices,error:ne,count:nc}=await nq.order("captured_at",{ascending:false}).limit(Math.min(Math.max(need,100),2000));if(ne)throw ne;
  if(kind!=="all")return out({ok:true,page,pageSize:size,total:nc||0,rows:(notices||[]).slice(offset,offset+size)});
  const {data:comments,error:ce,count:cc}=await db.from("insight_public_comments").select("comment_key,article_key,actor_name,actor_url,actor_image_url,body,occurred_at,is_root",{count:"exact"}).eq("member_id",m.scope).eq("is_creator",false).order("occurred_at",{ascending:false}).limit(Math.min(Math.max(need,100),2000));if(ce)throw ce;const keys=[...new Set((comments||[]).map((r:any)=>r.article_key).filter(Boolean))];const {data:arts}=keys.length?await db.from("insight_public_articles").select("article_key,title,url").eq("member_id",m.scope).in("article_key",keys):{data:[] as any[]};const am=new Map((arts||[]).map((a:any)=>[a.article_key,a]));const cr=(comments||[]).map((r:any)=>{const a:any=am.get(r.article_key)||{},type=r.is_root?"comment":"reply";return{id:`public-comment:${r.comment_key}`,member_id:m.scope,notification_type:type,raw_text:`${r.actor_name||"noteユーザー"}さんが「${a.title||"記事"}」に${type==="reply"?"返信":"コメント"}しました`,actor_name:r.actor_name,actor_url:r.actor_url,actor_image_url:r.actor_image_url,target_title:a.title||null,target_url:a.url||null,occurred_at:r.occurred_at,captured_at:r.occurred_at,is_read:false,meta:{source:"canonical-public-comments",comment_key:r.comment_key,body:r.body}}});const merged=[...(notices||[]),...cr].sort((a:any,b:any)=>ts(b)-ts(a));return out({ok:true,page,pageSize:size,total:Number(nc||0)+Number(cc||0),rows:merged.slice(offset,offset+size)});
}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
