import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ORIGIN="https://mumei-s.github.io",db=createClient(U,K,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const{data:s}=await db.from("insight_member_sessions").select("application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const{data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),scope:noteId==="ss_yr"?"owner":String(a.id),noteId}}
const txt=(v:any,d="")=>typeof v==="string"?v:d;
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function pg(b:any){const page=Math.max(1,num(b.page,1)),pageSize=Math.min(100,Math.max(20,num(b.pageSize,100)));return{page,pageSize,from:(page-1)*pageSize,to:page*pageSize-1}}
function validDate(v:any){if(!v)return null;const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()}
async function runInfo(scope:string,direction:string){const{data,error}=await db.from("insight_relation_sync_runs").select("id,expected_count,received_count,complete,baseline,added_count,removed_count,error,created_at").eq("member_id",scope).eq("direction",direction).order("created_at",{ascending:false}).limit(30);if(error)throw error;const latest=data?.[0]||null,previous=data?.[1]||null;return{latest,previous,timeline:(data||[]).map((r:any,i:number)=>({at:r.created_at,total:num(r.expected_count),named:num(r.received_count),complete:Boolean(r.complete),added:num(r.added_count),removed:num(r.removed_count),delta:data?.[i+1]?num(r.expected_count)-num(data[i+1].expected_count):0,error:r.error||null}))}}
async function current(m:any,b:any){const{page,pageSize,from,to}=pg(b),direction=txt(b.direction,"followers")==="followings"?"followings":"followers",q=txt(b.query).trim();let query=db.from("insight_relations").select("person_key,actor_name,actor_url,actor_image_url,source_rank,first_seen_at,last_seen_at,last_changed_at",{count:"exact"}).eq("member_id",m.scope).eq("direction",direction).eq("active",true);if(q)query=query.or(`actor_name.ilike.%${q}%,actor_url.ilike.%${q}%`);const[{data,error,count},info]=await Promise.all([query.order("source_rank",{ascending:true,nullsFirst:false}).order("last_seen_at",{ascending:false}).range(from,to),runInfo(m.scope,direction)]);if(error)throw error;const l=info.latest,p=info.previous,official=num(l?.expected_count,count||0),complete=Boolean(l?.complete),capped=!complete&&official>1000;return{ok:true,page,pageSize,total:count||0,officialTotal:official,namedCount:num(l?.received_count,count||0),complete,capped,scannedAt:l?.created_at||null,netDelta:l&&p?official-num(p.expected_count):0,message:complete?"全件照合済み。人物単位の増減を確定できます。":capped?"人物一覧はnote側の1000人上限。総数の増減は追跡し、見えない人物の解除は推測しません。":"まだ完全同期がありません。データ更新で同期してください。",rows:data||[],timeline:info.timeline}}
async function changes(m:any,b:any){const{page,pageSize,from,to}=pg(b),direction=txt(b.direction,"followers")==="followings"?"followings":"followers",change=txt(b.change,"all"),dateFrom=validDate(b.dateFrom),dateTo=validDate(b.dateTo);let q=db.from("insight_relation_events").select("id,event_type,person_key,actor_name,actor_url,actor_image_url,detected_at",{count:"exact"}).eq("member_id",m.scope).eq("direction",direction);if(change==="added"||change==="removed")q=q.eq("event_type",change);if(dateFrom)q=q.gte("detected_at",dateFrom);if(dateTo)q=q.lt("detected_at",dateTo);const[{data,error,count},info]=await Promise.all([q.order("detected_at",{ascending:false}).range(from,to),runInfo(m.scope,direction)]);if(error)throw error;const latest=info.latest,official=num(latest?.expected_count),complete=Boolean(latest?.complete),capped=!complete&&official>1000;return{ok:true,page,pageSize,total:count||0,rows:data||[],officialTotal:official,complete,capped,scannedAt:latest?.created_at||null,timeline:info.timeline,message:complete?"人物単位の増減を確定表示しています。":capped?"1000人上限のため、総数推移は正確ですが解除した人物名は判定保留です。":"データ更新後に増減履歴が作成されます。"}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),a=txt(b.action,"current");if(a==="changes")return out(await changes(m,b));return out(await current(m,b))}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
