import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-ingest-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function clean(v:unknown,max=2000){return typeof v==="string"?v.replace(/\u0000/g,"").trim().slice(0,max):null}
function classify(text:string){const t=text.replace(/\s+/g," ").trim();
 if(/(?:あなたのコメント.{0,80}(?:に|へ).{0,20}スキ(?:しました|されました)|コメントにスキしました|コメントをスキしました)/.test(t))return"comment_like";
 if(/(?:あなたの記事にスキしました|「[^」]{0,500}」にスキしました|新しいスキが\d*件?増えました|さん他?\d*名?があなたの記事にスキしました)/.test(t))return"like";
 if(/(?:あなたのコメント.{0,80}(?:に|へ)返信|コメントへの返信|コメントに返信しました|返信がありました)/.test(t))return"reply";
 if(/(?:あなたの記事.{0,80}コメントしました|新しいコメントが\d*件?増えました|コメントがありました)/.test(t))return"comment";
 if(/(?:あなたをフォローしました|フォローされました|新しいフォロワー|さんがあなたをフォロー)/.test(t))return"follow";
 if(/(?:あなたの記事が.{0,120}に追加されました|(?:共同|特典)?マガジン.{0,80}(?:記事|新しい記事).{0,20}追加しました|メンバー特典マガジンに記事)/.test(t))return"magazine";
 if(/(?:あなたの記事.{0,20}話題です|あなたの記事.{0,20}話題になりました|が話題です！?)/.test(t))return"buzz";
 if(/(?:あなたのメンバーシップ.{0,50}参加しました|あなたのメンバーシップ.{0,50}メンバーになりました|メンバーシップに参加しました)/.test(t))return"membership";
 if(/(?:あなたの記事が購入されました|あなたの有料記事が購入されました|購入がありました|さんがあなたの記事を購入しました)/.test(t))return"purchase";
 if(/(?:チップを送りました|チップを贈りました|チップを受け取りました|チップが届|サポートされました|サポートを受けました)/.test(t))return"tip";
 if(/(?:あなたの記事.{0,40}引用され|あなたの記事.{0,40}紹介され)/.test(t))return"quote";
 if(/あなたの記事を高評価しました/.test(t))return"rating";
 if(/あなたにポイント|ポイントが付与|ポイントを獲得/.test(t))return"points";
 return"other"}
async function identity(req:Request){const raw=req.headers.get("X-Ingest-Token")||"";if(!raw)throw new Error("INGEST_TOKEN_REQUIRED");const now=new Date().toISOString();const {data,error}=await db.from("insight_notification_ingest_tokens").select("member_id,expires_at").eq("token_hash",await sha(raw)).is("revoked_at",null).gt("expires_at",now).maybeSingle();if(error||!data?.member_id)throw new Error("INGEST_TOKEN_INVALID");const memberId=String(data.member_id);if(memberId==="owner")return{memberId,noteId:"ss_yr"};const {data:app}=await db.from("insight_access_applications").select("note_id,status,verified_at").eq("id",memberId).maybeSingle();if(app?.note_id&&app.status==="active"&&app.verified_at)return{memberId,noteId:String(app.note_id).toLowerCase()};const {data:profile}=await db.from("insight_notification_profiles").select("note_urlname").eq("member_id",memberId).maybeSingle();const noteId=String(profile?.note_urlname||"").toLowerCase();if(!noteId)throw new Error("INGEST_ACCOUNT_UNKNOWN");return{memberId,noteId}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);try{const who=await identity(req),body=await req.json().catch(()=>({})),suppliedNoteId=String(body?.noteId||"").trim().replace(/^@/,"").toLowerCase();if(!suppliedNoteId||suppliedNoteId!==who.noteId)return out({ok:false,error:"NOTIFICATION_ACCOUNT_MISMATCH",expectedNoteId:who.noteId},409);const incoming=Array.isArray(body?.notifications)?body.notifications.slice(0,1000):[];let inserted=0;for(const item of incoming){const raw=clean(item?.raw_text??item?.text,3000);if(!raw||raw.length<2)continue;const sourceUrl=clean(item?.source_url,1200),occurred=clean(item?.occurred_at,80),fingerprint=clean(item?.fingerprint,128)||await sha(`${raw}|${sourceUrl||""}|${occurred||""}`);const type=classify(raw);const {error}=await db.from("insight_notifications").insert({member_id:who.memberId,fingerprint,notification_type:type,raw_text:raw,actor_name:clean(item?.actor_name,200),actor_url:clean(item?.actor_url,1200),target_title:clean(item?.target_title,500),target_url:clean(item?.target_url,1200),source_url:sourceUrl,occurred_at:occurred&&!Number.isNaN(Date.parse(occurred))?new Date(occurred).toISOString():null,meta:{...(item?.meta&&typeof item.meta==="object"?item.meta:{}),synced_note_id:who.noteId,classifier:"action-v4"}});if(!error)inserted++;else if(error.code!=="23505")throw error}await db.from("insight_notification_sync_runs").insert({member_id:who.memberId,inserted_count:inserted,received_count:incoming.length,source:"browser-account-verified"});return out({ok:true,noteId:who.noteId,received:incoming.length,inserted})}catch(e){const message=e instanceof Error?e.message:"INGEST_ERROR";return out({ok:false,error:message},/REQUIRED|INVALID|UNKNOWN/.test(message)?401:500)}});
