import { createClient } from "npm:@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const ORIGIN="https://mumei-s.github.io";
function H(req:Request){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function out(req:Request,x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H(req)})}
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const {data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const {data:a}=await db.from("insight_access_applications").select("id,note_id,display_name,image_url,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");await db.from("insight_member_sessions").update({last_seen_at:new Date().toISOString()}).eq("id",s.id);const noteId=String(a.note_id).toLowerCase();return{id:String(a.id),noteId,displayName:String(a.display_name||noteId),imageUrl:a.image_url||null,scope:noteId==="ss_yr"?"owner":String(a.id)}}
function pg(b:any,def=100,max=100){const page=Math.max(1,Number(b?.page||1)),size=Math.min(max,Math.max(20,Number(b?.pageSize||def)));return{page,size,offset:(page-1)*size}}
const txt=(v:any,d="")=>typeof v==="string"?v:d;
async function summary(m:any){const [{data:fast,error:fe},{data:analysis,error:ae},{count:comments},{count:followers},{count:followings},{count:notifications},{data:arts}]=await Promise.all([
 db.rpc("insight_fast_summary",{p_member:m.scope}),
 db.rpc("insight_fast_analysis_v2",{p_member:m.scope}),
 db.from("insight_public_comments").select("comment_key",{count:"exact",head:true}).eq("member_id",m.scope),
 db.from("insight_relations").select("person_key",{count:"exact",head:true}).eq("member_id",m.scope).eq("direction","followers").eq("active",true),
 db.from("insight_relations").select("person_key",{count:"exact",head:true}).eq("member_id",m.scope).eq("direction","followings").eq("active",true),
 db.from("insight_notifications").select("id",{count:"exact",head:true}).in("member_id",m.scope===m.id?[m.id]:[m.scope,m.id]),
 db.from("insight_public_articles").select("article_key,title,url,publish_at,like_count,comment_count,last_seen_at").eq("member_id",m.scope).order("publish_at",{ascending:false}).limit(300)
 ]);if(fe)throw fe;if(ae)throw ae;return{ok:true,member:m,summary:fast||{},analysis:analysis||{},counts:{comments:comments||0,followers:followers||0,followings:followings||0,notifications:notifications||0},articles:arts||[]}}
async function likes(m:any,b:any){const {page,size,offset}=pg(b);const q=txt(b.query),sort=txt(b.sort,"newest"),status=txt(b.status,"all"),from=b.dateFrom||null,to=b.dateTo||null;const [{data,error},{data:count,error:ce}]=await Promise.all([db.rpc("insight_fast_like_page_scoped_status",{p_member:m.scope,p_offset:offset,p_limit:size,p_query:q,p_sort:sort,p_from:from,p_to:to,p_status:status}),db.rpc("insight_fast_like_count_scoped_status",{p_member:m.scope,p_query:q,p_from:from,p_to:to,p_status:status})]);if(error)throw error;if(ce)throw ce;return{ok:true,page,pageSize:size,total:Number(count||0),rows:data||[]}}
async function supporters(m:any,b:any){const {page,size,offset}=pg(b);const q=txt(b.query);const [{data,error},{data:count,error:ce}]=await Promise.all([db.rpc("insight_fast_ranking",{p_member:m.scope,p_offset:offset,p_limit:size,p_query:q}),db.rpc("insight_fast_ranking_count",{p_member:m.scope,p_query:q})]);if(error)throw error;if(ce)throw ce;return{ok:true,page,pageSize:size,total:Number(count||0),rows:data||[]}}
async function comments(m:any,b:any){const {page,size,offset}=pg(b);const q=txt(b.query),status=txt(b.status,"all");const [{data,error},{data:count,error:ce}]=await Promise.all([db.rpc("insight_fast_comment_threads",{p_member:m.scope,p_offset:offset,p_limit:size,p_query:q,p_status:status}),db.rpc("insight_fast_comment_thread_count",{p_member:m.scope,p_query:q,p_status:status})]);if(error)throw error;if(ce)throw ce;return{ok:true,page,pageSize:size,total:Number(count||0),rows:data||[]}}
async function commentThread(m:any,b:any){const key=txt(b.rootKey);if(!key)throw new Error("ROOT_KEY_REQUIRED");const {data:root,error}=await db.from("insight_public_comments").select("article_key,comment_key,parent_key,actor_key,actor_name,actor_url,actor_image_url,body,occurred_at,is_root,is_creator,is_creator_liked,like_count").eq("member_id",m.scope).eq("comment_key",key).maybeSingle();if(error)throw error;if(!root)throw new Error("COMMENT_THREAD_NOT_FOUND");const [{data:replies,error:re},{data:art}]=await Promise.all([db.from("insight_public_comments").select("article_key,comment_key,parent_key,actor_key,actor_name,actor_url,actor_image_url,body,occurred_at,is_root,is_creator,is_creator_liked,like_count").eq("member_id",m.scope).eq("parent_key",key).order("occurred_at",{ascending:true}),db.from("insight_public_articles").select("title,url").eq("member_id",m.scope).eq("article_key",root.article_key).maybeSingle()]);if(re)throw re;return{ok:true,articleTitle:art?.title||"記事",articleUrl:art?.url||null,rows:[root,...(replies||[])]}}
async function social(m:any,b:any){const {page,size,offset}=pg(b);const direction=txt(b.direction,"followers"),q=txt(b.query).trim();if(m.scope!==m.id){let query=db.from("insight_relations").select("person_key,actor_name,actor_url,actor_image_url,source_rank,last_seen_at",{count:"exact"}).eq("member_id",m.scope).eq("direction",direction).eq("active",true);if(q)query=query.or(`actor_name.ilike.%${q}%,actor_url.ilike.%${q}%`);const {data,error,count}=await query.order("source_rank",{ascending:true,nullsFirst:false}).range(offset,offset+size-1);if(error)throw error;return{ok:true,page,pageSize:size,total:count||0,rows:data||[]}}if(direction!=="followers")return{ok:true,page,pageSize:size,total:0,rows:[]};let query=db.from("insight_public_followers").select("person_key,actor_name,actor_url,last_seen_at",{count:"exact"}).eq("member_id",m.id);if(q)query=query.or(`actor_name.ilike.%${q}%,actor_url.ilike.%${q}%`);const {data,error,count}=await query.order("last_seen_at",{ascending:false}).range(offset,offset+size-1);if(error)throw error;return{ok:true,page,pageSize:size,total:count||0,rows:data||[]}}
async function changes(m:any,b:any){const {page,size,offset}=pg(b);if(m.scope===m.id)return{ok:true,page,pageSize:size,total:0,rows:[]};const direction=txt(b.direction,"followers"),kind=txt(b.change,"all");let q=db.from("insight_relation_events").select("id,event_type,person_key,actor_name,actor_url,actor_image_url,detected_at",{count:"exact"}).eq("member_id",m.scope).eq("direction",direction);if(kind!=="all")q=q.eq("event_type",kind);const {data,error,count}=await q.order("detected_at",{ascending:false}).range(offset,offset+size-1);if(error)throw error;return{ok:true,page,pageSize:size,total:count||0,rows:data||[]}}
async function notifications(m:any,b:any){const {page,size,offset}=pg(b);const ids=m.scope===m.id?[m.id]:[m.scope,m.id],kind=txt(b.kind,"all");let q=db.from("insight_notifications").select("id,member_id,notification_type,raw_text,actor_name,actor_url,target_title,target_url,occurred_at,captured_at,is_read,meta",{count:"exact"}).in("member_id",ids);if(kind!=="all")q=q.eq("notification_type",kind);const {data,error,count}=await q.order("captured_at",{ascending:false}).range(offset,offset+size-1);if(error)throw error;return{ok:true,page,pageSize:size,total:count||0,rows:data||[]}}
async function articlesPage(m:any){const {data,error}=await db.from("insight_public_articles").select("article_key,title,url,publish_at,like_count,comment_count,last_seen_at").eq("member_id",m.scope).order("publish_at",{ascending:false}).limit(1000);if(error)throw error;return{ok:true,total:(data||[]).length,rows:data||[]}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H(req)});try{if(req.method!=="POST")return out(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),a=txt(b.action,"summary");if(a==="summary")return out(req,await summary(m));if(a==="likes")return out(req,await likes(m,b));if(a==="supporters")return out(req,await supporters(m,b));if(a==="comments")return out(req,await comments(m,b));if(a==="comment_thread")return out(req,await commentThread(m,b));if(a==="social")return out(req,await social(m,b));if(a==="changes")return out(req,await changes(m,b));if(a==="notifications")return out(req,await notifications(m,b));if(a==="articles")return out(req,await articlesPage(m));return out(req,{ok:false,error:"UNKNOWN_ACTION"},400)}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out(req,{ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
