import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const ORIGIN="https://mumei-s.github.io";
const H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const txt=(v:any,d="")=>typeof v==="string"?v:d;
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const{data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const{data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),noteId,scope:noteId==="ss_yr"?"owner":String(a.id)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),page=Math.max(1,num(b.page,1)),pageSize=Math.min(500,Math.max(50,num(b.pageSize,500))),offset=(page-1)*pageSize,articleKey=txt(b.articleKey),from=b.dateFrom||null,to=b.dateTo||null;let q=db.from("insight_public_comments").select("article_key,comment_key,parent_key,actor_key,actor_name,actor_url,actor_image_url,body,occurred_at,is_root,is_creator,is_creator_liked,like_count",{count:"exact"}).eq("member_id",m.scope);if(articleKey)q=q.eq("article_key",articleKey);if(from)q=q.gte("occurred_at",from);if(to)q=q.lt("occurred_at",to);const{data,error,count}=await q.order("occurred_at",{ascending:false}).range(offset,offset+pageSize-1);if(error)throw error;const keys=[...new Set((data||[]).map((r:any)=>String(r.article_key||"")).filter(Boolean))];const{data:arts,error:ae}=keys.length?await db.from("insight_public_articles").select("article_key,title,url").eq("member_id",m.scope).in("article_key",keys):{data:[] as any[],error:null as any};if(ae)throw ae;const amap=new Map((arts||[]).map((a:any)=>[String(a.article_key),a]));const rows=(data||[]).map((r:any)=>{const a:any=amap.get(String(r.article_key))||{};return{...r,article_title:a.title||"記事",article_url:a.url||null}});return out({ok:true,page,pageSize,total:Number(count||0),rows,noteId:m.noteId})}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});