import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,NOTE="https://note.com";
const db=createClient(U,K,{auth:{persistSession:false}}),H={"Access-Control-Allow-Origin":"https://mumei-s.github.io","Access-Control-Allow-Headers":"content-type,x-cron-secret","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const obj=(v:any)=>v&&typeof v==="object"&&!Array.isArray(v)?v:{},arr=(v:any)=>Array.isArray(v)?v:[],txt=(v:any,d="")=>typeof v==="string"?v:d,num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
async function authorized(req:Request){const supplied=req.headers.get("X-Cron-Secret")||"";const{data,error}=await db.from("insight_notification_cron_secret").select("secret").eq("singleton",true).maybeSingle();if(error)throw error;return Boolean(supplied&&data?.secret&&supplied===data.secret)}
async function noteJson(path:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(NOTE+path,{headers:{Accept:"application/json","User-Agent":"Mumei-S-note-INSIGHT-like-backfill/1.4"},cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(`NOTE_${r.status}`);return obj(await r.json())}finally{clearTimeout(timer)}}
function pageRows(p:any){const data=p?.data,box=Array.isArray(data)?{}:obj(data),rows=Array.isArray(data)?data:arr(box.likes??box.users??box.contents),next=p?.next_page??p?.nextPage??box.next_page??box.nextPage,lastFlag=box.isLastPage??box.is_last_page??p?.isLastPage??p?.is_last_page,extra=obj(box.extra_fields??p?.extra_fields),total=num(p?.total_count??p?.totalCount??box.total_count??box.totalCount??extra.like_count,0);return{rows,last:lastFlag===true||rows.length===0||(next===null||next===false||next==="")&&lastFlag!==false,total}}
function addRows(found:Map<string,any>,rows:any[]){for(const raw of rows){const r=obj(raw),u=obj(r.user??r),urlname=txt(u.urlname),personKey=txt(u.key)||(u.id!=null?String(u.id):urlname);if(!personKey)continue;found.set(personKey,{key:personKey,name:txt(u.nickname??u.name,"noteユーザー"),url:urlname?`${NOTE}/${urlname}`:null,image:txt(u.user_profile_image_url??u.profileImageUrl??u.profile_image_url)||null,at:txt(r.created_at??r.createdAt)||null})}}
async function numericNoteId(key:string){for(const path of [`/api/v3/notes/${encodeURIComponent(key)}`,`/api/v1/notes/${encodeURIComponent(key)}`]){try{const p=await noteJson(path),d=obj(p.data),note=obj(d.note),id=num(d.id??d.note_id??note.id,0);if(id>0)return id}catch{}}return 0}
async function allLikes(key:string){const found=new Map<string,any>();let expected=0;for(let page=1;page<=100;page++){const p=await noteJson(`/api/v3/notes/${encodeURIComponent(key)}/likes?page=${page}&per_page=100`),q=pageRows(p),before=found.size;expected=Math.max(expected,q.total);addRows(found,q.rows);if((expected&&found.size>=expected)||q.last||found.size===before)break;await sleep(35)}if(expected&&found.size<expected){for(let start=found.size;start<expected&&start<5000;start+=100){const p=await noteJson(`/api/v3/notes/${encodeURIComponent(key)}/likes?size=100&start=${start}`),q=pageRows(p),before=found.size;expected=Math.max(expected,q.total);addRows(found,q.rows);if(found.size===before||found.size>=expected)break;await sleep(35)}}if(expected&&found.size<expected){const id=await numericNoteId(key);if(id>0){for(let page=1;page<=100;page++){try{const p=await noteJson(`/api/v1/note/${id}/likes?page=${page}`),q=pageRows(p),before=found.size;expected=Math.max(expected,q.total);addRows(found,q.rows);if((expected&&found.size>=expected)||q.last||found.size===before)break}catch{break}await sleep(35)}}}return[...found.values()]}
function articlePage(p:any,noteId:string){const d=obj(p.data),raw=arr(d.contents??d.notes),rows=raw.map((x:any)=>{const v=obj(obj(x).note??x),key=txt(v.key);return key?{article_key:key,title:txt(v.name??v.title,"無題の記事"),url:txt(v.noteUrl??v.url,`${NOTE}/${noteId}/n/${key}`),publish_at:txt(v.publishAt??v.publish_at)||null,like_count:num(v.likeCount??v.like_count),comment_count:num(v.commentCount??v.comment_count)}:null}).filter(Boolean) as any[];return{rows,last:Boolean(d.isLastPage??d.is_last_page)||rows.length===0}}
async function discoverCatalog(memberId:string,noteId:string){const found=new Map<string,any>();let pages=0;for(let page=1;page<=200;page++){const p=await noteJson(`/api/v2/creators/${encodeURIComponent(noteId)}/contents?kind=note&page=${page}&disabled_pinned=true&with_notes=false`),q=articlePage(p,noteId);pages=page;for(const row of q.rows)found.set(row.article_key,row);if(q.last)break;await sleep(25)}const now=new Date().toISOString(),rows=[...found.values()].map(x=>({member_id:memberId,...x,publish_at:x.publish_at&&!Number.isNaN(Date.parse(x.publish_at))?new Date(x.publish_at).toISOString():null,last_seen_at:now}));for(let i=0;i<rows.length;i+=400){const{error}=await db.from("insight_public_articles").upsert(rows.slice(i,i+400),{onConflict:"member_id,article_key"});if(error)throw error}return{pages,articles:rows.length}}
async function missingArticles(memberId:string){const{data:arts,error}=await db.from("insight_public_articles").select("article_key,like_count,last_seen_at").eq("member_id",memberId).gt("like_count",0).order("last_seen_at",{ascending:false}).limit(1000);if(error)throw error;const rows:any[]=[];for(const a of arts||[]){const{count,error:e}=await db.from("insight_public_likes").select("liker_key",{count:"exact",head:true}).eq("member_id",memberId).eq("article_key",a.article_key);if(e)throw e;const stored=Number(count||0),expected=Number(a.like_count||0);if(stored<expected)rows.push({...a,stored,missing:expected-stored})}return rows.sort((x,y)=>y.missing-x.missing).slice(0,20)}
async function backfillMember(memberId:string,noteId:string){const catalog=await discoverCatalog(memberId,noteId),missing=await missingArticles(memberId),result:any[]=[];for(const art of missing){try{const likes=await allLikes(String(art.article_key));for(let i=0;i<likes.length;i+=400){const rows=likes.slice(i,i+400).map(x=>({member_id:memberId,article_key:art.article_key,liker_key:x.key,actor_name:x.name,actor_url:x.url,actor_image_url:x.image,liked_at:x.at&&!Number.isNaN(Date.parse(x.at))?new Date(x.at).toISOString():null}));if(rows.length){const{error}=await db.from("insight_public_likes").upsert(rows,{onConflict:"member_id,article_key,liker_key"});if(error)throw error}}result.push({articleKey:art.article_key,expected:Number(art.like_count||0),before:art.stored,after:likes.length})}catch(e){result.push({articleKey:art.article_key,ok:false,error:e instanceof Error?e.message:String(e)})}await sleep(80)}return{memberId,noteId,catalog,articles:result.length,result}}
async function run(req:Request){if(!(await authorized(req)))throw new Error("CRON_SECRET_INVALID");const body=await req.json().catch(()=>({})),target=txt(body?.memberId).trim();let q=db.from("insight_notification_profiles").select("member_id,note_urlname").eq("public_watch_enabled",true).not("verified_at","is",null);if(target)q=q.eq("member_id",target);const{data:profiles,error}=await q.limit(100);if(error)throw error;const results:any[]=[];for(const p of profiles||[]){const memberId=String(p.member_id),noteId=txt(p.note_urlname);if(!noteId)continue;results.push(await backfillMember(memberId,noteId));await sleep(120)}return{ok:true,members:results.length,results}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);return out(await run(req))}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/CRON_SECRET/.test(msg)?401:500)}});