import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ORIGIN="https://mumei-s.github.io";
const db=createClient(U,K,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const clean=(v:any)=>String(v||"").replace(/\s+/g," ").trim().slice(0,40);
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const{data:s}=await db.from("insight_member_sessions").select("application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const{data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{scope:noteId==="ss_yr"?"owner":String(a.id),noteId}}
async function list(scope:string){const[{data:defs,error:de},{data:favs,error:fe}]=await Promise.all([db.from("insight_favorite_groups").select("name,created_at,updated_at").eq("member_id",scope).order("created_at",{ascending:true}),db.from("insight_favorite_creators").select("creator_key,group_name").eq("member_id",scope).order("created_at",{ascending:false})]);if(de)throw de;if(fe)throw fe;return{ok:true,definitions:(defs||[]).map((x:any)=>({name:clean(x.name),createdAt:x.created_at,updatedAt:x.updated_at})).filter((x:any)=>x.name),assignments:(favs||[]).map((x:any)=>({creatorKey:String(x.creator_key),groupName:clean(x.group_name)||null}))}}
async function create(scope:string,b:any){const name=clean(b?.name??b?.groupName);if(!name)throw new Error("GROUP_NAME_REQUIRED");const now=new Date().toISOString();const{data,error}=await db.from("insight_favorite_groups").upsert({member_id:scope,name,updated_at:now},{onConflict:"member_id,name"}).select("name,created_at,updated_at").single();if(error)throw error;return{ok:true,name:clean(data.name),createdAt:data.created_at,updatedAt:data.updated_at}}
async function assign(scope:string,b:any){const creatorKey=String(b?.creatorKey||"");if(!creatorKey)throw new Error("CREATOR_KEY_REQUIRED");const groupName=clean(b?.groupName)||null;if(groupName)await create(scope,{name:groupName});const{data,error}=await db.from("insight_favorite_creators").update({group_name:groupName}).eq("member_id",scope).eq("creator_key",creatorKey).select("creator_key,group_name").maybeSingle();if(error)throw error;if(!data)throw new Error("FAVORITE_NOT_FOUND");return{ok:true,creatorKey:String(data.creator_key),groupName:clean(data.group_name)||null}}
async function rename(scope:string,b:any){const from=clean(b?.from),to=clean(b?.to);if(!from||!to)throw new Error("GROUP_NAME_REQUIRED");if(from===to)return{ok:true,from,to};await create(scope,{name:to});const{error:fe}=await db.from("insight_favorite_creators").update({group_name:to}).eq("member_id",scope).eq("group_name",from);if(fe)throw fe;const{error:de}=await db.from("insight_favorite_groups").delete().eq("member_id",scope).eq("name",from);if(de)throw de;return{ok:true,from,to}}
async function remove(scope:string,b:any){const name=clean(b?.name??b?.groupName);if(!name)throw new Error("GROUP_NAME_REQUIRED");const{error:fe}=await db.from("insight_favorite_creators").update({group_name:null}).eq("member_id",scope).eq("group_name",name);if(fe)throw fe;const{error}=await db.from("insight_favorite_groups").delete().eq("member_id",scope).eq("name",name);if(error)throw error;return{ok:true,name}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);try{const m=await auth(req),b=await req.json().catch(()=>({})),a=String(b?.action||"list");if(a==="list")return out(await list(m.scope));if(a==="create")return out(await create(m.scope,b));if(a==="assign")return out(await assign(m.scope,b));if(a==="rename")return out(await rename(m.scope,b));if(a==="delete")return out(await remove(m.scope,b));return out({ok:false,error:"UNKNOWN_ACTION"},400)}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
