import { useEffect, useState } from "react";
import { CommandBattle } from "./game-command";
import { MatchBattle } from "./game-match-view";
import { TapRushBattle } from "./game-tap";
import { TargetRushBattle } from "./game-target-view";
import { loadCreatorGame } from "./game-data-client";
import type { CreatorGameData, GameMode } from "./game-types";

const games=[
 ["choice","COMMAND","読み合い・属性攻防・ラウンド制"],
 ["tap","TAP RUSH","10秒反射神経・コンボ・FEVER"],
 ["puzzle","ARCANE PUZZLE","実盤面マッチ・連鎖・スキルゲージ"],
 ["shoot","STAR SHOOTER","リアルタイム照準・ターゲット射撃"],
] as const;
function Art({src,label}:{src?:string|null;label:string}){return src?<img src={src} alt=""/>:<span className="premium-art-fallback">{label}</span>}
function Hp({enemy=false}:{enemy?:boolean}){return <span className={`premium-hp ${enemy?"enemy":""}`}><i/></span>}
function CommandConcept({playerArt,enemyArt}:{playerArt?:string|null;enemyArt?:string|null}){return <div className="premium-screen command-premium"><div className="premium-topline"><span>ROUND 03 / 10</span><b>COMMAND</b><span>ENERGY ◆◆◆◆◆◇</span></div><div className="command-stage"><section className="command-side enemy"><div className="hud-name"><small>OPPONENT</small><strong>ENEMY</strong><Hp enemy/></div><div className="premium-card tilt-enemy"><Art src={enemyArt} label="ENEMY CARD"/><span className="card-glass"/></div></section><div className="battle-center"><i className="battle-ray"/><strong>SKILL<br/>ACTIVATED</strong><b>VS</b><em>CRITICAL!</em></div><section className="command-side you"><div className="premium-card tilt-you"><Art src={playerArt} label="YOUR CARD"/><span className="card-glass"/></div><div className="hud-name"><small>YOU</small><strong>CREATOR</strong><Hp/></div></section></div><div className="command-dock"><button><b>⚔</b><span>ATTACK</span><small>属性攻撃</small></button><button><b>⬡</b><span>DEFEND</span><small>軽減・反撃</small></button><button><b>✦</b><span>SKILL</span><small>必殺技</small></button></div></div>}
function TapConcept({art}:{art?:string|null}){return <div className="premium-screen tap-premium"><div className="premium-topline"><span>TIME 06.42</span><b>TAP RUSH</b><span>SCORE 28,640</span></div><div className="tap-battlefield"><div className="tap-card-bg"><Art src={art} label="BATTLE CARD"/><span/></div><div className="combo-readout"><small>COMBO</small><strong>×48</strong><em>FEVER!</em></div><div className="tap-core-premium"><i/><i/><i/><b>TAP!</b><span>PERFECT</span></div><div className="tap-impact i1"/><div className="tap-impact i2"/><div className="tap-impact i3"/></div><div className="fever-meter"><span>FEVER GAUGE</span><i><b/></i><strong>86%</strong></div></div>}
function PuzzleConcept({playerArt,enemyArt}:{playerArt?:string|null;enemyArt?:string|null}){const gems=[0,1,2,3,4,1,3,0,2,4,2,2,4,1,0,3,4,1,3,0,1,0,2,4,3,4,3,1,0,2];return <div className="premium-screen puzzle-premium"><div className="premium-topline"><span>CHAIN 12</span><b>ARCANE PUZZLE</b><span>SKILL 92%</span></div><div className="puzzle-duel"><div className="puzzle-fighter"><div className="premium-card mini"><Art src={playerArt} label="YOU"/></div><Hp/></div><div className="puzzle-burst"><small>12 CHAIN</small><strong>ARCANE<br/>BURST</strong><em>4,820</em></div><div className="puzzle-fighter"><div className="premium-card mini enemy"><Art src={enemyArt} label="ENEMY"/></div><Hp enemy/></div></div><div className="premium-board">{gems.map((g,i)=><i key={i} className={`gem gem-${g}`}><span/></i>)}</div><div className="skill-gauge"><span>ULTIMATE</span><i><b/></i><strong>READY</strong></div></div>}
function ShootConcept({art}:{art?:string|null}){return <div className="premium-screen shoot-premium"><div className="premium-topline"><span>SCORE 124,800</span><b>STAR SHOOTER</b><span>COMBO ×19</span></div><div className="shoot-arena"><div className="boss-card"><Art src={art} label="BOSS CARD"/><span/></div><div className="boss-hud"><small>BOSS</small><strong>PHASE 2</strong><Hp enemy/></div><i className="shoot-target t1"/><i className="shoot-target t2"/><i className="shoot-target t3"/><div className="premium-crosshair"><span/><span/><b/></div><strong className="shoot-critical">CRITICAL<br/><em>9,640</em></strong><div className="shot-trail st1"/><div className="shot-trail st2"/></div><div className="shoot-footer"><span>BOOST ◆◆◆◇</span><strong>LOCK ON</strong><span>ULTIMATE 74%</span></div></div>}
function GameConcept({mode,title,desc,playerArt,enemyArt,onPlay,canPlay}:{mode:GameMode;title:string;desc:string;playerArt?:string|null;enemyArt?:string|null;onPlay:()=>void;canPlay:boolean}){return <article className={`game-concept premium-concept concept-${mode}`}><header className="concept-caption"><small>FINAL QUALITY CONCEPT</small><strong>{title}</strong><span>{desc}</span></header>{mode==="choice"?<CommandConcept playerArt={playerArt} enemyArt={enemyArt}/>:mode==="tap"?<TapConcept art={playerArt||enemyArt}/>:mode==="puzzle"?<PuzzleConcept playerArt={playerArt} enemyArt={enemyArt}/>:<ShootConcept art={enemyArt||playerArt}/>}<button className="concept-enter" disabled={!canPlay} onClick={onPlay}>{canPlay?"現在の試作を開く →":"名鑑カード登録後に参加"}</button></article>}
export function BattleArenaPage(){const[data,setData]=useState<CreatorGameData>({opponents:[],creators:[]});const[mode,setMode]=useState<GameMode|null>(null),[enemy,setEnemy]=useState(0);useEffect(()=>{void loadCreatorGame().then(x=>setData(x.data))},[]);const foe=data.opponents[enemy],player=data.creators[0],playerArt=player?.images?.[0]?.url??null,canPlay=Boolean(playerArt&&foe);return <div className="creator-world"><link rel="stylesheet" href={`${import.meta.env.BASE_URL}creator-world.css`}/><link rel="stylesheet" href={`${import.meta.env.BASE_URL}creator-world-premium.css`}/><link rel="stylesheet" href={`${import.meta.env.BASE_URL}creator-world-concept-v2.css`}/><main><header className="world-hero"><small>BATTLE ARENA</small><h1>CREATOR <span>WORLD</span></h1><p>名鑑で本人登録したカードだけを使う、高品質スマホゲーム型バトル。4モードは操作も演出も別ゲームです。</p></header><section><div className="world-heading"><div><small>SELECT ENEMY</small><h2>対戦カード</h2></div></div><div className="enemy-strip">{data.opponents.map((x,i)=><button key={x.id} className={enemy===i?"active":""} onClick={()=>setEnemy(i)}>{x.image_url?<img src={x.image_url} alt=""/>:<span/>}<b>{x.name}</b><small>{x.rarity}</small></button>)}</div></section>{!mode?<section className="mode-select"><div className="world-heading"><div><small>FINAL GAME CONCEPT</small><h2>完成時のゲーム画面イメージ</h2><p>BATTLE START → VS → ROUND / COMBO → SKILL → CRITICAL / COUNTER → WIN / LOSE → EXPまでを、この品質で演出する想定です。</p></div></div><div className="concept-grid premium-grid">{games.map(g=><GameConcept key={g[0]} mode={g[0]} title={g[1]} desc={g[2]} playerArt={playerArt} enemyArt={foe?.image_url} onPlay={()=>setMode(g[0])} canPlay={canPlay}/>)}</div></section>:null}{mode&&foe&&playerArt?<section className="active-game"><button className="mode-back" onClick={()=>setMode(null)}>← 完成イメージへ戻る</button><div className="versus-stage"><article className="fighter-card"><img src={playerArt} alt=""/><footer>{player?.display_name||player?.note_id||"CREATOR"}</footer></article><b className="vs-mark">VS</b><article className="fighter-card">{foe.image_url?<img src={foe.image_url} alt=""/>:<div>ENEMY</div>}<footer>{foe.name}</footer></article></div><div className="game-console" key={`${mode}-${foe.id}`}>{mode==="choice"?<CommandBattle/>:mode==="tap"?<TapRushBattle/>:mode==="puzzle"?<MatchBattle/>:<TargetRushBattle/>}</div></section>:null}</main></div>}
