import { useEffect, useMemo, useState } from "react";

type Evidence={id:string;original_name:string|null;mime_type:string|null;captured_at:string|null;created_at:string;url:string|null};
function localDateTime(){const n=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return n.toISOString().slice(0,16)}
function fmt(v:string|null){if(!v)return"日時不明";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(d)}

export function EvidencePage(){
 const[rows,setRows]=useState<Evidence[]>([]),[file,setFile]=useState<File|null>(null),[capturedAt,setCapturedAt]=useState(localDateTime),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const preview=useMemo(()=>file?.type.startsWith("image/")?URL.createObjectURL(file):"",[file]);
 async function load(){const r=await fetch("/owner/evidence-upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"list"})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error??"保存資料を読み込めませんでした。");setRows(p.rows??[])}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"読み込めませんでした。"))},[]);
 async function save(){if(!file||busy)return;setBusy(true);setMessage("");try{const f=new FormData();f.set("file",file);f.set("captured_at",new Date(capturedAt).toISOString());const r=await fetch("/owner/evidence-upload",{method:"POST",body:f});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error??"保存できませんでした。");setRows(p.rows??[]);setFile(null);setMessage("保存しました。下の資料庫からいつでも開けます。")}catch(e){setMessage(e instanceof Error?e.message:"保存できませんでした。")}finally{setBusy(false)}}
 async function remove(id:string){if(busy)return;setBusy(true);setMessage("");try{const r=await fetch("/owner/evidence-upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error??"削除できませんでした。");setRows(p.rows??[])}catch(e){setMessage(e instanceof Error?e.message:"削除できませんでした。")}finally{setBusy(false)}}
 return <div className="evidence-page"><style>{`
 .evidence-page{min-height:100vh;background:#070a0f;color:#f5f8fc;padding:22px 14px 80px;font-family:system-ui,sans-serif}.e-wrap{width:min(1050px,100%);margin:auto}.e-back{color:#54d8ff;font-weight:900;text-decoration:none}.e-head{padding:46px 0 22px}.e-head small{color:#54d8ff;font-weight:900;letter-spacing:.14em}.e-head h1{font-size:clamp(38px,7vw,64px);margin:8px 0}.e-head p,.e-muted{color:#9ca9bb;line-height:1.75}.e-panel{border:1px solid #28394d;border-radius:20px;background:#0e151f;padding:20px}.e-upload{display:grid;grid-template-columns:1.3fr .8fr auto;gap:12px;align-items:end}.e-upload label{display:grid;gap:7px;font-weight:850}.e-upload input{min-height:46px;border:1px solid #34465c;border-radius:11px;background:#070b11;color:#fff;padding:8px}.e-save{min-height:46px;border:0;border-radius:11px;background:#54d8ff;color:#071016;font-weight:950;padding:0 17px}.e-preview{max-width:100%;max-height:320px;object-fit:contain;margin-top:15px;border-radius:14px;background:#05080c}.e-title{display:flex;justify-content:space-between;align-items:end;gap:12px;margin:38px 0 14px}.e-title h2{margin:0;font-size:30px}.e-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:14px}.e-card{border:1px solid #2b3749;border-radius:17px;background:#0d141d;overflow:hidden}.e-thumb{display:grid;place-items:center;aspect-ratio:4/3;background:#05080c;color:#54d8ff;text-decoration:none;font-weight:950}.e-thumb img{width:100%;height:100%;object-fit:cover}.e-copy{padding:12px}.e-copy strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.e-copy small{display:block;color:#8493a8;margin-top:5px}.e-actions{display:flex;gap:7px;margin-top:10px}.e-actions a,.e-actions button{flex:1;border-radius:9px;padding:8px;border:1px solid #34465c;background:#131d29;color:#fff;text-align:center;text-decoration:none}.e-actions button{color:#ffadb5;border-color:#68404a}.e-message{color:#ffd76b;font-weight:850;margin-top:12px}@media(max-width:700px){.e-upload{grid-template-columns:1fr}.e-save{width:100%}}
 `}</style><main className="e-wrap"><a className="e-back" href="#dashboard">← INSIGHTへ戻る</a><header className="e-head"><small>INSIGHT EVIDENCE LIBRARY</small><h1>ダッシュボード資料庫</h1><p>noteダッシュボードのスクリーンショットやPDFを、撮影日時付きで保存して見返せる場所です。保存するだけで終わらず、下のアルバムから原寸表示できます。</p></header><section className="e-panel"><div className="e-upload"><label><span>画像・PDF</span><input type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label><span>スクショ日時</span><input type="datetime-local" value={capturedAt} onChange={e=>setCapturedAt(e.target.value)}/></label><button className="e-save" disabled={!file||busy} onClick={()=>void save()}>{busy?"処理中…":"資料庫へ保存"}</button></div>{preview?<img className="e-preview" src={preview} alt="選択画像"/>:null}{file&&!preview?<p className="e-muted">{file.name}</p>:null}{message?<p className="e-message">{message}</p>:null}</section><div className="e-title"><div><small style={{color:"#54d8ff",fontWeight:900}}>SAVED FILES</small><h2>保存済み</h2></div><strong>{rows.length}件</strong></div>{rows.length?<div className="e-grid">{rows.map(row=><article className="e-card" key={row.id}><a className="e-thumb" href={row.url??undefined} target={row.url?"_blank":undefined} rel="noreferrer">{row.url&&row.mime_type?.startsWith("image/")?<img src={row.url} alt=""/>:<span>{row.mime_type==="application/pdf"?"PDF":"FILE"}</span>}</a><div className="e-copy"><strong>{row.original_name||"保存資料"}</strong><small>{fmt(row.captured_at)}</small><div className="e-actions">{row.url?<a href={row.url} target="_blank" rel="noreferrer">開く</a>:null}<button disabled={busy} onClick={()=>void remove(row.id)}>削除</button></div></div></article>)}</div>:<section className="e-panel e-muted">まだ保存資料はありません。上からスクショを追加すると、ここにアルバム表示されます。</section>}</main></div>
}
