import { useEffect, useMemo, useState } from "react";

const API="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-fast-api-v2";
const OWNER_KEY="mumei-unified-owner-token";
type Evidence={id:string;original_name:string|null;mime_type:string|null;captured_at:string|null;created_at:string;url:string|null};
function localDateTime(){const n=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return n.toISOString().slice(0,16)}
function fmt(v:string|null){if(!v)return"日時不明";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(d)}
async function official(extra:Record<string,unknown>){const token=localStorage.getItem(OWNER_KEY)||"";const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json","X-Owner-Token":token},body:JSON.stringify({action:"official_save",...extra})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||"公式値を反映できませんでした");return p}

export function EvidenceV2(){
 const[rows,setRows]=useState<Evidence[]>([]),[file,setFile]=useState<File|null>(null),[capturedAt,setCapturedAt]=useState(localDateTime),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[selected,setSelected]=useState<Evidence|null>(null),[periodType,setPeriodType]=useState("all"),[views,setViews]=useState(""),[comments,setComments]=useState(""),[likes,setLikes]=useState("");
 const preview=useMemo(()=>file?.type.startsWith("image/")?URL.createObjectURL(file):"",[file]);
 async function load(){const r=await fetch("/owner/evidence-upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"list"})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error??"保存資料を読み込めませんでした。");setRows(p.rows??[])}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"読み込めませんでした。"))},[]);
 async function save(){if(!file||busy)return;setBusy(true);setMessage("");try{const f=new FormData();f.set("file",file);f.set("captured_at",new Date(capturedAt).toISOString());const r=await fetch("/owner/evidence-upload",{method:"POST",body:f});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error??"保存できませんでした。");setRows(p.rows??[]);setFile(null);setMessage("保存しました。必要なら下の『公式値に使う』からダッシュボードへ反映できます。")}catch(e){setMessage(e instanceof Error?e.message:"保存できませんでした。")}finally{setBusy(false)}}
 async function remove(id:string){if(busy)return;setBusy(true);try{const r=await fetch("/owner/evidence-upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error??"削除できませんでした。");setRows(p.rows??[]);if(selected?.id===id)setSelected(null)}catch(e){setMessage(e instanceof Error?e.message:"削除できませんでした。")}finally{setBusy(false)}}
 async function applyOfficial(){if(!selected)return;setBusy(true);setMessage("");try{await official({evidenceId:selected.id,periodType,totalViews:views,totalComments:comments,totalLikes:likes,capturedAt:selected.captured_at||selected.created_at});setMessage("このスクショをnote公式ダッシュボード値の根拠として反映しました。INSIGHTダッシュボードに表示されます。");setSelected(null);setViews("");setComments("");setLikes("")}catch(e){setMessage(e instanceof Error?e.message:"反映できませんでした。")}finally{setBusy(false)}}
 return <div className="ev2"><style>{`
 .ev2{min-height:100vh;background:#070a0f;color:#f5f8fc;padding:22px 14px 80px;font-family:system-ui,sans-serif}.ev2-wrap{width:min(1080px,100%);margin:auto}.ev2-back{color:#54d8ff;font-weight:900;text-decoration:none}.ev2-head{padding:42px 0 20px}.ev2-head h1{font-size:clamp(38px,7vw,60px);margin:7px 0}.ev2-head p,.muted{color:#9ba9bc;line-height:1.75}.ev2-panel{border:1px solid #2b394c;border-radius:20px;background:#0e151f;padding:20px}.ev2-upload{display:grid;grid-template-columns:1.3fr .8fr auto;gap:10px;align-items:end}.ev2-upload label,.ev2-official label{display:grid;gap:6px;font-weight:850}.ev2-upload input,.ev2-official input,.ev2-official select{min-height:44px;border:1px solid #34465c;border-radius:10px;background:#070b11;color:#fff;padding:8px}.ev2-save{min-height:44px;border:0;border-radius:10px;background:#54d8ff;color:#071016;font-weight:950;padding:0 15px}.ev2-preview{max-width:100%;max-height:300px;object-fit:contain;margin-top:14px;border-radius:13px;background:#05080c}.ev2-title{display:flex;justify-content:space-between;align-items:end;margin:36px 0 13px}.ev2-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:13px}.ev2-card{border:1px solid #2b3749;border-radius:16px;background:#0d141d;overflow:hidden}.ev2-thumb{display:grid;place-items:center;aspect-ratio:4/3;background:#05080c;color:#54d8ff;text-decoration:none}.ev2-thumb img{width:100%;height:100%;object-fit:cover}.ev2-copy{padding:11px}.ev2-copy strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ev2-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:9px}.ev2-actions a,.ev2-actions button{border:1px solid #34465c;border-radius:8px;background:#131d29;color:#fff;padding:8px;text-align:center;text-decoration:none}.ev2-actions .use{grid-column:1/-1;color:#071016;background:#ffd76b;border-color:#ffd76b;font-weight:950}.ev2-actions .delete{color:#ffadb5;border-color:#68404a}.ev2-official{margin-top:18px;border:1px solid #5c4e24;border-radius:18px;background:#17140d;padding:18px}.ev2-official h2{margin-top:0}.ev2-form{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.ev2-message{color:#ffd76b;font-weight:850;margin-top:12px}@media(max-width:700px){.ev2-upload,.ev2-form{grid-template-columns:1fr}.ev2-save{width:100%}}
 `}</style><main className="ev2-wrap"><a className="ev2-back" href="#dashboard">← INSIGHTへ戻る</a><header className="ev2-head"><small style={{color:"#54d8ff",fontWeight:900}}>INSIGHT EVIDENCE LIBRARY</small><h1>ダッシュボード資料庫</h1><p>スクショを置くだけの倉庫ではなく、保存画像をnote公式ダッシュボード値の根拠としてINSIGHTへ反映できます。</p></header><section className="ev2-panel"><div className="ev2-upload"><label>画像・PDF<input type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>スクショ日時<input type="datetime-local" value={capturedAt} onChange={e=>setCapturedAt(e.target.value)}/></label><button className="ev2-save" disabled={!file||busy} onClick={()=>void save()}>{busy?"処理中…":"資料庫へ保存"}</button></div>{preview?<img className="ev2-preview" src={preview} alt="選択画像"/>:null}{message?<p className="ev2-message">{message}</p>:null}</section>{selected?<section className="ev2-official"><h2>このスクショを公式値に使う</h2><p className="muted">画像を根拠として値を確認し、ここに入力した数値を「note公式値」としてダッシュボードへ表示します。画像そのものも資料庫に残ります。</p><div className="ev2-form"><label>期間<select value={periodType} onChange={e=>setPeriodType(e.target.value)}><option value="week">週</option><option value="month">月</option><option value="year">年</option><option value="all">全期間</option></select></label><label>全体ビュー<input inputMode="numeric" value={views} onChange={e=>setViews(e.target.value.replace(/\D/g,""))}/></label><label>コメント<input inputMode="numeric" value={comments} onChange={e=>setComments(e.target.value.replace(/\D/g,""))}/></label><label>スキ<input inputMode="numeric" value={likes} onChange={e=>setLikes(e.target.value.replace(/\D/g,""))}/></label></div><button className="ev2-save" style={{marginTop:12}} disabled={busy} onClick={()=>void applyOfficial()}>INSIGHTへ公式値として反映</button></section>:null}<div className="ev2-title"><div><small style={{color:"#54d8ff",fontWeight:900}}>SAVED FILES</small><h2 style={{margin:"4px 0"}}>保存済み資料</h2></div><strong>{rows.length}件</strong></div>{rows.length?<div className="ev2-grid">{rows.map(row=><article className="ev2-card" key={row.id}><a className="ev2-thumb" href={row.url??undefined} target={row.url?"_blank":undefined} rel="noreferrer">{row.url&&row.mime_type?.startsWith("image/")?<img src={row.url} alt=""/>:<span>{row.mime_type==="application/pdf"?"PDF":"FILE"}</span>}</a><div className="ev2-copy"><strong>{row.original_name||"保存資料"}</strong><small className="muted">{fmt(row.captured_at)}</small><div className="ev2-actions">{row.url?<a href={row.url} target="_blank" rel="noreferrer">開く</a>:null}<button className="delete" disabled={busy} onClick={()=>void remove(row.id)}>削除</button><button className="use" onClick={()=>setSelected(row)}>公式値に使う</button></div></div></article>)}</div>:<section className="ev2-panel muted">まだ保存資料はありません。</section>}</main></div>
}
