import { createPortal } from "react-dom";
import { useEffect, useMemo, useState } from "react";
import { FastInsightV6 } from "./fast-insight-v6";

const BASE="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-fast-api-v2";
const COMMENTS="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-comments-step";
const SOCIAL="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-social-rebuild";
const NOTIFY="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-notifications";
const V6="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-mobile-api-v6";
const MAG="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-magazine-mobile-v6";
const OWNER="mumei-unified-owner-token";
const LAST="mumei-insight-global-sync-v7";
const PAGE=20;
type Row=Record<string,any>;

function dt(v:any){if(!v)return"―";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function fmt(v:any){return new Intl.NumberFormat("ja-JP").format(Number(v||0))}
async function post(url:string,body:any={}){const token=localStorage.getItem(OWNER)||"";if(!token)throw new Error("OWNER_LOGIN_REQUIRED");const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","X-Owner-Token":token},body:JSON.stringify(body),cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||`HTTP_${r.status}`);return p}

function GlobalSync(){const[target,setTarget]=useState<HTMLElement|null>(null),[busy,setBusy]=useState(false),[last,setLast]=useState<number>(()=>Number(localStorage.getItem(LAST)||0)),[msg,setMsg]=useState("");
 useEffect(()=>{const find=()=>setTarget(document.querySelector<HTMLElement>(".iv3-toptools"));find();const o=new MutationObserver(find);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);
 async function sync(force=false){if(busy)return;const now=Date.now();if(!force&&now-last<3*60*1000)return;setBusy(true);setMsg("全体更新中…");const jobs=[post(BASE,{action:"quick_update"}),post(COMMENTS,{}),fetch(SOCIAL,{cache:"no-store"}).then(r=>r.json()),post(NOTIFY,{action:"watch-now"}),post(MAG,{action:"list",page:1,pageSize:15,relation:"all"})];const res=await Promise.allSettled(jobs);const ok=res.filter(x=>x.status==="fulfilled").length;const stamp=Date.now();localStorage.setItem(LAST,String(stamp));setLast(stamp);setBusy(false);setMsg(ok===jobs.length?"全体更新完了":`更新 ${ok}/${jobs.length} 完了`);window.dispatchEvent(new CustomEvent("insight-global-updated",{detail:{at:stamp,ok,total:jobs.length}}));setTimeout(()=>setMsg(""),2500)}
 useEffect(()=>{void sync(false);const id=window.setInterval(()=>{if(document.visibilityState==="visible")void sync(true)},10*60*1000);return()=>clearInterval(id)},[]);
 const ui=<div className="iv7-sync"><span>{busy?"更新中":last?`自動更新 ${dt(last)}`:"自動更新待ち"}</span><button disabled={busy} onClick={()=>void sync(true)}>全体更新</button>{msg?<small>{msg}</small>:null}</div>;
 return target?createPortal(ui,target):null}

const labels:Record<string,string>={reply:"返信",comment:"コメント",like:"スキ",follow:"フォロー",magazine:"マガジン",quote:"紹介・引用",buzz:"話題",purchase:"購入",tip:"チップ",rating:"評価",points:"ポイント",other:"その他"};
function NotificationV7(){const[kind,setKind]=useState("all"),[rows,setRows]=useState<Row[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[loadedPages,setLoadedPages]=useState(2),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(""),[lastImport,setLastImport]=useState<any>(null);
 async function load(pages=loadedPages){setLoading(true);setError("");try{const calls=[];for(let p=1;p<=pages;p++)calls.push(post(V6,{action:"notifications",page:p,pageSize:100,kind:"all"}));const all=await Promise.all(calls);const seen=new Set<number>(),merged:Row[]=[];for(const x of all)for(const r of x.rows||[])if(!seen.has(Number(r.id))){seen.add(Number(r.id));merged.push(r)}merged.sort((a,b)=>String(b.captured_at||b.occurred_at||"").localeCompare(String(a.captured_at||a.occurred_at||"")));setRows(merged);setCounts(all[0]?.counts||{});setLastImport(all[0]?.lastImport||null)}catch(e){setError(e instanceof Error?e.message:"通知を読めませんでした")}finally{setLoading(false)}}
 useEffect(()=>{void load(2);const h=()=>void load(loadedPages);window.addEventListener("insight-global-updated",h);return()=>window.removeEventListener("insight-global-updated",h)},[]);
 useEffect(()=>setPage(1),[kind]);
 const filtered=useMemo(()=>kind==="all"?rows:rows.filter(r=>r.notification_type===kind),[rows,kind]);const pages=Math.max(1,Math.ceil(filtered.length/PAGE)),shown=filtered.slice((page-1)*PAGE,page*PAGE);
 const tabs=[["all","すべて"],["reply","返信"],["comment","コメント"],["like","スキ"],["follow","フォロー"],["magazine","マガジン"],["quote","紹介"],["buzz","話題"],["purchase","購入"],["tip","チップ"]];
 async function older(){const next=loadedPages+1;setLoadedPages(next);await load(next)}
 return <div className="iv7-notify"><div className="iv7-head"><div><b>本人通知</b><small>一度読み込んだ通知をタブで切替。項目ごとの再読込はしません。</small></div><span>{fmt(counts[kind]??(kind==="all"?counts.all:filtered.length))}件</span></div><div className="iv7-auto"><b>公開通知は自動取得</b><span>ダッシュボード表示時＋10分ごと</span><small>他人の記事への返信・購入・チップなど公開取得できない通知だけ、必要なら追加します。</small><a href="./notification-import.html">追加が必要な通知だけ取り込む →</a>{lastImport?<em>保存データ更新 {dt(lastImport.created_at)}</em>:null}</div><div className="iv7-tabs">{tabs.map(([id,l])=><button key={id} className={kind===id?"active":""} onClick={()=>setKind(id)}>{l} {counts[id]!=null?fmt(counts[id]):""}</button>)}</div>{error?<p className="iv7-error">{error}</p>:null}{loading?<p className="iv7-empty">通知読込中…</p>:<div className="iv7-list">{shown.map(r=><article key={r.id}><div className="iv7-rowtop"><strong>{labels[r.notification_type]||r.notification_type}</strong><time>{dt(r.occurred_at||r.captured_at)}</time></div>{r.actor_name?<a className="iv7-person" href={r.actor_url||undefined} target="_blank" rel="noreferrer">{r.actor_name}</a>:null}<p>{r.raw_text}</p>{r.target_url?<a className="iv7-link" href={r.target_url} target="_blank" rel="noreferrer">{r.target_title||"通知先を開く"} ↗</a>:null}</article>)}</div>}<div className="iv7-pager"><button disabled={page<=1} onClick={()=>setPage(page-1)}>←</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>setPage(page+1)}>→</button></div>{rows.length>=loadedPages*100?<button className="iv7-older" disabled={loading} onClick={()=>void older()}>さらに過去100件を読み込む</button>:null}</div>}

export function FastInsightV7(){const[target,setTarget]=useState<HTMLElement|null>(null);useEffect(()=>{const tune=()=>{let found:HTMLElement|null=null;for(const p of document.querySelectorAll<HTMLElement>(".iv3-panel")){if(p.querySelector("h2")?.textContent?.trim()==="本人通知"){p.dataset.insightV7="notifications";found=p}else if(p.dataset.insightV7)delete p.dataset.insightV7}setTarget(found)};tune();const o=new MutationObserver(tune);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);return <><style>{`
.iv7-sync{display:inline-flex;align-items:center;gap:7px;flex-wrap:wrap;border:1px solid #345064;border-radius:9px;padding:5px 7px;background:#0b1720;color:#b9c8d6;font-size:11px}.iv7-sync button{border:1px solid #48708b;border-radius:7px;background:#102536;color:#8feaff;padding:5px 8px;font-weight:900}.iv7-sync small{color:#9effbd}.iv3-panel[data-insight-v7="notifications"]>.iv6-panel{display:none!important}.iv7-notify{display:block!important;max-width:100%;overflow:hidden;color:#eef5fc;font:13px/1.5 system-ui,-apple-system,sans-serif}.iv7-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.iv7-head>div{display:grid}.iv7-head b{font-size:18px}.iv7-head small{font-size:11px;color:#8e9daf}.iv7-head>span{color:#8feaff;font-weight:900}.iv7-auto{display:grid;gap:3px;border:1px solid #31516a;border-radius:10px;background:#0b1722;padding:9px;margin:9px 0}.iv7-auto b{color:#9effbd}.iv7-auto span,.iv7-auto small,.iv7-auto em{color:#91a2b5;font-size:11px;font-style:normal}.iv7-auto a{color:#b6ff38;text-decoration:none;font-weight:900;margin-top:3px}.iv7-tabs{display:flex;gap:5px;overflow-x:auto;scrollbar-width:none;padding-bottom:4px}.iv7-tabs::-webkit-scrollbar{display:none}.iv7-tabs button{flex:none;border:1px solid #34485e;border-radius:8px;background:#111c28;color:#fff;padding:6px 8px;font-size:11px;font-weight:850}.iv7-tabs button.active{background:#6658e8;border-color:#6658e8}.iv7-list{display:grid;gap:7px;margin-top:6px}.iv7-list article{border:1px solid #29394b;border-radius:10px;background:#0b121a;padding:9px}.iv7-rowtop{display:flex;justify-content:space-between;gap:8px}.iv7-rowtop strong{color:#8feaff;font-size:11px}.iv7-rowtop time{color:#8594a7;font-size:10px}.iv7-person,.iv7-link{color:#b9eaff;text-decoration:none}.iv7-person{display:block;font-weight:850;margin-top:5px}.iv7-list p{margin:6px 0;white-space:pre-wrap}.iv7-link{display:block;overflow:hidden;text-overflow:ellipsis}.iv7-pager{display:flex;justify-content:center;align-items:center;gap:10px;margin-top:10px}.iv7-pager button,.iv7-older{border:1px solid #36495f;border-radius:8px;background:#111c28;color:#fff;padding:7px 10px;font-weight:850}.iv7-older{display:block;margin:10px auto 0}.iv7-error{background:#2a151a;color:#ffb4bd;border-radius:8px;padding:8px}.iv7-empty{text-align:center;color:#8797a9;padding:18px}@media(min-width:760px){.iv7-list{grid-template-columns:repeat(2,minmax(0,1fr))}}
`}</style><FastInsightV6/><GlobalSync/>{target?createPortal(<NotificationV7/>,target):null}</>}
