import type { CSSProperties } from "react";

const page: CSSProperties = { minHeight: "100vh", background: "#070a0f", color: "#f7f9fc", fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" };
const wrap: CSSProperties = { width: "min(1180px, calc(100% - 28px))", margin: "0 auto" };
const card: CSSProperties = { border: "1px solid #253042", borderRadius: 22, background: "linear-gradient(180deg,#101722,#0b1017)", padding: 22, boxShadow: "0 18px 55px rgba(0,0,0,.25)" };
const button: CSSProperties = { display: "inline-flex", alignItems: "center", justifyContent: "center", minHeight: 48, borderRadius: 14, padding: "0 18px", fontWeight: 900, textDecoration: "none", border: "1px solid #8dcc31", background: "#b6ff38", color: "#101600" };

function Entrance({ title, label, copy, href, accent }: { title: string; label: string; copy: string; href: string; accent: string }) {
  return <article style={{ ...card, display: "flex", flexDirection: "column", minHeight: 245 }}><small style={{ color: accent, fontWeight: 900, letterSpacing: ".12em" }}>{label}</small><h2 style={{ fontSize: 29, margin: "10px 0 8px" }}>{title}</h2><p style={{ color: "#aab6c8", lineHeight: 1.75, margin: 0, flex: 1 }}>{copy}</p><a href={href} style={{ ...button, marginTop: 22, background: accent, borderColor: accent }}>開く →</a></article>;
}

export function HubHome() {
  return <div style={page}>
    <header style={{ borderBottom: "1px solid #202938", background: "rgba(7,10,15,.95)", position: "sticky", top: 0, zIndex: 20 }}><div style={{ ...wrap, minHeight: 68, display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16 }}><a href="#" style={{ color: "#fff", textDecoration: "none", fontWeight: 950, fontSize: 18 }}><span style={{ display: "block", color: "#b6ff38", fontSize: 11, letterSpacing: ".16em" }}>無名S note</span>CREATOR HUB</a><span style={{ color: "#7f8ba0", fontSize: 12 }}>INSIGHT × クリエイター名鑑</span></div></header>
    <main>
      <section style={{ ...wrap, padding: "70px 0 36px" }}><p style={{ color: "#b6ff38", fontWeight: 900, letterSpacing: ".15em", margin: 0 }}>MUMEI S NOTE CREATOR SYSTEM</p><h1 style={{ fontSize: "clamp(36px,7vw,76px)", lineHeight: 1.05, margin: "14px 0 18px", maxWidth: 950 }}>分析する。<br />名鑑でつながる。<br /><span style={{ color: "#b6ff38" }}>入口は、ここから。</span></h1><p style={{ maxWidth: 780, color: "#aab6c8", lineHeight: 1.8, fontSize: 16 }}>INSIGHT、クリエイター名鑑、管理ページを同じ基盤にまとめます。ログイン後は可能な限り長期間状態を保持し、利用資格はサービスごとに管理します。</p></section>
      <section style={{ ...wrap, display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))", gap: 16, paddingBottom: 60 }}><Entrance title="INSIGHT" label="ANALYTICS" copy="noteの反応・コメント・通知・フォロー・フォロワー・ダッシュボードを保存し、本人専用で分析します。" href="#access/insight" accent="#b6ff38" /><Entrance title="クリエイター名鑑" label="CREATOR DIRECTORY" copy="参加クリエイターのアイコン、カード、記事、ランキング、CREATOR WORLDを楽しむ公開・参加型エリアです。" href="#catalog" accent="#54d8ff" /><Entrance title="管理ページ" label="OWNER CONTROL" copy="管理者本人のINSIGHT・名鑑利用と、INSIGHT管理・クリエイター名鑑管理を分けて操作します。" href="#manage" accent="#ffcf5a" /></section>
      <section style={{ borderTop: "1px solid #202938", borderBottom: "1px solid #202938", background: "#0a0f16" }}><div style={{ ...wrap, padding: "58px 0", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: 18 }}><article style={card}><small style={{ color: "#b6ff38", fontWeight: 900 }}>INSIGHT</small><h2>noteの数字を、保存して深掘り。</h2><p style={{ color: "#aab6c8", lineHeight: 1.75 }}>全記事スキ、コメントの最終返信、通知、マガジン、フォロー・フォロワー差分、本人ダッシュボード値まで一つの履歴として扱います。</p><a href="#access/insight" style={button}>INSIGHTへ</a></article><article style={card}><small style={{ color: "#54d8ff", fontWeight: 900 }}>CREATOR DIRECTORY</small><h2>クリエイターを、カードと物語で見る。</h2><p style={{ color: "#aab6c8", lineHeight: 1.75 }}>名鑑、プロフィール、記事導線、カードゲーム、勝利数ランキングを同じnote IDへつなげます。</p><a href="#catalog" style={{ ...button, background: "#54d8ff", borderColor: "#54d8ff" }}>名鑑を見る</a></article></div></section>
      <section style={{ ...wrap, padding: "68px 0" }}><div style={{ border: "1px solid #4a3d68", borderRadius: 28, background: "radial-gradient(circle at 50% 0,#2d1e45,#0c1119 58%)", padding: "clamp(22px,5vw,44px)" }}><small style={{ color: "#ffd76b", fontWeight: 950, letterSpacing: ".16em" }}>CREATOR WORLD</small><h2 style={{ fontSize: "clamp(38px,7vw,68px)", margin: "8px 0" }}>ゲームセンター</h2><p style={{ color: "#aab6c8", lineHeight: 1.75 }}>対戦カードを選び、操作そのものが違う4つのゲームへ。</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(145px,1fr))", gap: 10, margin: "24px 0" }}>{[["COMMAND","選択式"],["TAP RUSH","タップ"],["ARCANE PUZZLE","パズル"],["STAR SHOOTER","シューティング"]].map(([code,name],i)=><article key={code} style={{ border: "1px solid #39465b", borderRadius: 16, background: "#0e151f", padding: 16 }}><small style={{ color: "#67ddff", fontWeight: 900 }}>0{i+1}</small><strong style={{ display: "block", marginTop: 18 }}>{code}</strong><span style={{ color: "#8f9caf", fontSize: 13 }}>{name}</span></article>)}</div><a href="#battle" style={{ ...button, width: "100%", boxSizing: "border-box", background: "#ffd76b", borderColor: "#ffd76b", color: "#160e00" }}>CREATOR WORLDへ入る →</a></div></section>
    </main>
    <footer style={{ borderTop: "1px solid #202938", padding: "26px 0", color: "#7f8ba0" }}><div style={wrap}>無名S note CREATOR HUB</div></footer>
  </div>;
}
