export {};
const STYLE_ID="mumei-inline-updates-v1-style";
let timer=0;
function installStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`
.miu-topactions .mumei-public-refresh-proxy.app-update-ready{border-color:#b6ff38!important;background:#17220c!important;color:#efffd4!important;box-shadow:0 0 0 2px rgba(182,255,56,.12)!important}.miu-topactions .mumei-public-refresh-proxy.app-update-ready span{color:#efffd4!important}.miv5-source-card.needs-update .miv5-source-main{cursor:pointer!important}
`;document.head.appendChild(s)}
function paint(){installStyle();const proxy=document.querySelector<HTMLButtonElement>(".mumei-public-refresh-proxy"),normal=document.querySelector<HTMLElement>(".miv5-source-card.normal");if(proxy&&normal){const update=normal.querySelector<HTMLElement>(".miv5-install-link.update-ready"),small=normal.querySelector<HTMLElement>(".miv5-source-main small"),label=proxy.querySelector<HTMLElement>("span"),sub=proxy.querySelector<HTMLElement>("small");proxy.classList.toggle("app-update-ready",Boolean(update));if(update){if(label)label.textContent="NEW INSIGHT本体更新";if(sub)sub.textContent=(small?.textContent||"最新版があります").replace(/^本体\s*/,"");proxy.title="タップでINSIGHT本体を最新版へ更新"}}for(const cls of ["notice","dashboard"]){const card=document.querySelector<HTMLElement>(`.miv5-source-card.${cls}`);if(card?.classList.contains("needs-update")){const main=card.querySelector<HTMLElement>(".miv5-source-main");if(main)main.title="更新があります。タップで更新画面へ進みます"}}}
function updateHref(card:HTMLElement|null){return(card?.querySelector<HTMLAnchorElement>(":scope > .miv5-install-link")?.href)||""}
document.addEventListener("click",e=>{const target=e.target as Element|null;if(!target)return;const proxy=target.closest(".mumei-public-refresh-proxy");if(proxy){const normal=document.querySelector<HTMLElement>(".miv5-source-card.normal"),update=normal?.querySelector<HTMLButtonElement>(".miv5-install-link.update-ready");if(update){e.preventDefault();e.stopImmediatePropagation();update.click();return}}const main=target.closest<HTMLElement>(".miv5-source-card.notice.needs-update .miv5-source-main,.miv5-source-card.dashboard.needs-update .miv5-source-main");if(main){const card=main.closest<HTMLElement>(".miv5-source-card"),href=updateHref(card);if(href){e.preventDefault();e.stopImmediatePropagation();location.assign(href)}}},true);
function schedule(ms=160){clearTimeout(timer);timer=window.setTimeout(paint,ms)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>schedule(0),{once:true});else schedule(0);new MutationObserver(()=>schedule()).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:["class","aria-busy"]});window.addEventListener("pageshow",()=>schedule(20));window.addEventListener("focus",()=>schedule(20));
