export {};

const PANEL_ID="mumei-insight-update-guide-v18";
const STYLE_ID="mumei-insight-update-guide-v18-style";
let timer=0;
function text(v:unknown){return String(v||"").replace(/\s+/g," ").trim()}
function installStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`#${PANEL_ID}{width:calc(100% - 8px);margin:4px auto 6px;padding:7px;border:1px solid #806a32;border-radius:12px;background:linear-gradient(135deg,#201708,#101722);color:#f8fbff;box-sizing:border-box}#${PANEL_ID} .mug-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:5px}#${PANEL_ID} .mug-head b{font-size:11px;color:#ffe6a0}#${PANEL_ID} .mug-head small{font-size:7px;color:#a7b8c8;text-align:right}#${PANEL_ID} .mug-items{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px}#${PANEL_ID} .mug-item{min-width:0;border:1px solid #3b5266;border-radius:9px;background:#0b1620;padding:5px;display:grid;grid-template-rows:auto auto 1fr auto;gap:2px}#${PANEL_ID} .mug-item strong{font-size:8.5px}#${PANEL_ID} .mug-item span{font-size:6.6px;line-height:1.25;color:#9eb2c2;min-height:16px}#${PANEL_ID} .mug-item em{font-style:normal;font-size:6.6px;color:#ffe2a0}#${PANEL_ID} .mug-item button{min-height:24px;border:1px solid #6d7e35;border-radius:7px;background:#b6ff38;color:#071016;font:900 7px/1 system-ui;padding:4px;cursor:pointer}@media(max-width:520px){#${PANEL_ID}{padding:6px}#${PANEL_ID} .mug-items{gap:3px}}`;document.head.appendChild(s)}
function normalRow(){const card=document.querySelector<HTMLElement>(".miv5-source-card.normal");if(!card||!card.classList.contains("needs-update"))return null;return{kind:"normal",label:"INSIGHT本体",desc:"画面・機能本体を最新版へ更新",small:text(card.querySelector(".miv5-source-main small")?.textContent)}}
function toolsRow(){const d=document.querySelector<HTMLElement>(".miv5-source-card.dashboard"),n=document.querySelector<HTMLElement>(".miv5-source-card.notice");if(!d?.classList.contains("needs-update")&&!n?.classList.contains("needs-update"))return null;const parts=[];if(d?.classList.contains("needs-update"))parts.push("Dashboard同期");if(n?.classList.contains("needs-update"))parts.push("本人通知");return{kind:"tools",label:"Dashboard / 本人通知",desc:"同じ導入センターで必要なツールだけ更新",small:parts.join("・")+" を確認"}}
function act(kind:string){if(kind==="normal"){document.querySelector<HTMLButtonElement>(".miv5-source-card.normal > .miv5-install-link.update-ready")?.click();return}const a=document.querySelector<HTMLAnchorElement>(".miv5-source-card.dashboard > .miv5-install-link.mumei-canonical-install")||document.querySelector<HTMLAnchorElement>(".miv5-source-card.notice > .miv5-install-link.mumei-canonical-install");if(a?.href){location.assign(a.href);return}location.assign(`./tool-setup.html?from=update&return=${encodeURIComponent(location.href)}`)}
function paint(){installStyle();const top=document.querySelector<HTMLElement>(".miv5-update");if(!top)return;const rows=[normalRow(),toolsRow()].filter(Boolean) as Array<{kind:string,label:string,desc:string,small:string}>;let panel=document.getElementById(PANEL_ID) as HTMLElement|null;if(!rows.length){panel?.remove();return}if(!panel){panel=document.createElement("section");panel.id=PANEL_ID;panel.setAttribute("role","status");top.insertAdjacentElement("afterend",panel)}panel.innerHTML=`<div class="mug-head"><b>⬆ 更新があります</b><small>Dashboardと本人通知は同じ導入センター</small></div><div class="mug-items">${rows.map(r=>`<div class="mug-item" data-kind="${r.kind}"><strong>${r.label}</strong><span>${r.desc}</span><em>${r.small||"最新版を確認してください"}</em><button type="button">更新案内を開く</button></div>`).join("")}</div>`;for(const b of panel.querySelectorAll<HTMLButtonElement>(".mug-item button")){b.addEventListener("click",()=>{const kind=b.closest<HTMLElement>(".mug-item")?.dataset.kind;if(kind)act(kind)})}}
function schedule(ms=80){window.clearTimeout(timer);timer=window.setTimeout(paint,ms)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>schedule(0),{once:true});else schedule(0);new MutationObserver(()=>schedule()).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:["class","disabled"]});window.addEventListener("pageshow",()=>schedule(0));window.addEventListener("focus",()=>schedule(0));window.addEventListener("storage",()=>schedule(0));
