import { FormEvent, useEffect, useMemo, useState } from "react";

const ACCESS = "https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-access";
const OWNER_ACCESS = "https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/unified-owner-access";
const OWNER_KEY = "mumei-unified-owner-token";
const OWNER_VIEW_KEY = "mumei-owner-insight-view";

type Status = "pending" | "approved" | "active" | "rejected" | "revoked";
type Application = {id:string;noteId:string;displayName:string|null;imageUrl:string|null;status:Status;approvedAt?:string|null;verifiedAt?:string|null;createdAt?:string|null;updatedAt?:string|null};
const card={border:"1px solid #29384b",borderRadius:18,background:"linear-gradient(180deg,#101722,#0a1018)",padding:18} as const;
const button={minHeight:40,borderRadius:10,padding:"0 12px",fontWeight:950,cursor:"pointer"} as const;

async function ownerStatus(){const token=localStorage.getItem(OWNER_KEY)||"";if(!token)return false;const response=await fetch(OWNER_ACCESS,{method:"POST",headers:{"Content-Type":"application/json","X-Owner-Token":token},body:JSON.stringify({action:"status"}),cache:"no-store"});const payload=await response.json().catch(()=>({}));return Boolean(response.ok&&payload?.authenticated)}
async function call(action:string,adminPass:string,extra:Record<string,unknown>={}){const response=await fetch(ACCESS,{method:"POST",headers:{"Content-Type":"application/json","X-Owner-Token":localStorage.getItem(OWNER_KEY)||"","X-Admin-Pass":adminPass},body:JSON.stringify({action,...extra}),cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok||payload?.ok===false)throw new Error(payload?.error||"OWNER_REQUEST_FAILED");return payload}
function fmt(value?:string|null){if(!value)return"—";const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(date)}
function Avatar({app}:{app:Application}){const name=app.displayName||app.noteId||"n";return app.imageUrl?<img src={app.imageUrl} alt="" referrerPolicy="no-referrer" style={{width:50,height:50,borderRadius:"50%",objectFit:"cover",border:"1px solid #43627d"}}/>:<span style={{width:50,height:50,borderRadius:"50%",display:"grid",placeItems:"center",background:"#1a2939",color:"#8feaff",fontWeight:950}}>{[...name][0]}</span>}
function statusLabel(app:Application){if(app.status==="approved"&&app.verifiedAt)return"再開待ち";return({pending:"承認待ち",approved:"本人認証待ち",active:"利用中",rejected:"却下履歴",revoked:"退会・停止履歴"} as Record<Status,string>)[app.status]}
const statusColor:Record<Status,string>={pending:"#ffcf69",approved:"#8feaff",active:"#9cffae",rejected:"#ff9aa8",revoked:"#ff9aa8"};

export function ManagementPage(){
 const[items,setItems]=useState<Application[]>([]),[loading,setLoading]=useState(true),[ownerChecked,setOwnerChecked]=useState(false),[authorized,setAuthorized]=useState(false),[adminPass,setAdminPass]=useState(""),[passInput,setPassInput]=useState(""),[unlocked,setUnlocked]=useState(false),[busyId,setBusyId]=useState<string|null>(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[lastUpdated,setLastUpdated]=useState<string|null>(null),[refreshing,setRefreshing]=useState(false),[unlockBusy,setUnlockBusy]=useState(false);
 const counts=useMemo(()=>({pending:items.filter(x=>x.status==="pending").length,approved:items.filter(x=>x.status==="approved").length,active:items.filter(x=>x.status==="active").length,inactive:items.filter(x=>x.status==="rejected"||x.status==="revoked").length}),[items]);
 const currentItems=useMemo(()=>items.filter(x=>x.status!=="rejected"&&x.status!=="revoked"),[items]);
 const historyItems=useMemo(()=>items.filter(x=>x.status==="rejected"||x.status==="revoked"),[items]);
 async function load(manual=false,pass=adminPass){if(!pass)return;setError("");if(manual)setRefreshing(true);try{const payload=await call("owner-list",pass);setItems(Array.isArray(payload.applications)?payload.applications:[]);setLastUpdated(new Date().toISOString())}catch(caught){const code=caught instanceof Error?caught.message:"OWNER_REQUEST_FAILED";if(code==="OWNER_LOGIN_REQUIRED"){localStorage.removeItem(OWNER_KEY);setAuthorized(false);window.location.hash="owner";return}if(code==="ADMIN_PASSWORD_INVALID"){setUnlocked(false);setAdminPass("");setPassInput("");setError("管理パスワードが違います。");return}setError(code)}finally{setLoading(false);if(manual)setRefreshing(false)}}
 useEffect(()=>{let live=true;void(async()=>{setLoading(true);try{const authenticated=await ownerStatus();if(!live)return;if(!authenticated){localStorage.removeItem(OWNER_KEY);setAuthorized(false);setOwnerChecked(true);window.location.hash="owner";return}setAuthorized(true);setOwnerChecked(true);setLoading(false)}catch{if(!live)return;localStorage.removeItem(OWNER_KEY);setAuthorized(false);setOwnerChecked(true);window.location.hash="owner"}})();return()=>{live=false}},[]);
 useEffect(()=>{if(!unlocked||!adminPass)return;let timer:number|undefined;void load(false,adminPass);timer=window.setInterval(()=>{if(document.visibilityState==="visible")void load(false,adminPass)},20_000);return()=>{if(timer)window.clearInterval(timer)}},[unlocked,adminPass]);
 async function unlock(event:FormEvent){event.preventDefault();if(!passInput)return;setUnlockBusy(true);setError("");setMessage("");try{const payload=await call("owner-list",passInput);setItems(Array.isArray(payload.applications)?payload.applications:[]);setAdminPass(passInput);setPassInput("");setUnlocked(true);setLastUpdated(new Date().toISOString());setLoading(false)}catch(caught){const code=caught instanceof Error?caught.message:"OWNER_REQUEST_FAILED";setError(code==="ADMIN_PASSWORD_INVALID"?"管理パスワードが違います。":"管理ページを開けませんでした。OWNER認証を確認してください。")}finally{setUnlockBusy(false)}}
 async function action(app:Application,actionName:"owner-approve"|"owner-reject"|"owner-revoke"|"owner-remove"){if(actionName==="owner-revoke"&&!window.confirm(`${app.displayName||app.noteId} のINSIGHT利用を停止しますか？\n参加履歴は管理用に残ります。`))return;if(actionName==="owner-remove"&&!window.confirm(`${app.displayName||app.noteId} をINSIGHTから強制退会させますか？\n全端末セッションと本人通知連携を失効し、現役参加者一覧から完全に外します。`))return;setBusyId(app.id);setError("");setMessage("");try{const payload=await call(actionName,adminPass,{id:app.id}),next=payload.application as Application;setMessage(actionName==="owner-approve"?(next.verifiedAt?`${next.displayName||next.noteId} の再参加を承認しました。本人確認済みのため申請者側で自動再開します。`:`${next.displayName||next.noteId} を承認しました。初回本人確認コードは申請者側だけに表示します。`):actionName==="owner-reject"?"申請を却下しました。":actionName==="owner-remove"?"参加者を強制退会しました。現役参加者一覧から外し、全端末セッションと本人通知連携を停止しました。":"利用を停止しました。管理上の履歴だけ残しています。");await load(false,adminPass)}catch(caught){const code=caught instanceof Error?caught.message:"変更できませんでした。";if(code==="ADMIN_PASSWORD_INVALID"){setUnlocked(false);setAdminPass("");setError("管理パスワードの再入力が必要です。")}else setError(code)}finally{setBusyId(null)}}
 async function logout(){const token=localStorage.getItem(OWNER_KEY)||"";try{await fetch(OWNER_ACCESS,{method:"POST",headers:{"Content-Type":"application/json","X-Owner-Token":token},body:JSON.stringify({action:"logout"}),cache:"no-store"})}catch{}localStorage.removeItem(OWNER_KEY);sessionStorage.removeItem(OWNER_VIEW_KEY);setAdminPass("");setUnlocked(false);window.location.hash="owner"}
 function backToInsight(){sessionStorage.removeItem(OWNER_VIEW_KEY);window.location.hash="dashboard"}
 function participantCard(app:Application,history=false){return <article key={app.id} style={{...card,padding:15,display:"grid",gridTemplateColumns:"50px minmax(0,1fr) auto",gap:12,alignItems:"center",borderColor:app.status==="pending"?"#5a4d2c":app.status==="approved"?"#31576a":app.status==="active"?"#315b3b":"#493139",opacity:history?.78:1}}><Avatar app={app}/><div style={{minWidth:0}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:17}}>{app.displayName||`@${app.noteId}`}</strong><span style={{color:statusColor[app.status],fontSize:11,fontWeight:950}}>{statusLabel(app)}</span></div><a href={`https://note.com/${app.noteId}`} target="_blank" rel="noreferrer" style={{color:"#69ccff",textDecoration:"none",fontSize:12}}>@{app.noteId} ↗</a><div style={{color:"#718399",fontSize:11,marginTop:5}}>申請 {fmt(app.createdAt)}　承認 {fmt(app.approvedAt)}　本人認証 {fmt(app.verifiedAt)}</div></div>{history?<div style={{color:"#718399",fontSize:11,fontWeight:900}}>履歴</div>:<div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end",maxWidth:270}}>{app.status==="pending"?<button disabled={busyId===app.id} onClick={()=>void action(app,"owner-approve")} style={{...button,border:0,background:"#b6ff38",color:"#111600"}}>承認</button>:null}{app.status==="pending"?<button disabled={busyId===app.id} onClick={()=>void action(app,"owner-reject")} style={{...button,border:"1px solid #69404a",background:"transparent",color:"#ffabb5"}}>却下</button>:null}{app.status==="approved"||app.status==="active"?<button disabled={busyId===app.id} onClick={()=>void action(app,"owner-revoke")} style={{...button,border:"1px solid #69404a",background:"transparent",color:"#ffabb5"}}>利用停止</button>:null}{app.status==="active"?<button disabled={busyId===app.id} onClick={()=>void action(app,"owner-remove")} style={{...button,border:"1px solid #b54858",background:"#351018",color:"#ffd6dc"}}>強制退会</button>:null}</div>}</article>}
 if(!ownerChecked||!authorized)return <div style={{minHeight:"100vh",background:"#070a0f",color:"#8d9caf",display:"grid",placeItems:"center",padding:20}}><span>{ownerChecked?"管理者入口へ移動しています…":"OWNER認証を確認しています…"}</span></div>;
 if(!unlocked)return <div style={{minHeight:"100vh",background:"#070a0f",color:"#f5f8fb",padding:"26px 14px"}}><main style={{width:"min(560px,100%)",margin:"0 auto"}}><button onClick={backToInsight} style={{...button,border:"1px solid #355b72",background:"#10202d",color:"#8feaff"}}>← 現在のINSIGHTへ戻る</button><header style={{padding:"46px 0 18px"}}><small style={{color:"#ffcf69",fontWeight:950,letterSpacing:".14em"}}>OWNER SECOND LOCK</small><h1 style={{fontSize:"clamp(34px,7vw,54px)",margin:"7px 0"}}>管理ページ</h1><p style={{color:"#94a3b7",lineHeight:1.75}}>OWNER本人認証に加えて、管理操作だけ二重ロックしています。パスワードはこの画面のメモリ内だけで保持し、ブラウザ保存はしません。</p></header>{error?<div style={{...card,marginBottom:12,borderColor:"#773f4a",color:"#ffadb8"}}>{error}</div>:null}<form onSubmit={unlock} style={{...card,display:"grid",gap:10}}><label style={{display:"grid",gap:6}}><span style={{fontSize:12,color:"#9fb0c3",fontWeight:900}}>管理パスワード</span><input type="password" value={passInput} onChange={e=>setPassInput(e.target.value)} autoComplete="current-password" required style={{minHeight:48,border:"1px solid #42556c",borderRadius:11,background:"#080d13",color:"#fff",padding:"0 12px",fontSize:16}} /></label><button disabled={unlockBusy} style={{...button,border:0,background:"#ffcf5a",color:"#171000",minHeight:48}}>{unlockBusy?"確認中…":"管理ページを開く"}</button></form></main></div>;
 return <div style={{minHeight:"100vh",background:"#070a0f",color:"#f5f8fb",padding:"22px 13px 70px"}}><main style={{width:"min(1080px,100%)",margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><button onClick={backToInsight} style={{...button,border:"1px solid #355b72",background:"#10202d",color:"#8feaff"}}>← 現在のINSIGHTへ戻る</button><button onClick={()=>void logout()} style={{...button,border:"1px solid #3a4658",background:"transparent",color:"#a9b6c7"}}>管理ログアウト</button></div>
  <header style={{padding:"42px 0 20px"}}><small style={{color:"#ffcf69",fontWeight:950,letterSpacing:".14em"}}>INSIGHT SALES ADMIN / OWNER ONLY</small><h1 style={{fontSize:"clamp(38px,7vw,62px)",margin:"7px 0"}}>INSIGHT 管理ページ</h1><p style={{color:"#94a3b7",lineHeight:1.75,maxWidth:760}}>OWNER本人認証＋管理パスワードの二重ロック。通常操作は承認・利用停止・強制退会だけです。本人確認コードの再発行は通常運用から外しました。</p></header>
  {message?<div style={{...card,marginBottom:12,borderColor:"#426329",color:"#c8ff84"}}>{message}</div>:null}{error?<div style={{...card,marginBottom:12,borderColor:"#773f4a",color:"#ffadb8"}}>{error}</div>:null}
  <section style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:8,marginBottom:14}}>{[["承認待ち",counts.pending,"#ffcf69"],["許可済み・再開待ち",counts.approved,"#8feaff"],["利用中",counts.active,"#9cffae"],["停止・退会履歴",counts.inactive,"#ff9aa8"]].map(([label,numValue,color])=><article key={String(label)} style={{...card,padding:"14px 8px",textAlign:"center"}}><small style={{color:String(color),fontWeight:900}}>{label}</small><strong style={{display:"block",fontSize:30,marginTop:3}}>{Number(numValue)}</strong></article>)}</section>
  <section style={{...card,padding:14,marginBottom:14,display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><strong>販売用固定URL</strong><div style={{color:"#8da0b5",fontSize:12,marginTop:3}}>https://mumei-s.github.io/note-insight/</div><small style={{color:"#70849a"}}>{lastUpdated?`最終更新 ${fmt(lastUpdated)}・自動更新ON`:"自動更新準備中"}</small></div><button disabled={refreshing} onClick={()=>void load(true,adminPass)} style={{...button,border:"1px solid #395068",background:"#111c29",color:"#8feaff",opacity:refreshing?.6:1}}>{refreshing?"更新中…":"今すぐ更新"}</button></section>
  {loading?<section style={card}>申請一覧を読み込んでいます…</section>:<section style={{display:"grid",gap:10}}>{currentItems.map(app=>participantCard(app))}{!currentItems.length?<article style={card}><strong>現在の参加申請・利用者はいません。</strong><p style={{color:"#8999ad",marginBottom:0}}>購入者が固定URLから申請すると、ここに表示されます。</p></article>:null}</section>}
  {historyItems.length?<details style={{...card,marginTop:16}}><summary style={{cursor:"pointer",fontWeight:950,color:"#aebdce"}}>停止・退会・却下の履歴（{historyItems.length}件）</summary><div style={{display:"grid",gap:10,marginTop:12}}>{historyItems.map(app=>participantCard(app,true))}</div></details>:null}
 </main><style>{`@media(max-width:650px){main>section:nth-of-type(1){grid-template-columns:repeat(2,minmax(0,1fr))!important}}`}</style></div>
}