import { useEffect, useMemo, useState } from "react";
import { INSIGHT_TOKEN_KEY } from "./insight-account-store";
import "./member-insight-analytics-v3.css";

const DASH="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-dashboard-data";
type Row=Record<string,any>;
type Mode="day"|"week"|"month";
type Metric="views"|"likes"|"comments";
type TrendKey="likes"|"comments"|"replies"|"followers"|"views";

const nf=new Intl.NumberFormat("ja-JP");
const n=(v:any)=>nf.format(Number(v||0));
const num=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
const short=(v:string)=>{const p=String(v||"").split("-");return p.length===3?`${Number(p[1])}/${Number(p[2])}`:v};
const jst=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);

async function loadAnalysis(days:number){const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");const r=await fetch(DASH,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify({action:"analysis",days}),cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"分析データを取得できませんでした");return p}
function weekKey(date:string){const d=new Date(`${date}T12:00:00+09:00`),day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);return d.toISOString().slice(0,10)}
function bucketLabel(key:string,mode:Mode){if(mode==="day")return short(key);if(mode==="week")return `${short(key)}〜`;const[y,m]=key.split("-");return`${Number(m)}月${m==="01"?` '${String(y).slice(-2)}`:""}`}
function fillDaily(rows:Row[],days:number){const by=new Map(rows.map(r=>[String(r.date),r]));const out:Row[]=[];for(let i=days-1;i>=0;i--){const key=jst(new Date(Date.now()-i*86400000)),r=by.get(key)||{};out.push({date:key,likes:num(r.likes),comments:num(r.comments),replies:num(r.replies),followers:r.followers==null?null:num(r.followers)})}let last:number|null=null;for(const r of out){if(r.followers!=null)last=r.followers;else if(last!=null)r.followers=last}return out}
function aggregate(rows:Row[],mode:Mode):Row[]{if(mode==="day")return rows.map(r=>({...r,label:bucketLabel(String(r.date),mode)}));const groups=new Map<string,Row>();for(const r of rows){const key=mode==="week"?weekKey(String(r.date)):String(r.date).slice(0,7),g=groups.get(key)||{date:key,likes:0,comments:0,replies:0,followers:null};g.likes+=num(r.likes);g.comments+=num(r.comments);g.replies+=num(r.replies);if(r.followers!=null)g.followers=r.followers;groups.set(key,g)}return[...groups.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(r=>({...r,label:bucketLabel(String(r.date),mode)}))}
function dashboardSeries(rows:Row[],mode:Mode):Row[]{const byDay=new Map<string,Row>();for(const r of rows||[]){const d=String(r.date||"");if(!d)continue;const prev=byDay.get(d);if(!prev||String(r.at||"")>String(prev.at||""))byDay.set(d,r)}const daily=[...byDay.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)));let prev:number|null=null;const deltas=daily.map(r=>{const total=num(r.views),value=prev==null?0:Math.max(0,total-prev);prev=total;return{date:r.date,views:value,totalViews:total}});if(mode==="day")return deltas.map(r=>({...r,label:bucketLabel(String(r.date),mode)}));const groups=new Map<string,Row>();for(const r of deltas){const key=mode==="week"?weekKey(String(r.date)):String(r.date).slice(0,7),g=groups.get(key)||{date:key,views:0,totalViews:0};g.views+=num(r.views);g.totalViews=num(r.totalViews);groups.set(key,g)}return[...groups.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(r=>({...r,label:bucketLabel(String(r.date),mode)}))}
function pct(now:number,prev:number){if(prev<=0)return now>0?100:0;return Math.round((now-prev)/prev*100)}
function Delta({now,prev}:{now:number;prev:number}){const p=pct(now,prev),up=p>=0;return <span className={up?"mia3-up":"mia3-down"}>{up?"▲":"▼"} {Math.abs(p)}%</span>}
function stat(rows:Row[],key:string){const v=rows.map(r=>num(r[key])).filter(Number.isFinite);if(!v.length)return{latest:0,avg:0,max:0,min:0};return{latest:v[v.length-1],avg:Math.round(v.reduce((a,b)=>a+b,0)/v.length),max:Math.max(...v),min:Math.min(...v)}}

function MetricChart({title,subtitle,rows,keyName,suffix="件",baseline=false}:{title:string;subtitle:string;rows:Row[];keyName:TrendKey;suffix?:string;baseline?:boolean}){const[index,setIndex]=useState(Math.max(0,rows.length-1));useEffect(()=>setIndex(Math.max(0,rows.length-1)),[rows.length,keyName]);const s=stat(rows,keyName),selected=rows[index]||null,prev=index>0?num(rows[index-1]?.[keyName]):0;const W=Math.max(720,rows.length*28),H=270,p={l:58,r:26,t:28,b:42},values=rows.map(r=>num(r[keyName])),rawMin=Math.min(...values,0),rawMax=Math.max(...values,1),min=baseline?0:Math.max(0,Math.floor((rawMin-(rawMax-rawMin)*.12)/5)*5),max=Math.max(min+1,Math.ceil((rawMax+(rawMax-rawMin)*.12)/5)*5),iw=W-p.l-p.r,ih=H-p.t-p.b,xy=(v:number,i:number)=>[p.l+(rows.length<=1?iw/2:i*iw/(rows.length-1)),p.t+ih-(v-min)/(max-min)*ih],ticks=[0,.25,.5,.75,1],every=Math.max(1,Math.ceil(rows.length/7)),pts=rows.map((r,i)=>xy(num(r[keyName]),i).join(",")).join(" ");return <article className="mia3-card wide"><header><div><small>{subtitle}</small><h2>{title}</h2></div></header><div className="mia3-statline"><span><small>最新</small><b>{n(s.latest)}{suffix}</b></span><span><small>平均</small><b>{n(s.avg)}{suffix}</b></span><span><small>最大</small><b>{n(s.max)}{suffix}</b></span><span><small>最小</small><b>{n(s.min)}{suffix}</b></span></div>{selected?<div className="mia3-selected"><b>{selected.label||selected.date}</b><strong>{n(selected[keyName])}{suffix}</strong>{index>0?<Delta now={num(selected[keyName])} prev={prev}/>:<small>最初の記録</small>}<small>グラフの点をタップすると数値を確認できます</small></div>:null}<div className="mia3-scroll"><svg viewBox={`0 0 ${W} ${H}`} style={{minWidth:W}} role="img" aria-label={`${title}グラフ`}>{ticks.map((t,i)=>{const value=min+(max-min)*t,y=p.t+ih-i*ih/(ticks.length-1);return <g key={i}><line className="mia3-gridline" x1={p.l} x2={W-p.r} y1={y} y2={y}/><text className="mia3-axis" x={p.l-10} y={y+4} textAnchor="end">{n(Math.round(value))}</text></g>})}<polyline className={`mia3-line ${keyName}`} points={pts}/>{rows.map((r,i)=>{const[x,y]=xy(num(r[keyName]),i),active=i===index;return <g key={`${r.date}:${i}`} onClick={()=>setIndex(i)} className="mia3-point"><circle className="hit" cx={x} cy={y} r="14"/><circle className={`dot ${keyName} ${active?"active":""}`} cx={x} cy={y} r={active?5:3}/>{active?<text className="mia3-value" x={x} y={Math.max(14,y-12)} textAnchor="middle">{n(r[keyName])}</text>:null}{i%every===0||i===rows.length-1?<text className="mia3-axis x" x={x} y={H-12} textAnchor="middle">{r.label}</text>:null}</g>})}</svg></div></article>}

function Donut({likes,comments,replies}:{likes:number;comments:number;replies:number}){const total=likes+comments+replies,vals=[{k:"スキ",v:likes,c:"like"},{k:"コメント",v:comments,c:"comment"},{k:"返信",v:replies,c:"reply"}],l=total?likes/total*100:0,c=total?comments/total*100:0,style=total?{background:`conic-gradient(var(--mia3-like) 0 ${l}%,var(--mia3-comment) ${l}% ${l+c}%,var(--mia3-reply) ${l+c}% 100%)`}:{background:"#172231"};return <article className="mia3-card"><header><div><small>REACTION MIX</small><h2>反応構成</h2></div></header><div className="mia3-donutwrap"><div className="mia3-donut" style={style}><div><strong>{n(total)}</strong><small>総反応</small></div></div><div className="mia3-donutlegend">{vals.map(x=><span key={x.k}><i className={x.c}/><b>{x.k}</b><strong>{n(x.v)}件</strong><em>{total?Math.round(x.v/total*100):0}%</em></span>)}</div></div></article>}

function ArticleBars({rows,metric,onMetric}:{rows:Row[];metric:Metric;onMetric:(m:Metric)=>void}){const sorted=[...rows].sort((a,b)=>num(b[metric])-num(a[metric])).slice(0,8),max=Math.max(1,...sorted.map(r=>num(r[metric]))),label=metric==="views"?"VIEW":metric==="likes"?"スキ":"コメント";return <article className="mia3-card"><header><div><small>TOP ARTICLES</small><h2>記事パフォーマンス TOP8</h2></div><div className="mia3-switch">{(["views","likes","comments"] as Metric[]).map(x=><button key={x} className={metric===x?"active":""} onClick={()=>onMetric(x)}>{x==="views"?"VIEW":x==="likes"?"スキ":"コメント"}</button>)}</div></header><div className="mia3-bars">{sorted.map((r,i)=><a key={r.article_key||r.url||i} href={r.url||undefined} target={r.url?"_blank":undefined} rel={r.url?"noreferrer":undefined}><em>{i+1}</em><div><b>{r.title||"無題の記事"}</b><div className="mia3-barrow"><span><i style={{width:`${Math.max(2,num(r[metric])/max*100)}%`}}/></span><strong>{n(r[metric])}</strong></div><small>VIEW {n(r.views)}　♡ {n(r.likes)}　💬 {n(r.comments)}</small></div></a>)}</div><p className="mia3-note">棒の右端が選択中の「{label}」実数です。</p></article>}

function Compare({c}:{c:Row}){const items=[{k:"スキ",now:num(c.likes7),prev:num(c.likesPrev7)},{k:"コメント",now:num(c.comments7),prev:num(c.commentsPrev7)},{k:"返信",now:num(c.replies7),prev:num(c.repliesPrev7)}];return <article className="mia3-card"><header><div><small>7 DAYS COMPARISON</small><h2>直近7日 vs 前7日</h2></div></header><div className="mia3-compare">{items.map(x=><div key={x.k}><span>{x.k}</span><b>{n(x.now)}件</b><small>前7日 {n(x.prev)}件</small><Delta now={x.now} prev={x.prev}/></div>)}</div></article>}

export function MemberInsightAnalyticsV3({revision=0,onBack}:{revision?:number;onBack?:()=>void}){const[mode,setMode]=useState<Mode>("day"),[data,setData]=useState<Row|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[metric,setMetric]=useState<Metric>("views");const days=mode==="day"?30:mode==="week"?90:365;useEffect(()=>{let dead=false;setLoading(true);setError("");void loadAnalysis(days).then(x=>{if(!dead)setData(x)}).catch(e=>{if(!dead)setError(e instanceof Error?e.message:"分析データを取得できませんでした")}).finally(()=>{if(!dead)setLoading(false)});return()=>{dead=true}},[days,revision]);const daily=useMemo(()=>fillDaily(data?.series||[],days),[data,days]),series=useMemo(()=>aggregate(daily,mode),[daily,mode]),dash=useMemo(()=>dashboardSeries(data?.dashboard||[],mode),[data,mode]),latest=data?.latestDashboard||{},comparison=data?.comparison||{},reaction=useMemo(()=>{let likes=0,comments=0,replies=0;for(const r of series){likes+=num(r.likes);comments+=num(r.comments);replies+=num(r.replies)}return{likes,comments,replies}},[series]),followers=series.filter(r=>r.followers!=null),currentFollowers=followers.length?num(followers[followers.length-1].followers):0;
if(loading&&!data)return <section className="mia3-page"><div className="mia3-loading">分析データを読み込み中…</div></section>;if(error&&!data)return <section className="mia3-page"><button className="mia3-back" onClick={onBack}>← INSIGHT</button><div className="mia3-error">{error}</div></section>;
return <section className="mia3-page"><header className="mia3-head"><div>{onBack?<button className="mia3-back" onClick={onBack}>← INSIGHT</button>:null}<small>INSIGHT ANALYTICS V3</small><h1>データ分析</h1><p>線を見るだけではなく、数字をタップして確認できる分析画面。</p></div><div className="mia3-mode">{(["day","week","month"] as Mode[]).map(x=><button key={x} className={mode===x?"active":""} onClick={()=>setMode(x)}>{x==="day"?"日別 30日":x==="week"?"週別 12週":"月別 12か月"}</button>)}</div></header><div className="mia3-sync"><div><b>ダッシュボード自動取得</b><span>{latest.capturedAt?`最終同期 ${new Date(latest.capturedAt).toLocaleString("ja-JP")} / 総VIEW ${n(latest.views)}`:"まだ統計同期がありません"}</span><small>通知・統計同期ツールv2.5.2を入れてnoteを開けば30分ごとに自動取得。今すぐ取得する場合はTampermonkeyメニューの「ダッシュボード統計を今すぐ同期」。</small></div><a href="https://note.com/" target="_blank" rel="noreferrer">noteを開く ↗</a></div>{error?<p className="mia3-error">{error}</p>:null}<div className="mia3-kpis"><article><small>総VIEW</small><strong>{n(latest.views)}</strong><span>{latest.capturedAt?"ダッシュボード実数":"同期待ち"}</span></article><article><small>期間スキ</small><strong>{n(reaction.likes)}</strong><span>直近7日 {n(comparison.likes7)}</span></article><article><small>期間コメント</small><strong>{n(reaction.comments)}</strong><span>直近7日 {n(comparison.comments7)}</span></article><article><small>最新フォロワー</small><strong>{n(currentFollowers)}</strong><span>{followers.length?"同期履歴から":"同期待ち"}</span></article></div><div className="mia3-grid"><MetricChart title="スキ推移" subtitle="LIKE TREND" rows={series} keyName="likes" baseline/><MetricChart title="コメント推移" subtitle="COMMENT TREND" rows={series} keyName="comments" baseline/><MetricChart title="返信推移" subtitle="REPLY TREND" rows={series} keyName="replies" baseline/>{followers.length?<MetricChart title="フォロワー推移" subtitle="FOLLOWER TREND" rows={followers} keyName="followers" suffix="人"/>:<article className="mia3-card wide"><p className="mia3-empty">フォロワー同期履歴が蓄積されると表示します。</p></article>}{dash.length>1?<MetricChart title="VIEW増加推移" subtitle="VIEW GROWTH" rows={dash} keyName="views" suffix="VIEW" baseline/>:<article className="mia3-card wide"><p className="mia3-empty">ダッシュボード統計が2回以上保存されるとVIEW増加推移を表示します。</p></article>}<Donut {...reaction}/><Compare c={comparison}/><ArticleBars rows={data?.topArticles||[]} metric={metric} onMetric={setMetric}/></div><div className="mia3-fallback"><b>スクショ取込について</b><p>通常は不要です。API直接取得の方が正確です。note側の統計API仕様が変わった時だけ、スクショ取込を予備機能として使う設計にします。</p></div></section>}
