import { useEffect, useMemo, useState } from "react";
import { FavoriteReader } from "./favorite-reader";
import { INSIGHT_TOKEN_KEY, setAccessIntent } from "./insight-account-store";
import "./member-insight-unified.css";

const HISTORY="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-history";
const MEMBER="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-api";
const OWNER_KEY="mumei-unified-owner-token";
const PAGE=100;
type Row=Record<string,any>;
type Tab="overview"|"likes"|"supporters"|"comments"|"commentRanking"|"magazines"|"favorites"|"social"|"notifications"|"articles";
type Summary={member:{noteId:string;displayName:string;imageUrl:string|null};summary:Record<string,any>;analysis:Record<string,any>;counts:{comments:number;followers:number;followings:number;notifications:number};articles:Row[]};

async function hist(action:string,extra:Record<string,unknown>={}){
 const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");
 const c=new AbortController(),timer=window.setTimeout(()=>c.abort(),25000);
 try{const r=await fetch(HISTORY,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify({action,...extra}),cache:"no-store",signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"INSIGHT_API_ERROR");return p}finally{clearTimeout(timer)}
}
const n=(v:any)=>new Intl.NumberFormat("ja-JP").format(Number(v||0));
const date=(v:any,withTime=true)=>{if(!v)return"—";const d=new Date(String(v));if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat("ja-JP",withTime?{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}:{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric"}).format(d)};
const isoDay=(v:string)=>v?`${v}T00:00:00+09:00`:null;
function nextDay(v:string){if(!v)return null;const d=new Date(`${v}T00:00:00+09:00`);return new Date(d.getTime()+86400000).toISOString()}
function monthRange(v:string){if(!v)return{dateFrom:null,dateTo:null};const[y,m]=v.split("-").map(Number),ny=m===12?y+1:y,nm=m===12?1:m+1;return{dateFrom:`${v}-01T00:00:00+09:00`,dateTo:`${ny}-${String(nm).padStart(2,"0")}-01T00:00:00+09:00`}}
function yearRange(v:string){const y=Number(v);return Number.isFinite(y)?{dateFrom:`${y}-01-01T00:00:00+09:00`,dateTo:`${y+1}-01-01T00:00:00+09:00`}:{dateFrom:null,dateTo:null}}
function Avatar({name,image}:{name:string;image?:string|null}){return image?<img className="miu-avatar" src={image} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer"/>:<span className="miu-avatar fallback">{[...String(name||"n")][0]}</span>}
function Person({row}:{row:Row}){const name=row.actor_name||row.name||"noteユーザー",url=row.actor_url||row.url,image=row.actor_image_url||row.image;return <span className="miu-person"><Avatar name={name} image={image}/><span><b>{name}</b>{url?<a href={url} target="_blank" rel="noreferrer">プロフィール ↗</a>:null}</span></span>}
function Pager({page,total,onPage}:{page:number;total:number;onPage:(x:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE));if(pages<=1)return null;return <div className="miu-pager"><button disabled={page<=1} onClick={()=>onPage(page-1)}>←</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>onPage(page+1)}>→</button></div>}
function SectionHead({k,title,count,children}:{k:string;title:string;count?:string;children?:React.ReactNode}){return <header className="miu-section-head"><div><small>{k}</small><h2>{title}</h2></div><div>{count?<strong>{count}</strong>:null}{children}</div></header>}

function FavoriteStar({row,onChange}:{row:Row;onChange:(favorite:boolean)=>void}){const[busy,setBusy]=useState(false);async function toggle(){if(busy)return;setBusy(true);try{const favorite=!Boolean(row.favorite);await hist("favorite_toggle",{creatorKey:String(row.liker_key||row.actor_key||row.creator_key||""),actorName:row.actor_name,actorUrl:row.actor_url,actorImageUrl:row.actor_image_url,favorite});onChange(favorite)}finally{setBusy(false)}}return <button className={`miu-star ${row.favorite?"active":""}`} disabled={busy} onClick={()=>void toggle()} aria-label={row.favorite?"お気に入り解除":"お気に入り登録"}>{row.favorite?"★":"☆"}</button>}

function Overview({data,onTab,revision}:{data:Summary;onTab:(t:Tab)=>void;revision:number}){
 const[supporters,setSupporters]=useState<Row[]>([]),[comments,setComments]=useState<Row[]>([]);
 useEffect(()=>{void Promise.all([hist("supporters",{page:1,pageSize:12}),hist("comment_ranking",{page:1,pageSize:8})]).then(([a,b])=>{setSupporters(a.rows||[]);setComments(b.rows||[])}).catch(()=>{})},[revision]);
 const recent=(data.articles||[]).slice(0,8);
 return <div className="miu-overview">
  <section className="miu-panel wide"><SectionHead k="TOP SUPPORTERS" title="よくスキしてくれる人" count={`${n(data.summary.supporterCount||data.analysis.uniqueSupporters)}人`}/><div className="miu-face-strip">{supporters.map((r,i)=><button key={r.liker_key||i} onClick={()=>onTab("supporters")}><Avatar name={r.actor_name} image={r.actor_image_url}/><span><b>{i+1}位</b><small>{r.actor_name}</small><em>♡ {n(r.like_count)}</em></span></button>)}</div>{!supporters.length?<p className="miu-empty">集計中…</p>:null}</section>
  <section className="miu-panel"><SectionHead k="COMMENT RANKING" title="コメント上位"/><div className="miu-mini-ranks">{comments.slice(0,5).map((r,i)=><button key={r.actor_key||i} onClick={()=>onTab("commentRanking")}><em>{i+1}</em><Avatar name={r.actor_name} image={r.actor_image_url}/><span><b>{r.actor_name}</b><small>初手 {n(r.initial_comment_count)}件</small></span></button>)}</div></section>
  <section className="miu-panel"><SectionHead k="QUICK ACCESS" title="すぐ確認"/><div className="miu-quick"><button onClick={()=>onTab("likes")}>♡ スキ履歴 <b>{n(data.summary.identifiedLikeCount)}</b></button><button onClick={()=>onTab("comments")}>💬 コメント <b>{n(data.counts.comments)}</b></button><button onClick={()=>onTab("magazines")}>▣ マガジン</button><button onClick={()=>onTab("favorites")}>★ お気に入り</button></div></section>
  <section className="miu-panel wide"><SectionHead k="ARTICLE ARCHIVE" title="最近の記事" count={`${n(data.articles.length)}件`}><button className="miu-textbtn" onClick={()=>onTab("articles")}>過去記事を探す →</button></SectionHead><div className="miu-article-grid compact">{recent.map(r=><a key={r.article_key} href={r.url} target="_blank" rel="noreferrer"><time>{date(r.publish_at,false)}</time><b>{r.title}</b><span>♡ {n(r.like_count)}　💬 {n(r.comment_count)}</span></a>)}</div></section>
 </div>
}

function Likes({revision}:{revision:number}){
 const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState("all"),[scope,setScope]=useState("all"),[day,setDay]=useState(""),[month,setMonth]=useState(""),[year,setYear]=useState(String(new Date().getFullYear())),[sort,setSort]=useState("newest"),[draft,setDraft]=useState(""),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const range=useMemo(()=>scope==="day"?{dateFrom:isoDay(day),dateTo:nextDay(day)}:scope==="month"?monthRange(month):scope==="year"?yearRange(year):{dateFrom:null,dateTo:null},[scope,day,month,year]);
 async function load(p=1){setLoading(true);setError("");try{const x=await hist("likes",{page:p,pageSize:PAGE,status,sort,query,...range});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p)}catch(e){setError(e instanceof Error?e.message:"読込失敗")}finally{setLoading(false)}}
 useEffect(()=>{void load(1)},[status,scope,day,month,year,sort,query,revision]);
 return <section className="miu-panel"><SectionHead k="LIKE HISTORY" title="スキ全履歴" count={`${n(total)}件`}/><div className="miu-tabs">{[["all","すべて"],["pending","未対応"],["completed","対応済み"]].map(x=><button key={x[0]} className={status===x[0]?"active":""} onClick={()=>setStatus(x[0])}>{x[1]}</button>)}</div><div className="miu-tools"><div className="miu-tabs mini">{[["all","全期間"],["day","日ごと"],["month","月ごと"],["year","年ごと"]].map(x=><button key={x[0]} className={scope===x[0]?"active":""} onClick={()=>setScope(x[0])}>{x[1]}</button>)}</div>{scope==="day"?<input type="date" value={day} onChange={e=>setDay(e.target.value)}/>:scope==="month"?<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>:scope==="year"?<input type="number" value={year} onChange={e=>setYear(e.target.value)}/>:null}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">新しい順</option><option value="oldest">古い順</option><option value="name">名前順</option></select><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="名前・ID・記事" onKeyDown={e=>{if(e.key==="Enter")setQuery(draft)}}/><button onClick={()=>setQuery(draft)}>検索</button></div>{error?<p className="miu-error">{error}</p>:loading?<p className="miu-empty">履歴を読み込み中…</p>:<div className="miu-card-grid">{rows.map(r=><article className="miu-like" key={`${r.article_key}:${r.liker_key}`}><div><Person row={r}/><FavoriteStar row={r} onChange={favorite=>setRows(v=>v.map(x=>x===r?{...x,favorite}:x))}/></div><a href={r.article_url} target="_blank" rel="noreferrer">{r.article_title}</a><time>{date(r.liked_at)}</time></article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>
}

function Supporters({revision}:{revision:number}){const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[open,setOpen]=useState<string|null>(null),[articles,setArticles]=useState<Record<string,Row[]>>({}),[loading,setLoading]=useState(true);async function load(p=1){setLoading(true);const x=await hist("supporters",{page:p,pageSize:PAGE});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p);setLoading(false)}useEffect(()=>{void load(1)},[revision]);async function toggle(r:Row){const k=String(r.liker_key);if(open===k){setOpen(null);return}setOpen(k);if(articles[k])return;const x=await hist("supporter_articles",{likerKey:k,page:1,pageSize:100});setArticles(v=>({...v,[k]:x.rows||[]}))}return <section className="miu-panel"><SectionHead k="SUPPORTER RANKING" title="全記事スキランキング" count={`${n(total)}人`}/>{loading?<p className="miu-empty">集計中…</p>:<div className="miu-rank-list">{rows.map((r,i)=><article key={r.liker_key}><div className="miu-rank-row"><em>{(page-1)*PAGE+i+1}</em><Person row={r}/><FavoriteStar row={r} onChange={favorite=>setRows(v=>v.map(x=>x===r?{...x,favorite}:x))}/><button onClick={()=>void toggle(r)}><b>{n(r.like_count)}</b><small>記事</small></button></div>{open===String(r.liker_key)?<div className="miu-expand">{(articles[String(r.liker_key)]||[]).map(a=><a key={a.article_key} href={a.url||a.article_url} target="_blank" rel="noreferrer"><span>{a.title||a.article_title}</span><time>{date(a.liked_at,false)}</time></a>)}</div>:null}</article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function commentState(r:Row,filter:string){if(filter==="heart_closed"||(r.heart_on_last_external&&(r.status==="unreplied"||r.status==="followup_pending")))return{key:"heart_closed",label:"♡で終了"};if(r.status==="unreplied")return{key:"unreplied",label:"未返信"};if(r.status==="followup_pending")return{key:"followup_pending",label:"相手の返信で停止"};if(r.status==="replied")return{key:"replied",label:"自分の返信で終了"};return{key:String(r.status||""),label:String(r.status||"")}}
function Comments({revision}:{revision:number}){const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState("all"),[detail,setDetail]=useState<Record<string,Row[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState("");async function load(p=1){setLoading(true);setError("");try{const x=await hist("comments",{page:p,pageSize:PAGE,status});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p)}catch(e){setError(e instanceof Error?e.message:"読込失敗")}finally{setLoading(false)}}async function open(k:string){if(detail[k])return;const x=await hist("comment_thread",{rootKey:k});setDetail(v=>({...v,[k]:x.rows||[]}))}useEffect(()=>{setDetail({});void load(1)},[status,revision]);return <section className="miu-panel"><SectionHead k="COMMENT HISTORY" title="コメント・返信履歴" count={`${n(total)}件`}/><div className="miu-tabs scroll">{[["all","すべて"],["pending","要対応"],["unreplied","未返信"],["followup_pending","相手返信"],["heart_closed","♡で終了"],["replied","自分返信"]].map(x=><button key={x[0]} className={status===x[0]?"active":""} onClick={()=>setStatus(x[0])}>{x[1]}</button>)}</div>{error?<p className="miu-error">{error}</p>:loading?<p className="miu-empty">履歴を読み込み中…</p>:<div className="miu-comment-list">{rows.map(r=>{const s=commentState(r,status);return <details key={r.root_key} onToggle={e=>{if((e.currentTarget as HTMLDetailsElement).open)void open(r.root_key)}}><summary><Person row={r}/><span className={`miu-state ${s.key}`}>{s.label}</span><p>{String(r.root_body||"").slice(0,120)}</p><a href={r.article_url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{r.article_title}</a><time>{date(r.last_at||r.root_at)}</time></summary><div className="miu-thread">{detail[r.root_key]?.map(m=><article key={m.comment_key} className={m.is_creator?"mine":""}><b>{m.is_creator?"あなた":m.actor_name}</b><small>{date(m.occurred_at)}</small><p>{m.body}</p></article>)||<p>会話を読み込み中…</p>}</div></details>})}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function CommentRanking({revision}:{revision:number}){const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[open,setOpen]=useState<string|null>(null),[comments,setComments]=useState<Record<string,Row[]>>({}),[loading,setLoading]=useState(true);async function load(p=1){setLoading(true);const x=await hist("comment_ranking",{page:p,pageSize:PAGE});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p);setLoading(false)}useEffect(()=>{void load(1)},[revision]);async function toggle(r:Row){const k=String(r.actor_key);if(open===k){setOpen(null);return}setOpen(k);if(comments[k])return;const x=await hist("commenter_comments",{actorKey:k,page:1,pageSize:100});setComments(v=>({...v,[k]:x.rows||[]}))}return <section className="miu-panel"><SectionHead k="COMMENT RANKING" title="初手コメント順位" count={`${n(total)}人`}/>{loading?<p className="miu-empty">集計中…</p>:<div className="miu-rank-list">{rows.map((r,i)=><article key={r.actor_key}><div className="miu-rank-row"><em>{(page-1)*PAGE+i+1}</em><Person row={r}/><button onClick={()=>void toggle(r)}><b>{n(r.initial_comment_count)}</b><small>初手</small></button></div><small className="miu-rank-sub">{n(r.article_count)}記事・最終 {date(r.last_comment_at)}</small>{open===String(r.actor_key)?<div className="miu-expand">{(comments[String(r.actor_key)]||[]).map(c=><a key={c.root_key||c.comment_key} href={c.article_url} target="_blank" rel="noreferrer"><span><b>{c.article_title}</b><small>{String(c.body||"").slice(0,90)}</small></span><time>{date(c.occurred_at,false)}</time></a>)}</div>:null}</article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Magazines({revision}:{revision:number}){const[rows,setRows]=useState<Row[]>([]),[refreshed,setRefreshed]=useState<string|null>(null),[mode,setMode]=useState("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{setLoading(true);void hist("magazines").then(x=>{setRows(x.rows||[]);setRefreshed(x.refreshedAt||null)}).catch(()=>setRows([])).finally(()=>setLoading(false))},[revision]);const visible=useMemo(()=>rows.filter(r=>{const ownerId=String(r.owner?.urlname||r.owner?.id||"").toLowerCase(),me=String(r.meNoteId||"").toLowerCase();if(mode==="owner"&&ownerId!==me)return false;if(mode==="member"&&ownerId===me)return false;const q=query.trim().toLowerCase();return !q||String(r.title||"").toLowerCase().includes(q)||ownerId.includes(q)}),[rows,mode,query]);return <section className="miu-panel"><SectionHead k="MAGAZINES" title="共同マガジン" count={`${n(rows.length)}誌`}/><div className="miu-tools"><div className="miu-tabs"><button className={mode==="all"?"active":""} onClick={()=>setMode("all")}>すべて</button><button className={mode==="owner"?"active":""} onClick={()=>setMode("owner")}>自分がオーナー</button><button className={mode==="member"?"active":""} onClick={()=>setMode("member")}>参加中</button></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="マガジン名・オーナー"/></div>{refreshed?<p className="miu-source">最終同期 {date(refreshed)}</p>:null}{loading?<p className="miu-empty">マガジンを読み込み中…</p>:visible.length?<div className="miu-mag-grid">{visible.map(r=><article key={r.key||r.url}><div><b>{r.title||"共同マガジン"}</b><small>{r.owner?.nickname||r.owner?.urlname||"オーナー不明"}</small></div><div className="miu-member-faces">{(r.members||[]).slice(0,6).map((m:any,i:number)=><Avatar key={m.id||i} name={m.nickname||m.urlname||"n"} image={m.profileImageUrl}/>)}</div><a href={r.url} target="_blank" rel="noreferrer">noteで開く ↗</a></article>)}</div>:<p className="miu-empty">このアカウントのマガジン保存データはまだありません。</p>}</section>}

function Favorites({revision}:{revision:number}){const owner=Boolean(localStorage.getItem(OWNER_KEY));const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{if(owner)return;setLoading(true);void hist("favorites").then(x=>setRows(x.rows||[])).finally(()=>setLoading(false))},[revision,owner]);if(owner)return <section className="miu-panel favorite"><SectionHead k="FAVORITE READER" title="お気に入り・記事Reader"/><FavoriteReader/></section>;return <section className="miu-panel"><SectionHead k="FAVORITES" title="お気に入り" count={`${n(rows.length)}人`}/>{loading?<p className="miu-empty">読み込み中…</p>:<div className="miu-favorite-grid">{rows.map(r=><article key={r.creator_key}><Person row={{actor_name:r.actor_name,actor_url:r.actor_url,actor_image_url:r.actor_image_url}}/><a href={r.actor_url} target="_blank" rel="noreferrer">プロフィール ↗</a></article>)}</div>}</section>}

function Social({revision}:{revision:number}){const[direction,setDirection]=useState("followers"),[mode,setMode]=useState("current"),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true);async function load(p=1){setLoading(true);const x=await hist(mode==="current"?"social":"changes",{page:p,pageSize:PAGE,direction,change:"all"});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p);setLoading(false)}useEffect(()=>{void load(1)},[direction,mode,revision]);return <section className="miu-panel"><SectionHead k="SOCIAL HISTORY" title="フォロー・フォロワー" count={`${n(total)}件`}/><div className="miu-tabs"><button className={direction==="followers"?"active":""} onClick={()=>setDirection("followers")}>フォロワー</button><button className={direction==="followings"?"active":""} onClick={()=>setDirection("followings")}>フォロー中</button><button className={mode==="changes"?"active":""} onClick={()=>setMode(mode==="changes"?"current":"changes")}>増減履歴</button></div>{loading?<p className="miu-empty">履歴を読み込み中…</p>:<div className="miu-card-grid">{rows.map((r,i)=><article className="miu-social" key={r.id||r.person_key||i}><Person row={r}/>{mode==="changes"?<b className={r.event_type==="removed"?"removed":"added"}>{r.event_type==="removed"?"減少":"追加"}</b>:null}<time>{date(r.detected_at||r.last_seen_at)}</time></article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Notifications({revision}:{revision:number}){const[kind,setKind]=useState("all"),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true);async function load(p=1){setLoading(true);const x=await hist("notifications",{page:p,pageSize:PAGE,kind});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p);setLoading(false)}useEffect(()=>{void load(1)},[kind,revision]);const tabs=[["all","すべて"],["reply","返信"],["comment","コメント"],["like","スキ"],["follow","フォロー"],["purchase","購入"],["tip","チップ"],["magazine","マガジン"]];return <section className="miu-panel"><SectionHead k="NOTIFICATIONS" title="本人通知・反応履歴" count={`${n(total)}件`}><a className="miu-setup" href="./notification-setup.html?from=insight&role=member" target="_blank" rel="noopener noreferrer">通知同期を設定</a></SectionHead><div className="miu-tabs scroll">{tabs.map(x=><button key={x[0]} className={kind===x[0]?"active":""} onClick={()=>setKind(x[0])}>{x[1]}</button>)}</div>{loading?<p className="miu-empty">通知履歴を読み込み中…</p>:<div className="miu-notice-list">{rows.map(r=><article key={`${r.member_id}:${r.id}`}><span>{r.notification_type}</span><b>{r.raw_text||r.target_title||"通知"}</b>{r.actor_name?<small>{r.actor_name}</small>:null}<time>{date(r.occurred_at||r.captured_at)}</time></article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Articles({data}:{data:Summary}){const[query,setQuery]=useState(""),[month,setMonth]=useState("all"),[sort,setSort]=useState("newest");const months=useMemo(()=>[...new Set((data.articles||[]).map(r=>String(r.publish_at||"").slice(0,7)).filter(Boolean))].sort().reverse(),[data.articles]);const visible=useMemo(()=>{const q=query.trim().toLowerCase();return [...(data.articles||[])].filter(r=>(month==="all"||String(r.publish_at||"").startsWith(month))&&(!q||String(r.title||"").toLowerCase().includes(q))).sort((a,b)=>(sort==="oldest"?1:-1)*(new Date(a.publish_at||0).getTime()-new Date(b.publish_at||0).getTime()))},[data.articles,query,month,sort]);return <section className="miu-panel"><SectionHead k="ARTICLE ARCHIVE" title="自分の記事・過去アーカイブ" count={`${n(visible.length)}件`}/><div className="miu-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="記事タイトルを検索"/><select value={month} onChange={e=>setMonth(e.target.value)}><option value="all">全期間</option>{months.map(m=><option value={m} key={m}>{m.replace("-","年")}月</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">新しい順</option><option value="oldest">古い順</option></select></div><div className="miu-article-grid">{visible.map(r=><a key={r.article_key} href={r.url} target="_blank" rel="noreferrer"><time>{date(r.publish_at,false)}</time><b>{r.title}</b><span>♡ {n(r.like_count)}　💬 {n(r.comment_count)}</span></a>)}</div></section>}

export function MemberInsightUnified({revision=0}:{revision?:number}){
 const[data,setData]=useState<Summary|null>(null),[tab,setTab]=useState<Tab>("overview"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[syncing,setSyncing]=useState(false);
 async function load(){setError("");try{setData(await hist("summary"))}catch(e){const msg=e instanceof Error?e.message:"INSIGHT_API_ERROR";if(/LOGIN|SESSION|INACTIVE/.test(msg)){localStorage.removeItem(INSIGHT_TOKEN_KEY);location.hash="access/insight";return}setError(msg)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[revision]);
 async function sync(){setSyncing(true);setError("");try{const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";const r=await fetch(MEMBER,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify({action:"sync"}),cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"同期失敗");await load()}catch(e){setError(e instanceof Error?e.message:"同期失敗")}finally{setSyncing(false)}}
 function switchAccount(){setAccessIntent("switch");location.hash="access/insight"}
 if(loading)return <div className="miu-loading">INSIGHT全履歴を読み込んでいます…</div>;
 if(!data)return <div className="miu-loading"><p>{error||"読み込めませんでした"}</p><button onClick={()=>{setLoading(true);void load()}}>再読込</button></div>;
 const s=data.summary||{},a=data.analysis||{};
 const nav:[Tab,string][]=[["overview","概要"],["likes","スキ履歴"],["supporters","スキ順位"],["comments","コメント"],["commentRanking","コメント順位"],["magazines","マガジン"],["favorites","お気に入り"],["social","フォロー"],["notifications","通知"],["articles","記事"]];
 return <div className="miu"><main><header className="miu-top"><Avatar name={data.member.displayName} image={data.member.imageUrl}/><div><small>MY NOTE INSIGHT</small><h1>{data.member.displayName}</h1><a href={`https://note.com/${data.member.noteId}`} target="_blank" rel="noreferrer">@{data.member.noteId} ↗</a></div><div className="miu-topactions"><button onClick={switchAccount}>アカウント切替</button><button className="sync" disabled={syncing} onClick={()=>void sync()}>{syncing?"更新中…":"データ更新"}</button></div></header>{error?<p className="miu-error">{error}</p>:null}<div className="miu-stats"><button onClick={()=>setTab("articles")}><small>記事</small><strong>{n(s.articleCount||data.articles.length)}</strong></button><button onClick={()=>setTab("likes")}><small>保存スキ</small><strong>{n(s.identifiedLikeCount)}</strong></button><button onClick={()=>setTab("supporters")}><small>スキした人数</small><strong>{n(s.supporterCount||a.uniqueSupporters)}</strong></button><button onClick={()=>setTab("comments")}><small>コメント</small><strong>{n(data.counts.comments)}</strong></button><button onClick={()=>setTab("social")}><small>フォロワー</small><strong>{n(data.counts.followers)}</strong></button><button onClick={()=>setTab("notifications")}><small>通知</small><strong>{n(data.counts.notifications)}</strong></button></div><nav className="miu-nav">{nav.map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>{tab==="overview"?<Overview data={data} onTab={setTab} revision={revision}/>:tab==="likes"?<Likes revision={revision}/>:tab==="supporters"?<Supporters revision={revision}/>:tab==="comments"?<Comments revision={revision}/>:tab==="commentRanking"?<CommentRanking revision={revision}/>:tab==="magazines"?<Magazines revision={revision}/>:tab==="favorites"?<Favorites revision={revision}/>:tab==="social"?<Social revision={revision}/>:tab==="notifications"?<Notifications revision={revision}/>:<Articles data={data}/>}</main></div>
}
