import { useEffect, useMemo, useState } from "react";
import { INSIGHT_TOKEN_KEY } from "./insight-account-store";
import "./member-insight-notifications-final.css";

const HISTORY="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-history";
const PAGE=100;
type Row=Record<string,any>;
const CATS=[
 ["all","すべて"],["like","スキ"],["comment_like","コメント♡"],["comment","コメント"],["reply","返信"],
 ["follow","フォロー"],["magazine_follow","マガジンフォロー"],["my_article_magazine_added","自分の記事追加"],
 ["magazine_article_added","マガジン記事追加"],["magazine_join","マガジン参加"],["membership_board","メンシプ掲示板"],
 ["membership_started","メンシプ開始"],["membership_plan","プラン追加"],["membership_join","メンシプ参加"],
 ["purchase","購入"],["tip","サポート"],["buzz","話題"],["rating","高評価"],["points","ポイント"],["other","その他"]
] as const;
const LABEL:Record<string,string>=Object.fromEntries(CATS);
async function post(body:Record<string,unknown>){const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");const c=new AbortController(),timer=window.setTimeout(()=>c.abort(),45000);try{const r=await fetch(HISTORY,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify(body),cache:"no-store",signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"INSIGHT_API_ERROR");return p}finally{clearTimeout(timer)}}
const date=(v:any)=>{if(!v)return"—";const d=new Date(String(v));if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
const canonical=(v:any)=>String(v||"").replace(/\s+/g," ").replace(/\s(?:たった今|昨日|\d+\s*(?:秒|分|時間|日|週|か月|ヶ月|月|年)前)$/u,"").trim();
function actorName(r:Row){if(r.actor_name)return String(r.actor_name);const m=canonical(r.raw_text).match(/^(.{1,120}?)\s*さん(?:他\d+名)?(?:が|の)/u);return m?.[1]?.trim()||""}
function mainText(r:Row){const raw=canonical(r.raw_text);if(r.notification_type==="my_article_magazine_added")return `📚 ${raw}`;if(r.notification_type==="magazine_article_added")return `📚 ${raw}`;if(r.notification_type==="magazine_join")return `👥 ${raw}`;if(r.notification_type==="magazine_follow")return `＋ ${raw}`;if(r.notification_type==="membership_board")return `📌 ${raw}`;if(r.notification_type==="membership_started")return `🚀 ${raw}`;if(r.notification_type==="membership_plan")return `🧩 ${raw}`;return raw}
function targetHref(r:Row){return String(r.target_url||r.source_url||r.actor_url||"")}
function targetLabel(r:Row){const u=String(r.target_url||"");if(/\/m\//.test(u))return"対象マガジンを開く ↗";if(/\/n\//.test(u))return"対象記事を開く ↗";return u?"対象ページを開く ↗":r.actor_url?"相手ページを開く ↗":""}
function rowKey(r:Row){return `${r.notification_type}|${canonical(r.raw_text)}|${String(r.actor_url||"").split("?")[0]}|${String(r.target_url||"").split("?")[0]}|${Math.floor(Date.parse(r.occurred_at||r.captured_at||0)/60000)}`}
export function MemberInsightNotificationsFinal({revision=0}:{revision?:number}){const[rows,setRows]=useState<Row[]>([]),[kind,setKind]=useState("all"),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");async function load(p=1,k=kind){setLoading(true);setError("");try{const x=await post({action:"notifications",kind:k,page:p,pageSize:PAGE}),seen=new Set<string>(),list:Row[]=[];for(const r of x.rows||[]){const key=rowKey(r);if(seen.has(key))continue;seen.add(key);list.push(r)}setRows(list);setTotal(Number(x.total||0));setPage(p)}catch(e){setError(e instanceof Error?e.message:"通知履歴の読込に失敗しました")}finally{setLoading(false)}}useEffect(()=>{void load(1,kind)},[kind,revision]);const pages=Math.max(1,Math.ceil(total/PAGE));const categoryCounts=useMemo(()=>{const m:Record<string,number>={};for(const r of rows)m[String(r.notification_type||"other")]=(m[String(r.notification_type||"other")]||0)+1;return m},[rows]);return <section id="minf-notifications" className="minf"><header className="minf-head"><div><small>NOTIFICATION HISTORY</small><h2>本人通知</h2><p>人物フォロー、マガジンフォロー、記事追加、参加、メンバーシップ系を別分類で表示します。</p></div></header><div className="minf-tabs" role="tablist">{CATS.map(([id,label])=><button key={id} className={kind===id?"active":""} onClick={()=>setKind(id)}>{label}{kind==="all"&&id!=="all"&&categoryCounts[id]?<small>{categoryCounts[id]}</small>:null}</button>)}</div>{error?<p className="minf-error">{error}</p>:null}{loading&&!rows.length?<p className="minf-empty">通知を読み込み中…</p>:rows.length?<div className="minf-list">{rows.map((r,i)=>{const href=targetHref(r),actor=actorName(r),label=LABEL[String(r.notification_type||"other")]||"その他";return <article key={r.id||i} className={`type-${String(r.notification_type||"other")}`}><div className="minf-meta"><span>{label}</span><time>{date(r.occurred_at||r.captured_at)}</time></div>{actor?<a className="minf-actor" href={r.actor_url||href||"#"} target="_blank" rel="noreferrer">{actor}</a>:null}{href?<a className="minf-main" href={href} target="_blank" rel="noreferrer">{mainText(r)}</a>:<div className="minf-main static">{mainText(r)}</div>}{targetLabel(r)&&href?<a className="minf-target" href={href} target="_blank" rel="noreferrer">{targetLabel(r)}</a>:null}</article>})}</div>:<p className="minf-empty">この分類の通知はありません。</p>}{pages>1?<div className="minf-pager"><button disabled={page<=1||loading} onClick={()=>void load(page-1)}>← 前</button><span>{page} / {pages}</span><button disabled={page>=pages||loading} onClick={()=>void load(page+1)}>次 →</button></div>:null}{kind==="other"?<p className="minf-other-note">「その他」は既知の通知分類に一致しなかったものだけです。ここに既知通知が入った場合は分類漏れとして修正対象になります。</p>:null}</section>}
