import { useEffect, useState } from "react";
import { INSIGHT_TOKEN_KEY } from "./insight-account-store";
import "./member-insight-completeness.css";

const ENDPOINT="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-data-completeness";
type Row=Record<string,any>;
const n=(v:any)=>new Intl.NumberFormat("ja-JP").format(Number(v||0));
const date=(v:any)=>{if(!v)return"—";const d=new Date(String(v));if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
async function load(){const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");const c=new AbortController(),timer=window.setTimeout(()=>c.abort(),30000);try{const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:"{}",cache:"no-store",signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"取得状態を確認できませんでした");return p}finally{window.clearTimeout(timer)}}
function jump(label:string){const buttons=[...document.querySelectorAll<HTMLButtonElement>(".miu-nav button")];const b=buttons.find(x=>x.textContent?.trim()===label);if(b)b.click();window.setTimeout(()=>document.querySelector<HTMLElement>(".miu")?.scrollIntoView({block:"start",behavior:"auto"}),60)}
function pick(items:Row[],pattern:RegExp){return items.find(x=>pattern.test(String(x.label||"")))||null}
export function MemberInsightCompleteness({revision=0}:{revision?:number}){const[data,setData]=useState<Row|null>(null),[error,setError]=useState("");useEffect(()=>{let dead=false;setError("");void load().then(x=>{if(!dead)setData(x)}).catch(e=>{if(!dead)setError(e instanceof Error?e.message:"取得状態の確認に失敗しました")});return()=>{dead=true}},[revision]);if(error)return <aside className="micmp error">取得状態：{error}</aside>;if(!data)return <aside className="micmp loading">公開データを照合中…</aside>;const items:Row[]=data.items||[],article=pick(items,/記事/),likes=pick(items,/スキ/),comments=pick(items,/コメント/),followers=pick(items,/フォロワー/),followings=pick(items,/フォロー中|フォロー(?!ワー)/);const shortcuts=[{label:"記事",value:article?.stored,tab:"記事"},{label:"スキ",value:likes?.stored,tab:"スキ履歴"},{label:"コメント",value:comments?.stored,tab:"コメント"},{label:"フォロワー",value:followers?.stored,tab:"フォロー"},{label:"フォロー",value:followings?.stored,tab:"フォロー"}];return <aside className={data.publicExact?"micmp exact":"micmp incomplete"}><header><b>{data.publicExact?"✓ 公開データ確認済み":"↻ 公開データ確認中"}</b><time>照合 {date(data.checkedAt)}</time></header><div className="micmp-shortcuts">{shortcuts.map(x=><button key={x.label} onClick={()=>jump(x.tab)}><span>{x.label}</span><b>{n(x.value)}</b></button>)}</div></aside>}
