import { useId, useState } from 'react';
export function InsightColumns({items,label,unit='件'}:{items:{label:string;value:number|null;sub?:string}[];label:string;unit?:string}){
 const id=useId().replace(/:/g,''),[focus,setFocus]=useState<number|null>(null),values=items.filter(x=>x.value!=null),max=Math.max(1,...values.map(x=>x.value!)),left=52,right=432,top=24,bottom=206,step=(right-left)/Math.max(1,items.length),width=Math.min(36,step*.64),x=(i:number)=>left+step*(i+.5),y=(v:number)=>bottom-v/max*(bottom-top),active=focus==null?null:items[focus];
 return <figure className="insight-columns"><figcaption><strong>{label}</strong><small>縦軸：{unit} · 棒をタップして詳細</small></figcaption><svg viewBox="0 0 454 248" role="img" aria-label={label}>
  <defs><linearGradient id={id+'bar'} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#d2fbff"/><stop offset=".18" stopColor="#41d9f0"/><stop offset=".8" stopColor="#107cab"/><stop offset="1" stopColor="#063f61"/></linearGradient><linearGradient id={id+'peak'} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#f1ffd2"/><stop offset=".2" stopColor="#b7f852"/><stop offset="1" stopColor="#48872b"/></linearGradient></defs>
  {[0,.5,1].map(t=><g key={t}><line x1={left} x2={right} y1={y(max*t)} y2={y(max*t)} stroke="#36576a" strokeDasharray={t?'3 5':undefined}/><text x={left-8} y={y(max*t)+4} textAnchor="end" fill="#b0c8d6" fontSize="12">{Math.round(max*t).toLocaleString()}</text></g>)}
  {items.map((r,i)=><g key={r.label} role="button" tabIndex={0} aria-label={`${r.label} ${r.value==null?'未取得':r.value.toLocaleString()+unit}${r.sub?' '+r.sub:''}`} onClick={()=>setFocus(i)} onFocus={()=>setFocus(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setFocus(i)}}} className={focus===i?'selected':''}>
   <rect x={x(i)-step/2} y={top} width={step} height={bottom-top+24} fill="#ffffff" fillOpacity="0"/>
   {r.value==null?<text x={x(i)} y={bottom-8} textAnchor="middle" fill="#9eb5c3" fontSize="16">—</text>:r.value===0?<line x1={x(i)-width/2} x2={x(i)+width/2} y1={bottom} y2={bottom} stroke="#8bf0ff" strokeWidth="3"/>:<><rect x={x(i)-width/2+3} y={y(r.value)+4} width={width} height={bottom-y(r.value)} rx="3" fill="#041827"/><rect x={x(i)-width/2} y={y(r.value)} width={width} height={bottom-y(r.value)} rx="3" fill={`url(#${id+(r.value===max?'peak':'bar')})`}/><path d={`M${x(i)-width/2+2} ${y(r.value)+3}h${width-4}`} stroke="#fff" strokeOpacity=".7" strokeWidth="2"/></>}
   {(items.length<=7||i%2===0||i===items.length-1)?<text x={x(i)} y="228" fill="#c2dbe5" textAnchor="middle" fontSize="12">{r.label}</text>:null}
   <title>{`${r.label}：${r.value==null?'未取得':r.value.toLocaleString()+unit}`}</title>
  </g>)}
 </svg><p className="insight-chart-readout" aria-live="polite">{active?<><span>{active.label} {active.sub||''}</span><b>{active.value==null?'未取得':active.value.toLocaleString(undefined,{maximumFractionDigits:1})+' '+unit}</b></>:<><span>取得済み {values.length} / {items.length}項目</span><b>{values.length?'ピーク '+max.toLocaleString(undefined,{maximumFractionDigits:1})+' '+unit:'未取得'}</b></>}</p></figure>
}
export function InsightScatter({items}:{items:{date:string;notif:number;pv:number}[]}){
 const[focus,setFocus]=useState<number|null>(null),maxN=Math.max(1,...items.map(x=>x.notif)),maxP=Math.max(1,...items.map(x=>x.pv)),picked=focus==null?null:items[focus];
 return <figure className="insight-columns"><figcaption><strong>通知とPVの関係</strong><small>点＝1日 · タップで日付と実績</small></figcaption><svg viewBox="0 0 454 262" role="img" aria-label="横軸は保存通知件数、縦軸は公式PV">
 {[0,.5,1].map(t=><g key={t}><line x1="58" x2="428" y1={210-t*182} y2={210-t*182} stroke="#36576a" strokeDasharray="3 5"/><text x="49" y={214-t*182} fill="#b0c8d6" textAnchor="end" fontSize="12">{Math.round(maxP*t).toLocaleString()}</text><text x={58+t*370} y="232" fill="#b0c8d6" textAnchor="middle" fontSize="12">{Math.round(maxN*t).toLocaleString()}</text></g>)}
 <text x="58" y="15" fill="#aeeaff" fontSize="12">公式PV</text><text x="243" y="254" fill="#aeeaff" textAnchor="middle" fontSize="12">保存通知（件）</text>
 {items.map((r,i)=><g key={r.date} role="button" tabIndex={0} aria-label={`${r.date} 通知${r.notif}件 PV${r.pv}`} onClick={()=>setFocus(i)} onFocus={()=>setFocus(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setFocus(i)}}}><circle cx={58+r.notif/maxN*370} cy={210-r.pv/maxP*182} r="14" fill="#ffffff" fillOpacity="0"/><circle cx={58+r.notif/maxN*370} cy={210-r.pv/maxP*182} r={focus===i?7:5} fill={focus===i?'#cbff78':'#66ddf7'} fillOpacity={focus===i?1:.7} stroke="#dbffff" strokeWidth="1"/><title>{`${r.date} 通知${r.notif}件 / PV${r.pv}`}</title></g>)}
 </svg><p className="insight-chart-readout" aria-live="polite"><span>{picked?.date||`${items.length}日を照合`}</span><b>{picked?`通知 ${picked.notif.toLocaleString()}件 / ${picked.pv.toLocaleString()} PV`:'点を選択'}</b></p></figure>
}
