import { useEffect, useState } from "react";
import { INSIGHT_TOKEN_KEY } from "./insight-account-store";
import "./member-insight-completeness.css";

const ENDPOINT="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-data-completeness";
type Row=Record<string,any>;
const n=(v:any)=>new Intl.NumberFormat("ja-JP").format(Number(v||0));
const date=(v:any)=>{if(!v)return"—";const d=new Date(String(v));if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
async function load(){const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");const c=new AbortController(),timer=window.setTimeout(()=>c.abort(),30000);try{const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:"{}",cache:"no-store",signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"取得状態を確認できませんでした");return p}finally{window.clearTimeout(timer)}}
export function MemberInsightCompleteness({revision=0}:{revision?:number}){const[data,setData]=useState<Row|null>(null),[error,setError]=useState("");useEffect(()=>{let dead=false;setError("");void load().then(x=>{if(!dead)setData(x)}).catch(e=>{if(!dead)setError(e instanceof Error?e.message:"取得状態の確認に失敗しました")});return()=>{dead=true}},[revision]);if(error)return <aside className="micmp error">取得状態：{error}</aside>;if(!data)return <aside className="micmp loading">取得範囲を照合中…</aside>;return <aside className={data.publicExact?"micmp exact":"micmp incomplete"}><header><div><small>DATA COMPLETENESS</small><b>{data.publicExact?"✓ 公開データ全件一致":"再取得が必要な項目があります"}</b></div><time>照合 {date(data.checkedAt)}</time></header><div className="micmp-grid">{(data.items||[]).map((x:Row)=><div key={x.id} className={x.exact?"ok":"wait"}><span>{x.exact?"✓":"↻"} {x.label}</span><b>{n(x.stored)} / {n(x.expected)}</b><small>{x.detail}</small></div>)}</div><footer><span>通知 {data.notifications?.synced?`最終同期 ${date(data.notifications.lastSyncAt)}`:"未同期"}</span><span>ダッシュボード {data.dashboard?.available?`最終取得 ${date(data.dashboard.capturedAt)}`:"未取得"}</span></footer>{!data.publicExact?<p>不足している数値を完全値として扱いません。「データ更新」で再取得し、保存件数とnote側件数が一致した項目だけ完了表示にします。</p>:null}</aside>}
