import { useEffect, useMemo, useState } from "react";
import { INSIGHT_TOKEN_KEY } from "./insight-account-store";
import "./member-insight-favorites-final.css";

const HISTORY="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-history";
const EXTRAS="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-extras";
const GROUPS="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-favorite-groups";
type Row=Record<string,any>;
const clean=(v:any)=>String(v||"").replace(/\s+/g," ").trim().slice(0,40);
const date=(v:any)=>{const d=new Date(String(v||""));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric"}).format(d)};
async function post(endpoint:string,body:Record<string,unknown>){const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify(body),cache:"no-store"}),p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"INSIGHT_API_ERROR");return p}
function Avatar({row}:{row:Row}){const name=String(row.actor_name||"noteユーザー"),img=String(row.actor_image_url||"");return img?<img src={img} alt="" referrerPolicy="no-referrer" loading="lazy" decoding="async"/>:<span>{[...name][0]||"n"}</span>}
export function MemberInsightFavoritesFinal({revision=0}:{revision?:number}){
  const[rows,setRows]=useState<Row[]>([]),[groups,setGroups]=useState<string[]>([]),[assigned,setAssigned]=useState<Record<string,string>>({}),[filter,setFilter]=useState("all"),[newGroup,setNewGroup]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[open,setOpen]=useState<string|null>(null),[articles,setArticles]=useState<Record<string,Row[]>>({}),[articleLoading,setArticleLoading]=useState(false),[query,setQuery]=useState("");
  async function load(){setLoading(true);setError("");try{const[f,g]=await Promise.all([post(HISTORY,{action:"favorites",page:1,pageSize:100}),post(GROUPS,{action:"list"})]);setRows(Array.isArray(f?.rows)?f.rows:[]);setGroups((Array.isArray(g?.definitions)?g.definitions:[]).map((x:any)=>clean(x?.name)).filter(Boolean));setAssigned(Object.fromEntries((Array.isArray(g?.assignments)?g.assignments:[]).map((x:any)=>[String(x?.creatorKey||""),clean(x?.groupName)]).filter((x:any)=>x[0]&&x[1])))}catch(e){setError(e instanceof Error?e.message:"お気に入りを取得できませんでした")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[revision]);
  const counts=useMemo(()=>Object.fromEntries(groups.map(g=>[g,rows.filter(r=>assigned[String(r.creator_key)]===g).length])),[groups,rows,assigned]);
  const visible=useMemo(()=>rows.filter(r=>filter==="all"||(filter==="ungrouped"?!assigned[String(r.creator_key)]:assigned[String(r.creator_key)]===filter)),[rows,filter,assigned]);
  async function create(){const name=clean(newGroup);if(!name)return;setBusy("create");setError("");try{await post(GROUPS,{action:"create",name});if(!groups.includes(name))setGroups(v=>[...v,name]);setNewGroup("");setFilter(name)}catch(e){setError(e instanceof Error?e.message:"グループを作れませんでした")}finally{setBusy("")}}
  async function assign(r:Row,name:string){const key=String(r.creator_key),prev=assigned[key]||"",next=clean(name);setAssigned(v=>{const x={...v};if(next)x[key]=next;else delete x[key];return x});setBusy(`assign:${key}`);try{await post(GROUPS,{action:"assign",creatorKey:key,groupName:next||null});if(next&&!groups.includes(next))setGroups(v=>[...v,next])}catch(e){setAssigned(v=>{const x={...v};if(prev)x[key]=prev;else delete x[key];return x});setError(e instanceof Error?e.message:"グループ割当を保存できませんでした")}finally{setBusy("")}}
  async function rename(name:string){const to=clean(prompt("新しいグループ名",name)||"");if(!to||to===name)return;setBusy(`rename:${name}`);try{await post(GROUPS,{action:"rename",from:name,to});setGroups(v=>v.map(x=>x===name?to:x));setAssigned(v=>Object.fromEntries(Object.entries(v).map(([k,g])=>[k,g===name?to:g])));if(filter===name)setFilter(to)}catch(e){setError(e instanceof Error?e.message:"名称変更できませんでした")}finally{setBusy("")}}
  async function removeGroup(name:string){if(!confirm(`「${name}」を削除しますか？\n所属クリエイターは未分類に戻ります。`))return;setBusy(`delete:${name}`);try{await post(GROUPS,{action:"delete",name});setGroups(v=>v.filter(x=>x!==name));setAssigned(v=>Object.fromEntries(Object.entries(v).filter(([,g])=>g!==name)));if(filter===name)setFilter("all")}catch(e){setError(e instanceof Error?e.message:"グループ削除できませんでした")}finally{setBusy("")}}
  async function loadArticles(r:Row){const key=String(r.creator_key);if(open===key){setOpen(null);return}setOpen(key);if(articles[key])return;setArticleLoading(true);try{const p=await post(EXTRAS,{action:"favorite_articles",creatorKey:key,creatorUrl:r.actor_url,page:1});setArticles(v=>({...v,[key]:Array.isArray(p?.rows)?p.rows:[]}))}catch(e){setError(e instanceof Error?e.message:"記事を取得できませんでした")}finally{setArticleLoading(false)}}
  async function setRead(r:Row,a:Row,read:boolean){const key=String(r.creator_key);setArticles(v=>({...v,[key]:(v[key]||[]).map(x=>x.key===a.key?{...x,read}:x)}));try{await post(EXTRAS,{action:"favorite_read_set",creatorKey:key,creatorUrl:r.actor_url,articleKey:a.key,articleUrl:a.url,read})}catch{}}
  return <section className="miff"><header className="miff-head"><div><small>FAVORITE CREATOR GROUPS</small><h2>お気に入り・グループ管理</h2><p>通知グループとは別。お気に入りクリエイターをグループ分けし、INSIGHTアカウントごとにサーバー保存します。</p></div><button onClick={()=>void load()}>再読込</button></header>
    <div className="miff-create"><input value={newGroup} onChange={e=>setNewGroup(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void create()}}} placeholder="例：必ず読む / AI / 仲間"/><button disabled={busy==="create"||!clean(newGroup)} onClick={()=>void create()}>{busy==="create"?"作成中…":"＋ グループ作成"}</button></div>
    <div className="miff-tabs"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>すべて <b>{rows.length}</b></button><button className={filter==="ungrouped"?"active":""} onClick={()=>setFilter("ungrouped")}>未分類 <b>{rows.filter(r=>!assigned[String(r.creator_key)]).length}</b></button>{groups.map(g=><span key={g}><button className={filter===g?"active":""} onClick={()=>setFilter(g)}>{g} <b>{counts[g]||0}</b></button><button title="名称変更" onClick={()=>void rename(g)}>✎</button><button className="delete" title="削除" onClick={()=>void removeGroup(g)}>×</button></span>)}</div>
    {error?<p className="miff-error">{error}</p>:null}
    {loading?<p className="miff-empty">お気に入りを読み込み中…</p>:visible.length?<div className="miff-list">{visible.map(r=>{const key=String(r.creator_key),g=assigned[key]||"",list=(articles[key]||[]).filter(a=>!query||String(a.title||"").toLowerCase().includes(query.toLowerCase())||String(a.excerpt||"").toLowerCase().includes(query.toLowerCase()));return <article className="miff-creator" key={key}><div className="miff-person"><Avatar row={r}/><div><b>{r.actor_name||"noteユーザー"}</b>{r.actor_url?<a href={r.actor_url} target="_blank" rel="noreferrer">プロフィール ↗</a>:null}<em className={g?"":"none"}>{g||"未分類"}</em></div></div><div className="miff-actions"><label><span>グループ</span><select value={g} disabled={busy===`assign:${key}`} onChange={e=>void assign(r,e.target.value)}><option value="">未分類</option>{groups.map(x=><option key={x} value={x}>{x}</option>)}</select></label><button onClick={()=>void loadArticles(r)}>{open===key?"記事を閉じる":"記事を見る"}</button></div>{open===key?<div className="miff-articles"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="記事を検索"/>{articleLoading&&!articles[key]?<p className="miff-empty">記事を取得中…</p>:list.length?<div>{list.map(a=><article key={a.key}><a href={a.url} target="_blank" rel="noreferrer" onClick={()=>void setRead(r,a,true)}>{a.thumbnail?<img src={a.thumbnail} alt="" referrerPolicy="no-referrer"/>:<span/>}<div><small>{a.read?"既読":"● 未読"}・{date(a.publishedAt)}</small><b>{a.title}</b><em>♡ {Number(a.likeCount||0)}　💬 {Number(a.commentCount||0)}</em></div></a><button onClick={()=>void setRead(r,a,!a.read)}>{a.read?"未読に戻す":"既読にする"}</button></article>)}</div>:<p className="miff-empty">記事はありません。</p>}</div>:null}</article>})}</div>:<p className="miff-empty">{rows.length?"このグループにはまだクリエイターがいません。":"お気に入りはまだありません。スキ履歴やランキングの☆から登録できます。"}</p>}
  </section>;
}
