import { useEffect, useMemo, useState } from "react";
import { INSIGHT_TOKEN_KEY } from "./insight-account-store";
import "./member-insight-comments-final.css";

const HISTORY="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-history";
const HEARTS="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-comment-hearts";
const PAGE=50;
type Row=Record<string,any>;
type Heart=Record<string,any>;
async function post(endpoint:string,body:Record<string,unknown>){const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");const c=new AbortController(),timer=window.setTimeout(()=>c.abort(),45000);try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify(body),cache:"no-store",signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"INSIGHT_API_ERROR");return p}finally{clearTimeout(timer)}}
const date=(v:any)=>{if(!v)return"—";const d=new Date(String(v));if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
const trim=(v:any,max=180)=>{const s=String(v||"").replace(/\s+/g," ").trim();return s.length>max?s.slice(0,max)+"…":s};
function Avatar({row}:{row:Row}){const image=String(row.actor_image_url||""),name=String(row.actor_name||"noteユーザー");return image?<img className="micf-avatar" src={image} alt="" referrerPolicy="no-referrer"/>:<span className="micf-avatar fallback">{[...name][0]||"人"}</span>}
function HeartState({row,heart}:{row:Row,heart?:Heart}){if(!row.last_is_creator)return <div className="micf-heart neutral">♡ 相手の次の返信を待っています</div>;if(!heart)return <div className="micf-heart checking">♡ 相手からの♡を照合中…</div>;if(heart.exact&&heart.counterpartHearted)return <div className="micf-heart yes">♥ {heart.counterpartName||row.actor_name||"相手"}さんから返信への♡あり <small>{date(heart.heartAt)}</small></div>;if(heart.exact&&heart.counterpartHearted===false)return <div className="micf-heart no">♡ {heart.counterpartName||row.actor_name||"相手"}さんから返信への♡なし</div>;return <div className="micf-heart checking">♡ 過去通知の本人照合を継続中</div>}
export function MemberInsightCommentsFinal({revision=0}:{revision?:number}){const[rows,setRows]=useState<Row[]>([]),[hearts,setHearts]=useState<Record<string,Heart>>({}),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState("");const pages=Math.max(1,Math.ceil(total/PAGE));async function load(p=1){setLoading(true);setError("");try{const x=await post(HISTORY,{action:"comments",page:p,pageSize:PAGE,query,status:"all"}),list=(x.rows||[]) as Row[];setRows(list);setTotal(Number(x.total||0));setPage(p);const keys=list.map(r=>String(r.root_key||"")).filter(Boolean);if(keys.length){const h=await post(HEARTS,{action:"batch",rootKeys:keys}),map:Record<string,Heart>={};for(const item of h.rows||[])map[String(item.rootKey)]=item;setHearts(map)}else setHearts({})}catch(e){setError(e instanceof Error?e.message:"コメント履歴の読込に失敗しました")}finally{setLoading(false)}}useEffect(()=>{void load(1)},[revision]);const shown=useMemo(()=>rows,[rows]);return <section id="micf-comments" className="micf"><header className="micf-head"><div><small>COMMENT THREADS</small><h2>コメント履歴</h2><p>会話の最終発言と、あなたの返信に対する相手本人の♡を別々に照合して表示します。</p></div></header><div className="micf-tools"><label><span>名前・本文検索</span><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load(1)}} placeholder="検索"/></label><button onClick={()=>void load(1)} disabled={loading}>検索</button></div>{error?<p className="micf-error">{error}</p>:null}{loading&&!rows.length?<p className="micf-empty">コメント履歴を読み込み中…</p>:shown.length?<div className="micf-list">{shown.map((r,i)=>{const heart=hearts[String(r.root_key||"")];return <article key={r.root_key||i}><Avatar row={r}/><div className="micf-body"><div className="micf-title"><b>{r.actor_name||"noteユーザー"}</b><time>{date(r.last_at||r.root_at)}</time></div><a className="micf-article" href={r.article_url||r.actor_url||"#"} target="_blank" rel="noreferrer">{r.article_title||"記事"} ↗</a><p className="micf-text">{trim(r.root_body)}</p><div className={r.last_is_creator?"micf-status creator":"micf-status pending"}>{r.last_is_creator?"✓ 自分が返信で終了":"● 相手が最後・返信待ち"}<small>{Number(r.message_count||1)}通</small></div><HeartState row={r} heart={heart}/>{r.actor_url?<a className="micf-person" href={r.actor_url} target="_blank" rel="noreferrer">相手プロフィール ↗</a>:null}</div></article>})}</div>:<p className="micf-empty">この条件のコメント履歴はありません。</p>}{pages>1?<div className="micf-pager"><button disabled={page<=1||loading} onClick={()=>void load(page-1)}>← 前</button><span>{page} / {pages}</span><button disabled={page>=pages||loading} onClick={()=>void load(page+1)}>次 →</button></div>:null}</section>}
