import { useEffect, useMemo, useState } from "react";
import { INSIGHT_TOKEN_KEY } from "./insight-account-store";
import "./member-insight-analytics-final.css";

const DASH="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-dashboard-data";
type Row=Record<string,any>;
type Metric="views"|"likes"|"comments";
const nf=new Intl.NumberFormat("ja-JP");
const n=(v:any)=>nf.format(Number(v||0));
const num=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
const jdate=(v:any)=>{const d=new Date(String(v||""));if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric"}).format(d)};
const jtime=(v:any)=>{const d=new Date(String(v||""));if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
async function load(days:number){const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");const c=new AbortController(),timer=window.setTimeout(()=>c.abort(),45000);try{const r=await fetch(DASH,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify({action:"analysis",days}),cache:"no-store",signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"分析データを取得できませんでした");return p}finally{window.clearTimeout(timer)}}
function cleanSnapshots(rows:Row[],days:number){const cutoff=Date.now()-days*86400000,by=new Map<string,Row>();for(const r of rows||[]){const at=String(r.at||r.date||""),t=Date.parse(at);if(t&&t<cutoff)continue;const key=String(r.date||"");if(!key)continue;const prev=by.get(key);if(!prev||String(r.at||"")>String(prev.at||""))by.set(key,r)}return[...by.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function LineChart({title,unit,rows,metric}:{title:string;unit:string;rows:Row[];metric:Metric}){const W=Math.max(760,rows.length*48),H=300,p={l:72,r:30,t:34,b:52},vals=rows.map(r=>num(r[metric])),min=0,max=Math.max(1,...vals),iw=W-p.l-p.r,ih=H-p.t-p.b,xy=(v:number,i:number)=>[p.l+(rows.length===1?iw/2:i*iw/(rows.length-1)),p.t+ih-(v-min)/(max-min)*ih],pts=rows.map((r,i)=>xy(num(r[metric]),i).join(",")).join(" "),ticks=[0,.25,.5,.75,1],every=Math.max(1,Math.ceil(rows.length/6));return <article className="miaf-chart"><header><div><small>OFFICIAL DASHBOARD</small><h2>{title}</h2></div><span className="miaf-legend"><i className={metric}/>{title}（{unit}）</span></header><div className="miaf-chartscroll"><svg viewBox={`0 0 ${W} ${H}`} style={{minWidth:W}} role="img" aria-label={`${title}。縦軸は${unit}、横軸は取得日。`}><text className="miaf-axis-title" x="12" y="18">{unit}</text>{ticks.map((t,i)=>{const v=Math.round(min+(max-min)*t),y=p.t+ih-i*ih/(ticks.length-1);return <g key={i}><line className="miaf-grid" x1={p.l} x2={W-p.r} y1={y} y2={y}/><text className="miaf-axis" x={p.l-12} y={y+4} textAnchor="end">{n(v)}</text></g>})}<line className="miaf-axisline" x1={p.l} x2={p.l} y1={p.t} y2={H-p.b}/><line className="miaf-axisline" x1={p.l} x2={W-p.r} y1={H-p.b} y2={H-p.b}/><polyline className={`miaf-line ${metric}`} points={pts}/>{rows.map((r,i)=>{const[x,y]=xy(num(r[metric]),i);return <g key={`${r.date}-${i}`}><circle className={`miaf-dot ${metric}`} cx={x} cy={y} r="4"><title>{`${r.date}: ${n(r[metric])}${unit}`}</title></circle>{i%every===0||i===rows.length-1?<text className="miaf-axis x" x={x} y={H-18} textAnchor="middle">{jdate(r.date)}</text>:null}</g>})}</svg></div><footer><span>縦軸：{unit}</span><span>横軸：ダッシュボード取得日</span><strong>最新 {n(rows.at(-1)?.[metric])}{unit}</strong></footer></article>}
function TopArticles({rows}:{rows:Row[]}){const top=[...(rows||[])].sort((a,b)=>num(b.views)-num(a.views)).slice(0,10),max=Math.max(1,...top.map(r=>num(r.views)));return <article className="miaf-top"><header><div><small>LATEST OFFICIAL SNAPSHOT</small><h2>記事別 VIEW TOP10</h2></div><span>単位：VIEW</span></header>{top.length?<div className="miaf-bars">{top.map((r,i)=><a key={r.article_key||r.url||i} href={r.url||undefined} target={r.url?"_blank":undefined} rel={r.url?"noreferrer":undefined}><em>{i+1}</em><div><b>{r.title||"無題の記事"}</b><span><i style={{width:`${Math.max(2,num(r.views)/max*100)}%`}}/></span><small>VIEW {n(r.views)}　♡ {n(r.likes)}　💬 {n(r.comments)}</small></div><strong>{n(r.views)}</strong></a>)}</div>:<p>記事別統計がまだ取り込まれていません。</p>}</article>}
export function MemberInsightAnalyticsFinal({revision=0,onBack}:{revision?:number;onBack?:()=>void}){const[days,setDays]=useState(90),[data,setData]=useState<Row|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[doneAt,setDoneAt]=useState<string|null>(null);async function refresh(){if(loading)return;setLoading(true);setError("");try{const p=await load(days);setData(p);setDoneAt(new Date().toISOString())}catch(e){setError(e instanceof Error?e.message:"分析データを取得できませんでした")}finally{setLoading(false)}}useEffect(()=>{void refresh()},[days,revision]);const snapshots=useMemo(()=>cleanSnapshots(data?.dashboard||[],days),[data,days]),ready=snapshots.length>=2,latest=data?.latestDashboard||null,articles=data?.topArticles||[],compare=data?.comparison||{};return <section className="miaf"><header className="miaf-head"><div>{onBack?<button className="miaf-back" onClick={onBack}>← INSIGHT</button>:null}<small>INSIGHT ANALYTICS</small><h1>分析</h1><p>取得した実データだけをグラフ化します。データがない状態では飾り線を表示しません。</p></div><button className={loading?"miaf-refresh loading":doneAt?"miaf-refresh done":"miaf-refresh"} onClick={()=>void refresh()} disabled={loading} aria-busy={loading}>{loading?"分析中…":doneAt?"✓ 分析を更新":"分析を実行"}</button></header><div className="miaf-range">{[[30,"30日"],[90,"90日"],[365,"1年"]].map(([d,label])=><button key={d} className={days===d?"active":""} onClick={()=>setDays(Number(d))}>{label}</button>)}</div>{error?<div className="miaf-error">{error}</div>:null}<section className={latest?"miaf-source ok":"miaf-source waiting"}><div><small>公式ダッシュボード連携</small><b>{latest?"取得済み":"未取得"}</b></div>{latest?<p>最終取込 {jtime(latest.capturedAt)}　総VIEW <strong>{n(latest.views)}</strong>　スキ <strong>{n(latest.likes)}</strong>　コメント <strong>{n(latest.comments)}</strong></p>:<p>note公式ダッシュボードの統計がまだINSIGHTへ保存されていません。通知・統計同期から取り込むと、実数グラフを生成します。</p>}</section>{!latest?<section className="miaf-explain"><h2>グラフはまだ表示しません</h2><p>分析元となる公式統計が0件のためです。仮の線や推測値は使いません。</p></section>:snapshots.length<2?<section className="miaf-explain"><h2>推移グラフは2回目の統計取得後に表示</h2><p>現在は公式スナップショットが1時点です。1点だけを線で結んだ飾りグラフは表示しません。</p>{articles.length?<TopArticles rows={articles}/>:null}</section>:<><div className="miaf-kpis"><span><small>直近7日スキ</small><b>{n(compare.likes7)}</b></span><span><small>直近7日コメント</small><b>{n(compare.comments7)}</b></span><span><small>直近7日返信</small><b>{n(compare.replies7)}</b></span><span><small>分析スナップショット</small><b>{snapshots.length}</b></span></div><LineChart title="総VIEW推移" unit="VIEW" rows={snapshots} metric="views"/><LineChart title="総スキ推移" unit="件" rows={snapshots} metric="likes"/><LineChart title="総コメント推移" unit="件" rows={snapshots} metric="comments"/><TopArticles rows={articles}/></>}{ready&&doneAt?<p className="miaf-complete">✓ 実データ分析完了　{jtime(doneAt)}</p>:null}</section>}
