import { useEffect, useMemo, useState } from "react";
import { INSIGHT_TOKEN_KEY, setAccessIntent } from "./insight-account-store";
import "./member-insight-full.css";

const HISTORY="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-history";
const MEMBER="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/insight-member-api";
type Row=Record<string,any>;
type Tab="overview"|"likes"|"comments"|"supporters"|"social"|"notifications"|"articles";

type Summary={member:{noteId:string;displayName:string;imageUrl:string|null};summary:Record<string,any>;analysis:Record<string,any>;counts:{comments:number;followers:number;followings:number;notifications:number};articles:Row[]};
type RefreshProps={revision:number};

async function call(endpoint:string,action:string,extra:Record<string,unknown>={}){
 const token=localStorage.getItem(INSIGHT_TOKEN_KEY)||"";if(!token)throw new Error("INSIGHT_LOGIN_REQUIRED");
 const c=new AbortController(),timer=window.setTimeout(()=>c.abort(),20000);
 try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","X-Insight-Token":token},body:JSON.stringify({action,...extra}),cache:"no-store",signal:c.signal});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||"INSIGHT_API_ERROR");return p}finally{clearTimeout(timer)}
}
const hist=(action:string,extra:Record<string,unknown>={})=>call(HISTORY,action,extra);
const n=(v:any)=>new Intl.NumberFormat("ja-JP").format(Number(v||0));
const date=(v:any)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
function Avatar({name,image}:{name:string;image?:string|null}){return image?<img className="mif-avatar" src={image} alt="" referrerPolicy="no-referrer"/>:<span className="mif-avatar fallback">{[...String(name||"n")][0]}</span>}
function Person({row}:{row:Row}){const name=row.actor_name||row.name||"noteユーザー",url=row.actor_url||row.url,image=row.actor_image_url||row.image;return <span className="mif-person"><Avatar name={name} image={image}/><span><b>{name}</b>{url?<a href={url} target="_blank" rel="noreferrer">note ↗</a>:null}</span></span>}
function Pager({page,total,onPage}:{page:number;total:number;onPage:(x:number)=>void}){const pages=Math.max(1,Math.ceil(total/100));if(pages<=1)return null;return <div className="mif-pager"><button disabled={page<=1} onClick={()=>onPage(page-1)}>←</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>onPage(page+1)}>→</button></div>}

function Likes({revision}:RefreshProps){const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");async function load(p=1){setLoading(true);setError("");try{const x=await hist("likes",{page:p,pageSize:100,status,sort:"newest"});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p)}catch(e){setError(e instanceof Error?e.message:"読込失敗")}finally{setLoading(false)}}useEffect(()=>{void load(page)},[status,revision]);return <section className="mif-panel"><header><div><small>LIKE HISTORY</small><h2>スキ全履歴</h2></div><strong>{n(total)}件</strong></header><div className="mif-subtabs">{[["all","すべて"],["pending","未対応"],["completed","対応済み"]].map(x=><button key={x[0]} className={status===x[0]?"active":""} onClick={()=>{setPage(1);setStatus(x[0])}}>{x[1]}</button>)}</div>{error?<p className="mif-error">{error}</p>:loading?<p className="mif-empty">全履歴を読み込み中…</p>:<div className="mif-list">{rows.map(r=><article className="mif-history" key={`${r.article_key}:${r.liker_key}`}><Person row={r}/><a className="mif-title" href={r.article_url} target="_blank" rel="noreferrer">{r.article_title}</a><time>{date(r.liked_at)}</time></article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Comments({revision}:RefreshProps){const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");const[detail,setDetail]=useState<Record<string,Row[]>>({});async function load(p=1){setLoading(true);setError("");try{const x=await hist("comments",{page:p,pageSize:100,status});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p)}catch(e){setError(e instanceof Error?e.message:"読込失敗")}finally{setLoading(false)}}async function open(key:string){if(detail[key])return;try{const x=await hist("comment_thread",{rootKey:key});setDetail(v=>({...v,[key]:x.rows||[]}))}catch{setDetail(v=>({...v,[key]:[]}))}}useEffect(()=>{setDetail({});void load(page)},[status,revision]);return <section className="mif-panel"><header><div><small>COMMENT HISTORY</small><h2>コメント・返信履歴</h2></div><strong>{n(total)}件</strong></header><div className="mif-subtabs">{[["all","すべて"],["pending","要対応"],["unreplied","未返信"],["followup_pending","相手返信"],["replied","自分返信"]].map(x=><button key={x[0]} className={status===x[0]?"active":""} onClick={()=>{setPage(1);setStatus(x[0])}}>{x[1]}</button>)}</div>{error?<p className="mif-error">{error}</p>:loading?<p className="mif-empty">コメント履歴を読み込み中…</p>:<div className="mif-list">{rows.map(r=><details className="mif-comment" key={r.root_key} onToggle={e=>{if((e.currentTarget as HTMLDetailsElement).open)void open(r.root_key)}}><summary><Person row={r}/><span className={`mif-state ${r.status}`}>{r.status==="unreplied"?"未返信":r.status==="followup_pending"?"相手の返信で停止":r.status==="replied"?"自分の返信で終了":r.status}</span><p>{String(r.root_body||"").slice(0,110)}</p><a href={r.article_url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{r.article_title}</a><time>{date(r.last_at||r.root_at)}</time></summary><div className="mif-thread">{detail[r.root_key]?.map(m=><article key={m.comment_key} className={m.is_creator?"mine":""}><b>{m.is_creator?"あなた":m.actor_name}</b><small>{date(m.occurred_at)}</small><p>{m.body}</p></article>)||<p>会話を読み込み中…</p>}</div></details>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Supporters({revision}:RefreshProps){const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true);async function load(p=1){setLoading(true);try{const x=await hist("supporters",{page:p,pageSize:100});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p)}finally{setLoading(false)}}useEffect(()=>{void load(page)},[revision]);return <section className="mif-panel"><header><div><small>SUPPORTER RANKING</small><h2>応援者ランキング</h2></div><strong>{n(total)}人</strong></header>{loading?<p className="mif-empty">集計中…</p>:<div className="mif-list">{rows.map((r,i)=><article className="mif-rank" key={r.liker_key}><em>{(page-1)*100+i+1}</em><Person row={r}/><strong>{n(r.like_count)}記事</strong></article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Social({revision}:RefreshProps){const[direction,setDirection]=useState("followers"),[mode,setMode]=useState("current"),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true);async function load(p=1){setLoading(true);try{const x=await hist(mode==="current"?"social":"changes",{page:p,pageSize:100,direction,change:"all"});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p)}finally{setLoading(false)}}useEffect(()=>{void load(page)},[direction,mode,revision]);return <section className="mif-panel"><header><div><small>SOCIAL HISTORY</small><h2>フォロー・フォロワー</h2></div><strong>{n(total)}件</strong></header><div className="mif-subtabs"><button className={direction==="followers"?"active":""} onClick={()=>{setPage(1);setDirection("followers")}}>フォロワー</button><button className={direction==="followings"?"active":""} onClick={()=>{setPage(1);setDirection("followings")}}>フォロー</button><button className={mode==="current"?"active":""} onClick={()=>{setPage(1);setMode("current")}}>現在</button><button className={mode==="changes"?"active":""} onClick={()=>{setPage(1);setMode("changes")}}>増減履歴</button></div>{loading?<p className="mif-empty">履歴を読み込み中…</p>:<div className="mif-list">{rows.map((r,i)=><article className="mif-social" key={r.id||r.person_key||i}><Person row={r}/>{mode==="changes"?<b className={r.event_type==="removed"?"removed":"added"}>{r.event_type==="removed"?"減少":"追加"}</b>:null}<time>{date(r.detected_at||r.last_seen_at)}</time></article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Notifications({revision}:RefreshProps){const[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true);async function load(p=1){setLoading(true);try{const x=await hist("notifications",{page:p,pageSize:100});setRows(x.rows||[]);setTotal(Number(x.total||0));setPage(p)}finally{setLoading(false)}}useEffect(()=>{void load(page)},[revision]);return <section className="mif-panel"><header><div><small>NOTIFICATION HISTORY</small><h2>本人通知・反応履歴</h2></div><strong>{n(total)}件</strong></header><a className="mif-notify-setup" href="./notification-setup.html?from=insight&role=member" target="_blank" rel="noopener noreferrer">本人通知の自動同期を設定 →</a>{loading?<p className="mif-empty">通知履歴を読み込み中…</p>:<div className="mif-list">{rows.map(r=><article className="mif-notice" key={`${r.member_id}:${r.id}`}><b>{r.raw_text||r.notification_type}</b><span>{r.actor_name||""}</span><time>{date(r.occurred_at||r.captured_at)}</time></article>)}</div>}<Pager page={page} total={total} onPage={p=>void load(p)}/></section>}

function Articles({revision}:RefreshProps){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{setLoading(true);void hist("articles").then(x=>setRows(x.rows||[])).finally(()=>setLoading(false))},[revision]);return <section className="mif-panel"><header><div><small>ARTICLE ARCHIVE</small><h2>記事一覧</h2></div><strong>{n(rows.length)}件</strong></header>{loading?<p className="mif-empty">記事を読み込み中…</p>:<div className="mif-list">{rows.map(r=><a className="mif-article" key={r.article_key} href={r.url} target="_blank" rel="noreferrer"><span><b>{r.title}</b><small>{date(r.publish_at)}</small></span><em>♥ {n(r.like_count)}　💬 {n(r.comment_count)}</em></a>)}</div>}</section>}

export function MemberInsightFull({revision=0}:{revision?:number}){
 const[data,setData]=useState<Summary|null>(null),[tab,setTab]=useState<Tab>("overview"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[syncing,setSyncing]=useState(false);
 async function load(){setError("");try{setData(await hist("summary"))}catch(e){const msg=e instanceof Error?e.message:"INSIGHT_API_ERROR";if(/LOGIN|SESSION|INACTIVE/.test(msg)){localStorage.removeItem(INSIGHT_TOKEN_KEY);location.hash="access/insight";return}setError(msg)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[revision]);
 async function sync(){setSyncing(true);setError("");try{await call(MEMBER,"sync");await load()}catch(e){setError(e instanceof Error?e.message:"同期失敗")}finally{setSyncing(false)}}
 function switchAccount(){setAccessIntent("switch");location.hash="access/insight"}
 const totals=useMemo(()=>{const s=data?.summary||{},a=data?.analysis||{},c=data?.counts||{comments:0,followers:0,followings:0,notifications:0};return{articles:Number(s.articleCount||0),likes:Number(s.identifiedLikeCount||0),supporters:Number(s.supporterCount||a.uniqueSupporters||0),comments:Number(c.comments||0),followers:Number(c.followers||a.followers?.total||0),followings:Number(c.followings||a.followings?.total||0),notifications:Number(c.notifications||0)}},[data]);
 if(loading)return <div className="mif-loading">INSIGHT全履歴を読み込んでいます…</div>;
 if(!data)return <div className="mif-loading"><p>{error||"読み込めませんでした"}</p><button onClick={()=>{setLoading(true);void load()}}>再読込</button></div>;
 return <div className="mif"><main><header className="mif-top"><Avatar name={data.member.displayName} image={data.member.imageUrl}/><div><small>MY NOTE INSIGHT</small><h1>{data.member.displayName}</h1><a href={`https://note.com/${data.member.noteId}`} target="_blank" rel="noreferrer">@{data.member.noteId} ↗</a></div><div className="mif-topactions"><button onClick={switchAccount}>アカウント切替</button><a href="./notification-setup.html?from=insight&role=member" target="_blank" rel="noopener noreferrer">本人通知</a><button className="sync" disabled={syncing} onClick={()=>void sync()}>{syncing?"同期中…":"データ更新"}</button></div></header>
 {error?<div className="mif-error">{error}</div>:null}
 <section className="mif-stats">{[["記事",totals.articles],["スキ履歴",totals.likes],["コメント",totals.comments],["フォロワー",totals.followers],["フォロー",totals.followings],["通知",totals.notifications]].map(([label,value])=><button key={String(label)} onClick={()=>{if(label==="スキ履歴")setTab("likes");else if(label==="コメント")setTab("comments");else if(label==="フォロワー"||label==="フォロー")setTab("social");else if(label==="通知")setTab("notifications");else if(label==="記事")setTab("articles")}}><small>{label}</small><strong>{n(value)}</strong></button>)}</section>
 <nav className="mif-nav">{([['overview','概要'],['likes','スキ履歴'],['comments','コメント'],['supporters','応援者'],['social','フォロー'],['notifications','通知'],['articles','記事']] as [Tab,string][]).map(([k,l])=><button className={tab===k?"active":""} key={k} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 {tab==="overview"?<section className="mif-overview"><article className="mif-panel"><header><div><small>FULL HISTORY RESTORED</small><h2>保存済み全履歴</h2></div></header><p>保存済みデータを直接表示しています。再同期を待たず、これまでのスキ・コメント・フォロー履歴を確認できます。</p><div className="mif-bigmetrics"><span><b>{n(totals.likes)}</b>スキ履歴</span><span><b>{n(totals.comments)}</b>コメント</span><span><b>{n(totals.supporters)}</b>応援者</span></div></article><article className="mif-panel"><header><div><small>ENGAGEMENT</small><h2>反応分析</h2></div></header><p>リピーター {n(data.analysis?.repeatSupporters)}人 / 未返信コメント {n(data.analysis?.unrepliedComments)}件 / 相手返信で停止 {n(data.analysis?.followupPendingComments)}件</p><div className="mif-recent">{(data.articles||[]).slice(0,8).map(r=><a key={r.article_key} href={r.url} target="_blank" rel="noreferrer"><b>{r.title}</b><span>♥ {n(r.like_count)}　💬 {n(r.comment_count)}</span></a>)}</div></article></section>:null}
 {tab==="likes"?<Likes revision={revision}/>:null}{tab==="comments"?<Comments revision={revision}/>:null}{tab==="supporters"?<Supporters revision={revision}/>:null}{tab==="social"?<Social revision={revision}/>:null}{tab==="notifications"?<Notifications revision={revision}/>:null}{tab==="articles"?<Articles revision={revision}/>:null}
 </main></div>
}
