import { useEffect, useState } from "react";

const ENDPOINT="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/unified-owner-access";
const KEY="mumei-unified-owner-token";
const RETURN_KEY="mumei-owner-return";
function nextRoute(){const route=sessionStorage.getItem(RETURN_KEY)||"";sessionStorage.removeItem(RETURN_KEY);return route==="dashboard"?route:"manage"}
async function call(action:string,extra:Record<string,unknown>={}){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","X-Owner-Token":localStorage.getItem(KEY)||""},body:JSON.stringify({action,...extra})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||"管理者認証に失敗しました");return p}

export function OwnerGate(){
 const[checking,setChecking]=useState(true),[code,setCode]=useState(""),[challengeId,setChallengeId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void(async()=>{try{if(localStorage.getItem(KEY)){const p=await call("status");if(p.authenticated){location.hash=nextRoute();return}}}catch{}finally{setChecking(false)}})()},[]);
 async function start(){setBusy(true);setMessage("");try{const p=await call("start");setCode(p.code);setChallengeId(p.challengeId)}catch(e){setMessage(e instanceof Error?e.message:"コードを発行できませんでした")}finally{setBusy(false)}}
 async function verify(){setBusy(true);setMessage("");try{const p=await call("verify",{challengeId});localStorage.setItem(KEY,p.ownerToken);location.hash=nextRoute()}catch(e){const m=e instanceof Error?e.message:"確認できませんでした";setMessage(m==="PROFILE_CODE_NOT_FOUND"?"noteプロフィールにコードが見つかりません。掲載して保存後、もう一度確認してください。":m)}finally{setBusy(false)}}
 if(checking)return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#070a0f",color:"#fff"}}>管理者セッション確認中…</div>;
 return <div style={{minHeight:"100vh",background:"#070a0f",color:"#f6f8fb",padding:"26px 14px"}}><main style={{width:"min(680px,100%)",margin:"0 auto"}}><a href="#" style={{color:"#ffcf5a",textDecoration:"none",fontWeight:900}}>← TOP</a><header style={{padding:"50px 0 22px"}}><small style={{color:"#ffcf5a",fontWeight:950,letterSpacing:".14em"}}>OWNER ACCESS</small><h1 style={{fontSize:"clamp(38px,7vw,60px)",margin:"8px 0"}}>管理者入口</h1><p style={{color:"#9ca9bb",lineHeight:1.7}}>参加者画面とは別のOWNER専用入口です。認証済みセッションが残っている間は、この画面を自動でスキップします。</p></header><section style={{border:"1px solid #334158",borderRadius:20,background:"#0e151f",padding:20}}>{!code?<><h2>管理者本人を確認</h2><p style={{color:"#9ca9bb",lineHeight:1.7}}>固定パスワードではなく、管理者noteプロフィールへ一時コードを掲載して本人確認します。</p><button disabled={busy} onClick={()=>void start()} style={{border:0,borderRadius:11,background:"#ffcf5a",color:"#171000",padding:"12px 16px",fontWeight:950}}>{busy?"発行中…":"本人確認コードを発行"}</button></>:<><p style={{color:"#9ca9bb"}}>このコードを管理者noteプロフィールへ一時掲載して保存してください。</p><code style={{display:"block",padding:16,borderRadius:12,background:"#05080c",color:"#ffcf5a",fontSize:21,fontWeight:950}}>{code}</code><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:14}}><a href="https://note.com/ss_yr" target="_blank" rel="noreferrer" style={{color:"#54d8ff",fontWeight:900}}>noteプロフィールを開く ↗</a><button disabled={busy} onClick={()=>void verify()} style={{border:0,borderRadius:11,background:"#ffcf5a",color:"#171000",padding:"10px 15px",fontWeight:950}}>管理者として確認</button></div></>}{message?<p style={{color:"#ffbd76",fontWeight:850}}>{message}</p>:null}</section></main></div>
}
