import { useEffect, useState } from "react";

const ENDPOINT="https://xxhaerjvrgmnadxjqetz.supabase.co/functions/v1/unified-owner-access";
const KEY="mumei-unified-owner-token";
async function status(){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","X-Owner-Token":localStorage.getItem(KEY)||""},body:JSON.stringify({action:"status"})});const p=await r.json().catch(()=>({}));return r.ok&&p.authenticated}

const card={border:"1px solid #2b394c",borderRadius:20,background:"linear-gradient(180deg,#101722,#0b1017)",padding:20} as const;
const link={display:"inline-flex",alignItems:"center",justifyContent:"center",minHeight:44,borderRadius:11,padding:"0 14px",textDecoration:"none",fontWeight:950} as const;

export function OwnerHub(){
 const[ready,setReady]=useState(false);
 useEffect(()=>{void(async()=>{if(!await status()){location.hash="owner";return}setReady(true)})()},[]);
 if(!ready)return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#070a0f",color:"#fff"}}>管理者確認中…</div>;
 return <div style={{minHeight:"100vh",background:"#070a0f",color:"#f6f8fb",padding:"24px 14px 70px"}}><main style={{width:"min(1080px,100%)",margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><a href="#" style={{color:"#ffcf5a",textDecoration:"none",fontWeight:900}}>← TOP</a><button onClick={()=>{localStorage.removeItem(KEY);location.hash="owner"}} style={{border:"1px solid #3a4658",borderRadius:9,background:"transparent",color:"#aab6c6",padding:"7px 10px"}}>管理ログアウト</button></div><header style={{padding:"46px 0 26px"}}><small style={{color:"#ffcf5a",fontWeight:950,letterSpacing:".14em"}}>OWNER CONTROL</small><h1 style={{fontSize:"clamp(40px,7vw,64px)",margin:"8px 0"}}>管理ハブ</h1><p style={{color:"#9ca9bb",lineHeight:1.7}}>参加者画面とは分離したOWNER専用画面です。名鑑管理を同じページ内へ二重表示せず、管理機能ごとに分けます。</p></header><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14}}><article style={card}><small style={{color:"#75e6ff",fontWeight:900}}>自分で使う</small><h2>自分のINSIGHT</h2><p style={{color:"#9ca9bb"}}>自分の分析ダッシュボードを開きます。</p><a href="#dashboard" style={{...link,background:"#75e6ff",color:"#071016"}}>INSIGHTを開く →</a></article><article style={card}><small style={{color:"#8fdcff",fontWeight:900}}>自分で使う</small><h2>自分の名鑑</h2><p style={{color:"#9ca9bb"}}>カードアルバムと自分の登録内容を確認します。</p><a href="#catalog" style={{...link,background:"#172434",color:"#8fdcff",border:"1px solid #35506a"}}>名鑑を開く →</a></article><article style={card}><small style={{color:"#b6ff38",fontWeight:900}}>管理する</small><h2>INSIGHT管理</h2><p style={{color:"#9ca9bb"}}>参加者の利用状態や認証状態を管理する専用画面です。</p><a href="#insight-admin" style={{...link,background:"#172434",color:"#b6ff38",border:"1px solid #3e5731"}}>INSIGHT管理 →</a></article><article style={card}><small style={{color:"#ffcf5a",fontWeight:900}}>管理する</small><h2>名鑑申請管理</h2><p style={{color:"#9ca9bb"}}>名鑑の申請・承認・非公開・退会処理だけを行います。</p><a href="#catalog-admin" style={{...link,background:"#172434",color:"#ffcf5a",border:"1px solid #5b4c26"}}>名鑑申請管理 →</a></article><article style={card}><small style={{color:"#ff87e1",fontWeight:900}}>管理する</small><h2>対戦カード管理</h2><p style={{color:"#9ca9bb"}}>参加者と戦うための対戦カード側だけを管理します。</p><a href="#game-admin" style={{...link,background:"#2a1530",color:"#ff9dea",border:"1px solid #5f3367"}}>対戦カード管理 →</a></article></section></main></div>
}
