CREATE TABLE IF NOT EXISTS private.insight_egress_catalog_state(member_id text PRIMARY KEY,last_completed_at timestamptz NOT NULL); CREATE TABLE IF NOT EXISTS private.insight_avatar_retry(actor_url text PRIMARY KEY,retry_after timestamptz NOT NULL); REVOKE ALL ON private.insight_egress_catalog_state,private.insight_avatar_retry FROM PUBLIC,anon,authenticated;
CREATE OR REPLACE FUNCTION public.insight_egress_authorize(p_secret text) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT jsonb_build_object('authorized',COALESCE(length(p_secret)>0 AND EXISTS(SELECT 1 FROM public.insight_notification_cron_secret WHERE singleton=true AND secret=p_secret),false),'maintenance',public.insight_background_maintenance()); $$;
CREATE OR REPLACE FUNCTION public.insight_missing_like_articles(p_member text,p_limit integer DEFAULT 20) RETURNS TABLE(article_key text,like_count integer,last_seen_at timestamptz,stored bigint,missing bigint) LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ WITH candidates AS MATERIALIZED (SELECT a.article_key,a.like_count,a.last_seen_at FROM public.insight_public_articles a WHERE a.member_id=p_member AND a.like_count>0 ORDER BY a.last_seen_at DESC,a.article_key LIMIT 1000), counted AS (SELECT a.*, (SELECT count(*) FROM public.insight_public_likes l WHERE l.member_id=p_member AND l.article_key=a.article_key) AS stored FROM candidates a) SELECT c.article_key,c.like_count,c.last_seen_at,c.stored,c.like_count::bigint-c.stored FROM counted c WHERE c.stored<c.like_count ORDER BY c.like_count::bigint-c.stored DESC,c.last_seen_at DESC,c.article_key LIMIT greatest(1,least(p_limit,100)); $$;
CREATE OR REPLACE FUNCTION public.insight_egress_catalog_due(p_member text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT NOT EXISTS(SELECT 1 FROM private.insight_egress_catalog_state WHERE member_id=p_member AND last_completed_at>now()-interval '24 hours'); $$;
CREATE OR REPLACE FUNCTION public.insight_egress_catalog_complete(p_member text) RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$ INSERT INTO private.insight_egress_catalog_state(member_id,last_completed_at) VALUES(p_member,now()) ON CONFLICT(member_id) DO UPDATE SET last_completed_at=EXCLUDED.last_completed_at; $$;
CREATE OR REPLACE FUNCTION public.insight_egress_upsert(p_table text,p_rows jsonb) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$
DECLARE keys text[]; pk text[]; cols text; assigns text; oldcols text; newcols text; affected integer; k text;
BEGIN
 IF NOT p_table=ANY(ARRAY['insight_public_articles','insight_public_comments','insight_public_likes','insight_public_followers']) THEN RAISE EXCEPTION 'TABLE_NOT_ALLOWED'; END IF;
 IF jsonb_typeof(p_rows) IS DISTINCT FROM 'array' OR jsonb_array_length(p_rows)>1000 THEN RAISE EXCEPTION 'INVALID_BATCH'; END IF;
 IF jsonb_array_length(p_rows)=0 THEN RETURN 0; END IF;
 SELECT array_agg(t.key ORDER BY t.key) INTO keys FROM jsonb_object_keys(p_rows->0) AS t(key);
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_rows) x WHERE (SELECT array_agg(t.key ORDER BY t.key) FROM jsonb_object_keys(x) t(key)) IS DISTINCT FROM keys) THEN RAISE EXCEPTION 'BATCH_COLUMNS_MUST_MATCH'; END IF;
 pk:=CASE p_table WHEN 'insight_public_articles' THEN ARRAY['member_id','article_key'] WHEN 'insight_public_comments' THEN ARRAY['member_id','article_key','comment_key'] WHEN 'insight_public_likes' THEN ARRAY['member_id','article_key','liker_key'] ELSE ARRAY['member_id','person_key'] END;
 IF NOT pk<@keys THEN RAISE EXCEPTION 'PRIMARY_KEY_REQUIRED'; END IF;
 FOREACH k IN ARRAY keys LOOP IF NOT EXISTS(SELECT 1 FROM pg_catalog.pg_attribute a WHERE a.attrelid=('public.'||p_table)::regclass AND a.attname=k AND a.attnum>0 AND NOT a.attisdropped) OR k='first_seen_at' THEN RAISE EXCEPTION 'COLUMN_NOT_ALLOWED: %',k; END IF; END LOOP;
 SELECT string_agg(format('%I',x),',') INTO cols FROM unnest(keys) x;
 SELECT string_agg(format('%I=EXCLUDED.%I',x,x),','),string_agg(format('old.%I',x),',' ) FILTER(WHERE x<>'last_seen_at'),string_agg(format('EXCLUDED.%I',x),',') FILTER(WHERE x<>'last_seen_at') INTO assigns,oldcols,newcols FROM unnest(keys) x WHERE NOT x=ANY(pk);
 IF assigns IS NULL OR oldcols IS NULL THEN EXECUTE format('WITH w AS (INSERT INTO public.%I (%s) SELECT %s FROM jsonb_populate_recordset(NULL::public.%I,$1) ON CONFLICT DO NOTHING RETURNING 1) SELECT count(*)::integer FROM w',p_table,cols,cols,p_table) USING p_rows INTO affected;
 ELSE EXECUTE format('WITH w AS (INSERT INTO public.%I AS old (%s) SELECT %s FROM jsonb_populate_recordset(NULL::public.%I,$1) ON CONFLICT (%s) DO UPDATE SET %s WHERE ROW(%s) IS DISTINCT FROM ROW(%s) RETURNING 1) SELECT count(*)::integer FROM w',p_table,cols,cols,p_table,(SELECT string_agg(format('%I',x),',') FROM unnest(pk) x),assigns,oldcols,newcols) USING p_rows INTO affected; END IF;
 RETURN affected;
END $fn$;
CREATE OR REPLACE FUNCTION public.insight_egress_insert_notifications(p_rows jsonb) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$ DECLARE n integer; BEGIN
 IF jsonb_typeof(p_rows) IS DISTINCT FROM 'array' OR jsonb_array_length(p_rows)>1000 THEN RAISE EXCEPTION 'INVALID_NOTIFICATION_BATCH'; END IF;
 INSERT INTO public.insight_notifications(member_id,fingerprint,notification_type,raw_text,actor_name,actor_url,actor_image_url,target_title,target_url,source_url,occurred_at,meta)
 SELECT r.member_id,r.fingerprint,COALESCE(r.notification_type,'other'),r.raw_text,r.actor_name,r.actor_url,r.actor_image_url,r.target_title,r.target_url,r.source_url,r.occurred_at,COALESCE(r.meta,'{}'::jsonb) FROM jsonb_populate_recordset(NULL::public.insight_notifications,p_rows) r ON CONFLICT(member_id,fingerprint) DO NOTHING;
 GET DIAGNOSTICS n=ROW_COUNT; RETURN n; END $fn$;
CREATE OR REPLACE FUNCTION public.insight_comment_refresh_batch(p_member text,p_article text,p_rows jsonb,p_notifications jsonb DEFAULT '[]') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$ DECLARE newkeys text[]; changed integer; inserted integer; events jsonb; BEGIN
 IF jsonb_typeof(p_rows) IS DISTINCT FROM 'array' OR jsonb_array_length(p_rows)>1000 THEN RAISE EXCEPTION 'INVALID_COMMENT_BATCH'; END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_rows) x WHERE x->>'member_id' IS DISTINCT FROM p_member OR x->>'article_key' IS DISTINCT FROM p_article) THEN RAISE EXCEPTION 'COMMENT_SCOPE_MISMATCH'; END IF;
 PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('insight-comment:'||p_member||':'||p_article,0));
 SELECT array_agg(x->>'comment_key') INTO newkeys FROM jsonb_array_elements(p_rows) x WHERE NOT EXISTS(SELECT 1 FROM public.insight_public_comments c WHERE c.member_id=p_member AND c.article_key=p_article AND c.comment_key=x->>'comment_key');
 changed:=public.insight_egress_upsert('insight_public_comments',p_rows);
 SELECT COALESCE(jsonb_agg(x),'[]') INTO events FROM jsonb_array_elements(p_notifications) x WHERE (x->'meta'->>'commentKey')=ANY(COALESCE(newkeys,ARRAY[]::text[]));
 inserted:=public.insight_egress_insert_notifications(events);
 RETURN jsonb_build_object('received',jsonb_array_length(p_rows),'changed',changed,'unchanged',jsonb_array_length(p_rows)-changed,'newNotifications',inserted);
 END $fn$;
CREATE OR REPLACE FUNCTION public.insight_followers_refresh_batch(p_member text,p_rows jsonb,p_baseline boolean) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$ DECLARE newkeys text[]; changed integer; inserted integer:=0; events jsonb; BEGIN
 IF jsonb_typeof(p_rows) IS DISTINCT FROM 'array' OR jsonb_array_length(p_rows)>1000 THEN RAISE EXCEPTION 'INVALID_FOLLOWER_BATCH'; END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_rows) x WHERE x->>'member_id' IS DISTINCT FROM p_member) THEN RAISE EXCEPTION 'FOLLOWER_SCOPE_MISMATCH'; END IF;
 PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('insight-followers:'||p_member,0));
 SELECT array_agg(x->>'person_key') INTO newkeys FROM jsonb_array_elements(p_rows) x WHERE NOT EXISTS(SELECT 1 FROM public.insight_public_followers c WHERE c.member_id=p_member AND c.person_key=x->>'person_key');
 changed:=public.insight_egress_upsert('insight_public_followers',p_rows);
 IF NOT p_baseline THEN SELECT COALESCE(jsonb_agg(jsonb_build_object('member_id',p_member,'fingerprint','public-follow|'||(x->>'person_key'),'notification_type','follow','raw_text',COALESCE(x->>'actor_name','noteユーザー')||'さんにフォローされました','actor_name',x->>'actor_name','actor_url',x->>'actor_url','meta',jsonb_build_object('source','public_watcher','derived',true,'person_key',x->>'person_key'))),'[]') INTO events FROM jsonb_array_elements(p_rows) x WHERE (x->>'person_key')=ANY(COALESCE(newkeys,ARRAY[]::text[])); inserted:=public.insight_egress_insert_notifications(events); END IF;
 RETURN jsonb_build_object('received',jsonb_array_length(p_rows),'changed',changed,'newNotifications',inserted); END $fn$;
CREATE OR REPLACE FUNCTION public.insight_missing_avatar_urls(p_limit integer DEFAULT 220) RETURNS TABLE(actor_url text) LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT DISTINCT r.actor_url FROM public.insight_relations r LEFT JOIN private.insight_avatar_retry a ON a.actor_url=r.actor_url WHERE r.active=true AND r.actor_image_url IS NULL AND r.actor_url IS NOT NULL AND (a.retry_after IS NULL OR a.retry_after<=now()) ORDER BY r.actor_url LIMIT greatest(1,least(p_limit,220)); $$;
CREATE OR REPLACE FUNCTION public.insight_apply_avatar_batch(p_rows jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $fn$ DECLARE nr integer; ne integer; BEGIN
 IF jsonb_typeof(p_rows) IS DISTINCT FROM 'array' OR jsonb_array_length(p_rows)>220 THEN RAISE EXCEPTION 'INVALID_AVATAR_BATCH'; END IF;
 UPDATE public.insight_relations r SET actor_image_url=x.image FROM jsonb_to_recordset(p_rows) AS x(url text,image text) WHERE r.actor_url=x.url AND r.actor_image_url IS NULL AND COALESCE(x.image,'')<>''; GET DIAGNOSTICS nr=ROW_COUNT;
 UPDATE public.insight_relation_events r SET actor_image_url=x.image FROM jsonb_to_recordset(p_rows) AS x(url text,image text) WHERE r.actor_url=x.url AND r.actor_image_url IS NULL AND COALESCE(x.image,'')<>''; GET DIAGNOSTICS ne=ROW_COUNT;
 INSERT INTO private.insight_avatar_retry(actor_url,retry_after) SELECT x.url,now()+interval '6 hours' FROM jsonb_to_recordset(p_rows) AS x(url text,image text) WHERE COALESCE(x.url,'')<>'' ON CONFLICT(actor_url) DO UPDATE SET retry_after=EXCLUDED.retry_after;
 RETURN jsonb_build_object('relations',nr,'events',ne,'rows',nr+ne); END $fn$;
DO $permissions$ DECLARE r record; BEGIN FOR r IN SELECT oid::regprocedure AS sig FROM pg_catalog.pg_proc WHERE pronamespace='public'::regnamespace AND proname IN ('insight_egress_authorize','insight_missing_like_articles','insight_egress_catalog_due','insight_egress_catalog_complete','insight_egress_upsert','insight_egress_insert_notifications','insight_comment_refresh_batch','insight_followers_refresh_batch','insight_missing_avatar_urls','insight_apply_avatar_batch') LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated',r.sig); EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role',r.sig); END LOOP; END $permissions$;
