create table if not exists public.insight_favorite_groups (
  id bigint generated by default as identity primary key,
  member_id text not null,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint insight_favorite_groups_name_len check (char_length(btrim(name)) between 1 and 40),
  constraint insight_favorite_groups_member_name_unique unique (member_id, name)
);

create index if not exists insight_favorite_groups_member_idx
  on public.insight_favorite_groups(member_id, created_at);

alter table public.insight_favorite_groups enable row level security;

insert into public.insight_favorite_groups(member_id,name)
select distinct member_id,btrim(group_name)
from public.insight_favorite_creators
where group_name is not null and btrim(group_name)<>''
on conflict(member_id,name) do nothing;
