create table if not exists public.insight_dm_threads (
  id bigint generated by default as identity primary key,
  member_id text not null references public.insight_notification_profiles(member_id) on delete cascade,
  thread_key text not null,
  room_url text,
  peer_note_id text,
  peer_name text,
  peer_url text,
  peer_image_url text,
  last_message_at timestamptz,
  last_synced_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb,
  unique(member_id, thread_key)
);

create table if not exists public.insight_dm_messages (
  id bigint generated by default as identity primary key,
  member_id text not null references public.insight_notification_profiles(member_id) on delete cascade,
  thread_key text not null,
  message_key text not null,
  direction text not null default 'unknown' check (direction in ('inbound','outbound','unknown')),
  sender_name text,
  sender_url text,
  sender_image_url text,
  body text,
  sent_at timestamptz,
  raw_text text,
  attachment_name text,
  attachment_url text,
  attachment_type text,
  captured_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb,
  unique(member_id, message_key)
);

create table if not exists public.insight_dm_sync_runs (
  id bigint generated by default as identity primary key,
  member_id text not null references public.insight_notification_profiles(member_id) on delete cascade,
  received_count integer not null default 0,
  upserted_count integer not null default 0,
  thread_count integer not null default 0,
  source text not null default 'note-dm-reader-v1',
  created_at timestamptz not null default now()
);

create index if not exists insight_dm_threads_member_last_idx on public.insight_dm_threads(member_id,last_message_at desc);
create index if not exists insight_dm_messages_member_thread_sent_idx on public.insight_dm_messages(member_id,thread_key,sent_at desc);
create index if not exists insight_dm_messages_member_sent_idx on public.insight_dm_messages(member_id,sent_at desc);

alter table public.insight_dm_threads enable row level security;
alter table public.insight_dm_messages enable row level security;
alter table public.insight_dm_sync_runs enable row level security;

comment on table public.insight_dm_threads is 'Private note message threads captured by the dedicated DM reader; accessed only through authenticated Edge Functions.';
comment on table public.insight_dm_messages is 'Private note one-to-one DM history captured by the dedicated DM reader; never mixed with notification history.';
