import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const ORIGIN="https://mumei-s.github.io";
function H(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H()})}
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const {data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const {data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),noteId,scope:noteId==="ss_yr"?"owner":String(a.id)}}
const txt=(v:any,d="")=>typeof v==="string"?v:d;
function cleanUrl(v:any){try{const u=new URL(String(v||""));u.search="";u.hash="";return u.toString().replace(/\/$/,"")}catch{return String(v||"").split("?")[0].replace(/\/$/,"")}}
function noteIdFromUrl(v:any){try{const u=new URL(String(v||""));if(u.hostname!=="note.com"&&u.hostname!=="www.note.com")return"";return u.pathname.split("/").filter(Boolean)[0]||""}catch{return""}}
function actorNameFromText(v:any){const t=String(v||"").replace(/\s+/g," ").trim();const m=t.match(/^(.{1,120}?)\s*さん(?:他\d+名)?(?:が|の)/);return m?.[1]?.trim()||null}
function effectiveActorUrl(row:any,me:string){if(row.actor_url)return row.actor_url;const type=String(row.notification_type||"");if(!["magazine","buzz","membership"].includes(type))return null;const id=noteIdFromUrl(row.target_url);if(!id||id.toLowerCase()===me.toLowerCase())return null;return`https://note.com/${id}`}
async function listReplies(m:any,page:number,size:number,offset:number){const [{data,error,count},{data:articles,error:ae}]=await Promise.all([
 db.from("insight_public_comments").select("comment_key,article_key,actor_key,actor_name,actor_url,actor_image_url,body,occurred_at",{count:"exact"}).eq("member_id",m.scope).not("parent_key","is",null).eq("is_creator",false).order("occurred_at",{ascending:false}).range(offset,offset+size-1),
 db.from("insight_public_articles").select("article_key,title,url").eq("member_id",m.scope)
]);if(error)throw error;if(ae)throw ae;const amap=new Map((articles||[]).map((a:any)=>[String(a.article_key),a]));const rows=(data||[]).map((r:any)=>{const a=amap.get(String(r.article_key))||{};return{id:`reply:${r.comment_key}`,member_id:m.scope,notification_type:"reply",raw_text:r.body||"コメントへの返信",actor_name:r.actor_name||null,actor_url:r.actor_url||null,actor_image_url:r.actor_image_url||null,target_title:a.title||"記事",target_url:a.url||null,occurred_at:r.occurred_at,captured_at:r.occurred_at,meta:{source:"public_comment_reply",comment_key:r.comment_key,article_key:r.article_key}}});return{ok:true,page,pageSize:size,total:count||0,rows}}
async function listNotices(m:any,kind:string,page:number,size:number,offset:number){const ids=m.scope===m.id?[m.id]:[m.scope,m.id];let q=db.from("insight_notifications").select("id,member_id,notification_type,raw_text,actor_name,actor_url,target_title,target_url,occurred_at,captured_at,is_read,meta",{count:"exact"}).in("member_id",ids);if(kind!=="all")q=q.eq("notification_type",kind);const {data,error,count}=await q.order("captured_at",{ascending:false}).range(offset,offset+size-1);if(error)throw error;const rows=(data||[]).map((r:any)=>{const actor_url=effectiveActorUrl(r,m.noteId);return{...r,actor_url,actor_name:r.actor_name||actorNameFromText(r.raw_text)||null,target_url:r.target_url?cleanUrl(r.target_url):null}});return{ok:true,page,pageSize:size,total:count||0,rows}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H()});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),kind=txt(b.kind,"all"),page=Math.max(1,Number(b.page||1)),size=Math.min(100,Math.max(20,Number(b.pageSize||100))),offset=(page-1)*size;if(kind==="reply")return out(await listReplies(m,page,size,offset));return out(await listNotices(m,kind,page,size,offset))}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
