import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const ORIGIN="https://mumei-s.github.io";
function H(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type,x-insight-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"}}
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H()})}
async function sha(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(req:Request){const raw=req.headers.get("X-Insight-Token")||"";if(!raw)throw new Error("INSIGHT_LOGIN_REQUIRED");const {data:s}=await db.from("insight_member_sessions").select("id,application_id,expires_at,revoked_at").eq("token_hash",await sha(raw)).maybeSingle();if(!s||s.revoked_at||Date.parse(s.expires_at)<=Date.now())throw new Error("INSIGHT_SESSION_INVALID");const {data:a}=await db.from("insight_access_applications").select("id,note_id,status").eq("id",s.application_id).maybeSingle();if(!a||a.status!=="active")throw new Error("INSIGHT_MEMBER_INACTIVE");const noteId=String(a.note_id||"").toLowerCase();return{id:String(a.id),noteId,scope:noteId==="ss_yr"?"owner":String(a.id)}}
const txt=(v:any,d="")=>typeof v==="string"?v:d;
function validDate(v:any){if(!v)return null;const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()}
function cleanUrl(v:any){try{const u=new URL(String(v||""));u.search="";u.hash="";return u.toString().replace(/\/$/,"")}catch{return String(v||"").split("?")[0].replace(/\/$/,"")}}
function noteIdFromUrl(v:any){try{const u=new URL(String(v||""));if(u.hostname!=="note.com"&&u.hostname!=="www.note.com")return"";return u.pathname.split("/").filter(Boolean)[0]||""}catch{return""}}
function actorNameFromText(v:any){const t=String(v||"").replace(/\s+/g," ").trim();const m=t.match(/^(.{1,120}?)\s*さん(?:他\d+名)?(?:が|の)/);return m?.[1]?.trim()||null}
function effectiveActorUrl(row:any,me:string){if(row.actor_url)return row.actor_url;const type=String(row.notification_type||"");if(!["magazine","buzz","membership"].includes(type))return null;const id=noteIdFromUrl(row.target_url);if(!id||id.toLowerCase()===me.toLowerCase())return null;return`https://note.com/${id}`}
async function syncStatus(m:any){const ids=m.scope===m.id?[m.id]:[m.scope,m.id],{data,error}=await db.from("insight_notification_sync_runs").select("member_id,received_count,inserted_count,source,created_at").in("member_id",ids).eq("source","browser-account-verified").order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return{pairedDataSeen:Boolean(data?.created_at),lastSyncAt:data?.created_at||null,received:Number(data?.received_count||0),inserted:Number(data?.inserted_count||0)}}
async function many(factory:(from:number,to:number)=>PromiseLike<any>,limit=6000){const rows:any[]=[];for(let start=0;start<limit;start+=1000){const res=await factory(start,Math.min(limit-1,start+999));if(res.error)throw res.error;const part=res.data||[];rows.push(...part);if(part.length<1000)break}return rows}

async function articleMap(scope:string){const rows=await many((from,to)=>db.from("insight_public_articles").select("article_key,title,url").eq("member_id",scope).range(from,to),3000);return new Map(rows.map((a:any)=>[String(a.article_key),a]))}
async function publicCommentRows(m:any,kind:"comment"|"reply"|"all",dateFrom:string|null,dateTo:string|null){let factory=(from:number,to:number)=>{let q=db.from("insight_public_comments").select("comment_key,article_key,parent_key,actor_key,actor_name,actor_url,actor_image_url,body,occurred_at").eq("member_id",m.scope).eq("is_creator",false);if(kind==="reply")q=q.not("parent_key","is",null);else if(kind==="comment")q=q.is("parent_key",null);if(dateFrom)q=q.gte("occurred_at",dateFrom);if(dateTo)q=q.lt("occurred_at",dateTo);return q.order("occurred_at",{ascending:false}).range(from,to)};const[data,amap]=await Promise.all([many(factory,6000),articleMap(m.scope)]);return data.map((r:any)=>{const type=r.parent_key?"reply":"comment",a=amap.get(String(r.article_key))||{};return{id:`public:${type}:${r.comment_key}`,member_id:m.scope,notification_type:type,raw_text:r.body||(type==="reply"?"コメントへの返信":"コメント"),actor_name:r.actor_name||null,actor_url:r.actor_url||null,actor_image_url:r.actor_image_url||null,target_title:a.title||"記事",target_url:a.url||null,occurred_at:r.occurred_at,captured_at:r.occurred_at,is_read:false,meta:{source:type==="reply"?"public_comment_reply":"public_comment_root",comment_key:r.comment_key,article_key:r.article_key,parent_key:r.parent_key||null}}})}
async function browserNoticeRows(m:any,kind:string,dateFrom:string|null,dateTo:string|null){const ids=m.scope===m.id?[m.id]:[m.scope,m.id];const rows=await many((from,to)=>{let q=db.from("insight_notifications").select("id,member_id,fingerprint,notification_type,raw_text,actor_name,actor_url,target_title,target_url,occurred_at,captured_at,is_read,meta").in("member_id",ids).not("fingerprint","like","public-comment-summary%").not("fingerprint","like","public-like-summary%");if(kind!=="all")q=q.eq("notification_type",kind);if(dateFrom)q=q.gte("captured_at",dateFrom);if(dateTo)q=q.lt("captured_at",dateTo);return q.order("captured_at",{ascending:false}).range(from,to)},6000);return rows.filter((r:any)=>{const source=String(r?.meta?.source||"");const derived=Boolean(r?.meta?.derived);return !(["comment","reply"].includes(String(r.notification_type||""))&&(derived||source==="member-public-watch"))}).map((r:any)=>{const actor_url=effectiveActorUrl(r,m.noteId);return{...r,actor_url,actor_name:r.actor_name||actorNameFromText(r.raw_text)||null,target_url:r.target_url?cleanUrl(r.target_url):null}})}
function eventTime(r:any){return Date.parse(String(r.occurred_at||r.captured_at||0))||0}
function commentDedupeKey(r:any){const type=String(r.notification_type||""),actor=cleanUrl(r.actor_url)||String(r.actor_name||""),target=cleanUrl(r.target_url)||String(r.target_title||""),t=eventTime(r),bucket=t?Math.floor(t/60000):String(r.id||"");return`${type}|${actor}|${target}|${bucket}`}
function combine(publicRows:any[],noticeRows:any[]){const map=new Map<string,any>();for(const r of noticeRows){const type=String(r.notification_type||"");map.set(type==="comment"||type==="reply"?`c:${commentDedupeKey(r)}`:`n:${r.member_id}:${r.id}`,r)}for(const r of publicRows){const key=`c:${commentDedupeKey(r)}`;map.set(key,r)}return[...map.values()].sort((a,b)=>eventTime(b)-eventTime(a))}
async function listCombined(m:any,kind:"all"|"comment"|"reply",page:number,size:number,offset:number,dateFrom:string|null,dateTo:string|null){const[notices,publicRows,sync]=await Promise.all([browserNoticeRows(m,kind,dateFrom,dateTo),publicCommentRows(m,kind,dateFrom,dateTo),syncStatus(m)]),merged=combine(publicRows,notices);return{ok:true,page,pageSize:size,total:merged.length,rows:merged.slice(offset,offset+size),dateFrom,dateTo,sync,sources:{browser:notices.length,publicComments:publicRows.length}}}
async function listNotices(m:any,kind:string,page:number,size:number,offset:number,dateFrom:string|null,dateTo:string|null){const[rows,sync]=await Promise.all([browserNoticeRows(m,kind,dateFrom,dateTo),syncStatus(m)]);return{ok:true,page,pageSize:size,total:rows.length,rows:rows.slice(offset,offset+size),dateFrom,dateTo,sync}}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H()});try{if(req.method!=="POST")return out({ok:false,error:"METHOD_NOT_ALLOWED"},405);const m=await auth(req),b=await req.json().catch(()=>({})),action=txt(b.action,"list");if(action==="status")return out({ok:true,sync:await syncStatus(m)});const kind=txt(b.kind,"all"),page=Math.max(1,Number(b.page||1)),size=Math.min(100,Math.max(20,Number(b.pageSize||100))),offset=(page-1)*size,dateFrom=validDate(b.dateFrom),dateTo=validDate(b.dateTo);if(kind==="all"||kind==="reply"||kind==="comment")return out(await listCombined(m,kind as "all"|"comment"|"reply",page,size,offset,dateFrom,dateTo));return out(await listNotices(m,kind,page,size,offset,dateFrom,dateTo))}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(msg);return out({ok:false,error:msg},/LOGIN|SESSION|INACTIVE/.test(msg)?401:500)}});
